#ifndef KEST_FPGA_DEFS_H_
#define KEST_FPGA_DEFS_H_

#define KEST_FPGA_SAMPLE_RATE 44100

#define FPGA_BOOT_MS 2500

#define COMMAND_BEGIN_PROGRAM	 	1
#define COMMAND_WRITE_BLOCK_INSTR 	2
#define COMMAND_WRITE_BLOCK_REG_0 	3
#define COMMAND_WRITE_BLOCK_REG_1 	4
#define COMMAND_ALLOC_DELAY 		5
#define COMMAND_END_PROGRAM	 		10
#define COMMAND_SET_INPUT_GAIN 		11
#define COMMAND_SET_OUTPUT_GAIN 	12
#define COMMAND_UPDATE_BLOCK_REG_0 	13
#define COMMAND_UPDATE_BLOCK_REG_1 	14
#define COMMAND_COMMIT_REG_UPDATES 	15
#define COMMAND_ALLOC_FILTER	 	16
#define COMMAND_WRITE_FILTER_COEF 	17
#define COMMAND_UPDATE_FILTER_COEF 	18
#define COMMAND_COMMIT_FILTER_COEF 	19
#define COMMAND_READOUT				20
#define COMMAND_GET_N_BLOCKS 		21
#define COMMAND_GET_BLOCK_INSTR		22
#define COMMAND_GET_BLOCK_REG		23
#define COMMAND_GET_N_DELAY_BUF		24
#define COMMAND_GET_DELAY_BUF_SIZE  25
#define COMMAND_GET_DELAY_BUF_DELAY 26
#define COMMAND_GET_DELAY_BUF_ADDR 	27
#define COMMAND_GET_DELAY_BUF_POS 	28
#define COMMAND_GET_DELAY_BUF_GAIN 	29
#define COMMAND_GET_DELAY_BUF_LRWA 	30
#define COMMAND_GET_SDRAM_READ_CNT	31
#define COMMAND_GET_SDRAM_WRITE_CNT	32
#define COMMAND_READ_COMMAND_LOG	33
#define COMMAND_GET_SAMPLE_COUNT	34
#define COMMAND_CLEAR_TIMEOUT_FLAG	35
#define COMMAND_CLEAR_BAD_FLAG		36
#define COMMAND_CLEAR_CMD_ERR_FLAG	37
#define COMMAND_READ				38
#define COMMAND_ENABLE_TAIL			39

#define SPI_RESPONSE_OK 1

#define KEST_FPGA_N_BLOCKS 256

#define KEST_FPGA_DATA_WIDTH 16
#define KEST_FPGA_FILTER_WIDTH 18
#define KEST_FPGA_MEM_ADDR_BYTES 2
#define KEST_FPGA_DATA_BYTES (KEST_FPGA_DATA_WIDTH / 8)

#if KEST_FPGA_DATA_WIDTH == 16
  typedef int16_t kest_fpga_sample_t;
#elif KEST_FPGA_DATA_WIDTH == 24
  typedef int32_t kest_fpga_sample_t;
#endif

static inline float kest_fpga_sample_to_float(kest_fpga_sample_t s)
{
	return powf(2, -(KEST_FPGA_DATA_WIDTH - 1)) * (float)s;
}

#endif
