Kestrel Interface: kest_preset_view.h File Reference
kest_preset_view.h File Reference
Data Structures
struct kest_preset_view_str
Functions
kest_ui_page * create_preset_view_for (kest_preset *preset)
int init_preset_view (kest_ui_page *page)
int configure_preset_view (kest_ui_page *page, void *data)
int create_preset_view_ui (kest_ui_page *page)
int free_preset_view_ui (kest_ui_page *page)
int free_preset_view (kest_ui_page *page)
int enter_preset_view (kest_ui_page *page)
int enter_preset_view_from (kest_ui_page *page, kest_ui_page *prev)
int refresh_preset_view (kest_ui_page *page)
int preset_view_recalculate_indices (kest_ui_page *page)
int preset_view_append_effect (kest_ui_page *page, kest_effect *effect)
int preset_view_populate_index_pos_array (kest_ui_page *page)
int preset_view_index_y_position (int index)
int preset_view_refresh_play_button (kest_ui_page *page)
int preset_view_refresh_save_button (kest_ui_page *page)
int preset_view_change_name (kest_ui_page *page, char *name)
int preset_view_set_left_button_mode (kest_ui_page *page, int mode)
void preset_view_rep_update (void *representer, void *representee)
Function Documentation
configure_preset_view()
int configure_preset_view (kest_ui_page * page, void * data)
Definition at line 337 of file kest_preset_view.c.
Referenced by create_preset_view_for(), and init_preset_view().
create_preset_view_for()
kest_ui_page * create_preset_view_for (kest_preset * preset)
Definition at line 9 of file kest_preset_view.c.
Referenced by create_new_preset_with_teensy(), load_saved_presets(), and seq_view_clicked_cb().
create_preset_view_ui()
int create_preset_view_ui (kest_ui_page * page)
Definition at line 418 of file kest_preset_view.c.
Referenced by init_preset_view().
enter_preset_view()
int enter_preset_view (kest_ui_page * page)
Definition at line 474 of file kest_preset_view.c.
Referenced by init_preset_view().
enter_preset_view_from()
int enter_preset_view_from (kest_ui_page * page, kest_ui_page * prev)
free_preset_view()
int free_preset_view (kest_ui_page * page)
Definition at line 523 of file kest_preset_view.c.
Referenced by create_preset_view_for(), and init_preset_view().
free_preset_view_ui()
int free_preset_view_ui (kest_ui_page * page)
init_preset_view()
int init_preset_view (kest_ui_page * page)
Definition at line 118 of file kest_preset_view.c.
Referenced by create_preset_view_for().
preset_view_append_effect()
int preset_view_append_effect (kest_ui_page * page, kest_effect * effect)
Definition at line 490 of file kest_preset_view.c.
Referenced by add_effect_from_menu_eff().
preset_view_change_name()
int preset_view_change_name (kest_ui_page * page, char * name)
Definition at line 554 of file kest_preset_view.c.
preset_view_index_y_position()
int preset_view_index_y_position (int index)
preset_view_populate_index_pos_array()
int preset_view_populate_index_pos_array (kest_ui_page * page)
preset_view_recalculate_indices()
int preset_view_recalculate_indices (kest_ui_page * page)
Definition at line 512 of file kest_preset_view.c.
preset_view_refresh_play_button()
int preset_view_refresh_play_button (kest_ui_page * page)
Definition at line 535 of file kest_preset_view.c.
preset_view_refresh_save_button()
int preset_view_refresh_save_button (kest_ui_page * page)
Definition at line 546 of file kest_preset_view.c.
preset_view_rep_update()
void preset_view_rep_update (void * representer, void * representee)
Definition at line 579 of file kest_preset_view.c.
Referenced by init_preset_view().
preset_view_set_left_button_mode()
int preset_view_set_left_button_mode (kest_ui_page * page, int mode)
Definition at line 567 of file kest_preset_view.c.
refresh_preset_view()
int refresh_preset_view (kest_ui_page * page)