Kestrel Interface: kest_dependent.c File Reference
kest_dependent.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 1
Functions
IMPLEMENT_LIST (kest_dependent)
kest_dependent kest_dependent_scope_entry (const char *key)
kest_dependent kest_dependent_block_reg (int block, int reg, int format)
kest_dependent kest_dependent_filter_coef (int filter, int coef, int format)
int kest_string_append_dependent (kest_string *str, kest_dependent dep)
int kest_dependent_is_updatable (int type)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 1
Definition at line 4 of file kest_dependent.c.
Function Documentation
IMPLEMENT_LIST()
IMPLEMENT_LIST (kest_dependent)
kest_dependent_block_reg()
kest_dependent kest_dependent_block_reg (int block, int reg, int format)
Definition at line 21 of file kest_dependent.c.
Referenced by kest_scope_entry_add_dependent_block_reg().
kest_dependent_filter_coef()
kest_dependent kest_dependent_filter_coef (int filter, int coef, int format)
Definition at line 31 of file kest_dependent.c.
Referenced by kest_scope_entry_add_dependent_filter_coef().
kest_dependent_is_updatable()
int kest_dependent_is_updatable (int type)
Definition at line 64 of file kest_dependent.c.
Referenced by kest_scope_transitivize_updatable_dependents_rec().
kest_dependent_scope_entry()
kest_dependent kest_dependent_scope_entry (const char * key)
Definition at line 8 of file kest_dependent.c.
Referenced by kest_scope_entry_add_dependent_scope_entry().
kest_string_append_dependent()
int kest_string_append_dependent (kest_string * str, kest_dependent dep)
Definition at line 41 of file kest_dependent.c.
Referenced by kest_scope_transitivize_updatable_dependents_rec(), and kest_updater_handle_update().