Kestrel Interface: kest_preset_settings.c File Reference
kest_preset_settings.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int init_preset_settings_page (kest_ui_page *page)
int configure_preset_settings_page (kest_ui_page *page, void *data)
void preset_settings_save_button_cb (lv_event_t *e)
void default_preset_button_cb (lv_event_t *e)
int create_preset_settings_page_ui (kest_ui_page *page)
int free_preset_settings_page_ui (kest_ui_page *page)
int preset_settings_page_free_all (kest_ui_page *page)
int enter_preset_settings_page (kest_ui_page *page)
int enter_preset_settings_page_forward (kest_ui_page *page)
int enter_preset_settings_page_back (kest_ui_page *page)
int refresh_preset_settings_page (kest_ui_page *page)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_preset_settings.c.
Function Documentation
configure_preset_settings_page()
int configure_preset_settings_page (kest_ui_page * page, void * data)
Definition at line 45 of file kest_preset_settings.c.
Referenced by configure_preset_view(), and init_preset_settings_page().
create_preset_settings_page_ui()
int create_preset_settings_page_ui (kest_ui_page * page)
Definition at line 122 of file kest_preset_settings.c.
Referenced by init_preset_settings_page().
default_preset_button_cb()
void default_preset_button_cb (lv_event_t * e)
Definition at line 105 of file kest_preset_settings.c.
enter_preset_settings_page()
int enter_preset_settings_page (kest_ui_page * page)
Definition at line 214 of file kest_preset_settings.c.
enter_preset_settings_page_back()
int enter_preset_settings_page_back (kest_ui_page * page)
Definition at line 230 of file kest_preset_settings.c.
enter_preset_settings_page_forward()
int enter_preset_settings_page_forward (kest_ui_page * page)
Definition at line 222 of file kest_preset_settings.c.
free_preset_settings_page_ui()
int free_preset_settings_page_ui (kest_ui_page * page)
Definition at line 198 of file kest_preset_settings.c.
Referenced by init_preset_settings_page().
init_preset_settings_page()
int init_preset_settings_page (kest_ui_page * page)
Definition at line 9 of file kest_preset_settings.c.
Referenced by init_preset_view().
preset_settings_page_free_all()
int preset_settings_page_free_all (kest_ui_page * page)
Definition at line 206 of file kest_preset_settings.c.
Referenced by init_preset_settings_page().
preset_settings_save_button_cb()
void preset_settings_save_button_cb (lv_event_t * e)
Definition at line 88 of file kest_preset_settings.c.
refresh_preset_settings_page()
int refresh_preset_settings_page (kest_ui_page * page)
Definition at line 238 of file kest_preset_settings.c.
Referenced by init_preset_settings_page().