Kestrel Interface: kest_fpga_cmd.c File Reference
kest_fpga_cmd.c File Reference
#include "kest_int.h"
Functions
IMPLEMENT_LIST (kest_fpga_command)
kest_fpga_command kest_fpga_command_begin_program ()
kest_fpga_command kest_fpga_command_end_program ()
kest_fpga_command kest_fpga_command_write_block_instr (int block, uint32_t instr)
kest_fpga_command kest_fpga_command_write_block_reg_0 (int block, float val, int format)
kest_fpga_command kest_fpga_command_write_block_reg_1 (int block, float val, int format)
kest_fpga_command kest_fpga_command_update_block_reg_0 (int block, float val, int format)
kest_fpga_command kest_fpga_command_update_block_reg_1 (int block, float val, int format)
kest_fpga_command kest_fpga_command_commit_reg_updates ()
kest_fpga_command kest_fpga_command_alloc_delay (int size, int delay)
kest_fpga_command kest_fpga_command_alloc_filter (int format, int order_ff, int order_fb)
kest_fpga_command kest_fpga_command_write_filter_coef (int handle, int coef, float val, int format)
kest_fpga_command kest_fpga_command_update_filter_coef (int handle, int coef, float val, int format)
kest_fpga_command kest_fpga_command_commit_filter_coefs (int handle)
kest_fpga_command kest_fpga_command_enable_tail ()
int kest_fpga_command_list_append_encoded (kest_fpga_command_list *cmds, kest_fpga_transfer_batch *batch)
int kest_fpga_command_append_encoded (kest_fpga_command cmd, kest_fpga_transfer_batch *batch)
char * kest_fpga_command_to_string (int command)
int kest_fpga_command_to_string_ (kest_fpga_command cmd, kest_string *str)
Function Documentation
IMPLEMENT_LIST()
IMPLEMENT_LIST (kest_fpga_command)
kest_fpga_command_alloc_delay()
kest_fpga_command kest_fpga_command_alloc_delay (int size, int delay)
Definition at line 75 of file kest_fpga_cmd.c.
Referenced by kest_alloc_to_command().
kest_fpga_command_alloc_filter()
kest_fpga_command kest_fpga_command_alloc_filter (int format, int order_ff, int order_fb)
Definition at line 84 of file kest_fpga_cmd.c.
Referenced by kest_alloc_to_command().
kest_fpga_command_append_encoded()
int kest_fpga_command_append_encoded (kest_fpga_command cmd, kest_fpga_transfer_batch * batch)
Definition at line 144 of file kest_fpga_cmd.c.
Referenced by kest_fpga_command_list_append_encoded().
kest_fpga_command_begin_program()
kest_fpga_command kest_fpga_command_begin_program ()
Definition at line 5 of file kest_fpga_cmd.c.
kest_fpga_command_commit_filter_coefs()
kest_fpga_command kest_fpga_command_commit_filter_coefs (int handle)
Definition at line 116 of file kest_fpga_cmd.c.
Referenced by kest_updater_generate_command_list().
kest_fpga_command_commit_reg_updates()
kest_fpga_command kest_fpga_command_commit_reg_updates ()
Definition at line 68 of file kest_fpga_cmd.c.
Referenced by kest_updater_generate_command_list().
kest_fpga_command_enable_tail()
kest_fpga_command kest_fpga_command_enable_tail ()
Definition at line 124 of file kest_fpga_cmd.c.
kest_fpga_command_end_program()
kest_fpga_command kest_fpga_command_end_program ()
Definition at line 12 of file kest_fpga_cmd.c.
kest_fpga_command_list_append_encoded()
int kest_fpga_command_list_append_encoded (kest_fpga_command_list * cmds, kest_fpga_transfer_batch * batch)
Definition at line 131 of file kest_fpga_cmd.c.
Referenced by kest_updater_generate_tx_batch().
kest_fpga_command_to_string()
char * kest_fpga_command_to_string (int command)
Definition at line 213 of file kest_fpga_cmd.c.
Referenced by kest_fpga_command_to_string_(), kest_fpga_comms_task(), kest_fpga_print_command_log(), kest_fpga_program_batch_send_careful(), and kest_fpga_transfer_batch_send_careful().
kest_fpga_command_to_string_()
int kest_fpga_command_to_string_ (kest_fpga_command cmd, kest_string * str)
Definition at line 244 of file kest_fpga_cmd.c.
Referenced by kest_updater_print_command_list().
kest_fpga_command_update_block_reg_0()
kest_fpga_command kest_fpga_command_update_block_reg_0 (int block, float val, int format)
Definition at line 48 of file kest_fpga_cmd.c.
Referenced by kest_fpga_write_to_command().
kest_fpga_command_update_block_reg_1()
kest_fpga_command kest_fpga_command_update_block_reg_1 (int block, float val, int format)
Definition at line 58 of file kest_fpga_cmd.c.
Referenced by kest_fpga_write_to_command().
kest_fpga_command_update_filter_coef()
kest_fpga_command kest_fpga_command_update_filter_coef (int handle, int coef, float val, int format)
Definition at line 105 of file kest_fpga_cmd.c.
Referenced by kest_fpga_write_to_command().
kest_fpga_command_write_block_instr()
kest_fpga_command kest_fpga_command_write_block_instr (int block, uint32_t instr)
Definition at line 19 of file kest_fpga_cmd.c.
Referenced by kest_fpga_write_to_command().
kest_fpga_command_write_block_reg_0()
kest_fpga_command kest_fpga_command_write_block_reg_0 (int block, float val, int format)
Definition at line 28 of file kest_fpga_cmd.c.
Referenced by kest_fpga_write_to_command().
kest_fpga_command_write_block_reg_1()
kest_fpga_command kest_fpga_command_write_block_reg_1 (int block, float val, int format)
Definition at line 38 of file kest_fpga_cmd.c.
Referenced by kest_fpga_write_to_command().
kest_fpga_command_write_filter_coef()
kest_fpga_command kest_fpga_command_write_filter_coef (int handle, int coef, float val, int format)
Definition at line 94 of file kest_fpga_cmd.c.
Referenced by kest_fpga_write_to_command().