Kestrel Interface: kest_file_task.c File Reference
kest_file_task.c File Reference
#include "kest_int.h"
Data Structures
struct kest_file_job
Macros
#define PRINTLINES_ALLOWED 0
#define KEST_FILE_JOB_NONE 0
#define KEST_FILE_JOB_SAVE_STATE 1
#define KEST_FILE_JOB_SAVE_PRESET 2
#define KEST_FILE_JOB_SAVE_SEQUENCE 3
#define KEST_STATE_SAVE_MIN_TIME_MS 3000
Functions
void kest_file_task (void *)
int kest_init_file_task ()
int kest_queue_state_save ()
int kest_queue_preset_save (kest_preset *preset)
int kest_queue_sequence_save (kest_sequence *sequence)
Variables
volatile int job_queue_initd = 0
QueueHandle_t file_job_queue
Macro Definition Documentation
KEST_FILE_JOB_NONE
#define KEST_FILE_JOB_NONE 0
Definition at line 7 of file kest_file_task.c.
KEST_FILE_JOB_SAVE_PRESET
#define KEST_FILE_JOB_SAVE_PRESET 2
Definition at line 9 of file kest_file_task.c.
Referenced by kest_file_task(), and kest_queue_preset_save().
KEST_FILE_JOB_SAVE_SEQUENCE
#define KEST_FILE_JOB_SAVE_SEQUENCE 3
Definition at line 10 of file kest_file_task.c.
Referenced by kest_file_task(), and kest_queue_sequence_save().
KEST_FILE_JOB_SAVE_STATE
#define KEST_FILE_JOB_SAVE_STATE 1
Definition at line 8 of file kest_file_task.c.
Referenced by kest_file_task(), and kest_queue_state_save().
KEST_STATE_SAVE_MIN_TIME_MS
#define KEST_STATE_SAVE_MIN_TIME_MS 3000
Definition at line 68 of file kest_file_task.c.
Referenced by kest_queue_state_save().
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 5 of file kest_file_task.c.
Function Documentation
kest_file_task()
void kest_file_task (void *)
Definition at line 25 of file kest_file_task.c.
Referenced by kest_init_file_task().
kest_init_file_task()
int kest_init_file_task ()
Definition at line 62 of file kest_file_task.c.
Referenced by kest_init().
kest_queue_preset_save()
int kest_queue_preset_save (kest_preset * preset)
Definition at line 106 of file kest_file_task.c.
Referenced by kest_preset_append_effect_eff(), kest_preset_move_effect(), kest_preset_remove_effect(), and preset_view_save_name().
kest_queue_sequence_save()
int kest_queue_sequence_save (kest_sequence * sequence)
Definition at line 123 of file kest_file_task.c.
Referenced by kest_sequence_delete_preset(), kest_sequence_move_preset(), kest_sequence_remove_preset(), sequence_append_preset(), sequence_append_preset_rp(), and sequence_list_add_cb().
kest_queue_state_save()
int kest_queue_state_save ()
Definition at line 70 of file kest_file_task.c.
Referenced by enter_ui_page(), enter_ui_page_backwards(), enter_ui_page_forwards(), and set_active_preset_from_sequence().
Variable Documentation
file_job_queue
QueueHandle_t file_job_queue
Definition at line 23 of file kest_file_task.c.
Referenced by kest_file_task(), kest_queue_preset_save(), kest_queue_sequence_save(), and kest_queue_state_save().
job_queue_initd
volatile int job_queue_initd = 0
Definition at line 22 of file kest_file_task.c.
Referenced by kest_file_task(), kest_queue_preset_save(), kest_queue_sequence_save(), and kest_queue_state_save().