Kestrel Interface: kest_pipeline.c File Reference
kest_pipeline.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int init_m_pipeline (kest_pipeline *pipeline)
kest_effect * kest_pipeline_append_effect_eff (kest_pipeline *pipeline, kest_effect_desc *eff)
int kest_pipeline_remove_effect (kest_pipeline *pipeline, uint16_t id)
int kest_pipeline_move_effect (kest_pipeline *pipeline, int new_pos, int old_pos)
int kest_pipeline_get_n_effects (kest_pipeline *pipeline)
int clone_pipeline (kest_pipeline *dest, kest_pipeline *src)
void gut_pipeline (kest_pipeline *pipeline)
int kest_pipeline_create_fpga_transfer_batch (kest_pipeline *pipeline, kest_fpga_transfer_batch *batch)
kest_effect * kest_pipeline_get_effect_by_id (kest_pipeline *pipeline, int id)
int kest_pipeline_rectify_ids (kest_pipeline *pipeline, int preset_id)
int kest_pipeline_activate_dma (kest_pipeline *pipeline)
int kest_pipeline_deactivate_lfos (kest_pipeline *pipeline)
int kest_pipeline_activate_lfos (kest_pipeline *pipeline)
int kest_pipeline_deactivate_dma (kest_pipeline *pipeline)
int kest_pipeline_update_fpga (kest_pipeline *pipeline)
int kest_pipeline_update_positions (kest_pipeline *pipeline)
int kest_effect_ptr_list_update_positions (kest_effect_ptr_list *effects)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_pipeline.c.
Function Documentation
clone_pipeline()
int clone_pipeline (kest_pipeline * dest, kest_pipeline * src)
Definition at line 183 of file kest_pipeline.c.
Referenced by clone_preset().
gut_pipeline()
void gut_pipeline (kest_pipeline * pipeline)
Definition at line 220 of file kest_pipeline.c.
Referenced by gut_preset().
init_m_pipeline()
int init_m_pipeline (kest_pipeline * pipeline)
Definition at line 9 of file kest_pipeline.c.
Referenced by init_m_preset().
kest_effect_ptr_list_update_positions()
int kest_effect_ptr_list_update_positions (kest_effect_ptr_list * effects)
Definition at line 493 of file kest_pipeline.c.
Referenced by kest_standalone_generate_program_batch().
kest_pipeline_activate_dma()
int kest_pipeline_activate_dma (kest_pipeline * pipeline)
Definition at line 332 of file kest_pipeline.c.
Referenced by kest_preset_activate_dma().
kest_pipeline_activate_lfos()
int kest_pipeline_activate_lfos (kest_pipeline * pipeline)
Definition at line 369 of file kest_pipeline.c.
Referenced by kest_preset_activate_lfos().
kest_pipeline_append_effect_eff()
kest_effect * kest_pipeline_append_effect_eff (kest_pipeline * pipeline, kest_effect_desc * eff)
Definition at line 23 of file kest_pipeline.c.
Referenced by kest_preset_append_effect_eff().
kest_pipeline_create_fpga_transfer_batch()
int kest_pipeline_create_fpga_transfer_batch (kest_pipeline * pipeline, kest_fpga_transfer_batch * batch)
Definition at line 229 of file kest_pipeline.c.
Referenced by kest_preset_create_fpga_transfer_batch(), and kest_preset_program_fpga().
kest_pipeline_deactivate_dma()
int kest_pipeline_deactivate_dma (kest_pipeline * pipeline)
Definition at line 388 of file kest_pipeline.c.
Referenced by kest_preset_deactivate_dma().
kest_pipeline_deactivate_lfos()
int kest_pipeline_deactivate_lfos (kest_pipeline * pipeline)
Definition at line 351 of file kest_pipeline.c.
Referenced by kest_preset_deactivate_lfos().
kest_pipeline_get_effect_by_id()
kest_effect * kest_pipeline_get_effect_by_id (kest_pipeline * pipeline, int id)
Definition at line 275 of file kest_pipeline.c.
Referenced by kest_preset_get_effect_by_id().
kest_pipeline_get_n_effects()
int kest_pipeline_get_n_effects (kest_pipeline * pipeline)
Definition at line 164 of file kest_pipeline.c.
kest_pipeline_move_effect()
int kest_pipeline_move_effect (kest_pipeline * pipeline, int new_pos, int old_pos)
Definition at line 112 of file kest_pipeline.c.
Referenced by kest_preset_move_effect().
kest_pipeline_rectify_ids()
int kest_pipeline_rectify_ids (kest_pipeline * pipeline, int preset_id)
Definition at line 312 of file kest_pipeline.c.
Referenced by kest_preset_rectify_ids().
kest_pipeline_remove_effect()
int kest_pipeline_remove_effect (kest_pipeline * pipeline, uint16_t id)
Definition at line 76 of file kest_pipeline.c.
Referenced by kest_preset_remove_effect().
kest_pipeline_update_fpga()
int kest_pipeline_update_fpga (kest_pipeline * pipeline)
Definition at line 406 of file kest_pipeline.c.
Referenced by kest_preset_update_fpga().
kest_pipeline_update_positions()
int kest_pipeline_update_positions (kest_pipeline * pipeline)
Definition at line 444 of file kest_pipeline.c.
Referenced by kest_preset_set_active().