Kestrel Interface: kest_fpga_comms.c File Reference
kest_fpga_comms.c File Reference
#include "kest_int.h"
Data Structures
struct kest_fpga_msg
Macros
#define PRINTLINES_ALLOWED 0
#define KEST_FPGA_MSG_TYPE_BATCH 0
#define KEST_FPGA_MSG_TYPE_PROGRAM_BATCH 1
#define KEST_FPGA_MSG_TYPE_SET_INPUT_GAIN 2
#define KEST_FPGA_MSG_TYPE_SET_OUTPUT_GAIN 3
#define KEST_FPGA_MSG_TYPE_COMMAND 4
#define KEST_FPGA_MSG_TYPE_READ 5
#define KEST_FPGA_MSG_TYPE_BYTE_BATCH 6
#define PROGRAM_RETRIES 3
Functions
int kest_init_fpga_comms ()
void kest_fpga_comms_print_full_scan ()
void kest_fpga_handle_misalignment ()
void kest_command_log_test ()
void kest_fpga_comms_task (void *param)
int kest_fpga_queue_msg (kest_fpga_msg msg)
int kest_fpga_queue_transfer_batch (kest_fpga_transfer_batch batch)
int kest_fpga_queue_program_batch (kest_fpga_transfer_batch batch)
int kest_fpga_queue_input_gain_set (float gain_db)
int kest_fpga_queue_output_gain_set (float gain_db)
int kest_fpga_queue_register_commit ()
int kest_fpga_queue_read (kest_fpga_read_spec *spec)
void get_and_sprint_flags (kest_string *str, kest_fpga_status_flags *flags)
void get_and_sprint_flags_compact (kest_string *str, kest_fpga_status_flags *flags)
void sprint_flags_compact (kest_string *str, kest_fpga_status_flags *flags)
void kest_fpga_print_command_log ()
Macro Definition Documentation
KEST_FPGA_MSG_TYPE_BATCH
#define KEST_FPGA_MSG_TYPE_BATCH 0
Definition at line 13 of file kest_fpga_comms.c.
Referenced by kest_fpga_comms_task(), and kest_fpga_queue_transfer_batch().
KEST_FPGA_MSG_TYPE_BYTE_BATCH
#define KEST_FPGA_MSG_TYPE_BYTE_BATCH 6
Definition at line 19 of file kest_fpga_comms.c.
Referenced by kest_fpga_comms_task().
KEST_FPGA_MSG_TYPE_COMMAND
#define KEST_FPGA_MSG_TYPE_COMMAND 4
Definition at line 17 of file kest_fpga_comms.c.
Referenced by kest_fpga_comms_task(), and kest_fpga_queue_register_commit().
KEST_FPGA_MSG_TYPE_PROGRAM_BATCH
#define KEST_FPGA_MSG_TYPE_PROGRAM_BATCH 1
Definition at line 14 of file kest_fpga_comms.c.
Referenced by kest_fpga_comms_task(), and kest_fpga_queue_program_batch().
KEST_FPGA_MSG_TYPE_READ
#define KEST_FPGA_MSG_TYPE_READ 5
Definition at line 18 of file kest_fpga_comms.c.
Referenced by kest_fpga_comms_task(), and kest_fpga_queue_read().
KEST_FPGA_MSG_TYPE_SET_INPUT_GAIN
#define KEST_FPGA_MSG_TYPE_SET_INPUT_GAIN 2
Definition at line 15 of file kest_fpga_comms.c.
Referenced by kest_fpga_comms_task(), and kest_fpga_queue_input_gain_set().
KEST_FPGA_MSG_TYPE_SET_OUTPUT_GAIN
#define KEST_FPGA_MSG_TYPE_SET_OUTPUT_GAIN 3
Definition at line 16 of file kest_fpga_comms.c.
Referenced by kest_fpga_comms_task(), and kest_fpga_queue_output_gain_set().
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 3 of file kest_fpga_comms.c.
PROGRAM_RETRIES
#define PROGRAM_RETRIES 3
Definition at line 36 of file kest_fpga_comms.c.
Referenced by kest_fpga_comms_task().
Function Documentation
get_and_sprint_flags()
void get_and_sprint_flags (kest_string * str, kest_fpga_status_flags * flags)
Definition at line 341 of file kest_fpga_comms.c.
Referenced by kest_fpga_comms_print_full_scan().
get_and_sprint_flags_compact()
void get_and_sprint_flags_compact (kest_string * str, kest_fpga_status_flags * flags)
Definition at line 351 of file kest_fpga_comms.c.
kest_command_log_test()
void kest_command_log_test ()
Definition at line 507 of file kest_fpga_comms.c.
kest_fpga_comms_print_full_scan()
void kest_fpga_comms_print_full_scan ()
Definition at line 377 of file kest_fpga_comms.c.
Referenced by kest_fpga_comms_task().
kest_fpga_comms_task()
void kest_fpga_comms_task (void * param)
Definition at line 42 of file kest_fpga_comms.c.
Referenced by kest_init_fpga_comms().
kest_fpga_handle_misalignment()
void kest_fpga_handle_misalignment ()
Definition at line 495 of file kest_fpga_comms.c.
Referenced by kest_fpga_comms_task().
kest_fpga_print_command_log()
void kest_fpga_print_command_log ()
Definition at line 471 of file kest_fpga_comms.c.
Referenced by kest_command_log_test(), and kest_fpga_handle_misalignment().
kest_fpga_queue_input_gain_set()
int kest_fpga_queue_input_gain_set (float gain_db)
Definition at line 298 of file kest_fpga_comms.c.
kest_fpga_queue_msg()
int kest_fpga_queue_msg (kest_fpga_msg msg)
Definition at line 259 of file kest_fpga_comms.c.
Referenced by kest_fpga_queue_input_gain_set(), kest_fpga_queue_output_gain_set(), kest_fpga_queue_program_batch(), kest_fpga_queue_read(), kest_fpga_queue_register_commit(), and kest_fpga_queue_transfer_batch().
kest_fpga_queue_output_gain_set()
int kest_fpga_queue_output_gain_set (float gain_db)
Definition at line 308 of file kest_fpga_comms.c.
kest_fpga_queue_program_batch()
int kest_fpga_queue_program_batch (kest_fpga_transfer_batch batch)
Definition at line 285 of file kest_fpga_comms.c.
Referenced by kest_preset_program_fpga(), and kest_updater_send().
kest_fpga_queue_read()
int kest_fpga_queue_read (kest_fpga_read_spec * spec)
Definition at line 328 of file kest_fpga_comms.c.
Referenced by kest_periodic_read_dispatch().
kest_fpga_queue_register_commit()
int kest_fpga_queue_register_commit ()
Definition at line 318 of file kest_fpga_comms.c.
kest_fpga_queue_transfer_batch()
int kest_fpga_queue_transfer_batch (kest_fpga_transfer_batch batch)
Definition at line 270 of file kest_fpga_comms.c.
Referenced by kest_effect_handle_updates(), kest_effect_handle_updates_inc_ui(), kest_effect_update_fpga(), kest_effect_update_sync_no_pw(), kest_pipeline_update_fpga(), and kest_updater_send().
kest_init_fpga_comms()
int kest_init_fpga_comms ()
Definition at line 7 of file kest_fpga_comms.c.
Referenced by kest_init().
sprint_flags_compact()
void sprint_flags_compact (kest_string * str, kest_fpga_status_flags * flags)
Definition at line 361 of file kest_fpga_comms.c.