Kestrel Interface: kest_event.c File Reference
kest_event.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 1
Functions
void kest_event_task (void *arg)
int kest_event_task_start ()
void kest_event_handle (kest_event event)
int kest_event_log (kest_event event)
Variables
QueueHandle_t event_queue = NULL
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 1
Definition at line 3 of file kest_event.c.
Function Documentation
kest_event_handle()
void kest_event_handle (kest_event event)
Definition at line 45 of file kest_event.c.
Referenced by kest_event_task().
kest_event_log()
int kest_event_log (kest_event event)
Definition at line 37 of file kest_event.c.
Referenced by app_main(), and main_task().
kest_event_task()
void kest_event_task (void * arg)
Definition at line 25 of file kest_event.c.
Referenced by kest_event_task_start().
kest_event_task_start()
int kest_event_task_start ()
Definition at line 11 of file kest_event.c.
Referenced by app_main(), and main_task().
Variable Documentation
event_queue
QueueHandle_t event_queue = NULL
Definition at line 7 of file kest_event.c.
Referenced by kest_event_log(), kest_event_task(), and kest_event_task_start().