Kestrel Interface: kest_dict_extract.c File Reference
kest_dict_extract.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
#define CHECK_MANDATORY_ATTR(attr)
#define ASSERT_ATTR_EXPR()
#define ASSERT_ATTR_CONST_EXPR()
#define ASSERT_ATTR_CONST_INT()
#define ASSERT_ATTR_STRING()
#define ASSERT_ATTR_LIST()
#define ASSERT_ATTR_DICT()
Functions
int kest_extract_lpf_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict, kest_dsp_resource *res)
int kest_extract_hpf_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict, kest_dsp_resource *res)
int kest_extract_bpf_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict, kest_dsp_resource *res)
int kest_extract_enum_setting_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict, kest_setting *setting)
int kest_extract_bool_setting_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict, kest_setting *setting)
int kest_extract_int_setting_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict, kest_setting *setting)
kest_setting * kest_extract_setting_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict)
int kest_extract_delay_buffer_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict, kest_dsp_resource *res)
int kest_extract_mem_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict, kest_dsp_resource *res)
int kest_extract_filter_coefs_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict, kest_dsp_resource *res)
int kest_extract_biquad_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict, kest_dsp_resource *res)
int kest_extract_polynomial_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict, kest_dsp_resource *res)
int kest_extract_filter_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict, kest_dsp_resource *res)
kest_dsp_resource * kest_extract_resource_from_dict (kest_eff_parsing_state *ps, kest_ast_node *dict_node, kest_dictionary *dict)
kest_parameter * kest_extract_parameter (kest_eff_parsing_state *ps, kest_eff_entry_dict *dict, const char *name)
kest_setting * kest_extract_setting (kest_eff_parsing_state *ps, kest_eff_entry_dict *dict, const char *name)
kest_dsp_resource * kest_extract_mem (kest_eff_parsing_state *ps, kest_eff_entry_dict *dict, const char *name)
kest_dsp_resource * kest_extract_delay (kest_eff_parsing_state *ps, kest_eff_entry_dict *dict, const char *name)
kest_dsp_resource * kest_extract_filter (kest_eff_parsing_state *ps, kest_eff_entry_dict *dict, const char *name)
kest_dsp_resource * kest_extract_lpf (kest_eff_parsing_state *ps, kest_eff_entry_dict *dict, const char *name)
kest_dsp_resource * kest_extract_hpf (kest_eff_parsing_state *ps, kest_eff_entry_dict *dict, const char *name)
kest_dsp_resource * kest_extract_bpf (kest_eff_parsing_state *ps, kest_eff_entry_dict *dict, const char *name)
kest_dsp_resource * kest_extract_lfo (kest_eff_parsing_state *ps, kest_eff_entry_dict *dict, const char *name)
kest_dsp_resource * kest_extract_polynomial (kest_eff_parsing_state *ps, kest_eff_entry_dict *dict, const char *name)
kest_dsp_resource * kest_extract_resource (kest_eff_parsing_state *ps, kest_eff_entry_dict *dict, const char *name)
Macro Definition Documentation
ASSERT_ATTR_CONST_EXPR
#define ASSERT_ATTR_CONST_EXPR ()
Value:
    do { \
    if (entry->type != KEST_EFF_ENTRY_TYPE_EXPR) { \
        kest_parser_error(ps, "%s \"%s\": attribute \"%s\" must be a numerical expression", type, name, key); \
        ret_val = ERR_BAD_ARGS; \
        continue; \
    } \
    else \
    { \
        if (!entry->value.val_expr) { \
            KEST_PRINTF_FORCE("entry->value.val_expr = NULL. Bug ?\n"); \
            ret_val = ERR_BAD_ARGS; \
            goto extract_finish; \
        } \
        if (!kest_expression_is_constant(entry->value.val_expr)) { \
            kest_parser_error(ps, "%s \"%s\": attribute \"%s\" must be constant", type, name, key); \
            ret_val = ERR_BAD_ARGS; \
            continue; \
        } \
         \
        value = kest_expression_evaluate(expr, NULL); \
    } \
} while (0)
Definition at line 988 of file kest_dict_extract.c.
Referenced by kest_extract_parameter(), and kest_extract_setting().
ASSERT_ATTR_CONST_INT
#define ASSERT_ATTR_CONST_INT ()
Definition at line 1011 of file kest_dict_extract.c.
Referenced by kest_extract_filter(), kest_extract_parameter(), and kest_extract_setting().
ASSERT_ATTR_DICT
#define ASSERT_ATTR_DICT ()
Value:
    do { \
    if (entry->type != KEST_EFF_ENTRY_TYPE_SUBDICT) { \
        kest_parser_error(ps, "%s \"%s\": attribute \"%s\" must be a dict", type, name, key); \
        ret_val = ERR_BAD_ARGS; \
        continue; \
    } \
    else \
    { \
        if (!entry->value.val_expr) { \
            KEST_PRINTF_FORCE("entry->value.val_dict = NULL. Bug ?\n"); \
            ret_val = ERR_BAD_ARGS; \
        } \
    } \
} while (0)
Definition at line 1076 of file kest_dict_extract.c.
Referenced by kest_extract_setting().
ASSERT_ATTR_EXPR
#define ASSERT_ATTR_EXPR ()
Value:
    do { \
    if (entry->type != KEST_EFF_ENTRY_TYPE_EXPR) { \
        kest_parser_error(ps, "%s \"%s\": attribute \"%s\" must be a numerical expression", type, name, key); \
        ret_val = ERR_BAD_ARGS; \
        continue; \
    } \
    else \
    { \
        if (!entry->value.val_expr) { \
            KEST_PRINTF_FORCE("entry->value.val_expr = NULL. Bug ?\n"); \
            ret_val = ERR_BAD_ARGS; \
            goto extract_finish; \
        } \
    } \
} while (0)
Definition at line 972 of file kest_dict_extract.c.
Referenced by kest_extract_bpf(), kest_extract_hpf(), kest_extract_lfo(), kest_extract_lpf(), and kest_extract_parameter().
ASSERT_ATTR_LIST
#define ASSERT_ATTR_LIST ()
Value:
    do { \
    if (entry->type != KEST_EFF_ENTRY_TYPE_LIST) { \
        kest_parser_error(ps, "%s \"%s\": attribute \"%s\" must be a list", type, name, key); \
        ret_val = ERR_BAD_ARGS; \
        continue; \
    } \
    else \
    { \
        if (!entry->value.val_expr) { \
            KEST_PRINTF_FORCE("entry->value.val_list = NULL. Bug ?\n"); \
            ret_val = ERR_BAD_ARGS; \
            goto extract_finish; \
        } \
    } \
} while (0)
Definition at line 1060 of file kest_dict_extract.c.
Referenced by kest_extract_filter(), and kest_extract_polynomial().
ASSERT_ATTR_STRING
#define ASSERT_ATTR_STRING ()
Value:
    do { \
    if (entry->type != KEST_EFF_ENTRY_TYPE_STR) { \
        kest_parser_error(ps, "%s \"%s\": attribute \"%s\" must be a string", type, name, key); \
        ret_val = ERR_BAD_ARGS; \
        continue; \
    } \
    else \
    { \
        if (!entry->value.val_string) { \
            KEST_PRINTF_FORCE("entry->value.val_string = NULL. Bug ?\n"); \
            ret_val = ERR_BAD_ARGS; \
            goto extract_finish; \
        } \
    } \
} while (0)
Definition at line 1044 of file kest_dict_extract.c.
Referenced by kest_extract_lfo(), kest_extract_parameter(), and kest_extract_setting().
CHECK_MANDATORY_ATTR
#define CHECK_MANDATORY_ATTR (attr)
Value:
    do { \
    if (!kest_eff_entry_dict_lookup(dict, attr)) { \
        kest_parser_error(ps, "%s \"%s\": mandatory attribute \"%s\" not found", type, name, attr); \
        return NULL; \
    }\
} while (0)
Definition at line 965 of file kest_dict_extract.c.
Referenced by kest_extract_bpf(), kest_extract_filter(), kest_extract_hpf(), kest_extract_lpf(), kest_extract_parameter(), kest_extract_polynomial(), and kest_extract_setting().
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 3 of file kest_dict_extract.c.
Function Documentation
kest_extract_biquad_from_dict()
int kest_extract_biquad_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict, kest_dsp_resource * res)
Definition at line 760 of file kest_dict_extract.c.
Referenced by kest_extract_resource_from_dict().
kest_extract_bool_setting_from_dict()
int kest_extract_bool_setting_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict, kest_setting * setting)
Definition at line 373 of file kest_dict_extract.c.
Referenced by kest_extract_setting_from_dict().
kest_extract_bpf()
kest_dsp_resource * kest_extract_bpf (kest_eff_parsing_state * ps, kest_eff_entry_dict * dict, const char * name)
Definition at line 2259 of file kest_dict_extract.c.
Referenced by kest_extract_resource().
kest_extract_bpf_from_dict()
int kest_extract_bpf_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict, kest_dsp_resource * res)
Definition at line 244 of file kest_dict_extract.c.
Referenced by kest_extract_resource_from_dict().
kest_extract_delay()
kest_dsp_resource * kest_extract_delay (kest_eff_parsing_state * ps, kest_eff_entry_dict * dict, const char * name)
Definition at line 1692 of file kest_dict_extract.c.
Referenced by kest_extract_resource().
kest_extract_delay_buffer_from_dict()
int kest_extract_delay_buffer_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict, kest_dsp_resource * res)
Definition at line 594 of file kest_dict_extract.c.
Referenced by kest_extract_resource_from_dict().
kest_extract_enum_setting_from_dict()
int kest_extract_enum_setting_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict, kest_setting * setting)
Definition at line 362 of file kest_dict_extract.c.
Referenced by kest_extract_setting_from_dict().
kest_extract_filter()
kest_dsp_resource * kest_extract_filter (kest_eff_parsing_state * ps, kest_eff_entry_dict * dict, const char * name)
Definition at line 1818 of file kest_dict_extract.c.
Referenced by kest_extract_resource().
kest_extract_filter_coefs_from_dict()
int kest_extract_filter_coefs_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict, kest_dsp_resource * res)
Definition at line 699 of file kest_dict_extract.c.
Referenced by kest_extract_biquad_from_dict(), kest_extract_filter_from_dict(), and kest_extract_polynomial_from_dict().
kest_extract_filter_from_dict()
int kest_extract_filter_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict, kest_dsp_resource * res)
Definition at line 834 of file kest_dict_extract.c.
Referenced by kest_extract_resource_from_dict().
kest_extract_hpf()
kest_dsp_resource * kest_extract_hpf (kest_eff_parsing_state * ps, kest_eff_entry_dict * dict, const char * name)
Definition at line 2125 of file kest_dict_extract.c.
Referenced by kest_extract_resource().
kest_extract_hpf_from_dict()
int kest_extract_hpf_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict, kest_dsp_resource * res)
Definition at line 126 of file kest_dict_extract.c.
Referenced by kest_extract_resource_from_dict().
kest_extract_int_setting_from_dict()
int kest_extract_int_setting_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict, kest_setting * setting)
Definition at line 403 of file kest_dict_extract.c.
Referenced by kest_extract_setting_from_dict().
kest_extract_lfo()
kest_dsp_resource * kest_extract_lfo (kest_eff_parsing_state * ps, kest_eff_entry_dict * dict, const char * name)
Definition at line 2398 of file kest_dict_extract.c.
Referenced by kest_extract_resource().
kest_extract_lpf()
kest_dsp_resource * kest_extract_lpf (kest_eff_parsing_state * ps, kest_eff_entry_dict * dict, const char * name)
Definition at line 1990 of file kest_dict_extract.c.
Referenced by kest_extract_resource().
kest_extract_lpf_from_dict()
int kest_extract_lpf_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict, kest_dsp_resource * res)
Definition at line 8 of file kest_dict_extract.c.
Referenced by kest_extract_resource_from_dict().
kest_extract_mem()
kest_dsp_resource * kest_extract_mem (kest_eff_parsing_state * ps, kest_eff_entry_dict * dict, const char * name)
Definition at line 1597 of file kest_dict_extract.c.
Referenced by kest_extract_resource().
kest_extract_mem_from_dict()
int kest_extract_mem_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict, kest_dsp_resource * res)
Definition at line 631 of file kest_dict_extract.c.
Referenced by kest_extract_resource_from_dict().
kest_extract_parameter()
kest_parameter * kest_extract_parameter (kest_eff_parsing_state * ps, kest_eff_entry_dict * dict, const char * name)
Definition at line 1093 of file kest_dict_extract.c.
Referenced by kest_parameters_section_extract().
kest_extract_polynomial()
kest_dsp_resource * kest_extract_polynomial (kest_eff_parsing_state * ps, kest_eff_entry_dict * dict, const char * name)
Definition at line 2561 of file kest_dict_extract.c.
Referenced by kest_extract_resource().
kest_extract_polynomial_from_dict()
int kest_extract_polynomial_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict, kest_dsp_resource * res)
Definition at line 798 of file kest_dict_extract.c.
Referenced by kest_extract_resource_from_dict().
kest_extract_resource()
kest_dsp_resource * kest_extract_resource (kest_eff_parsing_state * ps, kest_eff_entry_dict * dict, const char * name)
Definition at line 1527 of file kest_dict_extract.c.
Referenced by kest_resources_section_extract().
kest_extract_resource_from_dict()
kest_dsp_resource * kest_extract_resource_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict)
Definition at line 892 of file kest_dict_extract.c.
kest_extract_setting()
kest_setting * kest_extract_setting (kest_eff_parsing_state * ps, kest_eff_entry_dict * dict, const char * name)
Definition at line 1311 of file kest_dict_extract.c.
Referenced by kest_settings_section_extract().
kest_extract_setting_from_dict()
kest_setting * kest_extract_setting_from_dict (kest_eff_parsing_state * ps, kest_ast_node * dict_node, kest_dictionary * dict)
Definition at line 464 of file kest_dict_extract.c.