Kestrel Interface: kest_event.h File Reference
kest_event.h File Reference
Data Structures
struct kest_event
Macros
#define KEST_EVENT_NONE 0
#define KEST_EVENT_STARTUP 1
#define KEST_EVENT_PARAM_CHANGE 2
Functions
int kest_event_task_start ()
int kest_event_log (kest_event event)
Macro Definition Documentation
KEST_EVENT_NONE
#define KEST_EVENT_NONE 0
Definition at line 4 of file kest_event.h.
KEST_EVENT_PARAM_CHANGE
#define KEST_EVENT_PARAM_CHANGE 2
Definition at line 6 of file kest_event.h.
Referenced by kest_event_handle().
KEST_EVENT_STARTUP
#define KEST_EVENT_STARTUP 1
Definition at line 5 of file kest_event.h.
Referenced by app_main(), kest_event_handle(), and main_task().
Function Documentation
kest_event_log()
int kest_event_log (kest_event event)
Definition at line 37 of file kest_event.c.
Referenced by app_main(), and main_task().
kest_event_task_start()
int kest_event_task_start ()
Definition at line 11 of file kest_event.c.
Referenced by app_main(), and main_task().