Kestrel Interface: kest_preset_view.c File Reference
kest_preset_view.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
kest_ui_page * create_preset_view_for (kest_preset *preset)
int preset_view_effect_click_cb (kest_active_button *button)
int preset_view_effect_moved_cb (kest_active_button *button)
int preset_view_effect_delete_cb (kest_active_button *button)
int init_preset_view (kest_ui_page *page)
int preset_view_save_name (kest_ui_page *page)
void preset_view_save_name_cb (lv_event_t *e)
void preset_view_revert_name (lv_event_t *e)
void preset_view_enter_settings_page_cb (lv_event_t *e)
void preset_view_enter_main_menu_cb (lv_event_t *e)
void preset_view_play_button_cb (lv_event_t *e)
int configure_preset_view (kest_ui_page *page, void *data)
int create_preset_view_ui (kest_ui_page *page)
int enter_preset_view (kest_ui_page *page)
int preset_view_append_effect (kest_ui_page *page, kest_effect *effect)
int preset_view_recalculate_indices (kest_ui_page *page)
int free_preset_view (kest_ui_page *page)
int preset_view_refresh_play_button (kest_ui_page *page)
int preset_view_refresh_save_button (kest_ui_page *page)
int preset_view_change_name (kest_ui_page *page, char *name)
int preset_view_set_left_button_mode (kest_ui_page *page, int mode)
void preset_view_rep_update (void *representer, void *representee)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_preset_view.c.
Function Documentation
configure_preset_view()
int configure_preset_view (kest_ui_page * page, void * data)
Definition at line 337 of file kest_preset_view.c.
Referenced by create_preset_view_for(), and init_preset_view().
create_preset_view_for()
kest_ui_page * create_preset_view_for (kest_preset * preset)
Definition at line 9 of file kest_preset_view.c.
Referenced by create_new_preset_with_teensy(), load_saved_presets(), and seq_view_clicked_cb().
create_preset_view_ui()
int create_preset_view_ui (kest_ui_page * page)
Definition at line 418 of file kest_preset_view.c.
Referenced by init_preset_view().
enter_preset_view()
int enter_preset_view (kest_ui_page * page)
Definition at line 474 of file kest_preset_view.c.
Referenced by init_preset_view().
free_preset_view()
int free_preset_view (kest_ui_page * page)
Definition at line 523 of file kest_preset_view.c.
Referenced by create_preset_view_for(), and init_preset_view().
init_preset_view()
int init_preset_view (kest_ui_page * page)
Definition at line 118 of file kest_preset_view.c.
Referenced by create_preset_view_for().
preset_view_append_effect()
int preset_view_append_effect (kest_ui_page * page, kest_effect * effect)
Definition at line 490 of file kest_preset_view.c.
Referenced by add_effect_from_menu_eff().
preset_view_change_name()
int preset_view_change_name (kest_ui_page * page, char * name)
Definition at line 554 of file kest_preset_view.c.
preset_view_effect_click_cb()
int preset_view_effect_click_cb (kest_active_button * button)
Definition at line 47 of file kest_preset_view.c.
Referenced by init_preset_view().
preset_view_effect_delete_cb()
int preset_view_effect_delete_cb (kest_active_button * button)
Definition at line 93 of file kest_preset_view.c.
Referenced by init_preset_view().
preset_view_effect_moved_cb()
int preset_view_effect_moved_cb (kest_active_button * button)
Definition at line 69 of file kest_preset_view.c.
Referenced by init_preset_view().
preset_view_enter_main_menu_cb()
void preset_view_enter_main_menu_cb (lv_event_t * e)
Definition at line 302 of file kest_preset_view.c.
preset_view_enter_settings_page_cb()
void preset_view_enter_settings_page_cb (lv_event_t * e)
Definition at line 287 of file kest_preset_view.c.
Referenced by configure_preset_view().
preset_view_play_button_cb()
void preset_view_play_button_cb (lv_event_t * e)
Definition at line 307 of file kest_preset_view.c.
Referenced by configure_preset_view().
preset_view_recalculate_indices()
int preset_view_recalculate_indices (kest_ui_page * page)
Definition at line 512 of file kest_preset_view.c.
preset_view_refresh_play_button()
int preset_view_refresh_play_button (kest_ui_page * page)
Definition at line 535 of file kest_preset_view.c.
preset_view_refresh_save_button()
int preset_view_refresh_save_button (kest_ui_page * page)
Definition at line 546 of file kest_preset_view.c.
preset_view_rep_update()
void preset_view_rep_update (void * representer, void * representee)
Definition at line 579 of file kest_preset_view.c.
Referenced by init_preset_view().
preset_view_revert_name()
void preset_view_revert_name (lv_event_t * e)
Definition at line 274 of file kest_preset_view.c.
Referenced by configure_preset_view().
preset_view_save_name()
int preset_view_save_name (kest_ui_page * page)
Definition at line 237 of file kest_preset_view.c.
Referenced by preset_view_save_name_cb().
preset_view_save_name_cb()
void preset_view_save_name_cb (lv_event_t * e)
Definition at line 268 of file kest_preset_view.c.
Referenced by configure_preset_view().
preset_view_set_left_button_mode()
int preset_view_set_left_button_mode (kest_ui_page * page, int mode)
Definition at line 567 of file kest_preset_view.c.