Kestrel Interface: kest_effect.h File Reference
kest_effect.h File Reference
Data Structures
struct kest_effect
Macros
#define EFFECT_MODE_FULL_SPECTRUM 0
#define EFFECT_MODE_UPPER_SPECTRUM 1
#define EFFECT_MODE_LOWER_SPECTRUM 2
#define EFFECT_MODE_BAND 3
#define EFFECT_WET_MIX_PID 0xFFFF
#define EFFECT_BAND_LP_CUTOFF_PID 0xFFFE
#define EFFECT_BAND_HP_CUTOFF_PID 0xFFFD
#define EFFECT_BAND_MODE_SID 0xFFFF
Functions
const char * kest_effect_name (kest_effect *effect)
DECLARE_LINKED_PTR_LIST (kest_effect)
DECLARE_PTR_LIST (kest_effect)
int init_effect (kest_effect *effect)
int effect_set_id (kest_effect *effect, uint16_t preset_id, uint16_t effect_id)
int effect_rectify_param_ids (kest_effect *effect)
kest_parameter * effect_add_parameter (kest_effect *effect)
kest_setting * effect_add_setting (kest_effect *effect)
int init_default_effect_by_type (kest_effect *effect, uint16_t type, uint16_t preset_id, uint16_t effect_id)
int init_effect_from_effect_desc (kest_effect *effect, kest_effect_desc *eff)
int clone_effect (kest_effect *dest, kest_effect *src)
void free_effect (kest_effect *effect)
kest_parameter * effect_get_parameter (kest_effect *effect, int n)
kest_setting * effect_get_setting (kest_effect *effect, int n)
int kest_effect_update_fpga (kest_effect *effect)
int kest_fpga_transfer_batch_append_effect (kest_effect *effect, const kest_eff_resource_report *cxt, kest_eff_resource_report *report, kest_fpga_transfer_batch *batch)
int kest_effect_is_updated (kest_effect *effect)
int kest_effect_create_scope (kest_effect *effect)
int kest_effect_set_parameter (kest_effect *effect, const char *name, float value)
int kest_effect_set_setting (kest_effect *effect, const char *name, int value)
int kest_effect_update_reps (kest_effect *effect)
void kest_effect_preset_rep_update (void *representer, void *representee)
void kest_effect_page_rep_update (void *representer, void *representee)
int kest_effect_activate_dma (kest_effect *effect)
int kest_effect_deactivate_dma (kest_effect *effect)
int kest_effect_activate_dma_async (kest_effect *effect)
int kest_effect_deactivate_dma_async (kest_effect *effect)
int kest_effect_activate_lfos (kest_effect *effect)
int kest_effect_deactivate_lfos (kest_effect *effect)
int kest_effect_activate_lfos_async (kest_effect *effect)
int kest_effect_deactivate_lfos_async (kest_effect *effect)
int kest_effect_enable (kest_effect *effect)
int kest_effect_disable (kest_effect *effect)
int kest_effect_init_view_page (kest_effect *effect, struct kest_ui_page *parent)
int kest_effect_handle_updates (kest_effect *effect)
int kest_effect_handle_updates_inc_ui (kest_effect *effect)
void kest_effect_update_sync (void *effect_)
void kest_effect_update_sync_no_pw (void *effect_)
int kest_effect_update_pws (kest_effect *effect)
int kest_effect_clear_updates (kest_effect *effect)
int kest_effect_update_position (kest_effect *effect, kest_effect_fpga_position pos)
DECLARE_POOL (kest_effect)
Variables
kest_allocator kest_effect_allocator
kest_effect_pool kest_effect_mem_pool
Macro Definition Documentation
EFFECT_BAND_HP_CUTOFF_PID
#define EFFECT_BAND_HP_CUTOFF_PID 0xFFFD
Definition at line 12 of file kest_effect.h.
Referenced by init_effect().
EFFECT_BAND_LP_CUTOFF_PID
#define EFFECT_BAND_LP_CUTOFF_PID 0xFFFE
Definition at line 11 of file kest_effect.h.
Referenced by init_effect().
EFFECT_BAND_MODE_SID
#define EFFECT_BAND_MODE_SID 0xFFFF
Definition at line 13 of file kest_effect.h.
Referenced by init_effect().
EFFECT_MODE_BAND
#define EFFECT_MODE_BAND 3
Definition at line 7 of file kest_effect.h.
Referenced by init_effect(), and refresh_effect_settings_page().
EFFECT_MODE_FULL_SPECTRUM
#define EFFECT_MODE_FULL_SPECTRUM 0
Definition at line 4 of file kest_effect.h.
Referenced by init_effect(), and refresh_effect_settings_page().
EFFECT_MODE_LOWER_SPECTRUM
#define EFFECT_MODE_LOWER_SPECTRUM 2
Definition at line 6 of file kest_effect.h.
Referenced by init_effect(), and refresh_effect_settings_page().
EFFECT_MODE_UPPER_SPECTRUM
#define EFFECT_MODE_UPPER_SPECTRUM 1
Definition at line 5 of file kest_effect.h.
Referenced by init_effect(), and refresh_effect_settings_page().
EFFECT_WET_MIX_PID
#define EFFECT_WET_MIX_PID 0xFFFF
Definition at line 9 of file kest_effect.h.
Referenced by init_effect().
Function Documentation
clone_effect()
int clone_effect (kest_effect * dest, kest_effect * src)
Definition at line 462 of file kest_effect.c.
Referenced by clone_pipeline().
DECLARE_LINKED_PTR_LIST()
DECLARE_LINKED_PTR_LIST (kest_effect)
DECLARE_POOL()
DECLARE_POOL (kest_effect)
DECLARE_PTR_LIST()
DECLARE_PTR_LIST (kest_effect)
effect_add_parameter()
kest_parameter * effect_add_parameter (kest_effect * effect)
Definition at line 385 of file kest_effect.c.
Referenced by clone_effect().
effect_add_setting()
kest_setting * effect_add_setting (kest_effect * effect)
Definition at line 412 of file kest_effect.c.
Referenced by clone_effect().
effect_get_parameter()
kest_parameter * effect_get_parameter (kest_effect * effect, int n)
Definition at line 604 of file kest_effect.c.
Referenced by cxt_get_parameter_and_effect_by_id(), and cxt_get_parameter_by_id().
effect_get_setting()
kest_setting * effect_get_setting (kest_effect * effect, int n)
Definition at line 622 of file kest_effect.c.
Referenced by cxt_get_setting_by_id().
effect_rectify_param_ids()
int effect_rectify_param_ids (kest_effect * effect)
Definition at line 313 of file kest_effect.c.
Referenced by effect_set_id(), kest_pipeline_rectify_ids(), and kest_preset_append_effect_eff().
effect_set_id()
int effect_set_id (kest_effect * effect, uint16_t preset_id, uint16_t effect_id)
Definition at line 373 of file kest_effect.c.
free_effect()
void free_effect (kest_effect * effect)
Definition at line 587 of file kest_effect.c.
Referenced by gut_pipeline(), and kest_pipeline_remove_effect().
init_default_effect_by_type()
int init_default_effect_by_type (kest_effect * effect, uint16_t type, uint16_t preset_id, uint16_t effect_id)
init_effect()
int init_effect (kest_effect * effect)
Definition at line 25 of file kest_effect.c.
Referenced by clone_effect(), and init_effect_from_effect_desc().
init_effect_from_effect_desc()
int init_effect_from_effect_desc (kest_effect * effect, kest_effect_desc * eff)
Definition at line 112 of file kest_effect.c.
Referenced by kest_pipeline_append_effect_eff().
kest_effect_activate_dma()
int kest_effect_activate_dma (kest_effect * effect)
Definition at line 946 of file kest_effect.c.
kest_effect_activate_dma_async()
int kest_effect_activate_dma_async (kest_effect * effect)
Definition at line 980 of file kest_effect.c.
Referenced by kest_pipeline_activate_dma().
kest_effect_activate_lfos()
int kest_effect_activate_lfos (kest_effect * effect)
Definition at line 1086 of file kest_effect.c.
kest_effect_activate_lfos_async()
int kest_effect_activate_lfos_async (kest_effect * effect)
Definition at line 1121 of file kest_effect.c.
Referenced by kest_pipeline_activate_lfos().
kest_effect_clear_updates()
int kest_effect_clear_updates (kest_effect * effect)
Definition at line 1315 of file kest_effect.c.
Referenced by kest_effect_handle_updates_inc_ui().
kest_effect_create_scope()
int kest_effect_create_scope (kest_effect * effect)
Definition at line 693 of file kest_effect.c.
Referenced by init_effect_from_effect_desc().
kest_effect_deactivate_dma()
int kest_effect_deactivate_dma (kest_effect * effect)
Definition at line 1023 of file kest_effect.c.
Referenced by kest_fpga_batch_append_effect().
kest_effect_deactivate_dma_async()
int kest_effect_deactivate_dma_async (kest_effect * effect)
Definition at line 1055 of file kest_effect.c.
Referenced by kest_pipeline_deactivate_dma().
kest_effect_deactivate_lfos()
int kest_effect_deactivate_lfos (kest_effect * effect)
kest_effect_deactivate_lfos_async()
int kest_effect_deactivate_lfos_async (kest_effect * effect)
Definition at line 1158 of file kest_effect.c.
Referenced by kest_pipeline_deactivate_lfos().
kest_effect_disable()
int kest_effect_disable (kest_effect * effect)
Definition at line 1395 of file kest_effect.c.
Referenced by kest_pipeline_remove_effect().
kest_effect_enable()
int kest_effect_enable (kest_effect * effect)
Definition at line 1390 of file kest_effect.c.
kest_effect_handle_updates()
int kest_effect_handle_updates (kest_effect * effect)
Definition at line 1208 of file kest_effect.c.
Referenced by kest_active_preset_updater_task(), and kest_effect_update_sync().
kest_effect_handle_updates_inc_ui()
int kest_effect_handle_updates_inc_ui (kest_effect * effect)
Definition at line 1261 of file kest_effect.c.
Referenced by kest_active_preset_updater_task().
kest_effect_init_view_page()
int kest_effect_init_view_page (kest_effect * effect, struct kest_ui_page * parent)
Referenced by add_effect_from_menu_eff(), and configure_preset_view().
kest_effect_is_updated()
int kest_effect_is_updated (kest_effect * effect)
Definition at line 639 of file kest_effect.c.
Referenced by kest_effect_handle_updates(), kest_effect_handle_updates_inc_ui(), kest_effect_update_fpga(), kest_effect_update_sync_no_pw(), and kest_fpga_transfer_batch_append_effect_updates().
kest_effect_name()
const char * kest_effect_name (kest_effect * effect)
Definition at line 14 of file kest_effect.c.
Referenced by configure_effect_settings_page(), configure_effect_view(), configure_preset_view(), context_print_presets(), create_effect_view_ui(), and preset_view_append_effect().
kest_effect_page_rep_update()
void kest_effect_page_rep_update (void * representer, void * representee)
Definition at line 896 of file kest_effect.c.
Referenced by init_effect().
kest_effect_preset_rep_update()
void kest_effect_preset_rep_update (void * representer, void * representee)
Definition at line 873 of file kest_effect.c.
Referenced by init_effect().
kest_effect_set_parameter()
int kest_effect_set_parameter (kest_effect * effect, const char * name, float value)
Definition at line 826 of file kest_effect.c.
kest_effect_set_setting()
int kest_effect_set_setting (kest_effect * effect, const char * name, int value)
Definition at line 849 of file kest_effect.c.
kest_effect_update_fpga()
int kest_effect_update_fpga (kest_effect * effect)
Definition at line 652 of file kest_effect.c.
kest_effect_update_position()
int kest_effect_update_position (kest_effect * effect, kest_effect_fpga_position pos)
Definition at line 1453 of file kest_effect.c.
Referenced by kest_fpga_batch_append_effect().
kest_effect_update_pws()
int kest_effect_update_pws (kest_effect * effect)
Definition at line 1189 of file kest_effect.c.
Referenced by kest_effect_handle_updates_inc_ui().
kest_effect_update_reps()
int kest_effect_update_reps (kest_effect * effect)
Definition at line 933 of file kest_effect.c.
Referenced by kest_parameter_effect_rep_update(), and kest_setting_effect_rep_update().
kest_effect_update_sync()
void kest_effect_update_sync (void * effect_)
Definition at line 1326 of file kest_effect.c.
kest_effect_update_sync_no_pw()
void kest_effect_update_sync_no_pw (void * effect_)
Definition at line 1335 of file kest_effect.c.
kest_fpga_transfer_batch_append_effect()
int kest_fpga_transfer_batch_append_effect (kest_effect * effect, const kest_eff_resource_report * cxt, kest_eff_resource_report * report, kest_fpga_transfer_batch * batch)
Variable Documentation
kest_effect_allocator
kest_allocator kest_effect_allocator extern
Definition at line 11 of file kest_effect.c.
Referenced by clone_pipeline(), DECLARE_POOL(), free_effect(), and kest_pipeline_append_effect_eff().
kest_effect_mem_pool
kest_effect_pool kest_effect_mem_pool extern
Definition at line 12 of file kest_effect.c.
Referenced by DECLARE_POOL().