Kestrel Interface: kest_preset.h File Reference
kest_preset.h File Reference
Data Structures
struct kest_preset
Macros
#define PRESET_NAME_MAX_LEN 128
#define KEST_PRESET_MUTEX_TIMEOUT_MS 10
Functions
DECLARE_LINKED_PTR_LIST (kest_preset)
int init_m_preset (kest_preset *preset)
int init_m_pipeline (kest_pipeline *pipeline)
int preset_set_id (kest_preset *preset, uint16_t id)
int kest_preset_rectify_ids (kest_preset *preset)
int kest_preset_set_default_name_from_id (kest_preset *preset)
kest_effect * kest_preset_append_effect_eff (kest_preset *preset, kest_effect_desc *eff)
int kest_preset_remove_effect (kest_preset *preset, uint16_t id)
int kest_preset_move_effect (kest_preset *preset, int new_pos, int old_pos)
int clone_preset (kest_preset *dest, kest_preset *src)
void gut_preset (kest_preset *preset)
void free_preset (kest_preset *preset)
void kest_free_preset (kest_preset *preset)
int kest_preset_set_active (kest_preset *preset)
int kest_preset_set_inactive (kest_preset *preset)
int kest_preset_clear_pending (kest_preset *preset)
int kest_preset_add_representation (kest_preset *preset, kest_representation *rep)
int kest_preset_remove_representation (kest_preset *preset, kest_representation *rep)
int kest_preset_add_name_representation (kest_preset *preset, kest_representation *rep)
int kest_preset_remove_name_representation (kest_preset *preset, kest_representation *rep)
int kest_preset_add_id_representation (kest_preset *preset, kest_representation *rep)
int kest_preset_remove_id_representation (kest_preset *preset, kest_representation *rep)
int kest_preset_save (kest_preset *preset)
int kest_preset_update_representations (kest_preset *preset)
int kest_preset_update_name_representations (kest_preset *preset)
int kest_preset_update_id_representations (kest_preset *preset)
int kest_preset_create_fpga_transfer_batch (kest_preset *preset, kest_fpga_transfer_batch *batch)
int kest_preset_if_active_update_fpga (kest_preset *preset)
int kest_preset_if_active_reprogram_fpga (kest_preset *preset)
int kest_preset_program_fpga (kest_preset *preset)
void kest_preset_file_rep_update (void *representer, void *representee)
kest_effect * kest_preset_get_effect_by_id (kest_preset *preset, int id)
int kest_preset_activate_dma (kest_preset *preset)
int kest_preset_deactivate_dma (kest_preset *preset)
int kest_preset_activate_lfos (kest_preset *preset)
int kest_preset_deactivate_lfos (kest_preset *preset)
DECLARE_POOL (kest_preset)
Variables
kest_allocator kest_preset_allocator
kest_preset_pool kest_preset_mem_pool
Macro Definition Documentation
KEST_PRESET_MUTEX_TIMEOUT_MS
#define KEST_PRESET_MUTEX_TIMEOUT_MS 10
Definition at line 6 of file kest_preset.h.
PRESET_NAME_MAX_LEN
#define PRESET_NAME_MAX_LEN 128
Definition at line 4 of file kest_preset.h.
Referenced by clone_preset(), cxt_find_preset(), preset_view_save_name(), and sequence_view_set_name().
Function Documentation
clone_preset()
int clone_preset (kest_preset * dest, kest_preset * src)
Definition at line 310 of file kest_preset.c.
DECLARE_LINKED_PTR_LIST()
DECLARE_LINKED_PTR_LIST (kest_preset)
DECLARE_POOL()
DECLARE_POOL (kest_preset)
free_preset()
void free_preset (kest_preset * preset)
Definition at line 357 of file kest_preset.c.
Referenced by cxt_remove_preset(), kest_context_add_preset(), kest_context_add_preset_rp(), kest_free_preset(), and load_saved_presets().
gut_preset()
void gut_preset (kest_preset * preset)
Definition at line 333 of file kest_preset.c.
Referenced by free_preset().
init_m_pipeline()
int init_m_pipeline (kest_pipeline * pipeline)
Definition at line 9 of file kest_pipeline.c.
Referenced by init_m_preset().
init_m_preset()
int init_m_preset (kest_preset * preset)
Definition at line 17 of file kest_preset.c.
Referenced by kest_context_add_preset(), kest_context_add_preset_rp(), and load_saved_presets().
kest_free_preset()
void kest_free_preset (kest_preset * preset)
Definition at line 367 of file kest_preset.c.
Referenced by kest_sequence_delete_preset().
kest_preset_activate_dma()
int kest_preset_activate_dma (kest_preset * preset)
Definition at line 96 of file kest_preset.c.
Referenced by activate_active_preset_dma().
kest_preset_activate_lfos()
int kest_preset_activate_lfos (kest_preset * preset)
Definition at line 113 of file kest_preset.c.
Referenced by activate_active_preset_lfos().
kest_preset_add_id_representation()
int kest_preset_add_id_representation (kest_preset * preset, kest_representation * rep)
kest_preset_add_name_representation()
int kest_preset_add_name_representation (kest_preset * preset, kest_representation * rep)
kest_preset_add_representation()
int kest_preset_add_representation (kest_preset * preset, kest_representation * rep)
Definition at line 168 of file kest_preset.c.
Referenced by configure_preset_view(), and seq_plus_cb().
kest_preset_append_effect_eff()
kest_effect * kest_preset_append_effect_eff (kest_preset * preset, kest_effect_desc * eff)
Definition at line 244 of file kest_preset.c.
Referenced by add_effect_from_menu_eff(), and read_preset_from_file().
kest_preset_clear_pending()
int kest_preset_clear_pending (kest_preset * preset)
Definition at line 145 of file kest_preset.c.
Referenced by kest_fpga_comms_task().
kest_preset_create_fpga_transfer_batch()
int kest_preset_create_fpga_transfer_batch (kest_preset * preset, kest_fpga_transfer_batch * batch)
Definition at line 418 of file kest_preset.c.
kest_preset_deactivate_dma()
int kest_preset_deactivate_dma (kest_preset * preset)
Definition at line 105 of file kest_preset.c.
Referenced by kest_preset_set_inactive().
kest_preset_deactivate_lfos()
int kest_preset_deactivate_lfos (kest_preset * preset)
Definition at line 121 of file kest_preset.c.
kest_preset_file_rep_update()
void kest_preset_file_rep_update (void * representer, void * representee)
Definition at line 525 of file kest_preset.c.
Referenced by init_m_preset().
kest_preset_get_effect_by_id()
kest_effect * kest_preset_get_effect_by_id (kest_preset * preset, int id)
Definition at line 541 of file kest_preset.c.
Referenced by kest_active_preset_updater_task(), and kest_page_id_find_page().
kest_preset_if_active_reprogram_fpga()
int kest_preset_if_active_reprogram_fpga (kest_preset * preset)
Definition at line 489 of file kest_preset.c.
Referenced by add_effect_from_menu_eff(), kest_preset_move_effect(), and kest_preset_remove_effect().
kest_preset_if_active_update_fpga()
int kest_preset_if_active_update_fpga (kest_preset * preset)
Definition at line 507 of file kest_preset.c.
Referenced by kest_fpga_update_task(), preset_view_effect_delete_cb(), and sw_field_save_cb().
kest_preset_move_effect()
int kest_preset_move_effect (kest_preset * preset, int new_pos, int old_pos)
Definition at line 287 of file kest_preset.c.
Referenced by preset_view_effect_moved_cb().
kest_preset_program_fpga()
int kest_preset_program_fpga (kest_preset * preset)
Definition at line 431 of file kest_preset.c.
Referenced by kest_preset_if_active_reprogram_fpga().
kest_preset_rectify_ids()
int kest_preset_rectify_ids (kest_preset * preset)
Definition at line 82 of file kest_preset.c.
Referenced by load_saved_presets().
kest_preset_remove_effect()
int kest_preset_remove_effect (kest_preset * preset, uint16_t id)
Definition at line 269 of file kest_preset.c.
Referenced by cxt_remove_effect(), and preset_view_effect_delete_cb().
kest_preset_remove_id_representation()
int kest_preset_remove_id_representation (kest_preset * preset, kest_representation * rep)
kest_preset_remove_name_representation()
int kest_preset_remove_name_representation (kest_preset * preset, kest_representation * rep)
kest_preset_remove_representation()
int kest_preset_remove_representation (kest_preset * preset, kest_representation * rep)
Definition at line 202 of file kest_preset.c.
kest_preset_save()
int kest_preset_save (kest_preset * preset)
Definition at line 396 of file kest_preset.c.
Referenced by cxt_save_all_presets().
kest_preset_set_active()
int kest_preset_set_active (kest_preset * preset)
Definition at line 129 of file kest_preset.c.
Referenced by set_active_preset(), and set_active_preset_from_sequence().
kest_preset_set_default_name_from_id()
int kest_preset_set_default_name_from_id (kest_preset * preset)
Definition at line 214 of file kest_preset.c.
Referenced by configure_preset_settings_page(), and create_preset_view_ui().
kest_preset_set_inactive()
int kest_preset_set_inactive (kest_preset * preset)
Definition at line 155 of file kest_preset.c.
Referenced by set_active_preset(), and set_active_preset_from_sequence().
kest_preset_update_id_representations()
int kest_preset_update_id_representations (kest_preset * preset)
kest_preset_update_name_representations()
int kest_preset_update_name_representations (kest_preset * preset)
kest_preset_update_representations()
int kest_preset_update_representations (kest_preset * preset)
Definition at line 189 of file kest_preset.c.
Referenced by add_effect_from_menu_eff(), kest_preset_save(), and kest_preset_set_inactive().
preset_set_id()
int preset_set_id (kest_preset * preset, uint16_t id)
Definition at line 71 of file kest_preset.c.
Variable Documentation
kest_preset_allocator
kest_allocator kest_preset_allocator extern
Definition at line 12 of file kest_preset.c.
Referenced by DECLARE_POOL(), free_preset(), and load_saved_presets().
kest_preset_mem_pool
kest_preset_pool kest_preset_mem_pool extern
Definition at line 13 of file kest_preset.c.
Referenced by DECLARE_POOL().