Kestrel Interface: kest_update.c File Reference
kest_update.c File Reference
#include "kest_int.h"
Data Structures
struct kest_effect_update
struct kest_update_
Macros
#define PRINTLINES_ALLOWED 1
#define UPDATE_DATA_SIZE 32
#define KEST_EFFECT_UPDATE_BY_ID 0
#define KEST_EFFECT_UPDATE_BY_PTR 1
#define KEST_UPDATE_TYPE_NONE 0
#define KEST_UPDATE_TYPE_EFFECT 1
#define UPDATE_RATE_HZ 50
#define UPDATE_PERIOD_MS (1000.0f / (float)UPDATE_RATE_HZ)
Functions
void kest_active_preset_updater_task (void *arg)
void kest_active_preset_updater_start ()
int kest_active_preset_updater_notify_effect_by_id (int preset_id, int effect_id)
int kest_active_preset_updater_notify_effect_by_ptr (kest_effect *effect)
void kest_update_task (void *arg)
IMPLEMENT_LIST (kest_fpga_write)
IMPLEMENT_LIST (kest_fpga_alloc)
int kest_updater_state_init (kest_updater_state *state)
void kest_updater_state_destroy (kest_updater_state *state)
int kest_fpga_write_generate_update (kest_fpga_write *write, kest_dependent *dep, kest_effect *effect)
int kest_update_task_start ()
int kest_updater_handle_update (kest_updater_state *state, kest_update update)
int kest_updater_add_reg_update (kest_updater_state *state, kest_dependent *dep, kest_effect *effect)
int kest_updater_add_filter_coef_update (kest_updater_state *state, kest_dependent *dep, kest_effect *effect)
void kest_updater_print_reg_writes (kest_updater_state *state)
void kest_updater_print_filter_writes (kest_updater_state *state)
void kest_updater_print_command_list (kest_updater_state *state)
void kest_updater_print_instr_writes (kest_updater_state *state)
void kest_updater_print_allocs (kest_updater_state *state)
int kest_updater_drain_lists (kest_updater_state *state)
int kest_updater_generate_command_list (kest_updater_state *state)
int kest_updater_generate_tx_batch (kest_updater_state *state)
int kest_updater_send (kest_updater_state *state)
int kest_updater_notify_param (kest_parameter *param)
int kest_updater_notify_preset (kest_preset *preset)
int kest_update_queue (kest_update update)
int kest_updater_handle_preset_update (kest_updater_state *state, kest_preset *preset)
int kest_alloc_for_filter (kest_fpga_alloc *alloc, kest_dsp_resource *res)
int kest_alloc_for_delay (kest_fpga_alloc *alloc, kest_dsp_resource *res, kest_scope *scope)
int kest_alloc_to_command (kest_fpga_command *cmd, kest_fpga_alloc *alloc)
int kest_updater_handle_preset_update_add_filter_writes (kest_updater_state *state, int handle, kest_filter *filter, kest_scope *scope)
int kest_updater_handle_preset_update_add_effect (kest_updater_state *state, kest_effect *effect)
int kest_fpga_write_to_command (kest_fpga_command *dest, kest_fpga_write *src)
kest_fpga_transfer_batch kest_standalone_generate_program_batch (kest_effect_ptr_list *effects)
Variables
QueueHandle_t update_queue = NULL
QueueHandle_t update_queue_ = NULL
Macro Definition Documentation
KEST_EFFECT_UPDATE_BY_ID
#define KEST_EFFECT_UPDATE_BY_ID 0
Definition at line 9 of file kest_update.c.
Referenced by kest_active_preset_updater_notify_effect_by_id(), and kest_active_preset_updater_task().
KEST_EFFECT_UPDATE_BY_PTR
#define KEST_EFFECT_UPDATE_BY_PTR 1
Definition at line 10 of file kest_update.c.
Referenced by kest_active_preset_updater_notify_effect_by_ptr(), and kest_active_preset_updater_task().
KEST_UPDATE_TYPE_EFFECT
#define KEST_UPDATE_TYPE_EFFECT 1
Definition at line 21 of file kest_update.c.
Referenced by kest_active_preset_updater_notify_effect_by_id(), kest_active_preset_updater_notify_effect_by_ptr(), and kest_active_preset_updater_task().
KEST_UPDATE_TYPE_NONE
#define KEST_UPDATE_TYPE_NONE 0
Definition at line 20 of file kest_update.c.
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 1
Definition at line 3 of file kest_update.c.
UPDATE_DATA_SIZE
#define UPDATE_DATA_SIZE 32
Definition at line 7 of file kest_update.c.
UPDATE_PERIOD_MS
#define UPDATE_PERIOD_MS (1000.0f / (float)UPDATE_RATE_HZ)
Definition at line 32 of file kest_update.c.
Referenced by kest_active_preset_updater_task().
UPDATE_RATE_HZ
#define UPDATE_RATE_HZ 50
Definition at line 31 of file kest_update.c.
Function Documentation
IMPLEMENT_LIST() [1/2]
IMPLEMENT_LIST (kest_fpga_alloc)
IMPLEMENT_LIST() [2/2]
IMPLEMENT_LIST (kest_fpga_write)
kest_active_preset_updater_notify_effect_by_id()
int kest_active_preset_updater_notify_effect_by_id (int preset_id, int effect_id)
Definition at line 211 of file kest_update.c.
kest_active_preset_updater_notify_effect_by_ptr()
int kest_active_preset_updater_notify_effect_by_ptr (kest_effect * effect)
Definition at line 233 of file kest_update.c.
Referenced by kest_active_preset_updater_task(), and kest_periodic_mem_read_cb().
kest_active_preset_updater_start()
void kest_active_preset_updater_start ()
Definition at line 203 of file kest_update.c.
kest_active_preset_updater_task()
void kest_active_preset_updater_task (void * arg)
Definition at line 36 of file kest_update.c.
Referenced by kest_active_preset_updater_start().
kest_alloc_for_delay()
int kest_alloc_for_delay (kest_fpga_alloc * alloc, kest_dsp_resource * res, kest_scope * scope)
Definition at line 797 of file kest_update.c.
Referenced by kest_updater_handle_preset_update_add_effect().
kest_alloc_for_filter()
int kest_alloc_for_filter (kest_fpga_alloc * alloc, kest_dsp_resource * res)
Definition at line 779 of file kest_update.c.
Referenced by kest_updater_handle_preset_update_add_effect().
kest_alloc_to_command()
int kest_alloc_to_command (kest_fpga_command * cmd, kest_fpga_alloc * alloc)
Definition at line 855 of file kest_update.c.
Referenced by kest_updater_generate_command_list().
kest_fpga_write_generate_update()
int kest_fpga_write_generate_update (kest_fpga_write * write, kest_dependent * dep, kest_effect * effect)
Definition at line 317 of file kest_update.c.
Referenced by kest_updater_add_filter_coef_update(), and kest_updater_add_reg_update().
kest_fpga_write_to_command()
int kest_fpga_write_to_command (kest_fpga_command * dest, kest_fpga_write * src)
Definition at line 1005 of file kest_update.c.
Referenced by kest_updater_generate_command_list().
kest_standalone_generate_program_batch()
kest_fpga_transfer_batch kest_standalone_generate_program_batch (kest_effect_ptr_list * effects)
Definition at line 1188 of file kest_update.c.
kest_update_queue()
int kest_update_queue (kest_update update)
Definition at line 692 of file kest_update.c.
Referenced by kest_event_handle().
kest_update_task()
void kest_update_task (void * arg)
Definition at line 625 of file kest_update.c.
Referenced by kest_update_task_start().
kest_update_task_start()
int kest_update_task_start ()
Definition at line 423 of file kest_update.c.
Referenced by kest_init().
kest_updater_add_filter_coef_update()
int kest_updater_add_filter_coef_update (kest_updater_state * state, kest_dependent * dep, kest_effect * effect)
Definition at line 464 of file kest_update.c.
Referenced by kest_updater_handle_update().
kest_updater_add_reg_update()
int kest_updater_add_reg_update (kest_updater_state * state, kest_dependent * dep, kest_effect * effect)
Definition at line 438 of file kest_update.c.
Referenced by kest_updater_handle_update().
kest_updater_drain_lists()
int kest_updater_drain_lists (kest_updater_state * state)
Definition at line 605 of file kest_update.c.
Referenced by kest_update_task(), and kest_updater_handle_preset_update().
kest_updater_generate_command_list()
int kest_updater_generate_command_list (kest_updater_state * state)
Definition at line 1065 of file kest_update.c.
Referenced by kest_standalone_generate_program_batch(), and kest_update_task().
kest_updater_generate_tx_batch()
int kest_updater_generate_tx_batch (kest_updater_state * state)
Definition at line 1151 of file kest_update.c.
Referenced by kest_standalone_generate_program_batch(), and kest_update_task().
kest_updater_handle_preset_update()
int kest_updater_handle_preset_update (kest_updater_state * state, kest_preset * preset)
Definition at line 980 of file kest_update.c.
Referenced by kest_updater_handle_update().
kest_updater_handle_preset_update_add_effect()
int kest_updater_handle_preset_update_add_effect (kest_updater_state * state, kest_effect * effect)
Definition at line 898 of file kest_update.c.
Referenced by kest_standalone_generate_program_batch(), and kest_updater_handle_preset_update().
kest_updater_handle_preset_update_add_filter_writes()
int kest_updater_handle_preset_update_add_filter_writes (kest_updater_state * state, int handle, kest_filter * filter, kest_scope * scope)
Definition at line 874 of file kest_update.c.
Referenced by kest_updater_handle_preset_update_add_effect().
kest_updater_handle_update()
int kest_updater_handle_update (kest_updater_state * state, kest_update update)
Definition at line 702 of file kest_update.c.
Referenced by kest_update_task().
kest_updater_notify_param()
int kest_updater_notify_param (kest_parameter * param)
Definition at line 660 of file kest_update.c.
kest_updater_notify_preset()
int kest_updater_notify_preset (kest_preset * preset)
Definition at line 676 of file kest_update.c.
Referenced by kest_preset_set_active().
kest_updater_print_allocs()
void kest_updater_print_allocs (kest_updater_state * state)
Definition at line 572 of file kest_update.c.
Referenced by kest_update_task().
kest_updater_print_command_list()
void kest_updater_print_command_list (kest_updater_state * state)
Definition at line 540 of file kest_update.c.
Referenced by kest_update_task().
kest_updater_print_filter_writes()
void kest_updater_print_filter_writes (kest_updater_state * state)
Definition at line 515 of file kest_update.c.
Referenced by kest_update_task().
kest_updater_print_instr_writes()
void kest_updater_print_instr_writes (kest_updater_state * state)
Definition at line 567 of file kest_update.c.
Referenced by kest_update_task().
kest_updater_print_reg_writes()
void kest_updater_print_reg_writes (kest_updater_state * state)
Definition at line 490 of file kest_update.c.
Referenced by kest_update_task().
kest_updater_send()
int kest_updater_send (kest_updater_state * state)
Definition at line 1166 of file kest_update.c.
Referenced by kest_update_task().
kest_updater_state_destroy()
void kest_updater_state_destroy (kest_updater_state * state)
Definition at line 301 of file kest_update.c.
Referenced by kest_standalone_generate_program_batch().
kest_updater_state_init()
int kest_updater_state_init (kest_updater_state * state)
Definition at line 278 of file kest_update.c.
Referenced by kest_standalone_generate_program_batch(), and kest_update_task().
Variable Documentation
update_queue
QueueHandle_t update_queue = NULL
Definition at line 28 of file kest_update.c.
Referenced by kest_active_preset_updater_notify_effect_by_id(), kest_active_preset_updater_notify_effect_by_ptr(), kest_active_preset_updater_start(), and kest_active_preset_updater_task().
update_queue_
QueueHandle_t update_queue_ = NULL
Definition at line 271 of file kest_update.c.
Referenced by kest_update_queue(), kest_update_task(), kest_update_task_start(), kest_updater_notify_param(), and kest_updater_notify_preset().