Kestrel Interface: kest_expression.c File Reference
kest_expression.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <float.h>
#include <math.h>
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
#define KEST_EXPRESSION_CONST(x)
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_PTR_LIST (kest_expression)
IMPLEMENT_LINKED_PTR_LIST (kest_named_expression)
kest_expression kest_expression_const (float v)
int kest_expr_init_const (kest_expression *expr, float v)
kest_expression * kest_expr_new_const (float v)
int kest_expr_init_unary (kest_expression *expr, int unary_type, kest_expression *rhs)
kest_expression * kest_expr_new_unary (int unary_type, kest_expression *rhs)
int kest_expr_init_binary (kest_expression *expr, int binary_type, kest_expression *arg_1, kest_expression *arg_2)
kest_expression * kest_expr_new_binary (int binary_type, kest_expression *arg_1, kest_expression *arg_2)
int kest_expr_init_reference (kest_expression *expr, char *ref_name)
kest_expression * kest_expr_new_reference (char *ref_name)
int kest_expr_init_neg (kest_expression *expr, kest_expression *a)
kest_expression * kest_expr_new_neg (kest_expression *a)
int kest_expr_init_div (kest_expression *expr, kest_expression *a, kest_expression *b)
kest_expression * kest_expr_new_div (kest_expression *a, kest_expression *b)
int kest_expr_init_mul (kest_expression *expr, kest_expression *a, kest_expression *b)
kest_expression * kest_expr_new_mul (kest_expression *a, kest_expression *b)
int kest_expr_init_2x (kest_expression *expr, kest_expression *x)
kest_expression * kest_expr_new_2x (kest_expression *x)
int kest_expr_init_half_x (kest_expression *expr, kest_expression *x)
kest_expression * kest_expr_new_half_x (kest_expression *x)
int kest_expr_init_sin (kest_expression *expr, kest_expression *x)
kest_expression * kest_expr_new_sin (kest_expression *x)
int kest_expr_init_cos (kest_expression *expr, kest_expression *x)
kest_expression * kest_expr_new_cos (kest_expression *x)
int kest_expr_init_sub (kest_expression *expr, kest_expression *a, kest_expression *b)
kest_expression * kest_expr_new_sub (kest_expression *a, kest_expression *b)
int kest_expr_init_sum (kest_expression *expr, kest_expression *a, kest_expression *b)
kest_expression * kest_expr_new_sum (kest_expression *a, kest_expression *b)
char * kest_expression_type_to_str (int type)
int kest_expression_form (kest_expression *expr)
int kest_expression_arity (kest_expression *expr)
int kest_expression_refers_constant (kest_expression *expr)
int kest_expression_is_constant (kest_expression *expr)
int kest_expression_detect_constants_rec (kest_expression *expr, int depth)
int kest_expression_detect_constants (kest_expression *expr)
float kest_expression_evaluate (kest_expression *expr, kest_scope *scope)
int kest_expression_references_param_rec (kest_expression *expr, kest_parameter *param, int depth)
int kest_expression_references_param (kest_expression *expr, kest_parameter *param)
kest_interval kest_interval_real_line ()
kest_interval kest_interval_ab (float a, float b)
kest_interval kest_interval_a_ (float a)
kest_interval kest_interval__b (float b)
kest_interval kest_interval_singleton (float v)
kest_interval kest_expression_compute_range_rec (kest_expression *expr, kest_scope *scope, int depth)
kest_interval kest_expression_compute_range (kest_expression *expr, kest_scope *scope)
const char * kest_expression_function_string (kest_expression *expr)
const char * kest_expression_infix_operator_string (kest_expression *expr)
int kest_expression_print_rec (kest_expression *expr, char *buf, int buf_len, int depth)
int kest_expression_print (kest_expression *expr)
const char * kest_expression_to_string (kest_expression *expr)
int kest_expr_create_lpf_coefficients (kest_expression **array, kest_expression *cutoff, kest_expression *Q)
int kest_expr_create_hpf_coefficients (kest_expression **array, kest_expression *cutoff, kest_expression *Q)
int kest_expression_get_references_rec (kest_expression *expr, string_list *names, int depth)
int kest_expression_get_references (kest_expression *expr, string_list *names)
int kest_expression_updated_in_scope (kest_expression *expr, kest_scope *scope)
Variables
kest_expression kest_expression_standard_gain_min = KEST_EXPRESSION_CONST(KEST_STANDARD_GAIN_MIN)
kest_expression kest_expression_standard_gain_max = KEST_EXPRESSION_CONST(KEST_STANDARD_GAIN_MAX)
kest_expression kest_expression_zero = KEST_EXPRESSION_CONST(0)
kest_expression kest_expression_one = KEST_EXPRESSION_CONST(1)
kest_expression kest_expression_two = KEST_EXPRESSION_CONST(2)
kest_expression kest_expression_minus_one = KEST_EXPRESSION_CONST(-1)
kest_expression kest_expression_minus_two = KEST_EXPRESSION_CONST(-2)
kest_expression kest_expression_half = KEST_EXPRESSION_CONST(0.5)
kest_expression kest_expression_minus_half = KEST_EXPRESSION_CONST(-0.5)
kest_expression kest_expression_pi = KEST_EXPRESSION_CONST(M_PI)
kest_expression kest_expression_2pi = KEST_EXPRESSION_CONST(2 * M_PI)
kest_expression kest_expression_e = KEST_EXPRESSION_CONST(exp(1))
kest_expression kest_expression_sample_rate = KEST_EXPRESSION_CONST((float)KEST_FPGA_SAMPLE_RATE)
kest_expression kest_expression_int_max = KEST_EXPRESSION_CONST(pow(2, (float)KEST_FPGA_DATA_WIDTH - 1) - 1)
kest_expression kest_expression_int_min = KEST_EXPRESSION_CONST(-pow(2, (float)KEST_FPGA_DATA_WIDTH - 1))
kest_expression kest_expression_freq_max = KEST_EXPRESSION_CONST((float)KEST_FPGA_SAMPLE_RATE / 2 - 50)
kest_expression kest_expression_2pi_over_fs = KEST_EXPRESSION_CONST((2 * M_PI) / (float)KEST_FPGA_SAMPLE_RATE)
kest_expression kest_expression_root_2_over_2 = KEST_EXPRESSION_CONST(sqrt(2.0) / 2.0)
char expr_print_buf [256]
Macro Definition Documentation
KEST_EXPRESSION_CONST
#define KEST_EXPRESSION_CONST (x)
Value:
    {       \
    .type = KEST_EXPR_CONST,         \
    .val = {.val_float = (float)(x)},   \
    .constant = 1,                      \
    .cached = 1,                        \
    .cached_val = (float)(x)            \
};
Definition at line 21 of file kest_expression.c.
PRINTLINES_ALLOWED [1/2]
#define PRINTLINES_ALLOWED 0
Definition at line 10 of file kest_expression.c.
PRINTLINES_ALLOWED [2/2]
#define PRINTLINES_ALLOWED 0
Definition at line 10 of file kest_expression.c.
Function Documentation
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (kest_named_expression)
IMPLEMENT_PTR_LIST()
IMPLEMENT_PTR_LIST (kest_expression)
kest_expr_create_hpf_coefficients()
int kest_expr_create_hpf_coefficients (kest_expression ** array, kest_expression * cutoff, kest_expression * Q)
Definition at line 1611 of file kest_expression.c.
Referenced by kest_extract_hpf_from_dict().
kest_expr_create_lpf_coefficients()
int kest_expr_create_lpf_coefficients (kest_expression ** array, kest_expression * cutoff, kest_expression * Q)
Definition at line 1557 of file kest_expression.c.
Referenced by kest_extract_lpf_from_dict().
kest_expr_init_2x()
int kest_expr_init_2x (kest_expression * expr, kest_expression * x)
Definition at line 216 of file kest_expression.c.
Referenced by kest_expr_create_hpf_coefficients(), and kest_expr_create_lpf_coefficients().
kest_expr_init_binary()
int kest_expr_init_binary (kest_expression * expr, int binary_type, kest_expression * arg_1, kest_expression * arg_2)
Definition at line 110 of file kest_expression.c.
Referenced by kest_expr_init_2x(), kest_expr_init_div(), kest_expr_init_half_x(), kest_expr_init_mul(), kest_expr_init_sub(), and kest_expr_init_sum().
kest_expr_init_const()
int kest_expr_init_const (kest_expression * expr, float v)
Definition at line 59 of file kest_expression.c.
kest_expr_init_cos()
int kest_expr_init_cos (kest_expression * expr, kest_expression * x)
Definition at line 246 of file kest_expression.c.
Referenced by kest_expr_create_hpf_coefficients(), and kest_expr_create_lpf_coefficients().
kest_expr_init_div()
int kest_expr_init_div (kest_expression * expr, kest_expression * a, kest_expression * b)
Definition at line 196 of file kest_expression.c.
Referenced by kest_expr_create_hpf_coefficients(), and kest_expr_create_lpf_coefficients().
kest_expr_init_half_x()
int kest_expr_init_half_x (kest_expression * expr, kest_expression * x)
Definition at line 226 of file kest_expression.c.
Referenced by kest_expr_create_hpf_coefficients(), and kest_expr_create_lpf_coefficients().
kest_expr_init_mul()
int kest_expr_init_mul (kest_expression * expr, kest_expression * a, kest_expression * b)
Definition at line 206 of file kest_expression.c.
Referenced by kest_expr_create_hpf_coefficients(), and kest_expr_create_lpf_coefficients().
kest_expr_init_neg()
int kest_expr_init_neg (kest_expression * expr, kest_expression * a)
Definition at line 186 of file kest_expression.c.
Referenced by kest_expr_create_hpf_coefficients().
kest_expr_init_reference()
int kest_expr_init_reference (kest_expression * expr, char * ref_name)
Definition at line 144 of file kest_expression.c.
kest_expr_init_sin()
int kest_expr_init_sin (kest_expression * expr, kest_expression * x)
Definition at line 236 of file kest_expression.c.
Referenced by kest_expr_create_hpf_coefficients(), and kest_expr_create_lpf_coefficients().
kest_expr_init_sub()
int kest_expr_init_sub (kest_expression * expr, kest_expression * a, kest_expression * b)
Definition at line 256 of file kest_expression.c.
Referenced by kest_expr_create_hpf_coefficients(), and kest_expr_create_lpf_coefficients().
kest_expr_init_sum()
int kest_expr_init_sum (kest_expression * expr, kest_expression * a, kest_expression * b)
Definition at line 266 of file kest_expression.c.
Referenced by kest_expr_create_hpf_coefficients(), and kest_expr_create_lpf_coefficients().
kest_expr_init_unary()
int kest_expr_init_unary (kest_expression * expr, int unary_type, kest_expression * rhs)
Definition at line 79 of file kest_expression.c.
Referenced by kest_expr_init_cos(), kest_expr_init_neg(), and kest_expr_init_sin().
kest_expr_new_2x()
kest_expression * kest_expr_new_2x (kest_expression * x)
Definition at line 221 of file kest_expression.c.
kest_expr_new_binary()
kest_expression * kest_expr_new_binary (int binary_type, kest_expression * arg_1, kest_expression * arg_2)
Definition at line 125 of file kest_expression.c.
Referenced by kest_expr_new_2x(), kest_expr_new_div(), kest_expr_new_half_x(), kest_expr_new_mul(), kest_expr_new_sub(), kest_expr_new_sum(), and kest_parse_expression_rec_pratt().
kest_expr_new_const()
kest_expression * kest_expr_new_const (float v)
Definition at line 68 of file kest_expression.c.
Referenced by kest_extract_hpf_from_dict(), kest_extract_lpf_from_dict(), kest_parse_asm_arg_2(), and kest_parse_expression_rec_pratt().
kest_expr_new_cos()
kest_expression * kest_expr_new_cos (kest_expression * x)
Definition at line 251 of file kest_expression.c.
kest_expr_new_div()
kest_expression * kest_expr_new_div (kest_expression * a, kest_expression * b)
Definition at line 201 of file kest_expression.c.
kest_expr_new_half_x()
kest_expression * kest_expr_new_half_x (kest_expression * x)
Definition at line 231 of file kest_expression.c.
kest_expr_new_mul()
kest_expression * kest_expr_new_mul (kest_expression * a, kest_expression * b)
Definition at line 211 of file kest_expression.c.
kest_expr_new_neg()
kest_expression * kest_expr_new_neg (kest_expression * a)
Definition at line 191 of file kest_expression.c.
kest_expr_new_reference()
kest_expression * kest_expr_new_reference (char * ref_name)
Definition at line 162 of file kest_expression.c.
Referenced by kest_parse_asm_arg_2(), and kest_parse_expression_rec_pratt().
kest_expr_new_sin()
kest_expression * kest_expr_new_sin (kest_expression * x)
Definition at line 241 of file kest_expression.c.
kest_expr_new_sub()
kest_expression * kest_expr_new_sub (kest_expression * a, kest_expression * b)
Definition at line 261 of file kest_expression.c.
kest_expr_new_sum()
kest_expression * kest_expr_new_sum (kest_expression * a, kest_expression * b)
Definition at line 271 of file kest_expression.c.
kest_expr_new_unary()
kest_expression * kest_expr_new_unary (int unary_type, kest_expression * rhs)
Definition at line 93 of file kest_expression.c.
Referenced by kest_expr_new_cos(), kest_expr_new_neg(), kest_expr_new_sin(), and kest_parse_expression_rec_pratt().
kest_expression_arity()
int kest_expression_arity (kest_expression * expr)
Definition at line 348 of file kest_expression.c.
Referenced by kest_expression_compute_range_rec(), kest_expression_detect_constants_rec(), kest_expression_get_references_rec(), and kest_expression_references_param_rec().
kest_expression_compute_range()
kest_interval kest_expression_compute_range (kest_expression * expr, kest_scope * scope)
Definition at line 1364 of file kest_expression.c.
Referenced by kest_expression_compute_format().
kest_expression_compute_range_rec()
kest_interval kest_expression_compute_range_rec (kest_expression * expr, kest_scope * scope, int depth)
Definition at line 781 of file kest_expression.c.
Referenced by kest_expression_compute_range(), and kest_expression_compute_range_rec().
kest_expression_const()
kest_expression kest_expression_const (float v)
Definition at line 48 of file kest_expression.c.
Referenced by kest_expr_init_const(), and kest_expr_new_const().
kest_expression_detect_constants()
int kest_expression_detect_constants (kest_expression * expr)
Definition at line 452 of file kest_expression.c.
Referenced by kest_parse_expression().
kest_expression_detect_constants_rec()
int kest_expression_detect_constants_rec (kest_expression * expr, int depth)
Definition at line 403 of file kest_expression.c.
Referenced by kest_expression_detect_constants(), and kest_expression_detect_constants_rec().
kest_expression_evaluate()
float kest_expression_evaluate (kest_expression * expr, kest_scope * scope)
Definition at line 696 of file kest_expression.c.
Referenced by kest_expression_compute_range_rec(), kest_extract_filter_from_dict(), kest_extract_int_setting_from_dict(), kest_extract_mem_from_dict(), kest_extract_parameter_from_dict(), kest_extract_setting_from_dict(), kest_fpga_batch_append_block_register_updates(), kest_fpga_batch_append_block_regs(), kest_fpga_batch_append_filter_updates(), kest_fpga_batch_append_resource(), and kest_process_asm_line().
kest_expression_form()
int kest_expression_form (kest_expression * expr)
Definition at line 308 of file kest_expression.c.
Referenced by kest_expression_print_rec().
kest_expression_function_string()
const char * kest_expression_function_string (kest_expression * expr)
Definition at line 1369 of file kest_expression.c.
Referenced by kest_expression_print_rec().
kest_expression_get_references()
int kest_expression_get_references (kest_expression * expr, string_list * names)
Definition at line 1702 of file kest_expression.c.
Referenced by kest_expression_updated_in_scope(), and kest_scope_propagate_updates().
kest_expression_get_references_rec()
int kest_expression_get_references_rec (kest_expression * expr, string_list * names, int depth)
Definition at line 1669 of file kest_expression.c.
Referenced by kest_expression_get_references(), and kest_expression_get_references_rec().
kest_expression_infix_operator_string()
const char * kest_expression_infix_operator_string (kest_expression * expr)
Definition at line 1395 of file kest_expression.c.
Referenced by kest_expression_print_rec().
kest_expression_is_constant()
int kest_expression_is_constant (kest_expression * expr)
Definition at line 395 of file kest_expression.c.
Referenced by kest_extract_int_setting_from_dict(), kest_extract_parameter_from_dict(), and kest_extract_setting_from_dict().
kest_expression_print()
int kest_expression_print (kest_expression * expr)
Definition at line 1531 of file kest_expression.c.
kest_expression_print_rec()
int kest_expression_print_rec (kest_expression * expr, char * buf, int buf_len, int depth)
Definition at line 1413 of file kest_expression.c.
Referenced by kest_expression_print(), kest_expression_print_rec(), and kest_expression_to_string().
kest_expression_references_param()
int kest_expression_references_param (kest_expression * expr, kest_parameter * param)
Definition at line 736 of file kest_expression.c.
kest_expression_references_param_rec()
int kest_expression_references_param_rec (kest_expression * expr, kest_parameter * param, int depth)
Definition at line 703 of file kest_expression.c.
Referenced by kest_expression_references_param(), and kest_expression_references_param_rec().
kest_expression_refers_constant()
int kest_expression_refers_constant (kest_expression * expr)
Definition at line 371 of file kest_expression.c.
Referenced by kest_expression_compute_range_rec(), kest_expression_detect_constants_rec(), and kest_expression_is_constant().
kest_expression_to_string()
const char * kest_expression_to_string (kest_expression * expr)
Definition at line 1544 of file kest_expression.c.
Referenced by kest_dict_entry_to_string(), kest_expression_compute_format(), kest_expression_compute_range_rec(), kest_expression_get_references_rec(), kest_expression_updated_in_scope(), kest_extract_biquad_from_dict(), kest_extract_filter_from_dict(), kest_extract_hpf_from_dict(), kest_extract_lpf_from_dict(), kest_extract_parameter_from_dict(), kest_extract_polynomial_from_dict(), kest_parse_asm_arg_2(), kest_parse_asm_line(), and kest_process_asm_line().
kest_expression_type_to_str()
char * kest_expression_type_to_str (int type)
Definition at line 276 of file kest_expression.c.
Referenced by kest_extract_parameter_from_dict().
kest_expression_updated_in_scope()
int kest_expression_updated_in_scope (kest_expression * expr, kest_scope * scope)
Definition at line 1708 of file kest_expression.c.
Referenced by kest_fpga_batch_append_block_register_updates(), and kest_fpga_batch_append_filter_updates().
kest_interval__b()
kest_interval kest_interval__b (float b)
Definition at line 765 of file kest_expression.c.
kest_interval_a_()
kest_interval kest_interval_a_ (float a)
Definition at line 757 of file kest_expression.c.
kest_interval_ab()
kest_interval kest_interval_ab (float a, float b)
Definition at line 749 of file kest_expression.c.
Referenced by kest_expression_compute_range_rec().
kest_interval_real_line()
kest_interval kest_interval_real_line ()
Definition at line 741 of file kest_expression.c.
Referenced by kest_expression_compute_range_rec().
kest_interval_singleton()
kest_interval kest_interval_singleton (float v)
Definition at line 773 of file kest_expression.c.
Referenced by kest_expression_compute_range_rec().
Variable Documentation
expr_print_buf
char expr_print_buf[256]
Definition at line 1529 of file kest_expression.c.
Referenced by kest_expression_to_string().
kest_expression_2pi
kest_expression kest_expression_2pi = KEST_EXPRESSION_CONST(2 * M_PI)
Definition at line 39 of file kest_expression.c.
kest_expression_2pi_over_fs
kest_expression kest_expression_2pi_over_fs = KEST_EXPRESSION_CONST((2 * M_PI) / (float)KEST_FPGA_SAMPLE_RATE)
Definition at line 45 of file kest_expression.c.
Referenced by kest_expr_create_hpf_coefficients(), and kest_expr_create_lpf_coefficients().
kest_expression_e
kest_expression kest_expression_e = KEST_EXPRESSION_CONST(exp(1))
Definition at line 40 of file kest_expression.c.
kest_expression_freq_max
kest_expression kest_expression_freq_max = KEST_EXPRESSION_CONST((float)KEST_FPGA_SAMPLE_RATE / 2 - 50)
Definition at line 44 of file kest_expression.c.
Referenced by init_effect().
kest_expression_half
kest_expression kest_expression_half = KEST_EXPRESSION_CONST(0.5)
Definition at line 36 of file kest_expression.c.
Referenced by kest_expr_init_half_x(), and kest_expr_new_half_x().
kest_expression_int_max
kest_expression kest_expression_int_max = KEST_EXPRESSION_CONST(pow(2, (float)KEST_FPGA_DATA_WIDTH - 1) - 1)
Definition at line 42 of file kest_expression.c.
kest_expression_int_min
kest_expression kest_expression_int_min = KEST_EXPRESSION_CONST(-pow(2, (float)KEST_FPGA_DATA_WIDTH - 1))
Definition at line 43 of file kest_expression.c.
kest_expression_minus_half
kest_expression kest_expression_minus_half = KEST_EXPRESSION_CONST(-0.5)
Definition at line 37 of file kest_expression.c.
kest_expression_minus_one
kest_expression kest_expression_minus_one = KEST_EXPRESSION_CONST(-1)
Definition at line 34 of file kest_expression.c.
kest_expression_minus_two
kest_expression kest_expression_minus_two = KEST_EXPRESSION_CONST(-2)
Definition at line 35 of file kest_expression.c.
kest_expression_one
kest_expression kest_expression_one = KEST_EXPRESSION_CONST(1)
Definition at line 32 of file kest_expression.c.
Referenced by init_effect(), kest_expr_create_hpf_coefficients(), and kest_expr_create_lpf_coefficients().
kest_expression_pi
kest_expression kest_expression_pi = KEST_EXPRESSION_CONST(M_PI)
Definition at line 38 of file kest_expression.c.
kest_expression_root_2_over_2
kest_expression kest_expression_root_2_over_2 = KEST_EXPRESSION_CONST(sqrt(2.0) / 2.0)
Definition at line 46 of file kest_expression.c.
Referenced by kest_extract_hpf_from_dict(), and kest_extract_lpf_from_dict().
kest_expression_sample_rate
kest_expression kest_expression_sample_rate = KEST_EXPRESSION_CONST((float)KEST_FPGA_SAMPLE_RATE)
Definition at line 41 of file kest_expression.c.
kest_expression_standard_gain_max
kest_expression kest_expression_standard_gain_max = KEST_EXPRESSION_CONST(KEST_STANDARD_GAIN_MAX)
Definition at line 30 of file kest_expression.c.
Referenced by kest_init_context().
kest_expression_standard_gain_min
kest_expression kest_expression_standard_gain_min = KEST_EXPRESSION_CONST(KEST_STANDARD_GAIN_MIN)
Definition at line 29 of file kest_expression.c.
Referenced by kest_init_context().
kest_expression_two
kest_expression kest_expression_two = KEST_EXPRESSION_CONST(2)
Definition at line 33 of file kest_expression.c.
Referenced by kest_expr_init_2x(), and kest_expr_new_2x().
kest_expression_zero
kest_expression kest_expression_zero = KEST_EXPRESSION_CONST(0)
Definition at line 31 of file kest_expression.c.
Referenced by init_effect().