Kestrel Interface: kest_fpga_dma.c File Reference
kest_fpga_dma.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int kest_fpga_periodic_read_init (kest_fpga_periodic_read *read)
int kest_fpga_periodic_read_init_mem (kest_fpga_periodic_read *read)
int kest_periodic_read_dispatch (kest_fpga_periodic_read *read)
int kest_begin_periodic_read (kest_fpga_periodic_read *read)
int kest_periodic_mem_read_cb (kest_fpga_read_spec *read)
int kest_fpga_periodic_read_activate (kest_fpga_periodic_read *read)
int kest_fpga_periodic_read_deactivate (kest_fpga_periodic_read *read)
void kest_fpga_periodic_read_activate_async_wrapper (void *read)
void kest_fpga_periodic_read_deactivate_async_wrapper (void *read)
int kest_fpga_periodic_read_activate_async (kest_fpga_periodic_read *read)
int kest_fpga_periodic_read_deactivate_async (kest_fpga_periodic_read *read)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 5 of file kest_fpga_dma.c.
Function Documentation
kest_begin_periodic_read()
int kest_begin_periodic_read (kest_fpga_periodic_read * read)
Definition at line 58 of file kest_fpga_dma.c.
kest_fpga_periodic_read_activate()
int kest_fpga_periodic_read_activate (kest_fpga_periodic_read * read)
Definition at line 118 of file kest_fpga_dma.c.
Referenced by kest_effect_activate_dma(), and kest_fpga_periodic_read_activate_async_wrapper().
kest_fpga_periodic_read_activate_async()
int kest_fpga_periodic_read_activate_async (kest_fpga_periodic_read * read)
Definition at line 172 of file kest_fpga_dma.c.
Referenced by kest_effect_activate_dma_async().
kest_fpga_periodic_read_activate_async_wrapper()
void kest_fpga_periodic_read_activate_async_wrapper (void * read)
Definition at line 159 of file kest_fpga_dma.c.
Referenced by kest_fpga_periodic_read_activate_async().
kest_fpga_periodic_read_deactivate()
int kest_fpga_periodic_read_deactivate (kest_fpga_periodic_read * read)
Definition at line 139 of file kest_fpga_dma.c.
Referenced by kest_effect_deactivate_dma(), and kest_fpga_periodic_read_deactivate_async_wrapper().
kest_fpga_periodic_read_deactivate_async()
int kest_fpga_periodic_read_deactivate_async (kest_fpga_periodic_read * read)
Definition at line 189 of file kest_fpga_dma.c.
Referenced by kest_effect_deactivate_dma_async().
kest_fpga_periodic_read_deactivate_async_wrapper()
void kest_fpga_periodic_read_deactivate_async_wrapper (void * read)
Definition at line 167 of file kest_fpga_dma.c.
Referenced by kest_fpga_periodic_read_deactivate_async().
kest_fpga_periodic_read_init()
int kest_fpga_periodic_read_init (kest_fpga_periodic_read * read)
Definition at line 19 of file kest_fpga_dma.c.
kest_fpga_periodic_read_init_mem()
int kest_fpga_periodic_read_init_mem (kest_fpga_periodic_read * read)
Definition at line 29 of file kest_fpga_dma.c.
Referenced by kest_mem_slot_create().
kest_periodic_mem_read_cb()
int kest_periodic_mem_read_cb (kest_fpga_read_spec * read)
Definition at line 79 of file kest_fpga_dma.c.
Referenced by kest_fpga_periodic_read_init_mem().
kest_periodic_read_dispatch()
int kest_periodic_read_dispatch (kest_fpga_periodic_read * read)
Definition at line 46 of file kest_fpga_dma.c.
Referenced by kest_active_preset_updater_task().