Kestrel Interface: kest_expr_scope.c File Reference
kest_expr_scope.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int kest_scope_entry_init (kest_scope_entry *entry)
int kest_scope_entry_init_expr (kest_scope_entry *entry, kest_expression *expr)
int kest_scope_entry_init_param (kest_scope_entry *entry, kest_parameter *param)
int kest_scope_entry_init_setting (kest_scope_entry *entry, kest_setting *setting)
int kest_scope_entry_init_lfo (kest_scope_entry *entry, kest_lfo *lfo)
int kest_scope_entry_init_mem (kest_scope_entry *entry, kest_mem_slot *mem)
int kest_scope_entry_add_dependent_scope_entry (kest_scope_entry *entry, const char *key)
int kest_scope_entry_add_dependent_block_reg (kest_scope_entry *entry, int block, int reg, int format)
int kest_scope_entry_add_dependent_filter_coef (kest_scope_entry *entry, int filter, int coef, int format)
int kest_scope_entry_add_dependent (kest_scope_entry *entry, kest_dependent dep)
int kest_scope_entry_print (kest_scope_entry *entry, kest_string *str)
IMPLEMENT_DICT (kest_scope_entry)
kest_scope * kest_scope_new ()
int kest_scope_init (kest_scope *scope)
int kest_scope_add_entry (kest_scope *scope, const char *name, kest_scope_entry entry)
int kest_scope_add_mem (kest_scope *scope, const char *name, kest_mem_slot *mem)
int kest_scope_add_expr (kest_scope *scope, const char *name, struct kest_expression *expr)
int kest_scope_add_param (kest_scope *scope, kest_parameter *param)
int kest_scope_add_setting (kest_scope *scope, kest_setting *setting)
kest_scope_entry * kest_scope_add_entry_return_ptr (kest_scope *scope, const char *name, kest_scope_entry entry)
kest_scope_entry * kest_scope_add_lfo_return_entry (kest_scope *scope, const char *name, kest_lfo *lfo)
kest_scope_entry * kest_scope_add_mem_return_entry (kest_scope *scope, const char *name, kest_mem_slot *mem)
kest_scope_entry * kest_scope_add_expr_return_entry (kest_scope *scope, const char *name, kest_expression *expr)
kest_scope_entry * kest_scope_add_param_return_entry (kest_scope *scope, kest_parameter *param)
kest_scope_entry * kest_scope_add_setting_return_entry (kest_scope *scope, kest_setting *setting)
int kest_scope_add_params (kest_scope *scope, kest_parameter_pll *params)
int kest_scope_add_settings (kest_scope *scope, kest_setting_pll *settings)
kest_scope_entry * kest_scope_fetch (kest_scope *scope, const char *name)
kest_scope_entry * kest_scope_lookup (kest_scope *scope, const char *name)
size_t kest_scope_count (kest_scope *scope)
kest_scope_entry * kest_scope_index (kest_scope *scope, size_t n)
const char * kest_scope_index_key (kest_scope *scope, size_t n)
int kest_scope_entry_propagate_updates (kest_scope_entry *entry)
int kest_scope_detect_env_updates (kest_scope *scope)
int kest_scope_propagate_updates (kest_scope *scope)
int kest_scope_detect_dependencies (kest_scope *scope)
int kest_scope_add_block_reg_dependencies (kest_scope *scope, kest_expression *expr, int block, int reg, int format)
int kest_scope_add_filter_coef_dependencies (kest_scope *scope, kest_expression *expr, int filter, int coef, int format)
int kest_scope_transitivize_updatable_dependents_rec (kest_scope *scope, kest_scope_entry *entry, int depth)
int kest_scope_transitivize_updatable_dependents (kest_scope *scope)
int kest_scope_clear_updates (kest_scope *scope)
int kest_scope_entry_eval_rec (kest_scope_entry *entry, kest_scope *scope, float *dest, int depth)
int kest_scope_entry_eval (kest_scope_entry *entry, kest_scope *scope, float *dest)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 3 of file kest_expr_scope.c.
Function Documentation
IMPLEMENT_DICT()
IMPLEMENT_DICT (kest_scope_entry)
kest_scope_add_block_reg_dependencies()
int kest_scope_add_block_reg_dependencies (kest_scope * scope, kest_expression * expr, int block, int reg, int format)
Definition at line 718 of file kest_expr_scope.c.
Referenced by init_effect_from_effect_desc().
kest_scope_add_entry()
int kest_scope_add_entry (kest_scope * scope, const char * name, kest_scope_entry entry)
Definition at line 260 of file kest_expr_scope.c.
Referenced by kest_scope_add_expr(), kest_scope_add_mem(), kest_scope_add_param(), and kest_scope_add_setting().
kest_scope_add_entry_return_ptr()
kest_scope_entry * kest_scope_add_entry_return_ptr (kest_scope * scope, const char * name, kest_scope_entry entry)
Definition at line 333 of file kest_expr_scope.c.
Referenced by kest_scope_add_expr_return_entry(), kest_scope_add_lfo_return_entry(), kest_scope_add_mem_return_entry(), kest_scope_add_param_return_entry(), and kest_scope_add_setting_return_entry().
kest_scope_add_expr()
int kest_scope_add_expr (kest_scope * scope, const char * name, struct kest_expression * expr)
Definition at line 288 of file kest_expr_scope.c.
Referenced by kest_defs_section_extract(), kest_effect_create_scope(), and kest_scope_init().
kest_scope_add_expr_return_entry()
kest_scope_entry * kest_scope_add_expr_return_entry (kest_scope * scope, const char * name, kest_expression * expr)
Definition at line 372 of file kest_expr_scope.c.
kest_scope_add_filter_coef_dependencies()
int kest_scope_add_filter_coef_dependencies (kest_scope * scope, kest_expression * expr, int filter, int coef, int format)
Definition at line 749 of file kest_expr_scope.c.
Referenced by init_effect_from_effect_desc().
kest_scope_add_lfo_return_entry()
kest_scope_entry * kest_scope_add_lfo_return_entry (kest_scope * scope, const char * name, kest_lfo * lfo)
Definition at line 342 of file kest_expr_scope.c.
Referenced by kest_effect_create_scope().
kest_scope_add_mem()
int kest_scope_add_mem (kest_scope * scope, const char * name, kest_mem_slot * mem)
Definition at line 273 of file kest_expr_scope.c.
Referenced by kest_extract_mem_from_dict().
kest_scope_add_mem_return_entry()
kest_scope_entry * kest_scope_add_mem_return_entry (kest_scope * scope, const char * name, kest_mem_slot * mem)
Definition at line 357 of file kest_expr_scope.c.
Referenced by kest_effect_create_scope().
kest_scope_add_param()
int kest_scope_add_param (kest_scope * scope, kest_parameter * param)
Definition at line 303 of file kest_expr_scope.c.
Referenced by kest_eff_desc_create_scope(), kest_effect_create_scope(), and kest_scope_add_params().
kest_scope_add_param_return_entry()
kest_scope_entry * kest_scope_add_param_return_entry (kest_scope * scope, kest_parameter * param)
Definition at line 387 of file kest_expr_scope.c.
kest_scope_add_params()
int kest_scope_add_params (kest_scope * scope, kest_parameter_pll * params)
Definition at line 417 of file kest_expr_scope.c.
Referenced by kest_parse_tokens().
kest_scope_add_setting()
int kest_scope_add_setting (kest_scope * scope, kest_setting * setting)
Definition at line 318 of file kest_expr_scope.c.
Referenced by kest_effect_create_scope(), and kest_scope_add_settings().
kest_scope_add_setting_return_entry()
kest_scope_entry * kest_scope_add_setting_return_entry (kest_scope * scope, kest_setting * setting)
Definition at line 402 of file kest_expr_scope.c.
kest_scope_add_settings()
int kest_scope_add_settings (kest_scope * scope, kest_setting_pll * settings)
Definition at line 439 of file kest_expr_scope.c.
Referenced by kest_parse_tokens().
kest_scope_clear_updates()
int kest_scope_clear_updates (kest_scope * scope)
Definition at line 883 of file kest_expr_scope.c.
Referenced by kest_effect_clear_updates(), kest_effect_handle_updates(), kest_effect_update_fpga(), kest_effect_update_sync_no_pw(), and kest_fpga_transfer_batch_append_effect_updates().
kest_scope_count()
size_t kest_scope_count (kest_scope * scope)
Definition at line 471 of file kest_expr_scope.c.
Referenced by kest_expression_updated_in_scope(), and kest_scope_clear_updates().
kest_scope_detect_dependencies()
int kest_scope_detect_dependencies (kest_scope * scope)
Definition at line 646 of file kest_expr_scope.c.
Referenced by kest_effect_create_scope().
kest_scope_detect_env_updates()
int kest_scope_detect_env_updates (kest_scope * scope)
Definition at line 506 of file kest_expr_scope.c.
Referenced by kest_scope_propagate_updates().
kest_scope_entry_add_dependent()
int kest_scope_entry_add_dependent (kest_scope_entry * entry, kest_dependent dep)
Definition at line 164 of file kest_expr_scope.c.
Referenced by kest_scope_transitivize_updatable_dependents_rec().
kest_scope_entry_add_dependent_block_reg()
int kest_scope_entry_add_dependent_block_reg (kest_scope_entry * entry, int block, int reg, int format)
Definition at line 126 of file kest_expr_scope.c.
Referenced by kest_scope_add_block_reg_dependencies(), and kest_scope_entry_add_dependent().
kest_scope_entry_add_dependent_filter_coef()
int kest_scope_entry_add_dependent_filter_coef (kest_scope_entry * entry, int filter, int coef, int format)
Definition at line 145 of file kest_expr_scope.c.
Referenced by kest_scope_add_filter_coef_dependencies(), and kest_scope_entry_add_dependent().
kest_scope_entry_add_dependent_scope_entry()
int kest_scope_entry_add_dependent_scope_entry (kest_scope_entry * entry, const char * key)
Definition at line 105 of file kest_expr_scope.c.
Referenced by kest_scope_detect_dependencies(), and kest_scope_entry_add_dependent().
kest_scope_entry_eval()
int kest_scope_entry_eval (kest_scope_entry * entry, kest_scope * scope, float * dest)
Definition at line 986 of file kest_expr_scope.c.
Referenced by kest_driver_evaluate().
kest_scope_entry_eval_rec()
int kest_scope_entry_eval_rec (kest_scope_entry * entry, kest_scope * scope, float * dest, int depth)
Definition at line 918 of file kest_expr_scope.c.
Referenced by kest_expression_evaluate_rec(), and kest_scope_entry_eval().
kest_scope_entry_init()
int kest_scope_entry_init (kest_scope_entry * entry)
Definition at line 7 of file kest_expr_scope.c.
Referenced by kest_scope_entry_init_expr(), kest_scope_entry_init_lfo(), kest_scope_entry_init_mem(), kest_scope_entry_init_param(), and kest_scope_entry_init_setting().
kest_scope_entry_init_expr()
int kest_scope_entry_init_expr (kest_scope_entry * entry, kest_expression * expr)
Definition at line 19 of file kest_expr_scope.c.
Referenced by kest_scope_add_expr(), and kest_scope_add_expr_return_entry().
kest_scope_entry_init_lfo()
int kest_scope_entry_init_lfo (kest_scope_entry * entry, kest_lfo * lfo)
Definition at line 70 of file kest_expr_scope.c.
Referenced by kest_scope_add_lfo_return_entry().
kest_scope_entry_init_mem()
int kest_scope_entry_init_mem (kest_scope_entry * entry, kest_mem_slot * mem)
Definition at line 88 of file kest_expr_scope.c.
Referenced by kest_scope_add_mem(), and kest_scope_add_mem_return_entry().
kest_scope_entry_init_param()
int kest_scope_entry_init_param (kest_scope_entry * entry, kest_parameter * param)
Definition at line 36 of file kest_expr_scope.c.
Referenced by kest_scope_add_param(), and kest_scope_add_param_return_entry().
kest_scope_entry_init_setting()
int kest_scope_entry_init_setting (kest_scope_entry * entry, kest_setting * setting)
Definition at line 53 of file kest_expr_scope.c.
Referenced by kest_scope_add_setting(), and kest_scope_add_setting_return_entry().
kest_scope_entry_print()
int kest_scope_entry_print (kest_scope_entry * entry, kest_string * str)
Definition at line 182 of file kest_expr_scope.c.
Referenced by kest_scope_transitivize_updatable_dependents_rec().
kest_scope_entry_propagate_updates()
int kest_scope_entry_propagate_updates (kest_scope_entry * entry)
Definition at line 496 of file kest_expr_scope.c.
kest_scope_fetch()
kest_scope_entry * kest_scope_fetch (kest_scope * scope, const char * name)
Definition at line 461 of file kest_expr_scope.c.
Referenced by kest_expression_compute_max_rec(), kest_expression_compute_min_rec(), kest_expression_compute_range_rec(), and kest_expression_evaluate_rec().
kest_scope_index()
kest_scope_entry * kest_scope_index (kest_scope * scope, size_t n)
Definition at line 480 of file kest_expr_scope.c.
Referenced by kest_scope_clear_updates(), kest_scope_detect_dependencies(), kest_scope_detect_env_updates(), kest_scope_propagate_updates(), and kest_scope_transitivize_updatable_dependents().
kest_scope_index_key()
const char * kest_scope_index_key (kest_scope * scope, size_t n)
Definition at line 488 of file kest_expr_scope.c.
Referenced by kest_scope_detect_dependencies(), kest_scope_detect_env_updates(), and kest_scope_propagate_updates().
kest_scope_init()
int kest_scope_init (kest_scope * scope)
Definition at line 239 of file kest_expr_scope.c.
Referenced by kest_parse_tokens(), and kest_scope_new().
kest_scope_lookup()
kest_scope_entry * kest_scope_lookup (kest_scope * scope, const char * name)
Definition at line 466 of file kest_expr_scope.c.
Referenced by kest_driver_clone_for(), kest_driver_evaluate(), kest_effect_create_scope(), kest_expression_updated_in_scope(), kest_scope_add_block_reg_dependencies(), kest_scope_add_filter_coef_dependencies(), kest_scope_detect_dependencies(), kest_scope_propagate_updates(), kest_scope_transitivize_updatable_dependents_rec(), and kest_updater_handle_update().
kest_scope_new()
kest_scope * kest_scope_new ()
Definition at line 221 of file kest_expr_scope.c.
Referenced by kest_eff_desc_create_scope(), and kest_effect_create_scope().
kest_scope_propagate_updates()
int kest_scope_propagate_updates (kest_scope * scope)
Definition at line 560 of file kest_expr_scope.c.
Referenced by kest_effect_is_updated().
kest_scope_transitivize_updatable_dependents()
int kest_scope_transitivize_updatable_dependents (kest_scope * scope)
Definition at line 864 of file kest_expr_scope.c.
Referenced by init_effect_from_effect_desc().
kest_scope_transitivize_updatable_dependents_rec()
int kest_scope_transitivize_updatable_dependents_rec (kest_scope * scope, kest_scope_entry * entry, int depth)
Definition at line 781 of file kest_expr_scope.c.
Referenced by kest_scope_transitivize_updatable_dependents(), and kest_scope_transitivize_updatable_dependents_rec().