Kestrel Interface: kest_fpga_dma.h File Reference
kest_fpga_dma.h File Reference
Data Structures
struct kest_fpga_read_spec
struct kest_fpga_periodic_read
Macros
#define DATA_REQ_BLOCK_INSTR 1
#define DATA_REQ_BLOCK_REG 2
#define DATA_REQ_N_DELAY_BUF 3
#define DATA_REQ_DELAY_BUF_SIZE 4
#define DATA_REQ_DELAY_BUF_DELAY 5
#define DATA_REQ_DELAY_BUF_ADDR 6
#define DATA_REQ_DELAY_BUF_POS 7
#define DATA_REQ_DELAY_BUF_GAIN 8
#define DATA_REQ_DELAY_BUF_LRWA 9
#define DATA_REQ_SAMPLE_COUNT 10
#define DATA_REQ_SDRAM_READ_CNT 11
#define DATA_REQ_SDRAM_WRITE_CNT 12
#define DATA_REQ_STUCK_FLAGS 13
#define DATA_REQ_N_BLOCKS 14
#define DATA_REQ_MEM 15
#define DATA_REQ_COMMAND_LOG 33
Functions
int kest_fpga_periodic_read_init (kest_fpga_periodic_read *read)
int kest_fpga_periodic_read_init_mem (kest_fpga_periodic_read *read)
int kest_periodic_read_dispatch (kest_fpga_periodic_read *read)
int kest_periodic_mem_read_cb (kest_fpga_read_spec *spec)
int kest_fpga_periodic_read_activate (kest_fpga_periodic_read *read)
int kest_fpga_periodic_read_deactivate (kest_fpga_periodic_read *read)
int kest_fpga_periodic_read_activate_async (kest_fpga_periodic_read *read)
int kest_fpga_periodic_read_deactivate_async (kest_fpga_periodic_read *read)
Macro Definition Documentation
DATA_REQ_BLOCK_INSTR
#define DATA_REQ_BLOCK_INSTR 1
Definition at line 4 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_block_instr().
DATA_REQ_BLOCK_REG
#define DATA_REQ_BLOCK_REG 2
Definition at line 5 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_block_reg().
DATA_REQ_COMMAND_LOG
#define DATA_REQ_COMMAND_LOG 33
Definition at line 19 of file kest_fpga_dma.h.
DATA_REQ_DELAY_BUF_ADDR
#define DATA_REQ_DELAY_BUF_ADDR 6
Definition at line 9 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_delay_buffer_addr().
DATA_REQ_DELAY_BUF_DELAY
#define DATA_REQ_DELAY_BUF_DELAY 5
Definition at line 8 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_delay_buffer_delay().
DATA_REQ_DELAY_BUF_GAIN
#define DATA_REQ_DELAY_BUF_GAIN 8
Definition at line 11 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_delay_buffer_gain().
DATA_REQ_DELAY_BUF_LRWA
#define DATA_REQ_DELAY_BUF_LRWA 9
Definition at line 12 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_delay_buffer_last_rw_addr().
DATA_REQ_DELAY_BUF_POS
#define DATA_REQ_DELAY_BUF_POS 7
Definition at line 10 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_delay_buffer_pos().
DATA_REQ_DELAY_BUF_SIZE
#define DATA_REQ_DELAY_BUF_SIZE 4
Definition at line 7 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_delay_buffer_size().
DATA_REQ_MEM
#define DATA_REQ_MEM 15
Definition at line 18 of file kest_fpga_dma.h.
Referenced by kest_fpga_comms_task(), and kest_fpga_periodic_read_init_mem().
DATA_REQ_N_BLOCKS
#define DATA_REQ_N_BLOCKS 14
Definition at line 17 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_n_blocks().
DATA_REQ_N_DELAY_BUF
#define DATA_REQ_N_DELAY_BUF 3
Definition at line 6 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_n_delay_buffers().
DATA_REQ_SAMPLE_COUNT
#define DATA_REQ_SAMPLE_COUNT 10
Definition at line 13 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_sample_count().
DATA_REQ_SDRAM_READ_CNT
#define DATA_REQ_SDRAM_READ_CNT 11
Definition at line 14 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_sdram_read_count().
DATA_REQ_SDRAM_WRITE_CNT
#define DATA_REQ_SDRAM_WRITE_CNT 12
Definition at line 15 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_sdram_write_count().
DATA_REQ_STUCK_FLAGS
#define DATA_REQ_STUCK_FLAGS 13
Definition at line 16 of file kest_fpga_dma.h.
Referenced by kest_fpga_get_stuck_flags().
Function Documentation
kest_fpga_periodic_read_activate()
int kest_fpga_periodic_read_activate (kest_fpga_periodic_read * read)
Definition at line 118 of file kest_fpga_dma.c.
Referenced by kest_effect_activate_dma(), and kest_fpga_periodic_read_activate_async_wrapper().
kest_fpga_periodic_read_activate_async()
int kest_fpga_periodic_read_activate_async (kest_fpga_periodic_read * read)
Definition at line 172 of file kest_fpga_dma.c.
Referenced by kest_effect_activate_dma_async().
kest_fpga_periodic_read_deactivate()
int kest_fpga_periodic_read_deactivate (kest_fpga_periodic_read * read)
Definition at line 139 of file kest_fpga_dma.c.
Referenced by kest_effect_deactivate_dma(), and kest_fpga_periodic_read_deactivate_async_wrapper().
kest_fpga_periodic_read_deactivate_async()
int kest_fpga_periodic_read_deactivate_async (kest_fpga_periodic_read * read)
Definition at line 189 of file kest_fpga_dma.c.
Referenced by kest_effect_deactivate_dma_async().
kest_fpga_periodic_read_init()
int kest_fpga_periodic_read_init (kest_fpga_periodic_read * read)
Definition at line 19 of file kest_fpga_dma.c.
kest_fpga_periodic_read_init_mem()
int kest_fpga_periodic_read_init_mem (kest_fpga_periodic_read * read)
Definition at line 29 of file kest_fpga_dma.c.
Referenced by kest_mem_slot_create().
kest_periodic_mem_read_cb()
int kest_periodic_mem_read_cb (kest_fpga_read_spec * spec)
Definition at line 79 of file kest_fpga_dma.c.
Referenced by kest_fpga_periodic_read_init_mem().
kest_periodic_read_dispatch()
int kest_periodic_read_dispatch (kest_fpga_periodic_read * read)
Definition at line 46 of file kest_fpga_dma.c.
Referenced by kest_active_preset_updater_task().