Kestrel Interface: kest_fpga_io.h File Reference
kest_fpga_io.h File Reference
Data Structures
struct kest_fpga_transfer_batch
struct kest_fpga_status_flags
Macros
#define KEST_FPGA_SAMPLE_RATE 44100
#define FPGA_BOOT_MS 2500
#define COMMAND_BEGIN_PROGRAM 1
#define COMMAND_WRITE_BLOCK_INSTR 2
#define COMMAND_WRITE_BLOCK_REG_0 3
#define COMMAND_WRITE_BLOCK_REG_1 4
#define COMMAND_ALLOC_DELAY 5
#define COMMAND_END_PROGRAM 10
#define COMMAND_SET_INPUT_GAIN 11
#define COMMAND_SET_OUTPUT_GAIN 12
#define COMMAND_UPDATE_BLOCK_REG_0 13
#define COMMAND_UPDATE_BLOCK_REG_1 14
#define COMMAND_COMMIT_REG_UPDATES 15
#define COMMAND_ALLOC_FILTER 16
#define COMMAND_WRITE_FILTER_COEF 17
#define COMMAND_UPDATE_FILTER_COEF 18
#define COMMAND_COMMIT_FILTER_COEF 19
#define COMMAND_READOUT 20
#define COMMAND_GET_N_BLOCKS 21
#define COMMAND_GET_BLOCK_INSTR 22
#define COMMAND_GET_BLOCK_REG 23
#define COMMAND_GET_N_DELAY_BUF 24
#define COMMAND_GET_DELAY_BUF_SIZE 25
#define COMMAND_GET_DELAY_BUF_DELAY 26
#define COMMAND_GET_DELAY_BUF_ADDR 27
#define COMMAND_GET_DELAY_BUF_POS 28
#define COMMAND_GET_DELAY_BUF_GAIN 29
#define COMMAND_GET_DELAY_BUF_LRWA 30
#define COMMAND_GET_SDRAM_READ_CNT 31
#define COMMAND_GET_SDRAM_WRITE_CNT 32
#define COMMAND_READ_COMMAND_LOG 33
#define COMMAND_GET_SAMPLE_COUNT 34
#define COMMAND_CLEAR_TIMEOUT_FLAG 35
#define COMMAND_CLEAR_BAD_FLAG 36
#define COMMAND_CLEAR_CMD_ERR_FLAG 37
#define COMMAND_READ 38
#define SPI_RESPONSE_OK 1
#define KEST_FPGA_N_BLOCKS 256
#define KEST_FPGA_DATA_WIDTH 16
#define KEST_FPGA_FILTER_WIDTH 18
#define KEST_FPGA_DATA_BYTES (KEST_FPGA_DATA_WIDTH / 8)
#define DATA_REQ_N_BLOCKS 14
#define DATA_REQ_BLOCK_INSTR 1
#define DATA_REQ_BLOCK_REG 2
#define DATA_REQ_N_DELAY_BUF 3
#define DATA_REQ_DELAY_BUF_SIZE 4
#define DATA_REQ_DELAY_BUF_DELAY 5
#define DATA_REQ_DELAY_BUF_ADDR 6
#define DATA_REQ_DELAY_BUF_POS 7
#define DATA_REQ_DELAY_BUF_GAIN 8
#define DATA_REQ_DELAY_BUF_LRWA 9
#define DATA_REQ_SAMPLE_COUNT 10
#define DATA_REQ_SDRAM_READ_CNT 11
#define DATA_REQ_SDRAM_WRITE_CNT 12
#define DATA_REQ_STUCK_FLAGS 13
Typedefs
typedef int16_t kest_fpga_sample_t
Functions
kest_fpga_transfer_batch kest_new_fpga_transfer_batch ()
void kest_free_fpga_transfer_batch (kest_fpga_transfer_batch batch)
int kest_send_bytes_to_fpga (uint8_t *buf, int n)
int kest_send_byte_to_fpga (uint8_t byte)
int kest_fpga_send_byte (uint8_t byte)
uint8_t kest_fpga_read_byte ()
uint8_t kest_fpga_readout ()
void kest_fpga_set_input_gain (float gain_db)
void kest_fpga_set_output_gain (float gain_db)
void kest_fpga_commit_reg_updates ()
int kest_fpga_batch_append (kest_fpga_transfer_batch *seq, uint8_t x)
int kest_fpga_batch_append_16 (kest_fpga_transfer_batch *seq, uint16_t x)
int kest_fpga_batch_append_24 (kest_fpga_transfer_batch *seq, uint32_t x)
int kest_fpga_batch_append_32 (kest_fpga_transfer_batch *seq, uint32_t x)
int kest_fpga_transfer_batch_send (kest_fpga_transfer_batch batch)
int kest_fpga_transfer_batch_send_careful (kest_fpga_transfer_batch batch)
int kest_fpga_program_batch_send_careful (kest_fpga_transfer_batch batch)
int kest_fpga_program_batch_send (kest_fpga_transfer_batch batch)
int kest_fpga_spi_init ()
char * kest_fpga_command_to_string (int command)
int kest_fpga_decode_status_flags (kest_fpga_status_flags *flags, uint8_t byte)
int kest_fpga_send_byte_get_flags (uint8_t tx, kest_fpga_status_flags *flags)
int kest_fpga_get_status_flags (kest_fpga_status_flags *flags)
int kest_fpga_status_flags_print (kest_fpga_status_flags *flags)
int kest_fpga_status_flags_sprint (kest_string *str, kest_fpga_status_flags *flags)
int kest_fpga_get_n_blocks (kest_fpga_status_flags *flags)
uint32_t kest_fpga_get_block_instr (int block, kest_fpga_status_flags *flags)
uint16_t kest_fpga_get_block_reg (int block, int reg, kest_fpga_status_flags *flags)
int kest_fpga_get_n_delay_buffers (kest_fpga_status_flags *flags)
int kest_fpga_get_delay_buffer_size (int handle, kest_fpga_status_flags *flags)
int kest_fpga_get_delay_buffer_delay (int handle, kest_fpga_status_flags *flags)
int kest_fpga_get_delay_buffer_addr (int handle, kest_fpga_status_flags *flags)
int kest_fpga_get_delay_buffer_pos (int handle, kest_fpga_status_flags *flags)
uint16_t kest_fpga_get_delay_buffer_gain (int handle, kest_fpga_status_flags *flags)
int kest_fpga_get_delay_buffer_last_rw_addr (int handle, uint16_t *read_addr, uint16_t *write_addr, kest_fpga_status_flags *flags)
uint64_t kest_fpga_get_sample_count (kest_fpga_status_flags *flags)
uint64_t kest_fpga_get_sdram_read_count (kest_fpga_status_flags *flags)
uint64_t kest_fpga_get_sdram_write_count (kest_fpga_status_flags *flags)
uint32_t kest_fpga_get_stuck_flags (kest_fpga_status_flags *flags)
int kest_fpga_read_command_log (uint8_t *buf)
Macro Definition Documentation
COMMAND_ALLOC_DELAY
#define COMMAND_ALLOC_DELAY 5
Definition at line 14 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_append_resource(), kest_fpga_batch_print(), and kest_fpga_command_to_string().
COMMAND_ALLOC_FILTER
#define COMMAND_ALLOC_FILTER 16
Definition at line 21 of file kest_fpga_io.h.
Referenced by kest_command_log_test(), kest_fpga_batch_append_resource(), kest_fpga_batch_print(), and kest_fpga_command_to_string().
COMMAND_BEGIN_PROGRAM
#define COMMAND_BEGIN_PROGRAM 1
Definition at line 10 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_print(), kest_fpga_command_to_string(), kest_fpga_program_batch_send(), and kest_fpga_program_batch_send_careful().
COMMAND_CLEAR_BAD_FLAG
#define COMMAND_CLEAR_BAD_FLAG 36
Definition at line 41 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string(), and kest_fpga_comms_task().
COMMAND_CLEAR_CMD_ERR_FLAG
#define COMMAND_CLEAR_CMD_ERR_FLAG 37
Definition at line 42 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string(), kest_fpga_comms_print_full_scan(), kest_fpga_req_data(), and kest_fpga_req_data_p().
COMMAND_CLEAR_TIMEOUT_FLAG
#define COMMAND_CLEAR_TIMEOUT_FLAG 35
Definition at line 40 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string(), and kest_fpga_comms_task().
COMMAND_COMMIT_FILTER_COEF
#define COMMAND_COMMIT_FILTER_COEF 19
Definition at line 24 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_append_filter_updates(), kest_fpga_batch_print(), and kest_fpga_command_to_string().
COMMAND_COMMIT_REG_UPDATES
#define COMMAND_COMMIT_REG_UPDATES 15
Definition at line 20 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_print(), kest_fpga_command_to_string(), kest_fpga_commit_reg_updates(), and kest_fpga_queue_register_commit().
COMMAND_END_PROGRAM
#define COMMAND_END_PROGRAM 10
Definition at line 15 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_print(), kest_fpga_command_to_string(), kest_fpga_program_batch_send(), and kest_fpga_program_batch_send_careful().
COMMAND_GET_BLOCK_INSTR
#define COMMAND_GET_BLOCK_INSTR 22
Definition at line 27 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_GET_BLOCK_REG
#define COMMAND_GET_BLOCK_REG 23
Definition at line 28 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_GET_DELAY_BUF_ADDR
#define COMMAND_GET_DELAY_BUF_ADDR 27
Definition at line 32 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_GET_DELAY_BUF_DELAY
#define COMMAND_GET_DELAY_BUF_DELAY 26
Definition at line 31 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_GET_DELAY_BUF_GAIN
#define COMMAND_GET_DELAY_BUF_GAIN 29
Definition at line 34 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_GET_DELAY_BUF_LRWA
#define COMMAND_GET_DELAY_BUF_LRWA 30
Definition at line 35 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_GET_DELAY_BUF_POS
#define COMMAND_GET_DELAY_BUF_POS 28
Definition at line 33 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_GET_DELAY_BUF_SIZE
#define COMMAND_GET_DELAY_BUF_SIZE 25
Definition at line 30 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_GET_N_BLOCKS
#define COMMAND_GET_N_BLOCKS 21
Definition at line 26 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_GET_N_DELAY_BUF
#define COMMAND_GET_N_DELAY_BUF 24
Definition at line 29 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_GET_SAMPLE_COUNT
#define COMMAND_GET_SAMPLE_COUNT 34
Definition at line 39 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_GET_SDRAM_READ_CNT
#define COMMAND_GET_SDRAM_READ_CNT 31
Definition at line 36 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_GET_SDRAM_WRITE_CNT
#define COMMAND_GET_SDRAM_WRITE_CNT 32
Definition at line 37 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_READ
#define COMMAND_READ 38
Definition at line 43 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string(), kest_fpga_req_data(), and kest_fpga_req_data_p().
COMMAND_READ_COMMAND_LOG
#define COMMAND_READ_COMMAND_LOG 33
Definition at line 38 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string().
COMMAND_READOUT
#define COMMAND_READOUT 20
Definition at line 25 of file kest_fpga_io.h.
Referenced by kest_fpga_command_to_string(), kest_fpga_readout(), kest_fpga_readout_byte(), kest_fpga_readout_bytes(), kest_fpga_req_data(), and kest_fpga_req_data_p().
COMMAND_SET_INPUT_GAIN
#define COMMAND_SET_INPUT_GAIN 11
Definition at line 16 of file kest_fpga_io.h.
Referenced by kest_command_log_test(), kest_fpga_batch_print(), kest_fpga_command_to_string(), and kest_fpga_set_input_gain().
COMMAND_SET_OUTPUT_GAIN
#define COMMAND_SET_OUTPUT_GAIN 12
Definition at line 17 of file kest_fpga_io.h.
Referenced by kest_command_log_test(), kest_fpga_batch_print(), kest_fpga_command_to_string(), and kest_fpga_set_output_gain().
COMMAND_UPDATE_BLOCK_REG_0
#define COMMAND_UPDATE_BLOCK_REG_0 13
Definition at line 18 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_append_block_register_updates(), kest_fpga_batch_print(), and kest_fpga_command_to_string().
COMMAND_UPDATE_BLOCK_REG_1
#define COMMAND_UPDATE_BLOCK_REG_1 14
Definition at line 19 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_append_block_register_updates(), kest_fpga_batch_print(), and kest_fpga_command_to_string().
COMMAND_UPDATE_FILTER_COEF
#define COMMAND_UPDATE_FILTER_COEF 18
Definition at line 23 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_append_filter_updates(), kest_fpga_batch_print(), and kest_fpga_command_to_string().
COMMAND_WRITE_BLOCK_INSTR
#define COMMAND_WRITE_BLOCK_INSTR 2
Definition at line 11 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_append_block_instr(), kest_fpga_batch_print(), and kest_fpga_command_to_string().
COMMAND_WRITE_BLOCK_REG_0
#define COMMAND_WRITE_BLOCK_REG_0 3
Definition at line 12 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_append_block_regs(), kest_fpga_batch_print(), and kest_fpga_command_to_string().
COMMAND_WRITE_BLOCK_REG_1
#define COMMAND_WRITE_BLOCK_REG_1 4
Definition at line 13 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_append_block_regs(), kest_fpga_batch_print(), and kest_fpga_command_to_string().
COMMAND_WRITE_FILTER_COEF
#define COMMAND_WRITE_FILTER_COEF 17
Definition at line 22 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_append_resource(), kest_fpga_batch_print(), and kest_fpga_command_to_string().
DATA_REQ_BLOCK_INSTR
#define DATA_REQ_BLOCK_INSTR 1
Definition at line 135 of file kest_fpga_io.h.
Referenced by kest_fpga_get_block_instr().
DATA_REQ_BLOCK_REG
#define DATA_REQ_BLOCK_REG 2
Definition at line 136 of file kest_fpga_io.h.
Referenced by kest_fpga_get_block_reg().
DATA_REQ_DELAY_BUF_ADDR
#define DATA_REQ_DELAY_BUF_ADDR 6
Definition at line 141 of file kest_fpga_io.h.
Referenced by kest_fpga_get_delay_buffer_addr().
DATA_REQ_DELAY_BUF_DELAY
#define DATA_REQ_DELAY_BUF_DELAY 5
Definition at line 140 of file kest_fpga_io.h.
Referenced by kest_fpga_get_delay_buffer_delay().
DATA_REQ_DELAY_BUF_GAIN
#define DATA_REQ_DELAY_BUF_GAIN 8
Definition at line 143 of file kest_fpga_io.h.
Referenced by kest_fpga_get_delay_buffer_gain().
DATA_REQ_DELAY_BUF_LRWA
#define DATA_REQ_DELAY_BUF_LRWA 9
Definition at line 144 of file kest_fpga_io.h.
Referenced by kest_fpga_get_delay_buffer_last_rw_addr().
DATA_REQ_DELAY_BUF_POS
#define DATA_REQ_DELAY_BUF_POS 7
Definition at line 142 of file kest_fpga_io.h.
Referenced by kest_fpga_get_delay_buffer_pos().
DATA_REQ_DELAY_BUF_SIZE
#define DATA_REQ_DELAY_BUF_SIZE 4
Definition at line 139 of file kest_fpga_io.h.
Referenced by kest_fpga_get_delay_buffer_size().
DATA_REQ_N_BLOCKS
#define DATA_REQ_N_BLOCKS 14
Definition at line 134 of file kest_fpga_io.h.
Referenced by kest_fpga_get_n_blocks().
DATA_REQ_N_DELAY_BUF
#define DATA_REQ_N_DELAY_BUF 3
Definition at line 138 of file kest_fpga_io.h.
Referenced by kest_fpga_get_n_delay_buffers().
DATA_REQ_SAMPLE_COUNT
#define DATA_REQ_SAMPLE_COUNT 10
Definition at line 145 of file kest_fpga_io.h.
Referenced by kest_fpga_get_sample_count().
DATA_REQ_SDRAM_READ_CNT
#define DATA_REQ_SDRAM_READ_CNT 11
Definition at line 146 of file kest_fpga_io.h.
Referenced by kest_fpga_get_sdram_read_count().
DATA_REQ_SDRAM_WRITE_CNT
#define DATA_REQ_SDRAM_WRITE_CNT 12
Definition at line 147 of file kest_fpga_io.h.
Referenced by kest_fpga_get_sdram_write_count().
DATA_REQ_STUCK_FLAGS
#define DATA_REQ_STUCK_FLAGS 13
Definition at line 148 of file kest_fpga_io.h.
Referenced by kest_fpga_get_stuck_flags().
FPGA_BOOT_MS
#define FPGA_BOOT_MS 2500
Definition at line 6 of file kest_fpga_io.h.
Referenced by kest_fpga_comms_task().
KEST_FPGA_DATA_BYTES
#define KEST_FPGA_DATA_BYTES (KEST_FPGA_DATA_WIDTH / 8)
Definition at line 51 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_print().
KEST_FPGA_DATA_WIDTH
#define KEST_FPGA_DATA_WIDTH 16
Definition at line 49 of file kest_fpga_io.h.
Referenced by float_to_q_nminus1(), and kest_compute_register_formats().
KEST_FPGA_FILTER_WIDTH
#define KEST_FPGA_FILTER_WIDTH 18
Definition at line 50 of file kest_fpga_io.h.
Referenced by kest_filter_compute_format(), and kest_fpga_batch_append_resource().
KEST_FPGA_N_BLOCKS
#define KEST_FPGA_N_BLOCKS 256
Definition at line 47 of file kest_fpga_io.h.
Referenced by kest_new_fpga_transfer_batch().
KEST_FPGA_SAMPLE_RATE
#define KEST_FPGA_SAMPLE_RATE 44100
Definition at line 4 of file kest_fpga_io.h.
Referenced by kest_fpga_batch_append_resource().
SPI_RESPONSE_OK
#define SPI_RESPONSE_OK 1
Definition at line 45 of file kest_fpga_io.h.
Typedef Documentation
kest_fpga_sample_t
typedef int16_t kest_fpga_sample_t
Definition at line 54 of file kest_fpga_io.h.
Function Documentation
kest_fpga_batch_append()
int kest_fpga_batch_append (kest_fpga_transfer_batch * seq, uint8_t x)
Definition at line 220 of file kest_fpga_io.c.
Referenced by kest_fpga_batch_append_16(), kest_fpga_batch_append_24(), kest_fpga_batch_append_32(), kest_fpga_batch_append_block_instr(), kest_fpga_batch_append_block_register_updates(), kest_fpga_batch_append_block_regs(), kest_fpga_batch_append_filter_updates(), and kest_fpga_batch_append_resource().
kest_fpga_batch_append_16()
int kest_fpga_batch_append_16 (kest_fpga_transfer_batch * seq, uint16_t x)
Definition at line 242 of file kest_fpga_io.c.
Referenced by kest_fpga_batch_append_block_number(), kest_fpga_batch_append_block_register_updates(), kest_fpga_batch_append_block_regs(), kest_fpga_batch_append_filter_updates(), and kest_fpga_batch_append_resource().
kest_fpga_batch_append_24()
int kest_fpga_batch_append_24 (kest_fpga_transfer_batch * seq, uint32_t x)
Definition at line 258 of file kest_fpga_io.c.
Referenced by kest_fpga_batch_append_filter_updates(), and kest_fpga_batch_append_resource().
kest_fpga_batch_append_32()
int kest_fpga_batch_append_32 (kest_fpga_transfer_batch * seq, uint32_t x)
Definition at line 275 of file kest_fpga_io.c.
Referenced by kest_fpga_batch_append_block_instr().
kest_fpga_command_to_string()
char * kest_fpga_command_to_string (int command)
Definition at line 105 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task(), kest_fpga_print_command_log(), kest_fpga_program_batch_send_careful(), and kest_fpga_transfer_batch_send_careful().
kest_fpga_commit_reg_updates()
void kest_fpga_commit_reg_updates ()
Definition at line 485 of file kest_fpga_io.c.
kest_fpga_decode_status_flags()
int kest_fpga_decode_status_flags (kest_fpga_status_flags * flags, uint8_t byte)
Definition at line 490 of file kest_fpga_io.c.
Referenced by get_and_sprint_flags_compact(), kest_fpga_get_status_flags(), and kest_fpga_send_byte_get_flags().
kest_fpga_get_block_instr()
uint32_t kest_fpga_get_block_instr (int block, kest_fpga_status_flags * flags)
Definition at line 656 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_block_reg()
uint16_t kest_fpga_get_block_reg (int block, int reg, kest_fpga_status_flags * flags)
Definition at line 676 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_delay_buffer_addr()
int kest_fpga_get_delay_buffer_addr (int handle, kest_fpga_status_flags * flags)
Definition at line 705 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_delay_buffer_delay()
int kest_fpga_get_delay_buffer_delay (int handle, kest_fpga_status_flags * flags)
Definition at line 698 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_delay_buffer_gain()
uint16_t kest_fpga_get_delay_buffer_gain (int handle, kest_fpga_status_flags * flags)
Definition at line 719 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_delay_buffer_last_rw_addr()
int kest_fpga_get_delay_buffer_last_rw_addr (int handle, uint16_t * read_addr, uint16_t * write_addr, kest_fpga_status_flags * flags)
Definition at line 726 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_delay_buffer_pos()
int kest_fpga_get_delay_buffer_pos (int handle, kest_fpga_status_flags * flags)
Definition at line 712 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_delay_buffer_size()
int kest_fpga_get_delay_buffer_size (int handle, kest_fpga_status_flags * flags)
Definition at line 691 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_n_blocks()
int kest_fpga_get_n_blocks (kest_fpga_status_flags * flags)
Definition at line 666 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_n_delay_buffers()
int kest_fpga_get_n_delay_buffers (kest_fpga_status_flags * flags)
Definition at line 686 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_sample_count()
uint64_t kest_fpga_get_sample_count (kest_fpga_status_flags * flags)
Definition at line 739 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_sdram_read_count()
uint64_t kest_fpga_get_sdram_read_count (kest_fpga_status_flags * flags)
Definition at line 744 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_sdram_write_count()
uint64_t kest_fpga_get_sdram_write_count (kest_fpga_status_flags * flags)
Definition at line 749 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_status_flags()
int kest_fpga_get_status_flags (kest_fpga_status_flags * flags)
Definition at line 507 of file kest_fpga_io.c.
Referenced by get_and_sprint_flags(), kest_fpga_comms_task(), kest_fpga_req_data(), and kest_fpga_req_data_p().
kest_fpga_get_stuck_flags()
uint32_t kest_fpga_get_stuck_flags (kest_fpga_status_flags * flags)
Definition at line 671 of file kest_fpga_io.c.
kest_fpga_program_batch_send()
int kest_fpga_program_batch_send (kest_fpga_transfer_batch batch)
Definition at line 369 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task().
kest_fpga_program_batch_send_careful()
int kest_fpga_program_batch_send_careful (kest_fpga_transfer_batch batch)
Definition at line 382 of file kest_fpga_io.c.
kest_fpga_read_byte()
uint8_t kest_fpga_read_byte ()
Definition at line 169 of file kest_fpga_io.c.
Referenced by get_and_sprint_flags_compact(), and kest_fpga_get_status_flags().
kest_fpga_read_command_log()
int kest_fpga_read_command_log (uint8_t * buf)
kest_fpga_readout()
uint8_t kest_fpga_readout ()
Definition at line 177 of file kest_fpga_io.c.
Referenced by kest_fpga_req_data(), and kest_fpga_req_data_p().
kest_fpga_send_byte()
int kest_fpga_send_byte (uint8_t byte)
Definition at line 148 of file kest_fpga_io.c.
Referenced by kest_command_log_test(), kest_fpga_commit_reg_updates(), kest_fpga_comms_print_full_scan(), kest_fpga_comms_task(), kest_fpga_handle_misalignment(), kest_fpga_program_batch_send(), kest_fpga_program_batch_send_careful(), and kest_fpga_readout_bytes().
kest_fpga_send_byte_get_flags()
int kest_fpga_send_byte_get_flags (uint8_t tx, kest_fpga_status_flags * flags)
Definition at line 153 of file kest_fpga_io.c.
Referenced by kest_fpga_req_data(), and kest_fpga_req_data_p().
kest_fpga_set_input_gain()
void kest_fpga_set_input_gain (float gain_db)
Definition at line 432 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task().
kest_fpga_set_output_gain()
void kest_fpga_set_output_gain (float gain_db)
Definition at line 458 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task().
kest_fpga_spi_init()
int kest_fpga_spi_init ()
Definition at line 20 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task().
kest_fpga_status_flags_print()
int kest_fpga_status_flags_print (kest_fpga_status_flags * flags)
Definition at line 537 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task().
kest_fpga_status_flags_sprint()
int kest_fpga_status_flags_sprint (kest_string * str, kest_fpga_status_flags * flags)
Definition at line 519 of file kest_fpga_io.c.
Referenced by get_and_sprint_flags().
kest_fpga_transfer_batch_send()
int kest_fpga_transfer_batch_send (kest_fpga_transfer_batch batch)
Definition at line 422 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task(), kest_fpga_set_input_gain(), and kest_fpga_set_output_gain().
kest_fpga_transfer_batch_send_careful()
int kest_fpga_transfer_batch_send_careful (kest_fpga_transfer_batch batch)
Definition at line 334 of file kest_fpga_io.c.
Referenced by kest_fpga_transfer_batch_send().
kest_free_fpga_transfer_batch()
void kest_free_fpga_transfer_batch (kest_fpga_transfer_batch batch)
Definition at line 215 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task(), and kest_pipeline_create_fpga_transfer_batch().
kest_new_fpga_transfer_batch()
kest_fpga_transfer_batch kest_new_fpga_transfer_batch ()
Definition at line 203 of file kest_fpga_io.c.
Referenced by kest_effect_update_fpga(), and kest_pipeline_create_fpga_transfer_batch().
kest_send_byte_to_fpga()
int kest_send_byte_to_fpga (uint8_t byte)
kest_send_bytes_to_fpga()
int kest_send_bytes_to_fpga (uint8_t * buf, int n)