Kestrel Interface: kest_parameter_widget.c File Reference
kest_parameter_widget.c File Reference
#include "kest_int.h"
#include "kest_param_update.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (kest_parameter_widget)
IMPLEMENT_LINKED_PTR_LIST (kest_setting_widget)
int parameter_widget_update_value (kest_parameter_widget *pw)
void param_widget_rep_update (void *representer, void *representee)
int nullify_parameter_widget (kest_parameter_widget *pw)
void format_parameter_widget_value_label_v (kest_parameter_widget *pw, float v)
void format_parameter_widget_value_label (kest_parameter_widget *pw)
void parameter_widget_update_value_label_v (kest_parameter_widget *pw, float v)
void parameter_widget_update_value_label (kest_parameter_widget *pw)
int configure_parameter_widget (kest_parameter_widget *pw, kest_parameter *param, kest_preset *preset, kest_ui_page *parent)
void kest_parameter_widget_refresh_timer_wrapper (lv_timer_t *timer)
void kest_parameter_widget_refresh_async_wrapper (void *pw)
int kest_parameter_widget_refresh (kest_parameter_widget *pw)
void parameter_widget_refresh (kest_parameter_widget *pw)
void parameter_widget_refresh_cb (lv_event_t *event)
void parameter_widget_change_cb_inner (kest_parameter_widget *pw)
void parameter_widget_change_cb (lv_event_t *event)
void parameter_widget_pressing_cb (lv_event_t *event)
void parameter_widget_released_cb (lv_event_t *event)
int parameter_widget_create_ui (kest_parameter_widget *pw, lv_obj_t *parent)
int parameter_widget_create_ui_no_callback (kest_parameter_widget *pw, lv_obj_t *parent)
void free_parameter_widget (kest_parameter_widget *pw)
int kest_parameter_widget_align_nominal_value (kest_parameter_widget *pw)
int setting_widget_update_value (kest_setting_widget *sw)
void setting_widget_rep_update (void *representer, void *representee)
int nullify_setting_widget (kest_setting_widget *sw)
void sw_field_display_bare_value (kest_setting_widget *sw)
void sw_field_display_value_with_units (kest_setting_widget *sw)
int configure_setting_widget (kest_setting_widget *sw, kest_setting *setting, kest_preset *preset, kest_ui_page *parent)
void setting_widget_refresh_cb (lv_event_t *event)
int setting_widget_calc_value (kest_setting_widget *sw, int16_t *target)
void sw_field_reject (kest_setting_widget *sw)
void sw_field_save_cb (lv_event_t *e)
void sw_field_cancel_cb (lv_event_t *e)
void edit_sw_field_cb (lv_event_t *e)
void setting_widget_change_cb_inner (kest_setting_widget *sw)
void setting_widget_change_cb (lv_event_t *event)
int setting_widget_create_ui (kest_setting_widget *sw, lv_obj_t *parent)
int setting_widget_create_ui_no_callback (kest_setting_widget *sw, lv_obj_t *parent)
void free_setting_widget (kest_setting_widget *sw)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 3 of file kest_parameter_widget.c.
Function Documentation
configure_parameter_widget()
int configure_parameter_widget (kest_parameter_widget * pw, kest_parameter * param, kest_preset * preset, kest_ui_page * parent)
Definition at line 188 of file kest_parameter_widget.c.
Referenced by configure_effect_settings_page(), configure_effect_view(), configure_main_menu(), and create_parameter_widget_menu_item().
configure_setting_widget()
int configure_setting_widget (kest_setting_widget * sw, kest_setting * setting, kest_preset * preset, kest_ui_page * parent)
Definition at line 694 of file kest_parameter_widget.c.
Referenced by configure_effect_settings_page(), and configure_effect_view().
edit_sw_field_cb()
void edit_sw_field_cb (lv_event_t * e)
Definition at line 891 of file kest_parameter_widget.c.
Referenced by setting_widget_create_ui().
format_parameter_widget_value_label()
void format_parameter_widget_value_label (kest_parameter_widget * pw)
Definition at line 71 of file kest_parameter_widget.c.
Referenced by parameter_widget_update_value_label().
format_parameter_widget_value_label_v()
void format_parameter_widget_value_label_v (kest_parameter_widget * pw, float v)
Definition at line 58 of file kest_parameter_widget.c.
Referenced by parameter_widget_update_value_label_v().
free_parameter_widget()
void free_parameter_widget (kest_parameter_widget * pw)
Definition at line 540 of file kest_parameter_widget.c.
Referenced by free_effect_view().
free_setting_widget()
void free_setting_widget (kest_setting_widget * sw)
Definition at line 1081 of file kest_parameter_widget.c.
IMPLEMENT_LINKED_PTR_LIST() [1/2]
IMPLEMENT_LINKED_PTR_LIST (kest_parameter_widget)
IMPLEMENT_LINKED_PTR_LIST() [2/2]
IMPLEMENT_LINKED_PTR_LIST (kest_setting_widget)
kest_parameter_widget_align_nominal_value()
int kest_parameter_widget_align_nominal_value (kest_parameter_widget * pw)
Definition at line 550 of file kest_parameter_widget.c.
Referenced by enter_main_menu().
kest_parameter_widget_refresh()
int kest_parameter_widget_refresh (kest_parameter_widget * pw)
Definition at line 239 of file kest_parameter_widget.c.
Referenced by enter_main_menu(), enter_menu_page(), kest_parameter_if_updated_refresh_pw(), kest_parameter_widget_refresh_async_wrapper(), and kest_parameter_widget_refresh_timer_wrapper().
kest_parameter_widget_refresh_async_wrapper()
void kest_parameter_widget_refresh_async_wrapper (void * pw)
Definition at line 234 of file kest_parameter_widget.c.
Referenced by kest_parameter_if_updated_refresh_pw_async().
kest_parameter_widget_refresh_timer_wrapper()
void kest_parameter_widget_refresh_timer_wrapper (lv_timer_t * timer)
Definition at line 217 of file kest_parameter_widget.c.
nullify_parameter_widget()
int nullify_parameter_widget (kest_parameter_widget * pw)
Definition at line 30 of file kest_parameter_widget.c.
Referenced by configure_effect_view(), configure_main_menu(), create_parameter_widget_menu_item(), and init_effect_settings_page().
nullify_setting_widget()
int nullify_setting_widget (kest_setting_widget * sw)
Definition at line 585 of file kest_parameter_widget.c.
Referenced by configure_effect_view(), and init_effect_settings_page().
param_widget_rep_update()
void param_widget_rep_update (void * representer, void * representee)
Definition at line 14 of file kest_parameter_widget.c.
Referenced by nullify_parameter_widget().
parameter_widget_change_cb()
void parameter_widget_change_cb (lv_event_t * event)
Definition at line 370 of file kest_parameter_widget.c.
Referenced by parameter_widget_create_ui().
parameter_widget_change_cb_inner()
void parameter_widget_change_cb_inner (kest_parameter_widget * pw)
Definition at line 299 of file kest_parameter_widget.c.
Referenced by parameter_widget_change_cb(), and parameter_widget_change_cb_settings_wrapper().
parameter_widget_create_ui()
int parameter_widget_create_ui (kest_parameter_widget * pw, lv_obj_t * parent)
Definition at line 414 of file kest_parameter_widget.c.
Referenced by create_effect_settings_page_ui(), create_effect_view_ui(), create_main_menu_ui(), and create_preset_settings_page_ui().
parameter_widget_create_ui_no_callback()
int parameter_widget_create_ui_no_callback (kest_parameter_widget * pw, lv_obj_t * parent)
Definition at line 431 of file kest_parameter_widget.c.
Referenced by create_menu_item_ui(), and parameter_widget_create_ui().
parameter_widget_pressing_cb()
void parameter_widget_pressing_cb (lv_event_t * event)
Definition at line 383 of file kest_parameter_widget.c.
Referenced by parameter_widget_create_ui().
parameter_widget_refresh()
void parameter_widget_refresh (kest_parameter_widget * pw)
Definition at line 271 of file kest_parameter_widget.c.
Referenced by kest_parameter_widget_rep_update().
parameter_widget_refresh_cb()
void parameter_widget_refresh_cb (lv_event_t * event)
Definition at line 285 of file kest_parameter_widget.c.
parameter_widget_released_cb()
void parameter_widget_released_cb (lv_event_t * event)
Definition at line 399 of file kest_parameter_widget.c.
Referenced by parameter_widget_create_ui().
parameter_widget_update_value()
int parameter_widget_update_value (kest_parameter_widget * pw)
Definition at line 84 of file kest_parameter_widget.c.
Referenced by kest_parameter_widget_refresh(), param_widget_rep_update(), parameter_widget_create_ui_no_callback(), parameter_widget_refresh(), and parameter_widget_refresh_cb().
parameter_widget_update_value_label()
void parameter_widget_update_value_label (kest_parameter_widget * pw)
Definition at line 173 of file kest_parameter_widget.c.
Referenced by kest_parameter_widget_refresh(), param_widget_rep_update(), parameter_widget_create_ui_no_callback(), parameter_widget_refresh(), and parameter_widget_refresh_cb().
parameter_widget_update_value_label_v()
void parameter_widget_update_value_label_v (kest_parameter_widget * pw, float v)
Definition at line 158 of file kest_parameter_widget.c.
Referenced by parameter_widget_change_cb_inner().
setting_widget_calc_value()
int setting_widget_calc_value (kest_setting_widget * sw, int16_t * target)
Definition at line 722 of file kest_parameter_widget.c.
Referenced by setting_widget_change_cb_inner().
setting_widget_change_cb()
void setting_widget_change_cb (lv_event_t * event)
Definition at line 951 of file kest_parameter_widget.c.
Referenced by setting_widget_create_ui().
setting_widget_change_cb_inner()
void setting_widget_change_cb_inner (kest_setting_widget * sw)
Definition at line 913 of file kest_parameter_widget.c.
Referenced by setting_widget_change_cb().
setting_widget_create_ui()
int setting_widget_create_ui (kest_setting_widget * sw, lv_obj_t * parent)
Definition at line 964 of file kest_parameter_widget.c.
Referenced by create_effect_view_ui().
setting_widget_create_ui_no_callback()
int setting_widget_create_ui_no_callback (kest_setting_widget * sw, lv_obj_t * parent)
Definition at line 997 of file kest_parameter_widget.c.
Referenced by create_effect_settings_page_ui(), and setting_widget_create_ui().
setting_widget_refresh_cb()
void setting_widget_refresh_cb (lv_event_t * event)
Definition at line 712 of file kest_parameter_widget.c.
setting_widget_rep_update()
void setting_widget_rep_update (void * representer, void * representee)
Definition at line 574 of file kest_parameter_widget.c.
Referenced by nullify_setting_widget().
setting_widget_update_value()
int setting_widget_update_value (kest_setting_widget * sw)
Definition at line 644 of file kest_parameter_widget.c.
Referenced by setting_widget_create_ui_no_callback(), and setting_widget_rep_update().
sw_field_cancel_cb()
void sw_field_cancel_cb (lv_event_t * e)
Definition at line 866 of file kest_parameter_widget.c.
Referenced by edit_sw_field_cb().
sw_field_display_bare_value()
void sw_field_display_bare_value (kest_setting_widget * sw)
Definition at line 607 of file kest_parameter_widget.c.
Referenced by edit_sw_field_cb().
sw_field_display_value_with_units()
void sw_field_display_value_with_units (kest_setting_widget * sw)
Definition at line 620 of file kest_parameter_widget.c.
Referenced by setting_widget_refresh_cb(), setting_widget_update_value(), sw_field_cancel_cb(), sw_field_reject(), and sw_field_save_cb().
sw_field_reject()
void sw_field_reject (kest_setting_widget * sw)
Definition at line 764 of file kest_parameter_widget.c.
Referenced by sw_field_save_cb().
sw_field_save_cb()
void sw_field_save_cb (lv_event_t * e)
Definition at line 772 of file kest_parameter_widget.c.
Referenced by edit_sw_field_cb().