Kestrel Interface: kest_preset.c File Reference
kest_preset.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 1
Functions
IMPLEMENT_LINKED_PTR_LIST (kest_preset)
int init_m_preset (kest_preset *preset)
int preset_set_id (kest_preset *preset, uint16_t id)
int kest_preset_rectify_ids (kest_preset *preset)
int kest_preset_set_active (kest_preset *preset)
int kest_preset_set_inactive (kest_preset *preset)
int kest_preset_add_representation (kest_preset *preset, kest_representation *rep)
int kest_preset_update_representations (kest_preset *preset)
int kest_preset_remove_representation (kest_preset *preset, kest_representation *rep)
int kest_preset_set_default_name_from_id (kest_preset *preset)
kest_effect * kest_preset_append_effect_eff (kest_preset *preset, kest_effect_desc *eff)
int kest_preset_remove_effect (kest_preset *preset, uint16_t id)
int kest_preset_move_effect (kest_preset *preset, int new_pos, int old_pos)
int clone_preset (kest_preset *dest, kest_preset *src)
void gut_preset (kest_preset *preset)
void free_preset (kest_preset *preset)
void kest_free_preset (kest_preset *preset)
kest_preset * create_new_preset_with_teensy ()
int kest_preset_save (kest_preset *preset)
int kest_preset_create_fpga_transfer_batch (kest_preset *preset, kest_fpga_transfer_batch *batch)
int kest_preset_program_fpga (kest_preset *preset)
int kest_preset_if_active_update_fpga (kest_preset *preset)
void kest_preset_file_rep_update (void *representer, void *representee)
kest_effect * kest_preset_get_effect_by_id (kest_preset *preset, int id)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 1
Definition at line 4 of file kest_preset.c.
Function Documentation
clone_preset()
int clone_preset (kest_preset * dest, kest_preset * src)
Definition at line 240 of file kest_preset.c.
create_new_preset_with_teensy()
kest_preset * create_new_preset_with_teensy ()
Definition at line 332 of file kest_preset.c.
free_preset()
void free_preset (kest_preset * preset)
Definition at line 287 of file kest_preset.c.
Referenced by cxt_remove_preset(), kest_context_add_preset(), kest_context_add_preset_rp(), kest_free_preset(), and load_saved_presets().
gut_preset()
void gut_preset (kest_preset * preset)
Definition at line 263 of file kest_preset.c.
Referenced by free_preset().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (kest_preset)
init_m_preset()
int init_m_preset (kest_preset * preset)
Definition at line 13 of file kest_preset.c.
Referenced by kest_context_add_preset(), kest_context_add_preset_rp(), and load_saved_presets().
kest_free_preset()
void kest_free_preset (kest_preset * preset)
Definition at line 297 of file kest_preset.c.
Referenced by kest_sequence_delete_preset().
kest_preset_add_representation()
int kest_preset_add_representation (kest_preset * preset, kest_representation * rep)
Definition at line 110 of file kest_preset.c.
Referenced by configure_preset_view(), and seq_plus_cb().
kest_preset_append_effect_eff()
kest_effect * kest_preset_append_effect_eff (kest_preset * preset, kest_effect_desc * eff)
Definition at line 186 of file kest_preset.c.
Referenced by add_effect_from_menu_eff(), and read_preset_from_file().
kest_preset_create_fpga_transfer_batch()
int kest_preset_create_fpga_transfer_batch (kest_preset * preset, kest_fpga_transfer_batch * batch)
Definition at line 399 of file kest_preset.c.
kest_preset_file_rep_update()
void kest_preset_file_rep_update (void * representer, void * representee)
Definition at line 457 of file kest_preset.c.
Referenced by init_m_preset().
kest_preset_get_effect_by_id()
kest_effect * kest_preset_get_effect_by_id (kest_preset * preset, int id)
Definition at line 473 of file kest_preset.c.
Referenced by kest_page_id_find_page().
kest_preset_if_active_update_fpga()
int kest_preset_if_active_update_fpga (kest_preset * preset)
Definition at line 439 of file kest_preset.c.
Referenced by add_effect_from_menu_eff(), kest_preset_move_effect(), kest_preset_remove_effect(), preset_view_effect_delete_cb(), and sw_field_save_cb().
kest_preset_move_effect()
int kest_preset_move_effect (kest_preset * preset, int new_pos, int old_pos)
Definition at line 221 of file kest_preset.c.
Referenced by preset_view_effect_moved_cb().
kest_preset_program_fpga()
int kest_preset_program_fpga (kest_preset * preset)
Definition at line 412 of file kest_preset.c.
Referenced by kest_preset_if_active_update_fpga(), and kest_preset_set_active().
kest_preset_rectify_ids()
int kest_preset_rectify_ids (kest_preset * preset)
Definition at line 70 of file kest_preset.c.
Referenced by load_saved_presets().
kest_preset_remove_effect()
int kest_preset_remove_effect (kest_preset * preset, uint16_t id)
Definition at line 207 of file kest_preset.c.
Referenced by cxt_remove_effect(), and preset_view_effect_delete_cb().
kest_preset_remove_representation()
int kest_preset_remove_representation (kest_preset * preset, kest_representation * rep)
Definition at line 144 of file kest_preset.c.
kest_preset_save()
int kest_preset_save (kest_preset * preset)
Definition at line 377 of file kest_preset.c.
Referenced by cxt_save_all_presets().
kest_preset_set_active()
int kest_preset_set_active (kest_preset * preset)
Definition at line 84 of file kest_preset.c.
Referenced by set_active_preset(), and set_active_preset_from_sequence().
kest_preset_set_default_name_from_id()
int kest_preset_set_default_name_from_id (kest_preset * preset)
Definition at line 156 of file kest_preset.c.
Referenced by configure_preset_settings_page(), and create_preset_view_ui().
kest_preset_set_inactive()
int kest_preset_set_inactive (kest_preset * preset)
Definition at line 98 of file kest_preset.c.
Referenced by set_active_preset(), and set_active_preset_from_sequence().
kest_preset_update_representations()
int kest_preset_update_representations (kest_preset * preset)
Definition at line 131 of file kest_preset.c.
Referenced by add_effect_from_menu_eff(), kest_preset_save(), kest_preset_set_active(), kest_preset_set_inactive(), and preset_view_save_name().
preset_set_id()
int preset_set_id (kest_preset * preset, uint16_t id)
Definition at line 59 of file kest_preset.c.