Kestrel Interface: kest_fpga_io.c File Reference
kest_fpga_io.c File Reference
#include "kest_int.h"
#include <driver/spi_master.h>
Macros
#define PRINTLINES_ALLOWED 0
#define PIN_NUM_MISO 14
#define PIN_NUM_MOSI 6
#define PIN_NUM_CLK 5
#define PIN_NUM_CS 4
Functions
int kest_fpga_spi_init ()
int kest_fpga_txrx (uint8_t *tx, uint8_t *rx, size_t len)
char * kest_fpga_command_to_string (int command)
int kest_fpga_send_byte (uint8_t byte)
int kest_fpga_send_byte_get_flags (uint8_t tx, kest_fpga_status_flags *flags)
uint8_t kest_fpga_read_byte ()
uint8_t kest_fpga_readout ()
uint8_t kest_fpga_readout_byte ()
int kest_fpga_readout_bytes (uint8_t *buf, int n)
kest_fpga_transfer_batch kest_new_fpga_transfer_batch ()
void kest_free_fpga_transfer_batch (kest_fpga_transfer_batch batch)
int kest_fpga_batch_append (kest_fpga_transfer_batch *seq, uint8_t x)
int kest_fpga_batch_append_16 (kest_fpga_transfer_batch *seq, uint16_t x)
int kest_fpga_batch_append_24 (kest_fpga_transfer_batch *seq, uint32_t x)
int kest_fpga_batch_append_32 (kest_fpga_transfer_batch *seq, uint32_t x)
int kest_fpga_batch_concat (kest_fpga_transfer_batch *seq, kest_fpga_transfer_batch *seq2)
int kest_fpga_transfer_batch_send_careful (kest_fpga_transfer_batch batch)
int kest_fpga_program_batch_send (kest_fpga_transfer_batch batch)
int kest_fpga_program_batch_send_careful (kest_fpga_transfer_batch batch)
int kest_fpga_transfer_batch_send (kest_fpga_transfer_batch batch)
void kest_fpga_set_input_gain (float gain_db)
void kest_fpga_set_output_gain (float gain_db)
void kest_fpga_commit_reg_updates ()
int kest_fpga_decode_status_flags (kest_fpga_status_flags *flags, uint8_t byte)
int kest_fpga_get_status_flags (kest_fpga_status_flags *flags)
int kest_fpga_status_flags_sprint (kest_string *str, kest_fpga_status_flags *flags)
int kest_fpga_status_flags_print (kest_fpga_status_flags *flags)
int64_t kest_fpga_req_data (int req, int n_bytes, kest_fpga_status_flags *flags)
int64_t kest_fpga_req_data_p (uint8_t req, uint8_t *p, int n, int m, kest_fpga_status_flags *flags)
uint32_t kest_fpga_get_block_instr (int block, kest_fpga_status_flags *flags)
int kest_fpga_get_n_blocks (kest_fpga_status_flags *flags)
uint32_t kest_fpga_get_stuck_flags (kest_fpga_status_flags *flags)
uint16_t kest_fpga_get_block_reg (int block, int reg, kest_fpga_status_flags *flags)
int kest_fpga_get_n_delay_buffers (kest_fpga_status_flags *flags)
int kest_fpga_get_delay_buffer_size (int handle, kest_fpga_status_flags *flags)
int kest_fpga_get_delay_buffer_delay (int handle, kest_fpga_status_flags *flags)
int kest_fpga_get_delay_buffer_addr (int handle, kest_fpga_status_flags *flags)
int kest_fpga_get_delay_buffer_pos (int handle, kest_fpga_status_flags *flags)
uint16_t kest_fpga_get_delay_buffer_gain (int handle, kest_fpga_status_flags *flags)
int kest_fpga_get_delay_buffer_last_rw_addr (int handle, uint16_t *read_addr, uint16_t *write_addr, kest_fpga_status_flags *flags)
uint64_t kest_fpga_get_sample_count (kest_fpga_status_flags *flags)
uint64_t kest_fpga_get_sdram_read_count (kest_fpga_status_flags *flags)
uint64_t kest_fpga_get_sdram_write_count (kest_fpga_status_flags *flags)
Variables
spi_device_handle_t spi_handle
Macro Definition Documentation
PIN_NUM_CLK
#define PIN_NUM_CLK 5
Definition at line 14 of file kest_fpga_io.c.
Referenced by kest_fpga_spi_init().
PIN_NUM_CS
#define PIN_NUM_CS 4
Definition at line 15 of file kest_fpga_io.c.
Referenced by kest_fpga_spi_init().
PIN_NUM_MISO
#define PIN_NUM_MISO 14
Definition at line 12 of file kest_fpga_io.c.
Referenced by kest_fpga_spi_init().
PIN_NUM_MOSI
#define PIN_NUM_MOSI 6
Definition at line 13 of file kest_fpga_io.c.
Referenced by kest_fpga_spi_init().
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_fpga_io.c.
Function Documentation
kest_fpga_batch_append()
int kest_fpga_batch_append (kest_fpga_transfer_batch * seq, uint8_t x)
Definition at line 220 of file kest_fpga_io.c.
Referenced by kest_fpga_batch_append_16(), kest_fpga_batch_append_24(), kest_fpga_batch_append_32(), kest_fpga_batch_append_block_instr(), kest_fpga_batch_append_block_register_updates(), kest_fpga_batch_append_block_regs(), kest_fpga_batch_append_filter_updates(), and kest_fpga_batch_append_resource().
kest_fpga_batch_append_16()
int kest_fpga_batch_append_16 (kest_fpga_transfer_batch * seq, uint16_t x)
Definition at line 242 of file kest_fpga_io.c.
Referenced by kest_fpga_batch_append_block_number(), kest_fpga_batch_append_block_register_updates(), kest_fpga_batch_append_block_regs(), kest_fpga_batch_append_filter_updates(), and kest_fpga_batch_append_resource().
kest_fpga_batch_append_24()
int kest_fpga_batch_append_24 (kest_fpga_transfer_batch * seq, uint32_t x)
Definition at line 258 of file kest_fpga_io.c.
Referenced by kest_fpga_batch_append_filter_updates(), and kest_fpga_batch_append_resource().
kest_fpga_batch_append_32()
int kest_fpga_batch_append_32 (kest_fpga_transfer_batch * seq, uint32_t x)
Definition at line 275 of file kest_fpga_io.c.
Referenced by kest_fpga_batch_append_block_instr().
kest_fpga_batch_concat()
int kest_fpga_batch_concat (kest_fpga_transfer_batch * seq, kest_fpga_transfer_batch * seq2)
Definition at line 294 of file kest_fpga_io.c.
kest_fpga_command_to_string()
char * kest_fpga_command_to_string (int command)
Definition at line 105 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task(), kest_fpga_print_command_log(), kest_fpga_program_batch_send_careful(), and kest_fpga_transfer_batch_send_careful().
kest_fpga_commit_reg_updates()
void kest_fpga_commit_reg_updates ()
Definition at line 485 of file kest_fpga_io.c.
kest_fpga_decode_status_flags()
int kest_fpga_decode_status_flags (kest_fpga_status_flags * flags, uint8_t byte)
Definition at line 490 of file kest_fpga_io.c.
Referenced by get_and_sprint_flags_compact(), kest_fpga_get_status_flags(), and kest_fpga_send_byte_get_flags().
kest_fpga_get_block_instr()
uint32_t kest_fpga_get_block_instr (int block, kest_fpga_status_flags * flags)
Definition at line 656 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_block_reg()
uint16_t kest_fpga_get_block_reg (int block, int reg, kest_fpga_status_flags * flags)
Definition at line 676 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_delay_buffer_addr()
int kest_fpga_get_delay_buffer_addr (int handle, kest_fpga_status_flags * flags)
Definition at line 705 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_delay_buffer_delay()
int kest_fpga_get_delay_buffer_delay (int handle, kest_fpga_status_flags * flags)
Definition at line 698 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_delay_buffer_gain()
uint16_t kest_fpga_get_delay_buffer_gain (int handle, kest_fpga_status_flags * flags)
Definition at line 719 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_delay_buffer_last_rw_addr()
int kest_fpga_get_delay_buffer_last_rw_addr (int handle, uint16_t * read_addr, uint16_t * write_addr, kest_fpga_status_flags * flags)
Definition at line 726 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_delay_buffer_pos()
int kest_fpga_get_delay_buffer_pos (int handle, kest_fpga_status_flags * flags)
Definition at line 712 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_delay_buffer_size()
int kest_fpga_get_delay_buffer_size (int handle, kest_fpga_status_flags * flags)
Definition at line 691 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_n_blocks()
int kest_fpga_get_n_blocks (kest_fpga_status_flags * flags)
Definition at line 666 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_n_delay_buffers()
int kest_fpga_get_n_delay_buffers (kest_fpga_status_flags * flags)
Definition at line 686 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_sample_count()
uint64_t kest_fpga_get_sample_count (kest_fpga_status_flags * flags)
Definition at line 739 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_sdram_read_count()
uint64_t kest_fpga_get_sdram_read_count (kest_fpga_status_flags * flags)
Definition at line 744 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_sdram_write_count()
uint64_t kest_fpga_get_sdram_write_count (kest_fpga_status_flags * flags)
Definition at line 749 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_print_full_scan().
kest_fpga_get_status_flags()
int kest_fpga_get_status_flags (kest_fpga_status_flags * flags)
Definition at line 507 of file kest_fpga_io.c.
Referenced by get_and_sprint_flags(), kest_fpga_comms_task(), kest_fpga_req_data(), and kest_fpga_req_data_p().
kest_fpga_get_stuck_flags()
uint32_t kest_fpga_get_stuck_flags (kest_fpga_status_flags * flags)
Definition at line 671 of file kest_fpga_io.c.
kest_fpga_program_batch_send()
int kest_fpga_program_batch_send (kest_fpga_transfer_batch batch)
Definition at line 369 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task().
kest_fpga_program_batch_send_careful()
int kest_fpga_program_batch_send_careful (kest_fpga_transfer_batch batch)
Definition at line 382 of file kest_fpga_io.c.
kest_fpga_read_byte()
uint8_t kest_fpga_read_byte ()
Definition at line 169 of file kest_fpga_io.c.
Referenced by get_and_sprint_flags_compact(), and kest_fpga_get_status_flags().
kest_fpga_readout()
uint8_t kest_fpga_readout ()
Definition at line 177 of file kest_fpga_io.c.
Referenced by kest_fpga_req_data(), and kest_fpga_req_data_p().
kest_fpga_readout_byte()
uint8_t kest_fpga_readout_byte ()
Definition at line 185 of file kest_fpga_io.c.
kest_fpga_readout_bytes()
int kest_fpga_readout_bytes (uint8_t * buf, int n)
Definition at line 193 of file kest_fpga_io.c.
kest_fpga_req_data()
int64_t kest_fpga_req_data (int req, int n_bytes, kest_fpga_status_flags * flags)
Definition at line 560 of file kest_fpga_io.c.
Referenced by kest_fpga_get_n_blocks(), kest_fpga_get_n_delay_buffers(), kest_fpga_get_sample_count(), kest_fpga_get_sdram_read_count(), kest_fpga_get_sdram_write_count(), and kest_fpga_get_stuck_flags().
kest_fpga_req_data_p()
int64_t kest_fpga_req_data_p (uint8_t req, uint8_t * p, int n, int m, kest_fpga_status_flags * flags)
Definition at line 603 of file kest_fpga_io.c.
Referenced by kest_fpga_get_block_instr(), kest_fpga_get_block_reg(), kest_fpga_get_delay_buffer_addr(), kest_fpga_get_delay_buffer_delay(), kest_fpga_get_delay_buffer_gain(), kest_fpga_get_delay_buffer_last_rw_addr(), kest_fpga_get_delay_buffer_pos(), and kest_fpga_get_delay_buffer_size().
kest_fpga_send_byte()
int kest_fpga_send_byte (uint8_t byte)
Definition at line 148 of file kest_fpga_io.c.
Referenced by kest_command_log_test(), kest_fpga_commit_reg_updates(), kest_fpga_comms_print_full_scan(), kest_fpga_comms_task(), kest_fpga_handle_misalignment(), kest_fpga_program_batch_send(), kest_fpga_program_batch_send_careful(), and kest_fpga_readout_bytes().
kest_fpga_send_byte_get_flags()
int kest_fpga_send_byte_get_flags (uint8_t tx, kest_fpga_status_flags * flags)
Definition at line 153 of file kest_fpga_io.c.
Referenced by kest_fpga_req_data(), and kest_fpga_req_data_p().
kest_fpga_set_input_gain()
void kest_fpga_set_input_gain (float gain_db)
Definition at line 432 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task().
kest_fpga_set_output_gain()
void kest_fpga_set_output_gain (float gain_db)
Definition at line 458 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task().
kest_fpga_spi_init()
int kest_fpga_spi_init ()
Definition at line 20 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task().
kest_fpga_status_flags_print()
int kest_fpga_status_flags_print (kest_fpga_status_flags * flags)
Definition at line 537 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task().
kest_fpga_status_flags_sprint()
int kest_fpga_status_flags_sprint (kest_string * str, kest_fpga_status_flags * flags)
Definition at line 519 of file kest_fpga_io.c.
Referenced by get_and_sprint_flags().
kest_fpga_transfer_batch_send()
int kest_fpga_transfer_batch_send (kest_fpga_transfer_batch batch)
Definition at line 422 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task(), kest_fpga_set_input_gain(), and kest_fpga_set_output_gain().
kest_fpga_transfer_batch_send_careful()
int kest_fpga_transfer_batch_send_careful (kest_fpga_transfer_batch batch)
Definition at line 334 of file kest_fpga_io.c.
Referenced by kest_fpga_transfer_batch_send().
kest_fpga_txrx()
int kest_fpga_txrx (uint8_t * tx, uint8_t * rx, size_t len)
Definition at line 53 of file kest_fpga_io.c.
Referenced by kest_fpga_program_batch_send(), kest_fpga_program_batch_send_careful(), kest_fpga_read_byte(), kest_fpga_readout(), kest_fpga_readout_byte(), kest_fpga_readout_bytes(), kest_fpga_send_byte(), kest_fpga_send_byte_get_flags(), kest_fpga_transfer_batch_send(), and kest_fpga_transfer_batch_send_careful().
kest_free_fpga_transfer_batch()
void kest_free_fpga_transfer_batch (kest_fpga_transfer_batch batch)
Definition at line 215 of file kest_fpga_io.c.
Referenced by kest_fpga_comms_task(), and kest_pipeline_create_fpga_transfer_batch().
kest_new_fpga_transfer_batch()
kest_fpga_transfer_batch kest_new_fpga_transfer_batch ()
Definition at line 203 of file kest_fpga_io.c.
Referenced by kest_effect_update_fpga(), and kest_pipeline_create_fpga_transfer_batch().
Variable Documentation
spi_handle
spi_device_handle_t spi_handle
Definition at line 17 of file kest_fpga_io.c.
Referenced by kest_fpga_spi_init(), and kest_fpga_txrx().