Kestrel Interface: kest_resource.c File Reference
kest_resource.c File Reference
#include <stdio.h>
#include <math.h>
#include <float.h>
#include <stdlib.h>
#include <string.h>
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (kest_dsp_resource)
IMPLEMENT_PTR_LIST (kest_dsp_resource)
IMPLEMENT_LIST (kest_dsp_resource)
IMPLEMENT_POOL (kest_dsp_resource)
int kest_init_dsp_resource (kest_dsp_resource *res)
int kest_dsp_resource_create_filter (kest_dsp_resource *res)
int string_to_resource_type (const char *type_str)
char * kest_dsp_resource_type_to_string (int type)
int kest_mem_slot_set_addr (kest_mem_slot *mem, int addr)
int kest_mem_slot_set_effective_addr (kest_mem_slot *mem, int addr)
int kest_resources_assign_handles (kest_dsp_resource_pll *list)
kest_eff_resource_report empty_m_eff_resource_report ()
int kest_filter_init (kest_filter *filter)
kest_filter * kest_filter_create (kest_allocator *alloc)
int kest_filter_clone (kest_filter *dest, kest_filter *src)
kest_filter * kest_filter_make_clone (kest_filter *src)
kest_mem_slot * kest_mem_slot_create (kest_allocator *alloc)
kest_delay * kest_delay_create (kest_allocator *alloc)
int kest_delay_init (kest_delay *delay)
int kest_lfo_init (kest_lfo *lfo)
kest_lfo * kest_lfo_create (kest_allocator *alloc)
void kest_lfo_activate_sync (void *lfo_)
void kest_lfo_deactivate_sync (void *lfo_)
int kest_lfo_activate_async (kest_lfo *lfo)
int kest_lfo_deactivate_async (kest_lfo *lfo)
int kest_lfo_evaluate_rec (kest_lfo *lfo, kest_scope *scope, float *dest, int depth)
int kest_lfo_evaluate (kest_lfo *lfo, kest_scope *scope, float *dest)
int kest_resource_report_integrate (kest_eff_resource_report *a, const kest_eff_resource_report *b)
int kest_dsp_resource_clone (kest_dsp_resource *dest, kest_dsp_resource *src)
kest_dsp_resource * kest_dsp_resource_make_clone (kest_dsp_resource *src)
kest_dsp_resource * kest_dsp_resource_make_clone_for_effect (kest_dsp_resource *src, kest_effect *effect)
Variables
kest_allocator kest_dsp_resource_allocator
kest_dsp_resource_pool kest_dsp_resource_mem_pool
kest_dsp_resource sin_lut
kest_dsp_resource tanh_lut
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 10 of file kest_resource.c.
Function Documentation
empty_m_eff_resource_report()
kest_eff_resource_report empty_m_eff_resource_report ()
Definition at line 187 of file kest_resource.c.
Referenced by kest_pipeline_create_fpga_transfer_batch().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (kest_dsp_resource)
IMPLEMENT_LIST()
IMPLEMENT_LIST (kest_dsp_resource)
IMPLEMENT_POOL()
IMPLEMENT_POOL (kest_dsp_resource)
IMPLEMENT_PTR_LIST()
IMPLEMENT_PTR_LIST (kest_dsp_resource)
kest_delay_create()
kest_delay * kest_delay_create (kest_allocator * alloc)
Definition at line 288 of file kest_resource.c.
Referenced by kest_dsp_resource_clone(), and kest_extract_delay().
kest_delay_init()
int kest_delay_init (kest_delay * delay)
Definition at line 300 of file kest_resource.c.
Referenced by kest_dsp_resource_clone().
kest_dsp_resource_clone()
int kest_dsp_resource_clone (kest_dsp_resource * dest, kest_dsp_resource * src)
Definition at line 521 of file kest_resource.c.
Referenced by kest_dsp_resource_make_clone().
kest_dsp_resource_create_filter()
int kest_dsp_resource_create_filter (kest_dsp_resource * res)
Definition at line 63 of file kest_resource.c.
kest_dsp_resource_make_clone()
kest_dsp_resource * kest_dsp_resource_make_clone (kest_dsp_resource * src)
Definition at line 588 of file kest_resource.c.
Referenced by kest_block_clone(), and kest_dsp_resource_make_clone_for_effect().
kest_dsp_resource_make_clone_for_effect()
kest_dsp_resource * kest_dsp_resource_make_clone_for_effect (kest_dsp_resource * src, kest_effect * effect)
Definition at line 609 of file kest_resource.c.
Referenced by init_effect_from_effect_desc().
kest_dsp_resource_type_to_string()
char * kest_dsp_resource_type_to_string (int type)
Definition at line 106 of file kest_resource.c.
Referenced by kest_fpga_write_generate_update().
kest_filter_clone()
int kest_filter_clone (kest_filter * dest, kest_filter * src)
Definition at line 227 of file kest_resource.c.
Referenced by kest_filter_make_clone().
kest_filter_create()
kest_filter * kest_filter_create (kest_allocator * alloc)
Definition at line 210 of file kest_resource.c.
Referenced by kest_dsp_resource_create_filter(), kest_extract_biquad_from_dict(), kest_extract_bpf(), kest_extract_bpf_from_dict(), kest_extract_filter(), kest_extract_filter_from_dict(), kest_extract_hpf(), kest_extract_hpf_from_dict(), kest_extract_lpf(), kest_extract_lpf_from_dict(), kest_extract_polynomial(), and kest_extract_polynomial_from_dict().
kest_filter_init()
int kest_filter_init (kest_filter * filter)
Definition at line 196 of file kest_resource.c.
kest_filter_make_clone()
kest_filter * kest_filter_make_clone (kest_filter * src)
Definition at line 251 of file kest_resource.c.
Referenced by kest_dsp_resource_clone().
kest_init_dsp_resource()
int kest_init_dsp_resource (kest_dsp_resource * res)
Definition at line 45 of file kest_resource.c.
Referenced by kest_extract_bpf(), kest_extract_delay(), kest_extract_filter(), kest_extract_hpf(), kest_extract_lfo(), kest_extract_lpf(), kest_extract_mem(), kest_extract_polynomial(), and kest_extract_resource_from_dict().
kest_lfo_activate_async()
int kest_lfo_activate_async (kest_lfo * lfo)
Definition at line 387 of file kest_resource.c.
Referenced by kest_effect_activate_lfos_async().
kest_lfo_activate_sync()
void kest_lfo_activate_sync (void * lfo_)
Definition at line 334 of file kest_resource.c.
Referenced by kest_effect_activate_lfos(), and kest_lfo_activate_async().
kest_lfo_create()
kest_lfo * kest_lfo_create (kest_allocator * alloc)
Definition at line 322 of file kest_resource.c.
Referenced by kest_dsp_resource_clone(), and kest_extract_lfo().
kest_lfo_deactivate_async()
int kest_lfo_deactivate_async (kest_lfo * lfo)
Definition at line 403 of file kest_resource.c.
Referenced by kest_effect_deactivate_lfos_async().
kest_lfo_deactivate_sync()
void kest_lfo_deactivate_sync (void * lfo_)
Definition at line 368 of file kest_resource.c.
Referenced by kest_lfo_deactivate_async().
kest_lfo_evaluate()
int kest_lfo_evaluate (kest_lfo * lfo, kest_scope * scope, float * dest)
Definition at line 497 of file kest_resource.c.
Referenced by kest_scope_entry_eval_rec().
kest_lfo_evaluate_rec()
int kest_lfo_evaluate_rec (kest_lfo * lfo, kest_scope * scope, float * dest, int depth)
Definition at line 417 of file kest_resource.c.
Referenced by kest_lfo_evaluate().
kest_lfo_init()
int kest_lfo_init (kest_lfo * lfo)
Definition at line 312 of file kest_resource.c.
Referenced by kest_dsp_resource_clone(), and kest_lfo_create().
kest_mem_slot_create()
kest_mem_slot * kest_mem_slot_create (kest_allocator * alloc)
Definition at line 274 of file kest_resource.c.
Referenced by kest_dsp_resource_clone(), kest_extract_mem(), and kest_extract_mem_from_dict().
kest_mem_slot_set_addr()
int kest_mem_slot_set_addr (kest_mem_slot * mem, int addr)
Definition at line 121 of file kest_resource.c.
kest_mem_slot_set_effective_addr()
int kest_mem_slot_set_effective_addr (kest_mem_slot * mem, int addr)
Definition at line 130 of file kest_resource.c.
Referenced by kest_block_instr_encode_positional(), and kest_block_instr_encode_resource_aware().
kest_resource_report_integrate()
int kest_resource_report_integrate (kest_eff_resource_report * a, const kest_eff_resource_report * b)
Definition at line 502 of file kest_resource.c.
Referenced by kest_fpga_batch_append_effect().
kest_resources_assign_handles()
int kest_resources_assign_handles (kest_dsp_resource_pll * list)
Definition at line 142 of file kest_resource.c.
Referenced by kest_parse_tokens().
string_to_resource_type()
int string_to_resource_type (const char * type_str)
Definition at line 83 of file kest_resource.c.
Referenced by kest_extract_resource_from_dict().
Variable Documentation
kest_dsp_resource_allocator
kest_allocator kest_dsp_resource_allocator
Definition at line 24 of file kest_resource.c.
Referenced by DECLARE_POOL().
kest_dsp_resource_mem_pool
kest_dsp_resource_pool kest_dsp_resource_mem_pool
Definition at line 25 of file kest_resource.c.
Referenced by DECLARE_POOL().
sin_lut
kest_dsp_resource sin_lut
Initial value:
= {
    .type   = KEST_DSP_RESOURCE_LUT,
    .name   = NULL,
    .handle = 0,
    .size   = NULL,
    .delay  = NULL,
    .data   = NULL
}
Definition at line 27 of file kest_resource.c.
Referenced by kest_process_asm_line().
tanh_lut
kest_dsp_resource tanh_lut
Initial value:
= {
    .type   = KEST_DSP_RESOURCE_LUT,
    .name   = NULL,
    .handle = 1,
    .size   = NULL,
    .delay  = NULL,
    .data   = NULL
}
Definition at line 36 of file kest_resource.c.
Referenced by kest_process_asm_line().