Kestrel Interface: kest_fpga_instr.c File Reference
kest_fpga_instr.c File Reference
#include "kest_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
const kest_asm_instr_desc * kest_instr_name_to_desc (char *name)
const kest_asm_instr_desc * kest_instr_opcode_to_desc (int opcode)
void kest_instr_print_format_fr (kest_string *str, int opcode, int src_a, int src_a_reg, int src_b, int src_b_reg, int src_c, int src_c_reg, int dest, int shift, int res_addr)
void kest_instr_print_format_a (kest_string *str, uint32_t instr)
void kest_instr_print_format_b (kest_string *str, uint32_t instr)
void kest_instr_print (kest_string *str, uint32_t instr)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file kest_fpga_instr.c.
Function Documentation
kest_instr_name_to_desc()
const kest_asm_instr_desc * kest_instr_name_to_desc (char * name)
Definition at line 421 of file kest_fpga_instr.c.
Referenced by kest_process_asm_line().
kest_instr_opcode_to_desc()
const kest_asm_instr_desc * kest_instr_opcode_to_desc (int opcode)
Definition at line 463 of file kest_fpga_instr.c.
Referenced by kest_instr_print_format_fr().
kest_instr_print()
void kest_instr_print (kest_string * str, uint32_t instr)
Definition at line 626 of file kest_fpga_instr.c.
Referenced by kest_fpga_batch_print(), and kest_fpga_comms_print_full_scan().
kest_instr_print_format_a()
void kest_instr_print_format_a (kest_string * str, uint32_t instr)
Definition at line 565 of file kest_fpga_instr.c.
Referenced by kest_instr_print().
kest_instr_print_format_b()
void kest_instr_print_format_b (kest_string * str, uint32_t instr)
Definition at line 598 of file kest_fpga_instr.c.
Referenced by kest_instr_print().
kest_instr_print_format_fr()
void kest_instr_print_format_fr (kest_string * str, int opcode, int src_a, int src_a_reg, int src_b, int src_b_reg, int src_c, int src_c_reg, int dest, int shift, int res_addr)
Definition at line 500 of file kest_fpga_instr.c.
Referenced by kest_instr_print_format_a(), and kest_instr_print_format_b().