Kestrel Interface: kest_driver.h File Reference
kest_driver.h File Reference
Data Structures
struct kest_driver_scope_entry
struct kest_driver
Macros
#define KEST_DRIVER_NOTHING 0
#define KEST_DRIVER_SCOPE_ENTRY 1
Functions
DECLARE_LIST (kest_driver)
int kest_driver_init (kest_driver *driver)
int kest_driver_init_scope_entry (kest_driver *driver, const char *key)
int kest_driver_evaluate (kest_driver *driver, struct kest_scope *scope, float *dest)
int kest_driver_clone (kest_driver *dest, kest_driver *src)
kest_driver * kest_driver_make_clone (kest_driver *src)
int kest_driver_clone_for (kest_driver *dest, kest_driver *src, struct kest_effect *effect)
Macro Definition Documentation
KEST_DRIVER_NOTHING
#define KEST_DRIVER_NOTHING 0
Definition at line 4 of file kest_driver.h.
KEST_DRIVER_SCOPE_ENTRY
#define KEST_DRIVER_SCOPE_ENTRY 1
Definition at line 5 of file kest_driver.h.
Referenced by kest_driver_clone(), kest_driver_clone_for(), kest_driver_evaluate(), and kest_driver_init_scope_entry().
Function Documentation
DECLARE_LIST()
DECLARE_LIST (kest_driver)
kest_driver_clone()
int kest_driver_clone (kest_driver * dest, kest_driver * src)
Definition at line 79 of file kest_driver.c.
Referenced by kest_driver_clone_for(), and kest_driver_make_clone().
kest_driver_clone_for()
int kest_driver_clone_for (kest_driver * dest, kest_driver * src, struct kest_effect * effect)
Definition at line 122 of file kest_driver.c.
Referenced by init_effect_from_effect_desc().
kest_driver_evaluate()
int kest_driver_evaluate (kest_driver * driver, struct kest_scope * scope, float * dest)
Definition at line 42 of file kest_driver.c.
Referenced by kest_parameter_evaluate_rec(), and kest_parameter_if_driven_refresh().
kest_driver_init()
int kest_driver_init (kest_driver * driver)
Definition at line 9 of file kest_driver.c.
kest_driver_init_scope_entry()
int kest_driver_init_scope_entry (kest_driver * driver, const char * key)
Definition at line 19 of file kest_driver.c.
Referenced by kest_extract_parameter().
kest_driver_make_clone()
kest_driver * kest_driver_make_clone (kest_driver * src)
Definition at line 109 of file kest_driver.c.