Kestrel Interface: kest_fpga_instr.h File Reference
kest_fpga_instr.h File Reference
Data Structures
struct kest_instr_arg_fmt
struct kest_asm_instr_desc
Macros
#define KEST_ARG_POS_NONE -1
#define SHIFT_POLICY_0 0
#define SHIFT_POLICY_1 1
#define SHIFT_POLICY_SFAB 2
#define SHIFT_POLICY_MFAB 3
#define SHIFT_POLICY_FA 4
#define SHIFT_POLICY_FB 5
#define SHIFT_POLICY_FC 6
#define SHIFT_POLICY_SET 7
Functions
const kest_asm_instr_desc * kest_instr_name_to_desc (char *name)
const kest_asm_instr_desc * kest_instr_opcode_to_desc (int opcode)
void kest_instr_print (kest_string *str, uint32_t instr)
Macro Definition Documentation
KEST_ARG_POS_NONE
#define KEST_ARG_POS_NONE -1
Definition at line 4 of file kest_fpga_instr.h.
SHIFT_POLICY_0
#define SHIFT_POLICY_0 0
Definition at line 6 of file kest_fpga_instr.h.
Referenced by kest_init_block().
SHIFT_POLICY_1
#define SHIFT_POLICY_1 1
Definition at line 7 of file kest_fpga_instr.h.
Referenced by shift_policy_determine_shift().
SHIFT_POLICY_FA
#define SHIFT_POLICY_FA 4
Definition at line 10 of file kest_fpga_instr.h.
Referenced by shift_policy_determine_shift().
SHIFT_POLICY_FB
#define SHIFT_POLICY_FB 5
Definition at line 11 of file kest_fpga_instr.h.
Referenced by shift_policy_determine_shift().
SHIFT_POLICY_FC
#define SHIFT_POLICY_FC 6
Definition at line 12 of file kest_fpga_instr.h.
Referenced by shift_policy_determine_shift().
SHIFT_POLICY_MFAB
#define SHIFT_POLICY_MFAB 3
Definition at line 9 of file kest_fpga_instr.h.
Referenced by shift_policy_determine_shift().
SHIFT_POLICY_SET
#define SHIFT_POLICY_SET 7
Definition at line 13 of file kest_fpga_instr.h.
Referenced by shift_policy_determine_shift().
SHIFT_POLICY_SFAB
#define SHIFT_POLICY_SFAB 2
Definition at line 8 of file kest_fpga_instr.h.
Referenced by shift_policy_determine_shift().
Function Documentation
kest_instr_name_to_desc()
const kest_asm_instr_desc * kest_instr_name_to_desc (char * name)
Definition at line 421 of file kest_fpga_instr.c.
Referenced by kest_process_asm_line().
kest_instr_opcode_to_desc()
const kest_asm_instr_desc * kest_instr_opcode_to_desc (int opcode)
Definition at line 463 of file kest_fpga_instr.c.
Referenced by kest_instr_print_format_fr().
kest_instr_print()
void kest_instr_print (kest_string * str, uint32_t instr)
Definition at line 626 of file kest_fpga_instr.c.
Referenced by kest_fpga_batch_print(), and kest_fpga_comms_print_full_scan().