Kestrel Interface: kest_resource.h File Reference
kest_resource.h File Reference
Data Structures
struct kest_dsp_resource
struct kest_filter
struct kest_mem_slot
struct kest_delay
struct kest_lfo
struct kest_eff_resource_report
Macros
#define KEST_DSP_RESOURCE_NOTHING 0
#define KEST_DSP_RESOURCE_LUT 1
#define KEST_DSP_RESOURCE_MEM 2
#define KEST_DSP_RESOURCE_DELAY 3
#define KEST_DSP_RESOURCE_FILTER 4
#define KEST_DSP_RESOURCE_LFO 5
#define KEST_DELAY_UNITS_MS 0
#define KEST_DELAY_UNITS_SECONDS 1
#define KEST_DELAY_UNITS_SAMPLES 2
#define KEST_LFO_MODE_CENTER_AMP 0
#define KEST_LFO_MODE_MIN_MAX 1
#define KEST_LFO_SCALE_LINEAR 0
#define KEST_LFO_SCALE_LOG 1
Functions
int kest_init_dsp_resource (kest_dsp_resource *res)
int kest_dsp_resource_clone (kest_dsp_resource *dest, kest_dsp_resource *src)
kest_dsp_resource * kest_dsp_resource_make_clone (kest_dsp_resource *src)
kest_dsp_resource * kest_dsp_resource_make_clone_for_effect (kest_dsp_resource *src, struct kest_effect *effect)
int string_to_resource_type (const char *type_str)
char * kest_dsp_resource_type_to_string (int type)
DECLARE_LINKED_PTR_LIST (kest_dsp_resource)
DECLARE_PTR_LIST (kest_dsp_resource)
DECLARE_LIST (kest_dsp_resource)
int kest_filter_init (kest_filter *filter)
kest_filter * kest_filter_create (kest_allocator *alloc)
int kest_filter_clone (kest_filter *dest, kest_filter *src)
kest_filter * kest_filter_make_clone (kest_filter *src)
int kest_resources_assign_handles (kest_dsp_resource_pll *list)
kest_mem_slot * kest_mem_slot_create (kest_allocator *alloc)
int kest_mem_slot_set_addr (kest_mem_slot *mem, int addr)
int kest_mem_slot_set_effective_addr (kest_mem_slot *mem, int addr)
kest_delay * kest_delay_create (kest_allocator *alloc)
int kest_lfo_init (kest_lfo *lfo)
kest_lfo * kest_lfo_create (kest_allocator *alloc)
void kest_lfo_activate_sync (void *lfo_)
void kest_lfo_deactivate_sync (void *lfo_)
int kest_lfo_activate_async (kest_lfo *lfo)
int kest_lfo_deactivate_async (kest_lfo *lfo)
int kest_lfo_evaluate (kest_lfo *lfo, kest_scope *scope, float *dest)
int kest_lfo_evaluate_rec (kest_lfo *lfo, kest_scope *scope, float *dest, int depth)
kest_eff_resource_report empty_m_eff_resource_report ()
int kest_resource_report_integrate (kest_eff_resource_report *a, const kest_eff_resource_report *b)
DECLARE_POOL (kest_dsp_resource)
Variables
kest_dsp_resource sin_lut
kest_dsp_resource tanh_lut
kest_allocator kest_dsp_resource_allocator
kest_dsp_resource_pool kest_dsp_resource_mem_pool
Macro Definition Documentation
KEST_DELAY_UNITS_MS
#define KEST_DELAY_UNITS_MS 0
Definition at line 73 of file kest_resource.h.
Referenced by kest_alloc_for_delay(), kest_delay_init(), kest_extract_delay(), and kest_fpga_batch_append_resource().
KEST_DELAY_UNITS_SAMPLES
#define KEST_DELAY_UNITS_SAMPLES 2
Definition at line 75 of file kest_resource.h.
Referenced by kest_alloc_for_delay(), kest_extract_delay(), and kest_fpga_batch_append_resource().
KEST_DELAY_UNITS_SECONDS
#define KEST_DELAY_UNITS_SECONDS 1
Definition at line 74 of file kest_resource.h.
Referenced by kest_alloc_for_delay(), kest_extract_delay(), and kest_fpga_batch_append_resource().
KEST_DSP_RESOURCE_DELAY
#define KEST_DSP_RESOURCE_DELAY 3
Definition at line 7 of file kest_resource.h.
Referenced by kest_block_instr_encode_positional(), kest_block_instr_encode_resource_aware(), kest_dsp_resource_clone(), kest_dsp_resource_type_to_string(), kest_effect_desc_generate_res_rpt(), kest_effect_ptr_list_update_positions(), kest_extract_delay(), kest_extract_resource_from_dict(), kest_fpga_batch_append_resource(), kest_pipeline_update_positions(), kest_resources_assign_handles(), kest_updater_handle_preset_update_add_effect(), and string_to_resource_type().
KEST_DSP_RESOURCE_FILTER
#define KEST_DSP_RESOURCE_FILTER 4
Definition at line 8 of file kest_resource.h.
Referenced by init_effect_from_effect_desc(), kest_block_instr_encode_positional(), kest_block_instr_encode_resource_aware(), kest_dsp_resource_clone(), kest_dsp_resource_create_filter(), kest_dsp_resource_type_to_string(), kest_effect_desc_generate_res_rpt(), kest_effect_ptr_list_update_positions(), kest_extract_bpf(), kest_extract_filter(), kest_extract_hpf(), kest_extract_lpf(), kest_extract_resource_from_dict(), kest_fpga_batch_append_resource(), kest_fpga_batch_append_resource_updates(), kest_fpga_write_generate_update(), kest_parser_compute_formats(), kest_pipeline_update_positions(), kest_resources_assign_handles(), kest_updater_handle_preset_update_add_effect(), and string_to_resource_type().
KEST_DSP_RESOURCE_LFO
#define KEST_DSP_RESOURCE_LFO 5
Definition at line 9 of file kest_resource.h.
Referenced by gut_effect(), kest_active_preset_updater_task(), kest_dsp_resource_clone(), kest_dsp_resource_make_clone_for_effect(), kest_dsp_resource_type_to_string(), kest_effect_activate_lfos(), kest_effect_activate_lfos_async(), kest_effect_create_scope(), kest_effect_deactivate_lfos_async(), kest_effect_disable(), and kest_extract_lfo().
KEST_DSP_RESOURCE_LUT
#define KEST_DSP_RESOURCE_LUT 1
Definition at line 5 of file kest_resource.h.
Referenced by kest_block_instr_encode_positional(), kest_block_instr_encode_resource_aware(), and kest_dsp_resource_type_to_string().
KEST_DSP_RESOURCE_MEM
#define KEST_DSP_RESOURCE_MEM 2
Definition at line 6 of file kest_resource.h.
Referenced by gut_effect(), kest_active_preset_updater_task(), kest_block_instr_encode_positional(), kest_block_instr_encode_resource_aware(), kest_dsp_resource_clone(), kest_dsp_resource_make_clone_for_effect(), kest_dsp_resource_type_to_string(), kest_effect_activate_dma(), kest_effect_activate_dma_async(), kest_effect_create_scope(), kest_effect_deactivate_dma(), kest_effect_deactivate_dma_async(), kest_effect_desc_generate_res_rpt(), kest_effect_disable(), kest_effect_ptr_list_update_positions(), kest_extract_mem(), kest_extract_resource_from_dict(), kest_pipeline_update_positions(), kest_process_asm_line(), kest_resources_assign_handles(), and string_to_resource_type().
KEST_DSP_RESOURCE_NOTHING
#define KEST_DSP_RESOURCE_NOTHING 0
Definition at line 4 of file kest_resource.h.
Referenced by kest_dsp_resource_type_to_string(), kest_extract_resource_from_dict(), kest_init_dsp_resource(), and string_to_resource_type().
KEST_LFO_MODE_CENTER_AMP
#define KEST_LFO_MODE_CENTER_AMP 0
Definition at line 86 of file kest_resource.h.
Referenced by kest_extract_lfo(), and kest_lfo_evaluate_rec().
KEST_LFO_MODE_MIN_MAX
#define KEST_LFO_MODE_MIN_MAX 1
Definition at line 87 of file kest_resource.h.
Referenced by kest_extract_lfo(), and kest_lfo_evaluate_rec().
KEST_LFO_SCALE_LINEAR
#define KEST_LFO_SCALE_LINEAR 0
Definition at line 89 of file kest_resource.h.
Referenced by kest_extract_lfo().
KEST_LFO_SCALE_LOG
#define KEST_LFO_SCALE_LOG 1
Definition at line 90 of file kest_resource.h.
Referenced by kest_extract_lfo(), and kest_lfo_evaluate_rec().
Function Documentation
DECLARE_LINKED_PTR_LIST()
DECLARE_LINKED_PTR_LIST (kest_dsp_resource)
DECLARE_LIST()
DECLARE_LIST (kest_dsp_resource)
DECLARE_POOL()
DECLARE_POOL (kest_dsp_resource)
DECLARE_PTR_LIST()
DECLARE_PTR_LIST (kest_dsp_resource)
empty_m_eff_resource_report()
kest_eff_resource_report empty_m_eff_resource_report ()
Definition at line 187 of file kest_resource.c.
Referenced by kest_pipeline_create_fpga_transfer_batch().
kest_delay_create()
kest_delay * kest_delay_create (kest_allocator * alloc)
Definition at line 288 of file kest_resource.c.
Referenced by kest_dsp_resource_clone(), and kest_extract_delay().
kest_dsp_resource_clone()
int kest_dsp_resource_clone (kest_dsp_resource * dest, kest_dsp_resource * src)
Definition at line 521 of file kest_resource.c.
Referenced by kest_dsp_resource_make_clone().
kest_dsp_resource_make_clone()
kest_dsp_resource * kest_dsp_resource_make_clone (kest_dsp_resource * src)
Definition at line 588 of file kest_resource.c.
Referenced by kest_block_clone(), and kest_dsp_resource_make_clone_for_effect().
kest_dsp_resource_make_clone_for_effect()
kest_dsp_resource * kest_dsp_resource_make_clone_for_effect (kest_dsp_resource * src, struct kest_effect * effect)
Definition at line 609 of file kest_resource.c.
Referenced by init_effect_from_effect_desc().
kest_dsp_resource_type_to_string()
char * kest_dsp_resource_type_to_string (int type)
Definition at line 106 of file kest_resource.c.
Referenced by kest_fpga_write_generate_update().
kest_filter_clone()
int kest_filter_clone (kest_filter * dest, kest_filter * src)
Definition at line 227 of file kest_resource.c.
Referenced by kest_filter_make_clone().
kest_filter_create()
kest_filter * kest_filter_create (kest_allocator * alloc)
Definition at line 210 of file kest_resource.c.
Referenced by kest_dsp_resource_create_filter(), kest_extract_biquad_from_dict(), kest_extract_bpf(), kest_extract_bpf_from_dict(), kest_extract_filter(), kest_extract_filter_from_dict(), kest_extract_hpf(), kest_extract_hpf_from_dict(), kest_extract_lpf(), kest_extract_lpf_from_dict(), kest_extract_polynomial(), and kest_extract_polynomial_from_dict().
kest_filter_init()
int kest_filter_init (kest_filter * filter)
Definition at line 196 of file kest_resource.c.
kest_filter_make_clone()
kest_filter * kest_filter_make_clone (kest_filter * src)
Definition at line 251 of file kest_resource.c.
Referenced by kest_dsp_resource_clone().
kest_init_dsp_resource()
int kest_init_dsp_resource (kest_dsp_resource * res)
Definition at line 45 of file kest_resource.c.
Referenced by kest_extract_bpf(), kest_extract_delay(), kest_extract_filter(), kest_extract_hpf(), kest_extract_lfo(), kest_extract_lpf(), kest_extract_mem(), kest_extract_polynomial(), and kest_extract_resource_from_dict().
kest_lfo_activate_async()
int kest_lfo_activate_async (kest_lfo * lfo)
Definition at line 387 of file kest_resource.c.
Referenced by kest_effect_activate_lfos_async().
kest_lfo_activate_sync()
void kest_lfo_activate_sync (void * lfo_)
Definition at line 334 of file kest_resource.c.
Referenced by kest_effect_activate_lfos(), and kest_lfo_activate_async().
kest_lfo_create()
kest_lfo * kest_lfo_create (kest_allocator * alloc)
Definition at line 322 of file kest_resource.c.
Referenced by kest_dsp_resource_clone(), and kest_extract_lfo().
kest_lfo_deactivate_async()
int kest_lfo_deactivate_async (kest_lfo * lfo)
Definition at line 403 of file kest_resource.c.
Referenced by kest_effect_deactivate_lfos_async().
kest_lfo_deactivate_sync()
void kest_lfo_deactivate_sync (void * lfo_)
Definition at line 368 of file kest_resource.c.
Referenced by kest_lfo_deactivate_async().
kest_lfo_evaluate()
int kest_lfo_evaluate (kest_lfo * lfo, kest_scope * scope, float * dest)
Definition at line 497 of file kest_resource.c.
Referenced by kest_scope_entry_eval_rec().
kest_lfo_evaluate_rec()
int kest_lfo_evaluate_rec (kest_lfo * lfo, kest_scope * scope, float * dest, int depth)
Definition at line 417 of file kest_resource.c.
Referenced by kest_lfo_evaluate().
kest_lfo_init()
int kest_lfo_init (kest_lfo * lfo)
Definition at line 312 of file kest_resource.c.
Referenced by kest_dsp_resource_clone(), and kest_lfo_create().
kest_mem_slot_create()
kest_mem_slot * kest_mem_slot_create (kest_allocator * alloc)
Definition at line 274 of file kest_resource.c.
Referenced by kest_dsp_resource_clone(), kest_extract_mem(), and kest_extract_mem_from_dict().
kest_mem_slot_set_addr()
int kest_mem_slot_set_addr (kest_mem_slot * mem, int addr)
Definition at line 121 of file kest_resource.c.
kest_mem_slot_set_effective_addr()
int kest_mem_slot_set_effective_addr (kest_mem_slot * mem, int addr)
Definition at line 130 of file kest_resource.c.
Referenced by kest_block_instr_encode_positional(), and kest_block_instr_encode_resource_aware().
kest_resource_report_integrate()
int kest_resource_report_integrate (kest_eff_resource_report * a, const kest_eff_resource_report * b)
Definition at line 502 of file kest_resource.c.
Referenced by kest_fpga_batch_append_effect().
kest_resources_assign_handles()
int kest_resources_assign_handles (kest_dsp_resource_pll * list)
Definition at line 142 of file kest_resource.c.
Referenced by kest_parse_tokens().
string_to_resource_type()
int string_to_resource_type (const char * type_str)
Definition at line 83 of file kest_resource.c.
Referenced by kest_extract_resource_from_dict().
Variable Documentation
kest_dsp_resource_allocator
kest_allocator kest_dsp_resource_allocator extern
Definition at line 24 of file kest_resource.c.
Referenced by DECLARE_POOL().
kest_dsp_resource_mem_pool
kest_dsp_resource_pool kest_dsp_resource_mem_pool extern
Definition at line 25 of file kest_resource.c.
Referenced by DECLARE_POOL().
sin_lut
kest_dsp_resource sin_lut extern
Definition at line 27 of file kest_resource.c.
Referenced by kest_process_asm_line().
tanh_lut
kest_dsp_resource tanh_lut extern
Definition at line 36 of file kest_resource.c.
Referenced by kest_process_asm_line().