M: m_asm_parser.c File Reference
m_asm_parser.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
#define CH_DELIMITER 'c'
#define M_EXPR_DELIMITER "["
#define RS_DELIMITER "$"
#define DQ_CODELIMITER "]"
Functions
IMPLEMENT_LINKED_PTR_LIST (m_asm_line)
const m_arg_format * m_instr_arg_format (const char *instr)
int m_instr_opcode (const char *instr)
int m_parse_asm_arg (m_eff_parsing_state *ps, m_asm_operand *arg)
int m_parse_asm_arg_2 (m_eff_parsing_state *ps, m_asm_arg *arg)
int is_valid_instr (const char *instr)
int m_parse_asm_line (m_eff_parsing_state *ps)
int m_parse_asm (m_eff_parsing_state *ps)
m_dsp_resource * m_resource_get_by_name (m_dsp_resource_pll *resources, const char *name)
int m_process_asm_line (m_eff_parsing_state *ps, m_asm_line *line)
int m_process_asm_lines (m_eff_parsing_state *ps)
Macro Definition Documentation
CH_DELIMITER
#define CH_DELIMITER 'c'
Definition at line 13 of file m_asm_parser.c.
Referenced by m_parse_asm_arg(), and m_parse_asm_arg_2().
DQ_CODELIMITER
#define DQ_CODELIMITER "]"
Definition at line 16 of file m_asm_parser.c.
Referenced by m_parse_asm_arg(), and m_parse_asm_arg_2().
M_EXPR_DELIMITER
#define M_EXPR_DELIMITER "["
Definition at line 14 of file m_asm_parser.c.
Referenced by m_parse_asm_arg(), and m_parse_asm_arg_2().
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 8 of file m_asm_parser.c.
RS_DELIMITER
#define RS_DELIMITER "$"
Definition at line 15 of file m_asm_parser.c.
Referenced by m_parse_asm_arg(), and m_parse_asm_arg_2().
Function Documentation
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (m_asm_line)
is_valid_instr()
int is_valid_instr (const char * instr)
Definition at line 546 of file m_asm_parser.c.
Referenced by m_parse_asm_line().
m_instr_arg_format()
const m_arg_format * m_instr_arg_format (const char * instr)
Definition at line 174 of file m_asm_parser.c.
Referenced by m_process_asm_line().
m_instr_opcode()
int m_instr_opcode (const char * instr)
Definition at line 208 of file m_asm_parser.c.
Referenced by m_process_asm_line().
m_parse_asm()
int m_parse_asm (m_eff_parsing_state * ps)
Definition at line 1248 of file m_asm_parser.c.
Referenced by m_parse_code_section().
m_parse_asm_arg()
int m_parse_asm_arg (m_eff_parsing_state * ps, m_asm_operand * arg)
Definition at line 242 of file m_asm_parser.c.
Referenced by m_parse_asm_line().
m_parse_asm_arg_2()
int m_parse_asm_arg_2 (m_eff_parsing_state * ps, m_asm_arg * arg)
Definition at line 402 of file m_asm_parser.c.
Referenced by m_parse_asm_line().
m_parse_asm_line()
int m_parse_asm_line (m_eff_parsing_state * ps)
Definition at line 557 of file m_asm_parser.c.
Referenced by m_parse_asm().
m_process_asm_line()
int m_process_asm_line (m_eff_parsing_state * ps, m_asm_line * line)
Definition at line 1297 of file m_asm_parser.c.
Referenced by m_process_asm_lines().
m_process_asm_lines()
int m_process_asm_lines (m_eff_parsing_state * ps)
Definition at line 1491 of file m_asm_parser.c.
Referenced by m_read_eff_desc_from_file().
m_resource_get_by_name()
m_dsp_resource * m_resource_get_by_name (m_dsp_resource_pll * resources, const char * name)
Definition at line 1279 of file m_asm_parser.c.
Referenced by m_process_asm_line().