M: m_alloc.c File Reference
m_alloc.c File Reference
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
void * m_alloc (size_t size)
void m_free (void *ptr)
void * m_realloc (void *ptr, size_t size)
char * m_strndup (const char *str, size_t n)
void m_mem_monitor_task (void *param)
void m_mem_init ()
void lv_mem_init (void)
void lv_mem_deinit (void)
void * lv_malloc_core (size_t size)
void * lv_realloc_core (void *p, size_t new_size)
void lv_free_core (void *p)
void * m_lv_malloc (size_t size)
void m_lv_free (void *ptr)
void print_memory_report ()
void * m_allocator_alloc (m_allocator *a, size_t n)
void * m_allocator_realloc (m_allocator *a, void *p, size_t n)
void m_allocator_free (m_allocator *a, void *p)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file m_alloc.c.
Function Documentation
lv_free_core()
void lv_free_core (void * p)
Definition at line 209 of file m_alloc.c.
lv_malloc_core()
void * lv_malloc_core (size_t size)
Definition at line 200 of file m_alloc.c.
lv_mem_deinit()
void lv_mem_deinit (void)
Definition at line 195 of file m_alloc.c.
lv_mem_init()
void lv_mem_init (void)
Definition at line 190 of file m_alloc.c.
lv_realloc_core()
void * lv_realloc_core (void * p, size_t new_size)
Definition at line 204 of file m_alloc.c.
m_alloc()
void * m_alloc (size_t size)
Definition at line 11 of file m_alloc.c.
m_allocator_alloc()
void * m_allocator_alloc (m_allocator * a, size_t n)
Definition at line 230 of file m_alloc.c.
m_allocator_free()
void m_allocator_free (m_allocator * a, void * p)
Definition at line 246 of file m_alloc.c.
m_allocator_realloc()
void * m_allocator_realloc (m_allocator * a, void * p, size_t n)
Definition at line 238 of file m_alloc.c.
m_free()
void m_free (void * ptr)
Definition at line 50 of file m_alloc.c.
m_lv_free()
void m_lv_free (void * ptr)
Definition at line 219 of file m_alloc.c.
m_lv_malloc()
void * m_lv_malloc (size_t size)
Definition at line 214 of file m_alloc.c.
m_mem_init()
void m_mem_init ()
Definition at line 171 of file m_alloc.c.
Referenced by app_main().
m_mem_monitor_task()
void m_mem_monitor_task (void * param)
Definition at line 159 of file m_alloc.c.
Referenced by m_mem_init().
m_realloc()
void * m_realloc (void * ptr, size_t size)
Definition at line 77 of file m_alloc.c.
m_strndup()
char * m_strndup (const char * str, size_t n)
Definition at line 122 of file m_alloc.c.
print_memory_report()
void print_memory_report ()
Definition at line 225 of file m_alloc.c.
Referenced by app_main(), and m_mem_monitor_task().