M: m_bump_arena.h File Reference
m_bump_arena.h File Reference
Data Structures
struct m_bump_arena
Macros
#define M_BUMP_ARENA_ALLOC_ALIGN 4
#define M_BUMP_ARENA_INIT_ALIGN 64
Functions
int m_bump_arena_init_empty (m_bump_arena *arena)
int m_bump_arena_init (m_bump_arena *arena, size_t capacity)
void * m_bump_arena_alloc (m_bump_arena *arena, size_t size)
void * m_bump_arena_realloc (m_bump_arena *arena, void *p, size_t size)
void m_bump_arena_free (m_bump_arena *arena)
int m_bump_arena_reset (m_bump_arena *arena)
int m_bump_arena_destroy (m_bump_arena *arena)
Macro Definition Documentation
M_BUMP_ARENA_ALLOC_ALIGN
#define M_BUMP_ARENA_ALLOC_ALIGN 4
Definition at line 4 of file m_bump_arena.h.
Referenced by m_bump_arena_alloc().
M_BUMP_ARENA_INIT_ALIGN
#define M_BUMP_ARENA_INIT_ALIGN 64
Definition at line 5 of file m_bump_arena.h.
Referenced by m_bump_arena_init().
Function Documentation
m_bump_arena_alloc()
void * m_bump_arena_alloc (m_bump_arena * arena, size_t size)
Definition at line 69 of file m_bump_arena.c.
Referenced by m_bump_arena_realloc(), and m_parser_alloc().
m_bump_arena_destroy()
int m_bump_arena_destroy (m_bump_arena * arena)
Definition at line 130 of file m_bump_arena.c.
Referenced by m_eff_parser_deinit_mempool().
m_bump_arena_free()
void m_bump_arena_free (m_bump_arena * arena)
m_bump_arena_init()
int m_bump_arena_init (m_bump_arena * arena, size_t capacity)
Definition at line 38 of file m_bump_arena.c.
Referenced by m_eff_parser_init_mempool().
m_bump_arena_init_empty()
int m_bump_arena_init_empty (m_bump_arena * arena)
Definition at line 9 of file m_bump_arena.c.
m_bump_arena_realloc()
void * m_bump_arena_realloc (m_bump_arena * arena, void * p, size_t size)
Definition at line 100 of file m_bump_arena.c.
m_bump_arena_reset()
int m_bump_arena_reset (m_bump_arena * arena)
Definition at line 120 of file m_bump_arena.c.
Referenced by m_eff_parser_reset_mempool().