M: m_button.c File Reference
m_button.c File Reference
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (m_active_button)
int init_button (m_button *button)
m_button * new_button (const char *label)
int create_button_ui (m_button *button, lv_obj_t *parent)
int m_button_create_label_ui (m_button *button)
int button_set_clicked_cb (m_button *button, lv_event_cb_t cb, void *cb_arg)
int button_set_pressing_cb (m_button *button, lv_event_cb_t cb, void *cb_arg)
int button_set_long_pressed_cb (m_button *button, lv_event_cb_t cb, void *cb_arg)
int button_set_released_cb (m_button *button, lv_event_cb_t cb, void *cb_arg)
int m_button_set_label (m_button *button, const char *label)
int m_button_disable_alignment (m_button *button)
int m_button_set_alignment (m_button *button, lv_align_t align, int offs_x, int offs_y)
int m_button_set_size (m_button *button, int width, int height)
int m_button_add_sub_button (m_button *button, m_button *sub_button)
int m_button_hide (m_button *button)
int m_button_unhide (m_button *button)
int m_button_set_clickable (m_button *button)
int m_button_set_unclickable (m_button *button)
int m_button_set_opacity (m_button *button, int opacity)
int m_button_enable (m_button *button)
int m_button_disable (m_button *button)
int m_button_reset_state (m_button *button)
int m_button_delete_ui (m_button *button)
int init_danger_button (m_danger_button *button, void(*action_cb)(void *data), void *cb_arg, m_ui_page *parent)
int m_danger_button_create_ui (m_danger_button *button, lv_obj_t *parent)
void m_danger_button_confirm_cb (lv_event_t *e)
void m_danger_button_cancel_cb (lv_event_t *e)
void m_danger_button_value_changed_cb (lv_event_t *e)
void m_danger_button_activate_popup_cb (lv_event_t *e)
void m_active_button_scale_cb (void *data, int32_t value)
void m_active_button_glide_cb (void *data, int32_t value)
void m_active_button_del_button_fade_cb (void *data, int32_t value)
void m_active_button_del_button_faded_out_cb (lv_anim_t *anim)
void m_active_button_delete_anim_cb (void *data, int32_t value)
void m_active_button_trigger_scale_anim (m_active_button *button, int direction)
void m_active_button_trigger_glide_anim (m_active_button *button, int32_t new_pos_y)
void m_active_button_trigger_del_button_fade_in (m_active_button *button)
void m_active_button_trigger_del_button_fade_out (m_active_button *button)
void m_active_button_delete_anim_ready_cb (lv_anim_t *anim)
void m_active_button_trigger_delete_anim (m_active_button *button)
int m_active_button_force_index (m_active_button *button, int i)
int m_active_button_set_index (m_active_button *button, int i)
void m_active_button_del_button_remain_timer_cb (lv_timer_t *timer)
void m_active_button_clicked_cb (lv_event_t *e)
void m_active_button_long_pressed_cb (lv_event_t *e)
void m_active_button_pressing_cb (lv_event_t *e)
void m_active_button_release_cb (lv_event_t *e)
void m_active_button_del_cb (lv_event_t *e)
int m_active_button_init (m_active_button *button)
int m_active_button_add_del_button (m_active_button *button)
void m_active_button_set_representation (m_active_button *button, void *representer, void *representee, void(*update)(void *, void *))
int m_active_button_create_ui (m_active_button *button, lv_obj_t *parent)
void m_active_button_free (m_active_button *button)
int m_active_button_change_label (m_active_button *button, char *text)
int m_active_button_set_dimensions (m_active_button *button, int w, int h)
int m_active_button_swap_del_button_for_persistent_unclickable (m_active_button *button, const char *label)
int m_active_button_reset_del_button (m_active_button *button)
int m_active_button_array_init (m_active_button_array *array)
int m_active_button_array_set_length (m_active_button_array *array, int n)
m_active_button_array * m_active_button_array_new ()
m_active_button * m_active_button_array_append_new (m_active_button_array *array, void *data, char *label)
int m_active_button_array_append (m_active_button *button, m_active_button_array *array)
int m_active_button_array_remove (m_active_button_array *array, int index)
int m_active_button_array_index_y_position (m_active_button_array *array, int index)
int m_active_button_array_create_ui (m_active_button_array *array, lv_obj_t *parent)
int m_active_button_array_set_dimensions (m_active_button_array *array, int w, int h)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file m_button.c.
Function Documentation
button_set_clicked_cb()
int button_set_clicked_cb (m_button * button, lv_event_cb_t cb, void * cb_arg)
Definition at line 158 of file m_button.c.
Referenced by configure_main_menu(), init_danger_button(), m_active_button_add_del_button(), m_active_button_init(), ui_page_add_back_button(), ui_page_add_bottom_button(), ui_page_add_left_panel_button(), ui_page_add_parent_button(), and ui_page_add_right_panel_button().
button_set_long_pressed_cb()
int button_set_long_pressed_cb (m_button * button, lv_event_cb_t cb, void * cb_arg)
Definition at line 186 of file m_button.c.
Referenced by m_active_button_init().
button_set_pressing_cb()
int button_set_pressing_cb (m_button * button, lv_event_cb_t cb, void * cb_arg)
Definition at line 172 of file m_button.c.
Referenced by m_active_button_init().
button_set_released_cb()
int button_set_released_cb (m_button * button, lv_event_cb_t cb, void * cb_arg)
Definition at line 200 of file m_button.c.
Referenced by m_active_button_init().
create_button_ui()
int create_button_ui (m_button * button, lv_obj_t * parent)
Definition at line 68 of file m_button.c.
Referenced by create_button_ui(), create_main_menu_ui(), m_active_button_create_ui(), m_danger_button_create_ui(), ui_page_create_bottom_buttons(), and ui_page_create_panel_ui().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (m_active_button)
init_button()
int init_button (m_button * button)
Definition at line 11 of file m_button.c.
Referenced by configure_main_menu(), init_danger_button(), m_active_button_add_del_button(), m_active_button_init(), and new_button().
init_danger_button()
int init_danger_button (m_danger_button * button, void(* action_cb)(void *data), void * cb_arg, m_ui_page * parent)
Definition at line 461 of file m_button.c.
Referenced by configure_main_menu().
m_active_button_add_del_button()
int m_active_button_add_del_button (m_active_button * button)
Definition at line 1025 of file m_button.c.
Referenced by m_active_button_array_append_new().
m_active_button_array_append()
int m_active_button_array_append (m_active_button * button, m_active_button_array * array)
Definition at line 1331 of file m_button.c.
Referenced by m_active_button_array_append_new().
m_active_button_array_append_new()
m_active_button * m_active_button_array_append_new (m_active_button_array * array, void * data, char * label)
Definition at line 1290 of file m_button.c.
Referenced by configure_profile_view(), configure_sequence_view(), init_test_page(), profile_view_append_effect(), and seq_plus_cb().
m_active_button_array_create_ui()
int m_active_button_array_create_ui (m_active_button_array * array, lv_obj_t * parent)
Definition at line 1382 of file m_button.c.
Referenced by create_profile_view_ui(), create_sequence_view_ui(), and create_test_page_ui().
m_active_button_array_index_y_position()
int m_active_button_array_index_y_position (m_active_button_array * array, int index)
Definition at line 1377 of file m_button.c.
Referenced by m_active_button_array_append(), m_active_button_force_index(), and m_active_button_set_index().
m_active_button_array_init()
int m_active_button_array_init (m_active_button_array * array)
Definition at line 1229 of file m_button.c.
Referenced by m_active_button_array_new().
m_active_button_array_new()
m_active_button_array * m_active_button_array_new ()
Definition at line 1278 of file m_button.c.
Referenced by init_profile_view(), init_sequence_view(), and init_test_page().
m_active_button_array_remove()
int m_active_button_array_remove (m_active_button_array * array, int index)
Definition at line 1356 of file m_button.c.
Referenced by m_active_button_delete_anim_ready_cb().
m_active_button_array_set_dimensions()
int m_active_button_array_set_dimensions (m_active_button_array * array, int w, int h)
Definition at line 1398 of file m_button.c.
m_active_button_array_set_length()
int m_active_button_array_set_length (m_active_button_array * array, int n)
Definition at line 1258 of file m_button.c.
Referenced by init_profile_view(), init_sequence_view(), and init_test_page().
m_active_button_change_label()
int m_active_button_change_label (m_active_button * button, char * text)
Definition at line 1132 of file m_button.c.
Referenced by sequence_view_profile_button_rep_update().
m_active_button_clicked_cb()
void m_active_button_clicked_cb (lv_event_t * e)
Definition at line 779 of file m_button.c.
Referenced by m_active_button_init().
m_active_button_create_ui()
int m_active_button_create_ui (m_active_button * button, lv_obj_t * parent)
Definition at line 1067 of file m_button.c.
Referenced by m_active_button_array_create_ui(), profile_view_append_effect(), and seq_plus_cb().
m_active_button_del_button_fade_cb()
void m_active_button_del_button_fade_cb (void * data, int32_t value)
Definition at line 599 of file m_button.c.
Referenced by m_active_button_reset_del_button(), m_active_button_swap_del_button_for_persistent_unclickable(), m_active_button_trigger_del_button_fade_in(), and m_active_button_trigger_del_button_fade_out().
m_active_button_del_button_faded_out_cb()
void m_active_button_del_button_faded_out_cb (lv_anim_t * anim)
Definition at line 616 of file m_button.c.
Referenced by m_active_button_trigger_del_button_fade_out().
m_active_button_del_button_remain_timer_cb()
void m_active_button_del_button_remain_timer_cb (lv_timer_t * timer)
Definition at line 771 of file m_button.c.
Referenced by m_active_button_release_cb().
m_active_button_del_cb()
void m_active_button_del_cb (lv_event_t * e)
Definition at line 984 of file m_button.c.
Referenced by m_active_button_add_del_button().
m_active_button_delete_anim_cb()
void m_active_button_delete_anim_cb (void * data, int32_t value)
Definition at line 629 of file m_button.c.
Referenced by m_active_button_trigger_delete_anim().
m_active_button_delete_anim_ready_cb()
void m_active_button_delete_anim_ready_cb (lv_anim_t * anim)
Definition at line 712 of file m_button.c.
Referenced by m_active_button_trigger_delete_anim().
m_active_button_force_index()
int m_active_button_force_index (m_active_button * button, int i)
Definition at line 734 of file m_button.c.
Referenced by m_active_button_release_cb().
m_active_button_free()
void m_active_button_free (m_active_button * button)
Definition at line 1108 of file m_button.c.
Referenced by m_active_button_delete_anim_ready_cb().
m_active_button_glide_cb()
void m_active_button_glide_cb (void * data, int32_t value)
Definition at line 588 of file m_button.c.
Referenced by m_active_button_trigger_glide_anim().
m_active_button_init()
int m_active_button_init (m_active_button * button)
Definition at line 999 of file m_button.c.
Referenced by m_active_button_array_append_new().
m_active_button_long_pressed_cb()
void m_active_button_long_pressed_cb (lv_event_t * e)
Definition at line 802 of file m_button.c.
Referenced by m_active_button_init().
m_active_button_pressing_cb()
void m_active_button_pressing_cb (lv_event_t * e)
Definition at line 861 of file m_button.c.
Referenced by m_active_button_init().
m_active_button_release_cb()
void m_active_button_release_cb (lv_event_t * e)
Definition at line 938 of file m_button.c.
Referenced by m_active_button_init().
m_active_button_reset_del_button()
int m_active_button_reset_del_button (m_active_button * button)
Definition at line 1184 of file m_button.c.
Referenced by sequence_view_profile_button_rep_update().
m_active_button_scale_cb()
void m_active_button_scale_cb (void * data, int32_t value)
Definition at line 567 of file m_button.c.
Referenced by m_active_button_trigger_scale_anim().
m_active_button_set_dimensions()
int m_active_button_set_dimensions (m_active_button * button, int w, int h)
Definition at line 1142 of file m_button.c.
Referenced by m_active_button_array_set_dimensions().
m_active_button_set_index()
int m_active_button_set_index (m_active_button * button, int i)
Definition at line 751 of file m_button.c.
Referenced by m_active_button_array_remove(), and m_active_button_pressing_cb().
m_active_button_set_representation()
void m_active_button_set_representation (m_active_button * button, void * representer, void * representee, void(* update)(void *, void *))
Definition at line 1057 of file m_button.c.
Referenced by configure_sequence_view(), and seq_plus_cb().
m_active_button_swap_del_button_for_persistent_unclickable()
int m_active_button_swap_del_button_for_persistent_unclickable (m_active_button * button, const char * label)
Definition at line 1155 of file m_button.c.
Referenced by sequence_view_profile_button_rep_update().
m_active_button_trigger_del_button_fade_in()
void m_active_button_trigger_del_button_fade_in (m_active_button * button)
Definition at line 674 of file m_button.c.
Referenced by m_active_button_long_pressed_cb().
m_active_button_trigger_del_button_fade_out()
void m_active_button_trigger_del_button_fade_out (m_active_button * button)
Definition at line 697 of file m_button.c.
Referenced by m_active_button_del_button_remain_timer_cb().
m_active_button_trigger_delete_anim()
void m_active_button_trigger_delete_anim (m_active_button * button)
Definition at line 720 of file m_button.c.
Referenced by m_active_button_del_cb().
m_active_button_trigger_glide_anim()
void m_active_button_trigger_glide_anim (m_active_button * button, int32_t new_pos_y)
Definition at line 659 of file m_button.c.
Referenced by m_active_button_force_index(), and m_active_button_set_index().
m_active_button_trigger_scale_anim()
void m_active_button_trigger_scale_anim (m_active_button * button, int direction)
Definition at line 639 of file m_button.c.
Referenced by m_active_button_long_pressed_cb(), and m_active_button_release_cb().
m_button_add_sub_button()
int m_button_add_sub_button (m_button * button, m_button * sub_button)
Definition at line 274 of file m_button.c.
Referenced by m_active_button_add_del_button().
m_button_create_label_ui()
int m_button_create_label_ui (m_button * button)
Definition at line 144 of file m_button.c.
Referenced by m_active_button_reset_del_button(), m_active_button_swap_del_button_for_persistent_unclickable(), and m_button_set_label().
m_button_delete_ui()
int m_button_delete_ui (m_button * button)
Definition at line 434 of file m_button.c.
Referenced by m_active_button_free(), and m_button_delete_ui().
m_button_disable()
int m_button_disable (m_button * button)
Definition at line 401 of file m_button.c.
Referenced by configure_profile_view(), create_profile_view_ui(), create_sequence_view_ui(), profile_view_rep_update(), and sequence_view_rep_update().
m_button_disable_alignment()
int m_button_disable_alignment (m_button * button)
Definition at line 233 of file m_button.c.
Referenced by configure_main_menu().
m_button_enable()
int m_button_enable (m_button * button)
Definition at line 388 of file m_button.c.
Referenced by profile_view_rep_update(), profile_view_save_name(), sequence_view_rep_update(), and sequence_view_set_name().
m_button_hide()
int m_button_hide (m_button * button)
Definition at line 287 of file m_button.c.
Referenced by m_active_button_add_del_button(), m_active_button_del_button_faded_out_cb(), and m_active_button_reset_del_button().
m_button_reset_state()
int m_button_reset_state (m_button * button)
Definition at line 419 of file m_button.c.
Referenced by m_active_button_reset_del_button(), and m_active_button_swap_del_button_for_persistent_unclickable().
m_button_set_alignment()
int m_button_set_alignment (m_button * button, lv_align_t align, int offs_x, int offs_y)
Definition at line 243 of file m_button.c.
Referenced by m_active_button_add_del_button(), and m_active_button_array_append().
m_button_set_clickable()
int m_button_set_clickable (m_button * button)
Definition at line 332 of file m_button.c.
Referenced by m_active_button_reset_del_button().
m_button_set_label()
int m_button_set_label (m_button * button, const char * label)
Definition at line 214 of file m_button.c.
Referenced by configure_main_menu(), m_active_button_add_del_button(), m_active_button_change_label(), m_active_button_reset_del_button(), and m_active_button_swap_del_button_for_persistent_unclickable().
m_button_set_opacity()
int m_button_set_opacity (m_button * button, int opacity)
Definition at line 360 of file m_button.c.
Referenced by m_active_button_del_button_fade_cb(), m_active_button_delete_anim_cb(), and m_active_button_swap_del_button_for_persistent_unclickable().
m_button_set_size()
int m_button_set_size (m_button * button, int width, int height)
Definition at line 260 of file m_button.c.
Referenced by m_active_button_add_del_button(), m_active_button_array_append(), and m_active_button_set_dimensions().
m_button_set_unclickable()
int m_button_set_unclickable (m_button * button)
Definition at line 347 of file m_button.c.
Referenced by m_active_button_swap_del_button_for_persistent_unclickable().
m_button_unhide()
int m_button_unhide (m_button * button)
Definition at line 309 of file m_button.c.
Referenced by m_active_button_swap_del_button_for_persistent_unclickable(), m_active_button_trigger_del_button_fade_in(), and m_active_button_trigger_del_button_fade_out().
m_danger_button_activate_popup_cb()
void m_danger_button_activate_popup_cb (lv_event_t * e)
Definition at line 531 of file m_button.c.
Referenced by init_danger_button().
m_danger_button_cancel_cb()
void m_danger_button_cancel_cb (lv_event_t * e)
Definition at line 497 of file m_button.c.
Referenced by m_danger_button_activate_popup_cb().
m_danger_button_confirm_cb()
void m_danger_button_confirm_cb (lv_event_t * e)
Definition at line 489 of file m_button.c.
Referenced by m_danger_button_activate_popup_cb().
m_danger_button_create_ui()
int m_danger_button_create_ui (m_danger_button * button, lv_obj_t * parent)
Definition at line 479 of file m_button.c.
Referenced by create_main_menu_ui().
m_danger_button_value_changed_cb()
void m_danger_button_value_changed_cb (lv_event_t * e)
Definition at line 507 of file m_button.c.
new_button()
m_button * new_button (const char * label)
Definition at line 54 of file m_button.c.
Referenced by m_active_button_add_del_button(), ui_page_add_back_button(), ui_page_add_bottom_button(), ui_page_add_left_panel_button(), ui_page_add_parent_button(), and ui_page_add_right_panel_button().