M: m_context.h File Reference
m_context.h File Reference
Data Structures
struct m_context
Macros
#define MAX_N_PROFILES 256
#define CONTEXT_PROFILE_ID 0xFFFF
#define INPUT_GAIN_PID 0x0000
#define OUTPUT_GAIN_PID 0x0001
Typedefs
typedef m_profile_pll profile_ll
Functions
int m_init_context (m_context *cxt)
int m_context_init_effect_list (m_context *cxt)
int m_context_init_main_sequence (m_context *cxt)
int m_context_init_ui (m_context *cxt)
int m_context_enlarge_profile_array (m_context *cxt)
int m_context_set_n_profiles (m_context *cxt, int n)
int m_context_add_profile (m_context *cxt)
m_profile * m_context_add_profile_rp (m_context *cxt)
m_sequence * m_context_add_sequence_rp (m_context *cxt)
m_profile * cxt_get_profile_by_id (m_context *cxt, uint16_t profile_id)
m_effect * cxt_get_effect_by_id (m_context *cxt, uint16_t profile_id, uint16_t effect_id)
m_parameter * cxt_get_parameter_by_id (m_context *cxt, uint16_t profile_id, uint16_t effect_id, uint16_t parameter_id)
int cxt_get_parameter_and_effect_by_id (m_context *cxt, m_parameter_id id, m_parameter **pp, m_effect **tp)
m_setting * cxt_get_setting_by_id (m_context *cxt, uint16_t profile_id, uint16_t effect_id, uint16_t parameter_id)
m_profile * cxt_get_profile_by_fname (m_context *cxt, const char *fname)
m_sequence * cxt_get_sequence_by_fname (m_context *cxt, const char *fname)
int cxt_effect_id_to_position (m_context *cxt, uint16_t profile_id, uint16_t effect_id)
int cxt_effect_position_to_id (m_context *cxt, uint16_t profile_id, uint16_t effect_pos)
int cxt_remove_effect (m_context *cxt, uint16_t pid, uint16_t tid)
int cxt_remove_profile (m_context *cxt, m_profile *profile)
int cxt_remove_sequence (m_context *cxt, m_sequence *sequence)
int set_active_profile (m_profile *profile)
int set_active_profile_from_sequence (m_profile *profile)
int set_working_profile (m_profile *profile)
int context_no_default_profile (m_context *cxt)
int resolve_default_profile (m_context *cxt)
int set_profile_as_default (m_context *cxt, m_profile *profile)
int cxt_save_all_profiles (m_context *cxt)
void context_print_profiles (m_context *cxt)
int cxt_set_all_profiles_left_button_to_main_menu (m_context *cxt)
int cxt_handle_hw_switch (m_context *cxt, int sw)
m_profile * cxt_find_profile (m_context *cxt, const char *fname)
int m_cxt_obtain_mutex (m_context *cxt)
int m_cxt_release_mutex (m_context *cxt)
int m_cxt_queue_save_state (m_context *cxt)
int m_cxt_set_input_gain (m_context *cxt, float gain)
int m_cxt_set_output_gain (m_context *cxt, float gain)
m_effect_desc * m_cxt_get_effect_desc_from_cname (m_context *cxt, const char *cname)
Macro Definition Documentation
CONTEXT_PROFILE_ID
#define CONTEXT_PROFILE_ID 0xFFFF
Definition at line 6 of file m_context.h.
Referenced by cxt_get_parameter_and_effect_by_id(), m_init_context(), and parameter_widget_change_cb_inner().
INPUT_GAIN_PID
#define INPUT_GAIN_PID 0x0000
Definition at line 7 of file m_context.h.
Referenced by cxt_get_parameter_and_effect_by_id(), and m_init_context().
MAX_N_PROFILES
#define MAX_N_PROFILES 256
Definition at line 4 of file m_context.h.
OUTPUT_GAIN_PID
#define OUTPUT_GAIN_PID 0x0001
Definition at line 8 of file m_context.h.
Referenced by cxt_get_parameter_and_effect_by_id(), and m_init_context().
Typedef Documentation
profile_ll
typedef m_profile_pll profile_ll
Definition at line 10 of file m_context.h.
Function Documentation
context_no_default_profile()
int context_no_default_profile (m_context * cxt)
context_print_profiles()
void context_print_profiles (m_context * cxt)
Definition at line 537 of file m_context.c.
Referenced by app_main().
cxt_effect_id_to_position()
int cxt_effect_id_to_position (m_context * cxt, uint16_t profile_id, uint16_t effect_id)
Definition at line 323 of file m_context.c.
cxt_effect_position_to_id()
int cxt_effect_position_to_id (m_context * cxt, uint16_t profile_id, uint16_t effect_pos)
Definition at line 348 of file m_context.c.
cxt_find_profile()
m_profile * cxt_find_profile (m_context * cxt, const char * fname)
Definition at line 620 of file m_context.c.
cxt_get_effect_by_id()
m_effect * cxt_get_effect_by_id (m_context * cxt, uint16_t profile_id, uint16_t effect_id)
Definition at line 220 of file m_context.c.
Referenced by cxt_get_parameter_and_effect_by_id(), cxt_get_parameter_by_id(), and cxt_get_setting_by_id().
cxt_get_parameter_and_effect_by_id()
int cxt_get_parameter_and_effect_by_id (m_context * cxt, m_parameter_id id, m_parameter ** pp, m_effect ** tp)
Definition at line 259 of file m_context.c.
cxt_get_parameter_by_id()
m_parameter * cxt_get_parameter_by_id (m_context * cxt, uint16_t profile_id, uint16_t effect_id, uint16_t parameter_id)
Definition at line 246 of file m_context.c.
cxt_get_profile_by_fname()
m_profile * cxt_get_profile_by_fname (m_context * cxt, const char * fname)
Definition at line 721 of file m_context.c.
Referenced by m_cxt_restore_state(), m_page_id_find_page(), and read_sequence_from_file().
cxt_get_profile_by_id()
m_profile * cxt_get_profile_by_id (m_context * cxt, uint16_t profile_id)
Definition at line 200 of file m_context.c.
Referenced by cxt_effect_id_to_position(), cxt_effect_position_to_id(), cxt_get_effect_by_id(), cxt_remove_effect(), and sw_field_save_cb().
cxt_get_sequence_by_fname()
m_sequence * cxt_get_sequence_by_fname (m_context * cxt, const char * fname)
Definition at line 756 of file m_context.c.
Referenced by m_page_id_find_page().
cxt_get_setting_by_id()
m_setting * cxt_get_setting_by_id (m_context * cxt, uint16_t profile_id, uint16_t effect_id, uint16_t parameter_id)
Definition at line 310 of file m_context.c.
cxt_handle_hw_switch()
int cxt_handle_hw_switch (m_context * cxt, int sw)
Definition at line 602 of file m_context.c.
Referenced by footswitch_task().
cxt_remove_effect()
int cxt_remove_effect (m_context * cxt, uint16_t pid, uint16_t tid)
Definition at line 456 of file m_context.c.
cxt_remove_profile()
int cxt_remove_profile (m_context * cxt, m_profile * profile)
Definition at line 378 of file m_context.c.
Referenced by profile_listing_delete_button_cb().
cxt_remove_sequence()
int cxt_remove_sequence (m_context * cxt, m_sequence * sequence)
Definition at line 419 of file m_context.c.
Referenced by sequence_listing_delete_button_cb().
cxt_save_all_profiles()
int cxt_save_all_profiles (m_context * cxt)
Definition at line 647 of file m_context.c.
Referenced by seq_save_cb().
cxt_set_all_profiles_left_button_to_main_menu()
int cxt_set_all_profiles_left_button_to_main_menu (m_context * cxt)
Definition at line 582 of file m_context.c.
m_context_add_profile()
int m_context_add_profile (m_context * cxt)
Definition at line 114 of file m_context.c.
m_context_add_profile_rp()
m_profile * m_context_add_profile_rp (m_context * cxt)
Definition at line 141 of file m_context.c.
Referenced by create_new_profile_with_teensy().
m_context_add_sequence_rp()
m_sequence * m_context_add_sequence_rp (m_context * cxt)
Definition at line 175 of file m_context.c.
Referenced by sequence_list_add_cb().
m_context_enlarge_profile_array()
int m_context_enlarge_profile_array (m_context * cxt)
m_context_init_effect_list()
int m_context_init_effect_list (m_context * cxt)
Definition at line 94 of file m_context.c.
Referenced by app_main(), and main_task().
m_context_init_main_sequence()
int m_context_init_main_sequence (m_context * cxt)
Definition at line 67 of file m_context.c.
Referenced by m_init_context().
m_context_init_ui()
int m_context_init_ui (m_context * cxt)
Definition at line 103 of file m_context.c.
m_context_set_n_profiles()
int m_context_set_n_profiles (m_context * cxt, int n)
m_cxt_get_effect_desc_from_cname()
m_effect_desc * m_cxt_get_effect_desc_from_cname (m_context * cxt, const char * cname)
Definition at line 797 of file m_context.c.
Referenced by read_profile_from_file().
m_cxt_obtain_mutex()
int m_cxt_obtain_mutex (m_context * cxt)
Definition at line 667 of file m_context.c.
Referenced by m_cxt_clone_state().
m_cxt_queue_save_state()
int m_cxt_queue_save_state (m_context * cxt)
Definition at line 711 of file m_context.c.
Referenced by enter_ui_page(), enter_ui_page_backwards(), and enter_ui_page_forwards().
m_cxt_release_mutex()
int m_cxt_release_mutex (m_context * cxt)
Definition at line 697 of file m_context.c.
Referenced by m_cxt_clone_state().
m_cxt_set_input_gain()
int m_cxt_set_input_gain (m_context * cxt, float gain)
Definition at line 774 of file m_context.c.
Referenced by m_cxt_restore_state().
m_cxt_set_output_gain()
int m_cxt_set_output_gain (m_context * cxt, float gain)
Definition at line 786 of file m_context.c.
Referenced by m_cxt_restore_state().
m_init_context()
int m_init_context (m_context * cxt)
Definition at line 12 of file m_context.c.
Referenced by app_main(), and main_task().
resolve_default_profile()
int resolve_default_profile (m_context * cxt)
set_active_profile()
int set_active_profile (m_profile * profile)
Definition at line 473 of file m_context.c.
Referenced by profile_view_play_button_cb().
set_active_profile_from_sequence()
int set_active_profile_from_sequence (m_profile * profile)
Definition at line 502 of file m_context.c.
Referenced by m_cxt_restore_state(), m_sequence_advance(), m_sequence_begin(), m_sequence_begin_at(), m_sequence_regress(), and m_sequence_stop().
set_profile_as_default()
int set_profile_as_default (m_context * cxt, m_profile * profile)
set_working_profile()
int set_working_profile (m_profile * profile)
Definition at line 524 of file m_context.c.