M: m_dict_extract.h File Reference
m_dict_extract.h File Reference
Functions
m_setting * m_extract_setting_from_dict (m_eff_parsing_state *ps, m_ast_node *dict_node, m_dictionary *dict)
m_parameter * m_extract_parameter_from_dict (m_eff_parsing_state *ps, m_ast_node *dict_node, m_dictionary *dict)
m_dsp_resource * m_extract_resource_from_dict (m_eff_parsing_state *ps, m_ast_node *dict_node, m_dictionary *dict)
Function Documentation
m_extract_parameter_from_dict()
m_parameter * m_extract_parameter_from_dict (m_eff_parsing_state * ps, m_ast_node * dict_node, m_dictionary * dict)
Definition at line 9 of file m_dict_extract.c.
Referenced by m_parameters_section_extract().
m_extract_resource_from_dict()
m_dsp_resource * m_extract_resource_from_dict (m_eff_parsing_state * ps, m_ast_node * dict_node, m_dictionary * dict)
Definition at line 473 of file m_dict_extract.c.
Referenced by m_resources_section_extract().
m_extract_setting_from_dict()
m_setting * m_extract_setting_from_dict (m_eff_parsing_state * ps, m_ast_node * dict_node, m_dictionary * dict)
Definition at line 276 of file m_dict_extract.c.
Referenced by m_settings_section_extract().