M: m_dictionary.c File Reference
m_dictionary.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
const char * m_dict_entry_type_to_string (int type)
int m_dictionary_bucket_init (m_dictionary_bucket *bucket)
int m_dictionary_bucket_ensure_capacity (m_dictionary_bucket *bucket)
int m_dictionary_bucket_add_entry (m_dictionary_bucket *bucket, m_dictionary_entry entry)
int m_dictionary_bucket_add_entry_str (m_dictionary_bucket *bucket, const char *name, const char *value)
int m_dictionary_bucket_add_entry_int (m_dictionary_bucket *bucket, const char *name, int value)
int m_dictionary_bucket_add_entry_float (m_dictionary_bucket *bucket, const char *name, float value)
int m_dictionary_bucket_add_entry_expr (m_dictionary_bucket *bucket, const char *name, m_expression *value)
int m_dictionary_bucket_add_entry_dict (m_dictionary_bucket *bucket, const char *name, m_dictionary *value)
int m_dictionary_bucket_lookup (m_dictionary_bucket *bucket, const char *name, void *result, int type)
int m_dictionary_bucket_lookup_str (m_dictionary_bucket *bucket, const char *name, const char **result)
int m_dictionary_bucket_lookup_float (m_dictionary_bucket *bucket, const char *name, float *result)
int m_dictionary_bucket_lookup_int (m_dictionary_bucket *bucket, const char *name, int *result)
int m_dictionary_bucket_lookup_expr (m_dictionary_bucket *bucket, const char *name, m_expression **result)
int m_dictionary_bucket_lookup_dict (m_dictionary_bucket *bucket, const char *name, m_dictionary **result)
m_dictionary * m_new_dictionary ()
int m_dictionary_ensure_capacity (m_dictionary *dict)
int m_dictionary_add_entry (m_dictionary *dict, m_dictionary_entry entry)
int m_dictionary_add_entry_str (m_dictionary *dict, const char *name, const char *value)
int m_dictionary_add_entry_int (m_dictionary *dict, const char *name, int value)
int m_dictionary_add_entry_float (m_dictionary *dict, const char *name, float value)
int m_dictionary_add_entry_expr (m_dictionary *dict, const char *name, m_expression *value)
int m_dictionary_add_entry_dict (m_dictionary *dict, const char *name, m_dictionary *value)
int m_dictionary_lookup (m_dictionary *dict, const char *name, void *result, int type)
int m_dictionary_lookup_str (m_dictionary *dict, const char *name, const char **result)
int m_dictionary_lookup_float (m_dictionary *dict, const char *name, float *result)
int m_dictionary_lookup_int (m_dictionary *dict, const char *name, int *result)
int m_dictionary_lookup_expr (m_dictionary *dict, const char *name, m_expression **result)
int m_dictionary_lookup_dict (m_dictionary *dict, const char *name, m_dictionary **result)
void print_dict_entry (m_dictionary_entry *entry)
void print_dict (m_dictionary *dict)
int m_parse_dict_val (m_eff_parsing_state *ps, m_dictionary_entry *result)
int m_parse_dictionary (m_eff_parsing_state *ps, m_dictionary **result, const char *name)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 9 of file m_dictionary.c.
Function Documentation
m_dict_entry_type_to_string()
const char * m_dict_entry_type_to_string (int type)
Definition at line 14 of file m_dictionary.c.
Referenced by m_defs_section_extract().
m_dictionary_add_entry()
int m_dictionary_add_entry (m_dictionary * dict, m_dictionary_entry entry)
Definition at line 325 of file m_dictionary.c.
Referenced by m_parse_dictionary().
m_dictionary_add_entry_dict()
int m_dictionary_add_entry_dict (m_dictionary * dict, const char * name, m_dictionary * value)
Definition at line 442 of file m_dictionary.c.
m_dictionary_add_entry_expr()
int m_dictionary_add_entry_expr (m_dictionary * dict, const char * name, m_expression * value)
Definition at line 418 of file m_dictionary.c.
m_dictionary_add_entry_float()
int m_dictionary_add_entry_float (m_dictionary * dict, const char * name, float value)
Definition at line 394 of file m_dictionary.c.
m_dictionary_add_entry_int()
int m_dictionary_add_entry_int (m_dictionary * dict, const char * name, int value)
Definition at line 370 of file m_dictionary.c.
m_dictionary_add_entry_str()
int m_dictionary_add_entry_str (m_dictionary * dict, const char * name, const char * value)
Definition at line 346 of file m_dictionary.c.
m_dictionary_bucket_add_entry()
int m_dictionary_bucket_add_entry (m_dictionary_bucket * bucket, m_dictionary_entry entry)
Definition at line 72 of file m_dictionary.c.
Referenced by m_dictionary_add_entry().
m_dictionary_bucket_add_entry_dict()
int m_dictionary_bucket_add_entry_dict (m_dictionary_bucket * bucket, const char * name, m_dictionary * value)
Definition at line 179 of file m_dictionary.c.
Referenced by m_dictionary_add_entry_dict().
m_dictionary_bucket_add_entry_expr()
int m_dictionary_bucket_add_entry_expr (m_dictionary_bucket * bucket, const char * name, m_expression * value)
Definition at line 157 of file m_dictionary.c.
Referenced by m_dictionary_add_entry_expr().
m_dictionary_bucket_add_entry_float()
int m_dictionary_bucket_add_entry_float (m_dictionary_bucket * bucket, const char * name, float value)
Definition at line 135 of file m_dictionary.c.
Referenced by m_dictionary_add_entry_float().
m_dictionary_bucket_add_entry_int()
int m_dictionary_bucket_add_entry_int (m_dictionary_bucket * bucket, const char * name, int value)
Definition at line 113 of file m_dictionary.c.
Referenced by m_dictionary_add_entry_int().
m_dictionary_bucket_add_entry_str()
int m_dictionary_bucket_add_entry_str (m_dictionary_bucket * bucket, const char * name, const char * value)
Definition at line 91 of file m_dictionary.c.
Referenced by m_dictionary_add_entry_str().
m_dictionary_bucket_ensure_capacity()
int m_dictionary_bucket_ensure_capacity (m_dictionary_bucket * bucket)
Definition at line 37 of file m_dictionary.c.
Referenced by m_dictionary_bucket_add_entry(), m_dictionary_bucket_add_entry_dict(), m_dictionary_bucket_add_entry_expr(), m_dictionary_bucket_add_entry_float(), m_dictionary_bucket_add_entry_int(), and m_dictionary_bucket_add_entry_str().
m_dictionary_bucket_init()
int m_dictionary_bucket_init (m_dictionary_bucket * bucket)
Definition at line 27 of file m_dictionary.c.
Referenced by m_new_dictionary().
m_dictionary_bucket_lookup()
int m_dictionary_bucket_lookup (m_dictionary_bucket * bucket, const char * name, void * result, int type)
Definition at line 201 of file m_dictionary.c.
Referenced by m_dictionary_bucket_lookup_dict(), m_dictionary_bucket_lookup_expr(), m_dictionary_bucket_lookup_float(), m_dictionary_bucket_lookup_int(), m_dictionary_bucket_lookup_str(), and m_dictionary_lookup().
m_dictionary_bucket_lookup_dict()
int m_dictionary_bucket_lookup_dict (m_dictionary_bucket * bucket, const char * name, m_dictionary ** result)
Definition at line 271 of file m_dictionary.c.
m_dictionary_bucket_lookup_expr()
int m_dictionary_bucket_lookup_expr (m_dictionary_bucket * bucket, const char * name, m_expression ** result)
Definition at line 266 of file m_dictionary.c.
m_dictionary_bucket_lookup_float()
int m_dictionary_bucket_lookup_float (m_dictionary_bucket * bucket, const char * name, float * result)
Definition at line 256 of file m_dictionary.c.
m_dictionary_bucket_lookup_int()
int m_dictionary_bucket_lookup_int (m_dictionary_bucket * bucket, const char * name, int * result)
Definition at line 261 of file m_dictionary.c.
m_dictionary_bucket_lookup_str()
int m_dictionary_bucket_lookup_str (m_dictionary_bucket * bucket, const char * name, const char ** result)
Definition at line 251 of file m_dictionary.c.
m_dictionary_ensure_capacity()
int m_dictionary_ensure_capacity (m_dictionary * dict)
Definition at line 302 of file m_dictionary.c.
Referenced by m_dictionary_add_entry(), m_dictionary_add_entry_dict(), m_dictionary_add_entry_expr(), m_dictionary_add_entry_float(), m_dictionary_add_entry_int(), and m_dictionary_add_entry_str().
m_dictionary_lookup()
int m_dictionary_lookup (m_dictionary * dict, const char * name, void * result, int type)
Definition at line 466 of file m_dictionary.c.
Referenced by m_dictionary_lookup_dict(), m_dictionary_lookup_expr(), m_dictionary_lookup_float(), m_dictionary_lookup_int(), and m_dictionary_lookup_str().
m_dictionary_lookup_dict()
int m_dictionary_lookup_dict (m_dictionary * dict, const char * name, m_dictionary ** result)
Definition at line 496 of file m_dictionary.c.
Referenced by m_dictionary_section_lookup_dict().
m_dictionary_lookup_expr()
int m_dictionary_lookup_expr (m_dictionary * dict, const char * name, m_expression ** result)
Definition at line 491 of file m_dictionary.c.
Referenced by m_dictionary_section_lookup_expr(), m_extract_delay_buffer_from_dict(), m_extract_int_setting_from_dict(), m_extract_mem_from_dict(), m_extract_parameter_from_dict(), and m_extract_setting_from_dict().
m_dictionary_lookup_float()
int m_dictionary_lookup_float (m_dictionary * dict, const char * name, float * result)
Definition at line 481 of file m_dictionary.c.
Referenced by m_dictionary_section_lookup_float().
m_dictionary_lookup_int()
int m_dictionary_lookup_int (m_dictionary * dict, const char * name, int * result)
Definition at line 486 of file m_dictionary.c.
Referenced by m_dictionary_section_lookup_int().
m_dictionary_lookup_str()
int m_dictionary_lookup_str (m_dictionary * dict, const char * name, const char ** result)
Definition at line 476 of file m_dictionary.c.
Referenced by m_dictionary_section_lookup_str(), m_extract_bool_setting_from_dict(), m_extract_parameter_from_dict(), m_extract_resource_from_dict(), and m_extract_setting_from_dict().
m_new_dictionary()
m_dictionary * m_new_dictionary ()
Definition at line 277 of file m_dictionary.c.
Referenced by m_parse_dictionary().
m_parse_dict_val()
int m_parse_dict_val (m_eff_parsing_state * ps, m_dictionary_entry * result)
Definition at line 553 of file m_dictionary.c.
Referenced by m_parse_dictionary().
m_parse_dictionary()
int m_parse_dictionary (m_eff_parsing_state * ps, m_dictionary ** result, const char * name)
Definition at line 647 of file m_dictionary.c.
Referenced by m_parse_dict_val(), and m_parse_dictionary_section().
print_dict()
void print_dict (m_dictionary * dict)
Definition at line 534 of file m_dictionary.c.
print_dict_entry()
void print_dict_entry (m_dictionary_entry * entry)
Definition at line 501 of file m_dictionary.c.
Referenced by print_dict().