M: m_expression.c File Reference
m_expression.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <float.h>
#include <math.h>
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
#define M_EXPRESSION_CONST(x)
Functions
IMPLEMENT_LINKED_PTR_LIST (m_named_expression)
char * m_expression_type_to_str (int type)
int m_expression_form (m_expression *expr)
int m_expression_arity (m_expression *expr)
int m_expression_refers_constant (m_expression *expr)
int m_expression_is_constant (m_expression *expr)
int m_expression_detect_constants_rec (m_expression *expr, int depth)
int m_expression_detect_constants (m_expression *expr)
float m_expression_evaluate (m_expression *expr, m_expr_scope *scope)
int m_expression_references_param_rec (m_expression *expr, m_parameter *param, int depth)
int m_expression_references_param (m_expression *expr, m_parameter *param)
m_expression m_expression_const (float v)
m_expression * new_m_expression_const (float v)
m_expression * new_m_expression_unary (int unary_type, m_expression *rhs)
m_expression * new_m_expression_binary (int binary_type, m_expression *arg_1, m_expression *arg_2)
m_expression * new_m_expression_reference (char *ref_name)
m_interval m_interval_real_line ()
m_interval m_interval_ab (float a, float b)
m_interval m_interval_a_ (float a)
m_interval m_interval__b (float b)
m_interval m_interval_singleton (float v)
m_interval m_expression_compute_range_rec (m_expression *expr, m_expr_scope *scope, int depth)
m_interval m_expression_compute_range (m_expression *expr, m_expr_scope *scope)
const char * m_expression_function_string (m_expression *expr)
const char * m_expression_infix_operator_string (m_expression *expr)
int m_expression_print_rec (m_expression *expr, char *buf, int buf_len, int depth)
int m_expression_print (m_expression *expr)
const char * m_expression_to_string (m_expression *expr)
Variables
m_expression m_expression_standard_gain_min = M_EXPRESSION_CONST(M_STANDARD_GAIN_MIN)
m_expression m_expression_standard_gain_max = M_EXPRESSION_CONST(M_STANDARD_GAIN_MAX)
m_expression m_expression_zero = M_EXPRESSION_CONST(0)
m_expression m_expression_one = M_EXPRESSION_CONST(1)
m_expression m_expression_minus_one = M_EXPRESSION_CONST(-1)
m_expression m_expression_pi = M_EXPRESSION_CONST(M_PI)
m_expression m_expression_e = M_EXPRESSION_CONST(exp(1))
m_expression m_expression_sample_rate = M_EXPRESSION_CONST(M_FPGA_SAMPLE_RATE)
m_expression m_expression_int_max = M_EXPRESSION_CONST(pow(2, M_FPGA_DATA_WIDTH - 1) - 1)
m_expression m_expression_int_min = M_EXPRESSION_CONST(-pow(2, M_FPGA_DATA_WIDTH - 1))
m_expression m_expression_freq_max = M_EXPRESSION_CONST(M_FPGA_SAMPLE_RATE / 2 - 50)
char expr_print_buf [256]
Macro Definition Documentation
M_EXPRESSION_CONST
#define M_EXPRESSION_CONST (x)
Value:
    { \
    .type = M_EXPR_CONST,       \
    .val = {.val_float = x},    \
    .constant = 1,              \
    .cached = 1,                \
    .cached_val = x             \
};
Definition at line 17 of file m_expression.c.
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 10 of file m_expression.c.
Function Documentation
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (m_named_expression)
m_expression_arity()
int m_expression_arity (m_expression * expr)
Definition at line 107 of file m_expression.c.
Referenced by m_expression_compute_range_rec(), m_expression_detect_constants_rec(), and m_expression_references_param_rec().
m_expression_compute_range()
m_interval m_expression_compute_range (m_expression * expr, m_expr_scope * scope)
Definition at line 1203 of file m_expression.c.
Referenced by m_compute_register_formats().
m_expression_compute_range_rec()
m_interval m_expression_compute_range_rec (m_expression * expr, m_expr_scope * scope, int depth)
Definition at line 634 of file m_expression.c.
Referenced by m_expression_compute_range(), and m_expression_compute_range_rec().
m_expression_const()
m_expression m_expression_const (float v)
Definition at line 499 of file m_expression.c.
Referenced by new_m_expression_const().
m_expression_detect_constants()
int m_expression_detect_constants (m_expression * expr)
Definition at line 218 of file m_expression.c.
Referenced by m_parse_expression().
m_expression_detect_constants_rec()
int m_expression_detect_constants_rec (m_expression * expr, int depth)
Definition at line 162 of file m_expression.c.
Referenced by m_expression_detect_constants(), and m_expression_detect_constants_rec().
m_expression_evaluate()
float m_expression_evaluate (m_expression * expr, m_expr_scope * scope)
Definition at line 454 of file m_expression.c.
Referenced by m_expression_compute_range_rec(), m_extract_int_setting_from_dict(), m_extract_mem_from_dict(), m_extract_parameter_from_dict(), m_extract_setting_from_dict(), m_fpga_batch_append_block_register_updates(), m_fpga_batch_append_block_regs(), m_fpga_batch_append_resource(), and m_process_asm_line().
m_expression_form()
int m_expression_form (m_expression * expr)
Definition at line 68 of file m_expression.c.
Referenced by m_expression_print_rec().
m_expression_function_string()
const char * m_expression_function_string (m_expression * expr)
Definition at line 1208 of file m_expression.c.
Referenced by m_expression_print_rec().
m_expression_infix_operator_string()
const char * m_expression_infix_operator_string (m_expression * expr)
Definition at line 1233 of file m_expression.c.
Referenced by m_expression_print_rec().
m_expression_is_constant()
int m_expression_is_constant (m_expression * expr)
Definition at line 154 of file m_expression.c.
Referenced by m_extract_int_setting_from_dict(), m_extract_parameter_from_dict(), and m_extract_setting_from_dict().
m_expression_print()
int m_expression_print (m_expression * expr)
Definition at line 1369 of file m_expression.c.
m_expression_print_rec()
int m_expression_print_rec (m_expression * expr, char * buf, int buf_len, int depth)
Definition at line 1251 of file m_expression.c.
Referenced by m_expression_print(), m_expression_print_rec(), and m_expression_to_string().
m_expression_references_param()
int m_expression_references_param (m_expression * expr, m_parameter * param)
Definition at line 494 of file m_expression.c.
m_expression_references_param_rec()
int m_expression_references_param_rec (m_expression * expr, m_parameter * param, int depth)
Definition at line 461 of file m_expression.c.
Referenced by m_expression_references_param(), and m_expression_references_param_rec().
m_expression_refers_constant()
int m_expression_refers_constant (m_expression * expr)
Definition at line 130 of file m_expression.c.
Referenced by m_expression_compute_range_rec(), m_expression_detect_constants_rec(), and m_expression_is_constant().
m_expression_to_string()
const char * m_expression_to_string (m_expression * expr)
Definition at line 1382 of file m_expression.c.
Referenced by m_expression_compute_range_rec(), m_extract_parameter_from_dict(), and m_parse_asm_line().
m_expression_type_to_str()
char * m_expression_type_to_str (int type)
Definition at line 37 of file m_expression.c.
Referenced by m_extract_parameter_from_dict().
m_interval__b()
m_interval m_interval__b (float b)
Definition at line 618 of file m_expression.c.
m_interval_a_()
m_interval m_interval_a_ (float a)
Definition at line 610 of file m_expression.c.
m_interval_ab()
m_interval m_interval_ab (float a, float b)
Definition at line 602 of file m_expression.c.
Referenced by m_expression_compute_range_rec().
m_interval_real_line()
m_interval m_interval_real_line ()
Definition at line 594 of file m_expression.c.
Referenced by m_expression_compute_range_rec().
m_interval_singleton()
m_interval m_interval_singleton (float v)
Definition at line 626 of file m_expression.c.
Referenced by m_expression_compute_range_rec().
new_m_expression_binary()
m_expression * new_m_expression_binary (int binary_type, m_expression * arg_1, m_expression * arg_2)
Definition at line 545 of file m_expression.c.
Referenced by m_parse_expression_rec_pratt().
new_m_expression_const()
m_expression * new_m_expression_const (float v)
Definition at line 510 of file m_expression.c.
Referenced by m_parse_asm_arg_2(), and m_parse_expression_rec_pratt().
new_m_expression_reference()
m_expression * new_m_expression_reference (char * ref_name)
Definition at line 571 of file m_expression.c.
Referenced by m_parse_asm_arg_2(), and m_parse_expression_rec_pratt().
new_m_expression_unary()
m_expression * new_m_expression_unary (int unary_type, m_expression * rhs)
Definition at line 521 of file m_expression.c.
Referenced by m_parse_expression_rec_pratt().
Variable Documentation
expr_print_buf
char expr_print_buf[256]
Definition at line 1367 of file m_expression.c.
Referenced by m_expression_to_string().
m_expression_e
m_expression m_expression_e = M_EXPRESSION_CONST(exp(1))
Definition at line 31 of file m_expression.c.
m_expression_freq_max
m_expression m_expression_freq_max = M_EXPRESSION_CONST(M_FPGA_SAMPLE_RATE / 2 - 50)
Definition at line 35 of file m_expression.c.
Referenced by init_effect().
m_expression_int_max
m_expression m_expression_int_max = M_EXPRESSION_CONST(pow(2, M_FPGA_DATA_WIDTH - 1) - 1)
Definition at line 33 of file m_expression.c.
m_expression_int_min
m_expression m_expression_int_min = M_EXPRESSION_CONST(-pow(2, M_FPGA_DATA_WIDTH - 1))
Definition at line 34 of file m_expression.c.
m_expression_minus_one
m_expression m_expression_minus_one = M_EXPRESSION_CONST(-1)
Definition at line 29 of file m_expression.c.
m_expression_one
m_expression m_expression_one = M_EXPRESSION_CONST(1)
Definition at line 28 of file m_expression.c.
Referenced by init_effect().
m_expression_pi
m_expression m_expression_pi = M_EXPRESSION_CONST(M_PI)
Definition at line 30 of file m_expression.c.
m_expression_sample_rate
m_expression m_expression_sample_rate = M_EXPRESSION_CONST(M_FPGA_SAMPLE_RATE)
Definition at line 32 of file m_expression.c.
m_expression_standard_gain_max
m_expression m_expression_standard_gain_max = M_EXPRESSION_CONST(M_STANDARD_GAIN_MAX)
Definition at line 26 of file m_expression.c.
Referenced by m_init_context().
m_expression_standard_gain_min
m_expression m_expression_standard_gain_min = M_EXPRESSION_CONST(M_STANDARD_GAIN_MIN)
Definition at line 25 of file m_expression.c.
Referenced by m_init_context().
m_expression_zero
m_expression m_expression_zero = M_EXPRESSION_CONST(0)
Definition at line 27 of file m_expression.c.
Referenced by init_effect().