M: m_effect_view.h File Reference
m_effect_view.h File Reference
Data Structures
struct m_tv_grouping
struct m_effect_view_str
Macros
#define TRANSFORMER_VIEW_GRID_CELL_HSIZE 250
#define TRANSFORMER_VIEW_GRID_CELL_VSIZE 200
#define TRANSFORMER_VIEW_MAX_GROUPS 5
Functions
m_ui_page * create_effect_view_for (m_effect *effect)
int effect_view_configure (m_ui_page *page, void *effect)
int init_effect_view (m_ui_page *page)
int configure_effect_view (m_ui_page *page, void *data)
int create_effect_view_ui (m_ui_page *page)
int free_effect_view_ui (m_ui_page *page)
int free_effect_view (m_ui_page *page)
int enter_effect_view (m_ui_page *page)
int enter_effect_view_forward (m_ui_page *page)
int enter_effect_view_back (m_ui_page *page)
int refresh_effect_view (m_ui_page *page)
int effect_view_request_parameter_values (m_ui_page *page)
Macro Definition Documentation
TRANSFORMER_VIEW_GRID_CELL_HSIZE
#define TRANSFORMER_VIEW_GRID_CELL_HSIZE 250
Definition at line 4 of file m_effect_view.h.
TRANSFORMER_VIEW_GRID_CELL_VSIZE
#define TRANSFORMER_VIEW_GRID_CELL_VSIZE 200
Definition at line 5 of file m_effect_view.h.
TRANSFORMER_VIEW_MAX_GROUPS
#define TRANSFORMER_VIEW_MAX_GROUPS 5
Definition at line 7 of file m_effect_view.h.
Referenced by configure_effect_view(), create_effect_view_ui(), and init_effect_view().
Function Documentation
configure_effect_view()
int configure_effect_view (m_ui_page * page, void * data)
Definition at line 106 of file m_effect_view.c.
Referenced by create_effect_view_for(), and init_effect_view().
create_effect_view_for()
m_ui_page * create_effect_view_for (m_effect * effect)
Definition at line 9 of file m_effect_view.c.
create_effect_view_ui()
int create_effect_view_ui (m_ui_page * page)
Definition at line 192 of file m_effect_view.c.
Referenced by add_effect_from_menu_eff(), and init_effect_view().
effect_view_configure()
int effect_view_configure (m_ui_page * page, void * effect)
effect_view_request_parameter_values()
int effect_view_request_parameter_values (m_ui_page * page)
Referenced by enter_effect_view().
enter_effect_view()
int enter_effect_view (m_ui_page * page)
Definition at line 301 of file m_effect_view.c.
Referenced by init_effect_view().
enter_effect_view_back()
int enter_effect_view_back (m_ui_page * page)
enter_effect_view_forward()
int enter_effect_view_forward (m_ui_page * page)
free_effect_view()
int free_effect_view (m_ui_page * page)
Definition at line 324 of file m_effect_view.c.
Referenced by create_effect_view_for(), free_effect(), and gut_effect().
free_effect_view_ui()
int free_effect_view_ui (m_ui_page * page)
Definition at line 314 of file m_effect_view.c.
init_effect_view()
int init_effect_view (m_ui_page * page)
Definition at line 43 of file m_effect_view.c.
Referenced by create_effect_view_for().
refresh_effect_view()
int refresh_effect_view (m_ui_page * page)