M: m_effect.c File Reference
m_effect.c File Reference
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
#define INITIAL_PARAMETER_ARRAY_LENGTH 8
#define PARAMETER_ARRAY_CHUNK_SIZE 8
#define INITIAL_OPTION_ARRAY_LENGTH 8
#define OPTION_ARRAY_CHUNK_SIZE 8
Functions
IMPLEMENT_LINKED_PTR_LIST (m_effect)
const char * m_effect_name (m_effect *effect)
int init_effect (m_effect *effect)
int init_effect_from_effect_desc (m_effect *effect, m_effect_desc *eff)
int effect_rectify_param_ids (m_effect *effect)
int effect_set_id (m_effect *effect, uint16_t profile_id, uint16_t effect_id)
int request_append_effect (uint16_t type, m_effect *local)
m_parameter * effect_add_parameter (m_effect *effect)
m_setting * effect_add_setting (m_effect *effect)
int clone_effect (m_effect *dest, m_effect *src)
void gut_effect (m_effect *effect)
void free_effect (m_effect *effect)
m_parameter * effect_get_parameter (m_effect *effect, int n)
m_setting * effect_get_setting (m_effect *effect, int n)
int m_effect_update_fpga_registers (m_effect *effect)
m_expr_scope * m_effect_create_scope (m_effect *effect)
int m_effect_set_parameter (m_effect *effect, const char *name, float value)
int m_effect_set_setting (m_effect *effect, const char *name, int value)
void m_effect_profile_rep_update (void *representer, void *representee)
int m_effect_update_reps (m_effect *effect)
Macro Definition Documentation
INITIAL_OPTION_ARRAY_LENGTH
#define INITIAL_OPTION_ARRAY_LENGTH 8
Definition at line 10 of file m_effect.c.
INITIAL_PARAMETER_ARRAY_LENGTH
#define INITIAL_PARAMETER_ARRAY_LENGTH 8
Definition at line 7 of file m_effect.c.
OPTION_ARRAY_CHUNK_SIZE
#define OPTION_ARRAY_CHUNK_SIZE 8
Definition at line 11 of file m_effect.c.
PARAMETER_ARRAY_CHUNK_SIZE
#define PARAMETER_ARRAY_CHUNK_SIZE 8
Definition at line 8 of file m_effect.c.
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file m_effect.c.
Function Documentation
clone_effect()
int clone_effect (m_effect * dest, m_effect * src)
Definition at line 345 of file m_effect.c.
Referenced by clone_pipeline().
effect_add_parameter()
m_parameter * effect_add_parameter (m_effect * effect)
Definition at line 237 of file m_effect.c.
Referenced by clone_effect(), init_3_band_eq(), init_amplifier(), init_band_pass_filter(), init_compressor(), init_delay(), init_dirty_octave(), init_distortion(), init_envelope(), init_flanger(), init_high_pass_filter(), init_low_end_compressor(), init_low_pass_filter(), init_noise_suppressor(), init_percussifier(), and init_warbler().
effect_add_setting()
m_setting * effect_add_setting (m_effect * effect)
Definition at line 264 of file m_effect.c.
Referenced by clone_effect(), init_amplifier(), init_delay(), init_distortion(), and init_flanger().
effect_get_parameter()
m_parameter * effect_get_parameter (m_effect * effect, int n)
Definition at line 448 of file m_effect.c.
Referenced by cxt_get_parameter_and_effect_by_id(), and cxt_get_parameter_by_id().
effect_get_setting()
m_setting * effect_get_setting (m_effect * effect, int n)
Definition at line 466 of file m_effect.c.
Referenced by cxt_get_setting_by_id().
effect_rectify_param_ids()
int effect_rectify_param_ids (m_effect * effect)
Definition at line 130 of file m_effect.c.
Referenced by effect_set_id(), and m_profile_append_effect_eff().
effect_set_id()
int effect_set_id (m_effect * effect, uint16_t profile_id, uint16_t effect_id)
Definition at line 178 of file m_effect.c.
free_effect()
void free_effect (m_effect * effect)
Definition at line 433 of file m_effect.c.
Referenced by gut_pipeline(), and m_pipeline_remove_effect().
gut_effect()
void gut_effect (m_effect * effect)
Definition at line 410 of file m_effect.c.
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (m_effect)
init_effect()
int init_effect (m_effect * effect)
Definition at line 29 of file m_effect.c.
Referenced by clone_effect(), init_effect_from_effect_desc(), and init_effect_of_type().
init_effect_from_effect_desc()
int init_effect_from_effect_desc (m_effect * effect, m_effect_desc * eff)
Definition at line 103 of file m_effect.c.
Referenced by m_pipeline_append_effect_eff().
m_effect_create_scope()
m_expr_scope * m_effect_create_scope (m_effect * effect)
Definition at line 509 of file m_effect.c.
Referenced by init_effect_from_effect_desc().
m_effect_name()
const char * m_effect_name (m_effect * effect)
Definition at line 17 of file m_effect.c.
Referenced by configure_effect_settings_page(), configure_effect_view(), configure_profile_view(), context_print_profiles(), create_effect_view_ui(), and profile_view_append_effect().
m_effect_profile_rep_update()
void m_effect_profile_rep_update (void * representer, void * representee)
Definition at line 598 of file m_effect.c.
Referenced by init_effect().
m_effect_set_parameter()
int m_effect_set_parameter (m_effect * effect, const char * name, float value)
Definition at line 551 of file m_effect.c.
m_effect_set_setting()
int m_effect_set_setting (m_effect * effect, const char * name, int value)
Definition at line 574 of file m_effect.c.
m_effect_update_fpga_registers()
int m_effect_update_fpga_registers (m_effect * effect)
Definition at line 483 of file m_effect.c.
m_effect_update_reps()
int m_effect_update_reps (m_effect * effect)
Definition at line 613 of file m_effect.c.
Referenced by m_parameter_effect_rep_update(), and m_setting_effect_rep_update().
request_append_effect()
int request_append_effect (uint16_t type, m_effect * local)
Definition at line 190 of file m_effect.c.