M: m_expr_scope.h File Reference
m_expr_scope.h File Reference
Data Structures
struct m_expr_scope_entry
struct m_expr_scope
Macros
#define M_SCOPE_ENTRY_TYPE_EXPR 0
#define M_SCOPE_ENTRY_TYPE_PARAM 1
#define M_SCOPE_ENTRY_TYPE_SETTING 2
Functions
m_expr_scope_entry * m_new_expr_scope_entry_expr (const char *name, struct m_expression *expr)
m_expr_scope_entry * m_new_expr_scope_entry_param (struct m_parameter *param)
m_expr_scope_entry * m_new_expr_scope_entry_setting (struct m_setting *setting)
DECLARE_LINKED_PTR_LIST (m_expr_scope_entry)
m_expr_scope * m_new_expr_scope ()
int m_expr_scope_init (m_expr_scope *scope)
int m_expr_scope_add_expr (m_expr_scope *scope, const char *name, struct m_expression *expr)
int m_expr_scope_add_param (m_expr_scope *scope, struct m_parameter *param)
int m_expr_scope_add_setting (m_expr_scope *scope, struct m_setting *setting)
int m_expr_scope_add_params (m_expr_scope *scope, struct m_parameter_pll *params)
int m_expr_scope_add_settings (m_expr_scope *scope, struct m_setting_pll *settings)
m_expr_scope_entry * m_expr_scope_fetch (m_expr_scope *scope, const char *name)
m_expr_scope * m_expr_scope_copy (m_expr_scope *scope)
Macro Definition Documentation
M_SCOPE_ENTRY_TYPE_EXPR
#define M_SCOPE_ENTRY_TYPE_EXPR 0
Definition at line 4 of file m_expr_scope.h.
Referenced by m_expression_compute_range_rec(), and m_new_expr_scope_entry_expr().
M_SCOPE_ENTRY_TYPE_PARAM
#define M_SCOPE_ENTRY_TYPE_PARAM 1
Definition at line 5 of file m_expr_scope.h.
Referenced by m_expression_compute_range_rec(), and m_new_expr_scope_entry_param().
M_SCOPE_ENTRY_TYPE_SETTING
#define M_SCOPE_ENTRY_TYPE_SETTING 2
Definition at line 6 of file m_expr_scope.h.
Referenced by m_new_expr_scope_entry_setting().
Function Documentation
DECLARE_LINKED_PTR_LIST()
DECLARE_LINKED_PTR_LIST (m_expr_scope_entry)
m_expr_scope_add_expr()
int m_expr_scope_add_expr (m_expr_scope * scope, const char * name, struct m_expression * expr)
Definition at line 88 of file m_expr_scope.c.
Referenced by m_defs_section_extract(), and m_effect_create_scope().
m_expr_scope_add_param()
int m_expr_scope_add_param (m_expr_scope * scope, struct m_parameter * param)
Definition at line 106 of file m_expr_scope.c.
Referenced by m_eff_desc_create_scope(), m_effect_create_scope(), and m_expr_scope_add_params().
m_expr_scope_add_params()
int m_expr_scope_add_params (m_expr_scope * scope, struct m_parameter_pll * params)
Definition at line 142 of file m_expr_scope.c.
Referenced by m_parse_tokens().
m_expr_scope_add_setting()
int m_expr_scope_add_setting (m_expr_scope * scope, struct m_setting * setting)
Definition at line 124 of file m_expr_scope.c.
Referenced by m_effect_create_scope(), and m_expr_scope_add_settings().
m_expr_scope_add_settings()
int m_expr_scope_add_settings (m_expr_scope * scope, struct m_setting_pll * settings)
Definition at line 161 of file m_expr_scope.c.
Referenced by m_parse_tokens().
m_expr_scope_copy()
m_expr_scope * m_expr_scope_copy (m_expr_scope * scope)
m_expr_scope_fetch()
m_expr_scope_entry * m_expr_scope_fetch (m_expr_scope * scope, const char * name)
Definition at line 189 of file m_expr_scope.c.
Referenced by m_expression_compute_range_rec().
m_expr_scope_init()
int m_expr_scope_init (m_expr_scope * scope)
Definition at line 66 of file m_expr_scope.c.
Referenced by m_parse_tokens().
m_new_expr_scope()
m_expr_scope * m_new_expr_scope ()
Definition at line 76 of file m_expr_scope.c.
Referenced by m_eff_desc_create_scope(), and m_effect_create_scope().
m_new_expr_scope_entry_expr()
m_expr_scope_entry * m_new_expr_scope_entry_expr (const char * name, struct m_expression * expr)
Definition at line 11 of file m_expr_scope.c.
Referenced by m_expr_scope_add_expr().
m_new_expr_scope_entry_param()
m_expr_scope_entry * m_new_expr_scope_entry_param (struct m_parameter * param)
Definition at line 28 of file m_expr_scope.c.
Referenced by m_expr_scope_add_param().
m_new_expr_scope_entry_setting()
m_expr_scope_entry * m_new_expr_scope_entry_setting (struct m_setting * setting)
Definition at line 45 of file m_expr_scope.c.
Referenced by m_expr_scope_add_setting().