M: m_effect_init.c File Reference
m_effect_init.c File Reference
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int init_3_band_eq (m_effect *effect)
int init_amplifier (m_effect *effect)
int init_band_pass_filter (m_effect *effect)
int init_compressor (m_effect *effect)
int init_delay (m_effect *effect)
int init_dirty_octave (m_effect *effect)
int init_distortion (m_effect *effect)
int init_envelope (m_effect *effect)
int init_flanger (m_effect *effect)
int init_high_pass_filter (m_effect *effect)
int init_low_end_compressor (m_effect *effect)
int init_low_pass_filter (m_effect *effect)
int init_noise_suppressor (m_effect *effect)
int init_percussifier (m_effect *effect)
int init_warbler (m_effect *effect)
int init_effect_of_type (m_effect *effect, uint16_t type)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file m_effect_init.c.
Function Documentation
init_3_band_eq()
int init_3_band_eq (m_effect * effect)
Definition at line 14 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_amplifier()
int init_amplifier (m_effect * effect)
Definition at line 76 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_band_pass_filter()
int init_band_pass_filter (m_effect * effect)
Definition at line 134 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_compressor()
int init_compressor (m_effect * effect)
Definition at line 180 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_delay()
int init_delay (m_effect * effect)
Definition at line 258 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_dirty_octave()
int init_dirty_octave (m_effect * effect)
Definition at line 342 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_distortion()
int init_distortion (m_effect * effect)
Definition at line 372 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_effect_of_type()
int init_effect_of_type (m_effect * effect, uint16_t type)
Definition at line 1209 of file m_effect_init.c.
init_envelope()
int init_envelope (m_effect * effect)
Definition at line 484 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_flanger()
int init_flanger (m_effect * effect)
Definition at line 594 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_high_pass_filter()
int init_high_pass_filter (m_effect * effect)
Definition at line 709 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_low_end_compressor()
int init_low_end_compressor (m_effect * effect)
Definition at line 739 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_low_pass_filter()
int init_low_pass_filter (m_effect * effect)
Definition at line 881 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_noise_suppressor()
int init_noise_suppressor (m_effect * effect)
Definition at line 911 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_percussifier()
int init_percussifier (m_effect * effect)
Definition at line 973 of file m_effect_init.c.
Referenced by init_effect_of_type().
init_warbler()
int init_warbler (m_effect * effect)
Definition at line 1099 of file m_effect_init.c.
Referenced by init_effect_of_type().