M: m_effect_settings.h File Reference
m_effect_settings.h File Reference
Data Structures
struct effect_settings_page_str
Functions
int init_effect_settings_page (m_ui_page *page)
int configure_effect_settings_page (m_ui_page *page, void *data)
int create_effect_settings_page_ui (m_ui_page *page)
int refresh_effect_settings_page (m_ui_page *page)
int free_effect_settings_page_ui (m_ui_page *page)
int effect_settings_page_free_all (m_ui_page *page)
Function Documentation
configure_effect_settings_page()
int configure_effect_settings_page (m_ui_page * page, void * data)
Definition at line 48 of file m_effect_settings.c.
Referenced by configure_effect_view(), and init_effect_settings_page().
create_effect_settings_page_ui()
int create_effect_settings_page_ui (m_ui_page * page)
Definition at line 137 of file m_effect_settings.c.
Referenced by create_effect_view_ui(), and init_effect_settings_page().
effect_settings_page_free_all()
int effect_settings_page_free_all (m_ui_page * page)
Definition at line 276 of file m_effect_settings.c.
free_effect_settings_page_ui()
int free_effect_settings_page_ui (m_ui_page * page)
Definition at line 265 of file m_effect_settings.c.
init_effect_settings_page()
int init_effect_settings_page (m_ui_page * page)
Definition at line 9 of file m_effect_settings.c.
Referenced by init_effect_view().
refresh_effect_settings_page()
int refresh_effect_settings_page (m_ui_page * page)
Definition at line 182 of file m_effect_settings.c.
Referenced by band_control_value_changed_cb(), and create_effect_settings_page_ui().