M: m_effect_select.c File Reference
m_effect_select.c File Reference
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (m_effect_selector_button)
void enter_effect_selector_cb (lv_event_t *e)
int init_effect_selector_eff (m_ui_page *page)
int configure_effect_selector (m_ui_page *page, void *data)
int refresh_effect_selector (m_ui_page *page)
void add_effect_from_menu_eff (lv_event_t *e)
int init_effect_selector_button_from_effect (m_effect_selector_button *button, m_effect_desc *eff)
int create_effect_selector_button_ui_eff (m_effect_selector_button *button, lv_obj_t *parent)
int create_effect_selector_ui_eff (m_ui_page *page)
int enter_effect_selector (m_ui_page *page)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file m_effect_select.c.
Function Documentation
add_effect_from_menu_eff()
void add_effect_from_menu_eff (lv_event_t * e)
Definition at line 85 of file m_effect_select.c.
Referenced by create_effect_selector_button_ui_eff().
configure_effect_selector()
int configure_effect_selector (m_ui_page * page, void * data)
Definition at line 62 of file m_effect_select.c.
create_effect_selector_button_ui_eff()
int create_effect_selector_button_ui_eff (m_effect_selector_button * button, lv_obj_t * parent)
Definition at line 148 of file m_effect_select.c.
Referenced by create_effect_selector_ui_eff().
create_effect_selector_ui_eff()
int create_effect_selector_ui_eff (m_ui_page * page)
Definition at line 158 of file m_effect_select.c.
Referenced by init_effect_selector_eff().
enter_effect_selector()
int enter_effect_selector (m_ui_page * page)
Definition at line 190 of file m_effect_select.c.
Referenced by init_effect_selector_eff().
enter_effect_selector_cb()
void enter_effect_selector_cb (lv_event_t * e)
Definition at line 11 of file m_effect_select.c.
Referenced by configure_profile_view().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (m_effect_selector_button)
init_effect_selector_button_from_effect()
int init_effect_selector_button_from_effect (m_effect_selector_button * button, m_effect_desc * eff)
Definition at line 131 of file m_effect_select.c.
Referenced by init_effect_selector_eff().
init_effect_selector_eff()
int init_effect_selector_eff (m_ui_page * page)
Definition at line 16 of file m_effect_select.c.
Referenced by app_main(), and main_task().
refresh_effect_selector()
int refresh_effect_selector (m_ui_page * page)
Definition at line 80 of file m_effect_select.c.