M: m_eff_section.h File Reference
m_eff_section.h File Reference
Data Structures
struct m_eff_desc_file_section
Functions
int get_section_start_score (char *str, int current_score)
int m_settings_section_extract (m_eff_parsing_state *ps, m_setting_pll **list, struct m_ast_node *sect)
int m_parameters_section_extract (m_eff_parsing_state *ps, m_parameter_pll **list, struct m_ast_node *sect)
int m_resources_section_extract (m_eff_parsing_state *ps, m_dsp_resource_pll **list, struct m_ast_node *sect)
int m_defs_section_extract (m_eff_parsing_state *ps, m_expr_scope *scope, struct m_ast_node *sect)
int m_dictionary_section_lookup_str (m_ast_node *section, const char *name, const char **result)
int m_dictionary_section_lookup_float (m_ast_node *section, const char *name, float *result)
int m_dictionary_section_lookup_int (m_ast_node *section, const char *name, int *result)
int m_dictionary_section_lookup_expr (m_ast_node *section, const char *name, m_expression **result)
int m_dictionary_section_lookup_dict (m_ast_node *section, const char *name, m_dictionary **result)
int token_is_valid_section_name (char *str)
int m_parse_dictionary_section (m_eff_parsing_state *ps, m_ast_node *section)
int m_parse_code_section (m_eff_parsing_state *ps, m_ast_node *section)
Function Documentation
get_section_start_score()
int get_section_start_score (char * str, int current_score)
Definition at line 24 of file m_eff_section.c.
Referenced by m_parse_tokens().
m_defs_section_extract()
int m_defs_section_extract (m_eff_parsing_state * ps, m_expr_scope * scope, struct m_ast_node * sect)
Definition at line 137 of file m_eff_section.c.
Referenced by m_parse_tokens().
m_dictionary_section_lookup_dict()
int m_dictionary_section_lookup_dict (m_ast_node * section, const char * name, m_dictionary ** result)
Definition at line 237 of file m_eff_section.c.
m_dictionary_section_lookup_expr()
int m_dictionary_section_lookup_expr (m_ast_node * section, const char * name, m_expression ** result)
Definition at line 225 of file m_eff_section.c.
m_dictionary_section_lookup_float()
int m_dictionary_section_lookup_float (m_ast_node * section, const char * name, float * result)
Definition at line 201 of file m_eff_section.c.
m_dictionary_section_lookup_int()
int m_dictionary_section_lookup_int (m_ast_node * section, const char * name, int * result)
Definition at line 213 of file m_eff_section.c.
m_dictionary_section_lookup_str()
int m_dictionary_section_lookup_str (m_ast_node * section, const char * name, const char ** result)
Definition at line 189 of file m_eff_section.c.
Referenced by m_parse_tokens().
m_parameters_section_extract()
int m_parameters_section_extract (m_eff_parsing_state * ps, m_parameter_pll ** list, struct m_ast_node * sect)
Definition at line 41 of file m_eff_section.c.
Referenced by m_parse_tokens().
m_parse_code_section()
int m_parse_code_section (m_eff_parsing_state * ps, m_ast_node * section)
Definition at line 270 of file m_eff_section.c.
Referenced by m_parse_tokens().
m_parse_dictionary_section()
int m_parse_dictionary_section (m_eff_parsing_state * ps, m_ast_node * section)
Definition at line 249 of file m_eff_section.c.
Referenced by m_parse_tokens().
m_resources_section_extract()
int m_resources_section_extract (m_eff_parsing_state * ps, m_dsp_resource_pll ** list, struct m_ast_node * sect)
Definition at line 102 of file m_eff_section.c.
Referenced by m_parse_tokens().
m_settings_section_extract()
int m_settings_section_extract (m_eff_parsing_state * ps, m_setting_pll ** list, struct m_ast_node * sect)
Definition at line 70 of file m_eff_section.c.
Referenced by m_parse_tokens().
token_is_valid_section_name()
int token_is_valid_section_name (char * str)
Definition at line 9 of file m_eff_section.c.
Referenced by get_section_start_score().