M: m_eff_parser.c File Reference
m_eff_parser.c File Reference
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <stdio.h>
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 1
#define M_PARSER_PRINT_BUFLEN 1024
#define M_PARSER_PRINT_LOC_BUFLEN 128
#define PR_LINE_INDENT 4
Functions
int m_eff_parser_init_mempool ()
int m_eff_parser_reset_mempool ()
int m_eff_parser_deinit_mempool ()
void * m_parser_alloc (size_t size)
char * m_parser_strndup (const char *str, int n)
int m_parse_tokens (m_eff_parsing_state *ps)
int init_parsing_state (m_eff_parsing_state *ps)
int m_parser_lineize_content (m_eff_parsing_state *ps)
m_effect_desc * m_read_eff_desc_from_file (char *fname)
int m_parser_format_offending_section (char *line, int index, int length, char *buf, int buf_len, char *colour)
void m_parser_print_info_at (m_eff_parsing_state *ps, m_token_ll *token, const char *msg,...)
void m_parser_warn_at (m_eff_parsing_state *ps, m_token_ll *token, const char *msg,...)
void m_parser_error_at (m_eff_parsing_state *ps, m_token_ll *token, const char *msg,...)
void m_parser_print_info_at_line (m_eff_parsing_state *ps, int line, const char *msg,...)
void m_parser_warn_at_line (m_eff_parsing_state *ps, int line, const char *msg,...)
void m_parser_error_at_line (m_eff_parsing_state *ps, int line, const char *msg,...)
void m_parser_print_info_at_node (m_eff_parsing_state *ps, m_ast_node *node, const char *msg,...)
void m_parser_warn_at_node (m_eff_parsing_state *ps, m_ast_node *node, const char *msg,...)
void m_parser_error_at_node (m_eff_parsing_state *ps, m_ast_node *node, const char *msg,...)
void m_parser_print_info (m_eff_parsing_state *ps, const char *msg,...)
void m_parser_warn (m_eff_parsing_state *ps, const char *msg,...)
void m_parser_error (m_eff_parsing_state *ps, const char *msg,...)
Variables
const char * ver_str = "v1.0"
m_bump_arena m_eff_parser_mempool
int m_parser_mempool_initialised = 0
const char * err_colour = "\e[01;31m"
const char * info_colour = "\e[01;36m"
const char * warn_colour = "\e[01;32m"
const char * reset_colour = "\e[0m"
Macro Definition Documentation
M_PARSER_PRINT_BUFLEN
#define M_PARSER_PRINT_BUFLEN 1024
Definition at line 550 of file m_eff_parser.c.
Referenced by m_parser_error(), m_parser_error_at(), m_parser_error_at_line(), m_parser_error_at_node(), m_parser_format_offending_section(), m_parser_print_info(), m_parser_print_info_at(), m_parser_print_info_at_line(), m_parser_print_info_at_node(), m_parser_warn(), m_parser_warn_at(), m_parser_warn_at_line(), and m_parser_warn_at_node().
M_PARSER_PRINT_LOC_BUFLEN
#define M_PARSER_PRINT_LOC_BUFLEN 128
Definition at line 551 of file m_eff_parser.c.
Referenced by m_parser_error(), m_parser_error_at(), m_parser_error_at_line(), m_parser_error_at_node(), m_parser_print_info(), m_parser_print_info_at(), m_parser_print_info_at_line(), m_parser_print_info_at_node(), m_parser_warn(), m_parser_warn_at(), m_parser_warn_at_line(), and m_parser_warn_at_node().
PR_LINE_INDENT
#define PR_LINE_INDENT 4
Definition at line 558 of file m_eff_parser.c.
Referenced by m_parser_format_offending_section().
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 1
Definition at line 9 of file m_eff_parser.c.
Function Documentation
init_parsing_state()
int init_parsing_state (m_eff_parsing_state * ps)
Definition at line 354 of file m_eff_parser.c.
Referenced by m_read_eff_desc_from_file().
m_eff_parser_deinit_mempool()
int m_eff_parser_deinit_mempool ()
Definition at line 39 of file m_eff_parser.c.
Referenced by load_effects().
m_eff_parser_init_mempool()
int m_eff_parser_init_mempool ()
Definition at line 19 of file m_eff_parser.c.
Referenced by m_read_eff_desc_from_file().
m_eff_parser_reset_mempool()
int m_eff_parser_reset_mempool ()
Definition at line 29 of file m_eff_parser.c.
Referenced by load_effects().
m_parse_tokens()
int m_parse_tokens (m_eff_parsing_state * ps)
Definition at line 63 of file m_eff_parser.c.
Referenced by m_read_eff_desc_from_file().
m_parser_alloc()
void * m_parser_alloc (size_t size)
Definition at line 45 of file m_eff_parser.c.
Referenced by m_dictionary_bucket_ensure_capacity(), m_dictionary_ensure_capacity(), m_new_dictionary(), m_parse_asm_line(), m_parse_tokens(), m_parser_lineize_content(), m_parser_strndup(), m_read_eff_desc_from_file(), and m_token_ll_safe_aappend().
m_parser_error()
void m_parser_error (m_eff_parsing_state * ps, const char * msg, ...)
Definition at line 856 of file m_eff_parser.c.
Referenced by m_parse_dictionary(), m_parse_tokens(), and m_read_eff_desc_from_file().
m_parser_error_at()
void m_parser_error_at (m_eff_parsing_state * ps, m_token_ll * token, const char * msg, ...)
Definition at line 668 of file m_eff_parser.c.
Referenced by m_parse_asm_arg(), m_parse_asm_arg_2(), m_parse_asm_line(), m_parse_dictionary(), m_parse_expression(), m_parse_expression_rec_pratt(), and m_parse_tokens().
m_parser_error_at_line()
void m_parser_error_at_line (m_eff_parsing_state * ps, int line, const char * msg, ...)
Definition at line 740 of file m_eff_parser.c.
Referenced by m_defs_section_extract(), m_process_asm_line(), and m_tokenize_content().
m_parser_error_at_node()
void m_parser_error_at_node (m_eff_parsing_state * ps, m_ast_node * node, const char * msg, ...)
Definition at line 798 of file m_eff_parser.c.
Referenced by m_extract_delay_buffer_from_dict(), m_extract_int_setting_from_dict(), m_extract_parameter_from_dict(), m_extract_resource_from_dict(), m_extract_setting_from_dict(), and m_resources_section_extract().
m_parser_format_offending_section()
int m_parser_format_offending_section (char * line, int index, int length, char * buf, int buf_len, char * colour)
Definition at line 560 of file m_eff_parser.c.
Referenced by m_parser_error_at(), m_parser_print_info_at(), and m_parser_warn_at().
m_parser_lineize_content()
int m_parser_lineize_content (m_eff_parsing_state * ps)
Definition at line 379 of file m_eff_parser.c.
Referenced by m_read_eff_desc_from_file().
m_parser_print_info()
void m_parser_print_info (m_eff_parsing_state * ps, const char * msg, ...)
Definition at line 818 of file m_eff_parser.c.
m_parser_print_info_at()
void m_parser_print_info_at (m_eff_parsing_state * ps, m_token_ll * token, const char * msg, ...)
Definition at line 612 of file m_eff_parser.c.
m_parser_print_info_at_line()
void m_parser_print_info_at_line (m_eff_parsing_state * ps, int line, const char * msg, ...)
Definition at line 702 of file m_eff_parser.c.
m_parser_print_info_at_node()
void m_parser_print_info_at_node (m_eff_parsing_state * ps, m_ast_node * node, const char * msg, ...)
Definition at line 760 of file m_eff_parser.c.
m_parser_strndup()
char * m_parser_strndup (const char * str, int n)
Definition at line 50 of file m_eff_parser.c.
Referenced by m_parse_asm_line(), m_parse_dict_val(), m_parse_dictionary(), m_parse_tokens(), m_read_eff_desc_from_file(), and m_tokenize_content().
m_parser_warn()
void m_parser_warn (m_eff_parsing_state * ps, const char * msg, ...)
Definition at line 837 of file m_eff_parser.c.
m_parser_warn_at()
void m_parser_warn_at (m_eff_parsing_state * ps, m_token_ll * token, const char * msg, ...)
Definition at line 640 of file m_eff_parser.c.
m_parser_warn_at_line()
void m_parser_warn_at_line (m_eff_parsing_state * ps, int line, const char * msg, ...)
Definition at line 721 of file m_eff_parser.c.
m_parser_warn_at_node()
void m_parser_warn_at_node (m_eff_parsing_state * ps, m_ast_node * node, const char * msg, ...)
Definition at line 779 of file m_eff_parser.c.
Referenced by m_extract_bool_setting_from_dict(), m_extract_int_setting_from_dict(), m_extract_parameter_from_dict(), and m_extract_setting_from_dict().
m_read_eff_desc_from_file()
m_effect_desc * m_read_eff_desc_from_file (char * fname)
Definition at line 425 of file m_eff_parser.c.
Referenced by load_effects().
Variable Documentation
err_colour
const char* err_colour = "\e[01;31m"
Definition at line 553 of file m_eff_parser.c.
Referenced by m_parser_error_at(), and m_parser_format_offending_section().
info_colour
const char* info_colour = "\e[01;36m"
Definition at line 554 of file m_eff_parser.c.
Referenced by m_parser_print_info_at().
m_eff_parser_mempool
m_bump_arena m_eff_parser_mempool
Definition at line 16 of file m_eff_parser.c.
Referenced by m_eff_parser_deinit_mempool(), m_eff_parser_init_mempool(), m_eff_parser_reset_mempool(), and m_parser_alloc().
m_parser_mempool_initialised
int m_parser_mempool_initialised = 0
Definition at line 17 of file m_eff_parser.c.
Referenced by m_eff_parser_deinit_mempool(), m_eff_parser_init_mempool(), m_eff_parser_reset_mempool(), and m_read_eff_desc_from_file().
reset_colour
const char* reset_colour = "\e[0m"
Definition at line 556 of file m_eff_parser.c.
Referenced by m_parser_error_at(), m_parser_format_offending_section(), and m_parser_print_info_at().
ver_str
const char* ver_str = "v1.0"
Definition at line 14 of file m_eff_parser.c.
Referenced by m_tokenize_content().
warn_colour
const char* warn_colour = "\e[01;32m"
Definition at line 555 of file m_eff_parser.c.
Referenced by m_parser_warn_at().