M: m_eff_parser.h File Reference
m_eff_parser.h File Reference
Data Structures
struct m_ast_node
struct m_eff_parsing_state
Macros
#define M_EFF_PARSER_MEM_POOL_SIZE_KB 512
#define M_AST_NODE_ROOT 0
#define M_AST_NODE_SECTION 1
#define M_AST_NODE_DICT 2
Functions
int m_parse_dictionary (m_eff_parsing_state *ps, m_dictionary **result, const char *name)
m_effect_desc * m_read_eff_desc_from_file (char *fname)
void m_parser_print_info (m_eff_parsing_state *ps, const char *error_msg,...)
void m_parser_warn (m_eff_parsing_state *ps, const char *error_msg,...)
void m_parser_error (m_eff_parsing_state *ps, const char *error_msg,...)
void m_parser_print_info_at (m_eff_parsing_state *ps, m_token_ll *token, const char *error_msg,...)
void m_parser_warn_at (m_eff_parsing_state *ps, m_token_ll *token, const char *error_msg,...)
void m_parser_error_at (m_eff_parsing_state *ps, m_token_ll *token, const char *error_msg,...)
void m_parser_print_info_at_line (m_eff_parsing_state *ps, int line, const char *error_msg,...)
void m_parser_warn_at_line (m_eff_parsing_state *ps, int line, const char *error_msg,...)
void m_parser_error_at_line (m_eff_parsing_state *ps, int line, const char *error_msg,...)
void m_parser_print_info_at_node (m_eff_parsing_state *ps, m_ast_node *node, const char *error_msg,...)
void m_parser_warn_at_node (m_eff_parsing_state *ps, m_ast_node *node, const char *error_msg,...)
void m_parser_error_at_node (m_eff_parsing_state *ps, m_ast_node *node, const char *error_msg,...)
int m_eff_parser_init_mempool ()
int m_eff_parser_reset_mempool ()
int m_eff_parser_deinit_mempool ()
void * m_parser_alloc (size_t size)
char * m_parser_strndup (const char *str, int n)
Variables
const char * ver_str
Macro Definition Documentation
M_AST_NODE_DICT
#define M_AST_NODE_DICT 2
Definition at line 8 of file m_eff_parser.h.
M_AST_NODE_ROOT
#define M_AST_NODE_ROOT 0
Definition at line 6 of file m_eff_parser.h.
Referenced by m_parse_tokens().
M_AST_NODE_SECTION
#define M_AST_NODE_SECTION 1
Definition at line 7 of file m_eff_parser.h.
Referenced by m_dictionary_section_lookup_dict(), m_dictionary_section_lookup_expr(), m_dictionary_section_lookup_float(), m_dictionary_section_lookup_int(), m_dictionary_section_lookup_str(), m_parse_code_section(), m_parse_dictionary_section(), and m_parse_tokens().
M_EFF_PARSER_MEM_POOL_SIZE_KB
#define M_EFF_PARSER_MEM_POOL_SIZE_KB 512
Definition at line 4 of file m_eff_parser.h.
Referenced by m_eff_parser_init_mempool().
Function Documentation
m_eff_parser_deinit_mempool()
int m_eff_parser_deinit_mempool ()
Definition at line 39 of file m_eff_parser.c.
Referenced by load_effects().
m_eff_parser_init_mempool()
int m_eff_parser_init_mempool ()
Definition at line 19 of file m_eff_parser.c.
Referenced by m_read_eff_desc_from_file().
m_eff_parser_reset_mempool()
int m_eff_parser_reset_mempool ()
Definition at line 29 of file m_eff_parser.c.
Referenced by load_effects().
m_parse_dictionary()
int m_parse_dictionary (m_eff_parsing_state * ps, m_dictionary ** result, const char * name)
Definition at line 647 of file m_dictionary.c.
Referenced by m_parse_dict_val(), and m_parse_dictionary_section().
m_parser_alloc()
void * m_parser_alloc (size_t size)
Definition at line 45 of file m_eff_parser.c.
Referenced by m_dictionary_bucket_ensure_capacity(), m_dictionary_ensure_capacity(), m_new_dictionary(), m_parse_asm_line(), m_parse_tokens(), m_parser_lineize_content(), m_parser_strndup(), m_read_eff_desc_from_file(), and m_token_ll_safe_aappend().
m_parser_error()
void m_parser_error (m_eff_parsing_state * ps, const char * error_msg, ...)
Definition at line 856 of file m_eff_parser.c.
Referenced by m_parse_dictionary(), m_parse_tokens(), and m_read_eff_desc_from_file().
m_parser_error_at()
void m_parser_error_at (m_eff_parsing_state * ps, m_token_ll * token, const char * error_msg, ...)
Definition at line 668 of file m_eff_parser.c.
Referenced by m_parse_asm_arg(), m_parse_asm_arg_2(), m_parse_asm_line(), m_parse_dictionary(), m_parse_expression(), m_parse_expression_rec_pratt(), and m_parse_tokens().
m_parser_error_at_line()
void m_parser_error_at_line (m_eff_parsing_state * ps, int line, const char * error_msg, ...)
Definition at line 740 of file m_eff_parser.c.
Referenced by m_defs_section_extract(), m_process_asm_line(), and m_tokenize_content().
m_parser_error_at_node()
void m_parser_error_at_node (m_eff_parsing_state * ps, m_ast_node * node, const char * error_msg, ...)
Definition at line 798 of file m_eff_parser.c.
Referenced by m_extract_delay_buffer_from_dict(), m_extract_int_setting_from_dict(), m_extract_parameter_from_dict(), m_extract_resource_from_dict(), m_extract_setting_from_dict(), and m_resources_section_extract().
m_parser_print_info()
void m_parser_print_info (m_eff_parsing_state * ps, const char * error_msg, ...)
Definition at line 818 of file m_eff_parser.c.
m_parser_print_info_at()
void m_parser_print_info_at (m_eff_parsing_state * ps, m_token_ll * token, const char * error_msg, ...)
Definition at line 612 of file m_eff_parser.c.
m_parser_print_info_at_line()
void m_parser_print_info_at_line (m_eff_parsing_state * ps, int line, const char * error_msg, ...)
Definition at line 702 of file m_eff_parser.c.
m_parser_print_info_at_node()
void m_parser_print_info_at_node (m_eff_parsing_state * ps, m_ast_node * node, const char * error_msg, ...)
Definition at line 760 of file m_eff_parser.c.
m_parser_strndup()
char * m_parser_strndup (const char * str, int n)
Definition at line 50 of file m_eff_parser.c.
Referenced by m_parse_asm_line(), m_parse_dict_val(), m_parse_dictionary(), m_parse_tokens(), m_read_eff_desc_from_file(), and m_tokenize_content().
m_parser_warn()
void m_parser_warn (m_eff_parsing_state * ps, const char * error_msg, ...)
Definition at line 837 of file m_eff_parser.c.
m_parser_warn_at()
void m_parser_warn_at (m_eff_parsing_state * ps, m_token_ll * token, const char * error_msg, ...)
Definition at line 640 of file m_eff_parser.c.
m_parser_warn_at_line()
void m_parser_warn_at_line (m_eff_parsing_state * ps, int line, const char * error_msg, ...)
Definition at line 721 of file m_eff_parser.c.
m_parser_warn_at_node()
void m_parser_warn_at_node (m_eff_parsing_state * ps, m_ast_node * node, const char * error_msg, ...)
Definition at line 779 of file m_eff_parser.c.
Referenced by m_extract_bool_setting_from_dict(), m_extract_int_setting_from_dict(), m_extract_parameter_from_dict(), and m_extract_setting_from_dict().
m_read_eff_desc_from_file()
m_effect_desc * m_read_eff_desc_from_file (char * fname)
Definition at line 425 of file m_eff_parser.c.
Referenced by load_effects().
Variable Documentation
ver_str
const char* ver_str extern
Definition at line 14 of file m_eff_parser.c.
Referenced by m_tokenize_content().