M: m_fpga_encoding.h File Reference
m_fpga_encoding.h File Reference
Macros
#define ZERO_REGISTER_ADDR 2
#define POS_ONE_REGISTER_ADDR 3
#define NEG_ONE_REGISTER_ADDR 4
#define INSTR_FORMAT_A 0
#define INSTR_FORMAT_B 1
#define NO_SHIFT 255
#define DELAY_FORMAT 8
Functions
int m_fpga_batch_append_block_number (m_fpga_transfer_batch *batch, int block)
uint32_t m_block_instr_encode_resource_aware (m_block *block, const m_eff_resource_report *res)
int m_fpga_batch_append_effect (m_fpga_transfer_batch *batch, m_effect *effect, m_eff_resource_report *res, int *pos)
int m_fpga_transfer_batch_append_effect_register_updates (m_fpga_transfer_batch *batch, m_effect_desc *eff, m_expr_scope *scope, int pos)
int m_fpga_batch_append_effects (m_fpga_transfer_batch *batch, m_effect_pll *list, m_eff_resource_report *res, int *pos)
int m_fpga_batch_print (m_fpga_transfer_batch seq)
Macro Definition Documentation
DELAY_FORMAT
#define DELAY_FORMAT 8
Definition at line 13 of file m_fpga_encoding.h.
Referenced by m_fpga_batch_append_resource().
INSTR_FORMAT_A
#define INSTR_FORMAT_A 0
Definition at line 8 of file m_fpga_encoding.h.
Referenced by m_fpga_block_opcode_format().
INSTR_FORMAT_B
#define INSTR_FORMAT_B 1
Definition at line 9 of file m_fpga_encoding.h.
Referenced by m_fpga_block_opcode_format().
NEG_ONE_REGISTER_ADDR
#define NEG_ONE_REGISTER_ADDR 4
Definition at line 6 of file m_fpga_encoding.h.
NO_SHIFT
#define NO_SHIFT 255
Definition at line 11 of file m_fpga_encoding.h.
POS_ONE_REGISTER_ADDR
#define POS_ONE_REGISTER_ADDR 3
Definition at line 5 of file m_fpga_encoding.h.
ZERO_REGISTER_ADDR
#define ZERO_REGISTER_ADDR 2
Definition at line 4 of file m_fpga_encoding.h.
Function Documentation
m_block_instr_encode_resource_aware()
uint32_t m_block_instr_encode_resource_aware (m_block * block, const m_eff_resource_report * res)
Definition at line 60 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_block_instr().
m_fpga_batch_append_block_number()
int m_fpga_batch_append_block_number (m_fpga_transfer_batch * batch, int block)
Definition at line 96 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_block_instr(), m_fpga_batch_append_block_register_updates(), and m_fpga_batch_append_block_regs().
m_fpga_batch_append_effect()
int m_fpga_batch_append_effect (m_fpga_transfer_batch * batch, m_effect * effect, m_eff_resource_report * res, int * pos)
Definition at line 304 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_effects().
m_fpga_batch_append_effects()
int m_fpga_batch_append_effects (m_fpga_transfer_batch * batch, m_effect_pll * list, m_eff_resource_report * res, int * pos)
Definition at line 327 of file m_fpga_encoding.c.
Referenced by m_pipeline_create_fpga_transfer_batch().
m_fpga_batch_print()
int m_fpga_batch_print (m_fpga_transfer_batch seq)
Definition at line 463 of file m_fpga_encoding.c.
Referenced by m_fpga_comms_task().
m_fpga_transfer_batch_append_effect_register_updates()
int m_fpga_transfer_batch_append_effect_register_updates (m_fpga_transfer_batch * batch, m_effect_desc * eff, m_expr_scope * scope, int pos)
Definition at line 192 of file m_fpga_encoding.c.
Referenced by m_effect_update_fpga_registers().