M: m_fpga_io.h File Reference
m_fpga_io.h File Reference
Data Structures
struct m_fpga_transfer_batch
Macros
#define M_FPGA_SAMPLE_RATE 44100
#define COMMAND_BEGIN_PROGRAM 1
#define COMMAND_WRITE_BLOCK_INSTR 2
#define COMMAND_WRITE_BLOCK_REG_0 3
#define COMMAND_WRITE_BLOCK_REG_1 4
#define COMMAND_ALLOC_DELAY 5
#define COMMAND_END_PROGRAM 10
#define COMMAND_SET_INPUT_GAIN 11
#define COMMAND_SET_OUTPUT_GAIN 12
#define COMMAND_UPDATE_BLOCK_REG_0 13
#define COMMAND_UPDATE_BLOCK_REG_1 14
#define COMMAND_COMMIT_REG_UPDATES 15
#define COMMAND_ALLOC_FILTER 16
#define COMMAND_WRITE_FILTER_COEF 17
#define SPI_RESPONSE_OK 0
#define SPI_RESPONSE_INITIALISING 1
#define SPI_RESPONSE_PROGRAMMING 2
#define SPI_RESPONSE_REJECTED 3
#define SPI_RESPONSE_TIMEOUT 4
#define M_FPGA_N_BLOCKS 256
#define M_FPGA_BLOCK_ADDR_BYTES 1
#define M_FPGA_DATA_WIDTH 16
#define M_FPGA_DATA_BYTES (M_FPGA_DATA_WIDTH / 8)
Typedefs
typedef uint8_t m_fpga_block_addr_t
typedef int16_t m_fpga_sample_t
Functions
m_fpga_transfer_batch m_new_fpga_transfer_batch ()
void m_free_fpga_transfer_batch (m_fpga_transfer_batch batch)
int m_send_bytes_to_fpga (uint8_t *buf, int n)
int m_send_byte_to_fpga (uint8_t byte)
int m_fpga_send_byte (uint8_t byte)
uint8_t m_fpga_read_byte ()
void m_fpga_set_input_gain (float gain_db)
void m_fpga_set_output_gain (float gain_db)
void m_fpga_commit_reg_updates ()
int m_fpga_batch_append (m_fpga_transfer_batch *seq, uint8_t x)
int m_fpga_batch_append_16 (m_fpga_transfer_batch *seq, uint16_t x)
int m_fpga_batch_append_24 (m_fpga_transfer_batch *seq, uint32_t x)
int m_fpga_batch_append_32 (m_fpga_transfer_batch *seq, uint32_t x)
int m_fpga_transfer_batch_send (m_fpga_transfer_batch batch)
int m_fpga_spi_init ()
m_fpga_sample_t float_to_q_nminus1 (float x, int shift)
int16_t float_to_q15 (float x)
char * m_fpga_command_to_string (int command)
Macro Definition Documentation
COMMAND_ALLOC_DELAY
#define COMMAND_ALLOC_DELAY 5
Definition at line 12 of file m_fpga_io.h.
Referenced by m_fpga_batch_append_resource(), m_fpga_batch_print(), and m_fpga_command_to_string().
COMMAND_ALLOC_FILTER
#define COMMAND_ALLOC_FILTER 16
Definition at line 19 of file m_fpga_io.h.
Referenced by m_fpga_batch_print().
COMMAND_BEGIN_PROGRAM
#define COMMAND_BEGIN_PROGRAM 1
Definition at line 8 of file m_fpga_io.h.
Referenced by m_fpga_batch_print(), m_fpga_command_to_string(), and m_pipeline_create_fpga_transfer_batch().
COMMAND_COMMIT_REG_UPDATES
#define COMMAND_COMMIT_REG_UPDATES 15
Definition at line 18 of file m_fpga_io.h.
Referenced by m_fpga_batch_print(), m_fpga_command_to_string(), m_fpga_commit_reg_updates(), and m_fpga_queue_register_commit().
COMMAND_END_PROGRAM
#define COMMAND_END_PROGRAM 10
Definition at line 13 of file m_fpga_io.h.
Referenced by m_fpga_batch_print(), m_fpga_command_to_string(), and m_pipeline_create_fpga_transfer_batch().
COMMAND_SET_INPUT_GAIN
#define COMMAND_SET_INPUT_GAIN 11
Definition at line 14 of file m_fpga_io.h.
Referenced by m_fpga_batch_print(), m_fpga_command_to_string(), and m_fpga_set_input_gain().
COMMAND_SET_OUTPUT_GAIN
#define COMMAND_SET_OUTPUT_GAIN 12
Definition at line 15 of file m_fpga_io.h.
Referenced by m_fpga_batch_print(), m_fpga_command_to_string(), and m_fpga_set_output_gain().
COMMAND_UPDATE_BLOCK_REG_0
#define COMMAND_UPDATE_BLOCK_REG_0 13
Definition at line 16 of file m_fpga_io.h.
Referenced by m_fpga_batch_append_block_register_updates(), m_fpga_batch_print(), and m_fpga_command_to_string().
COMMAND_UPDATE_BLOCK_REG_1
#define COMMAND_UPDATE_BLOCK_REG_1 14
Definition at line 17 of file m_fpga_io.h.
Referenced by m_fpga_batch_append_block_register_updates(), m_fpga_batch_print(), and m_fpga_command_to_string().
COMMAND_WRITE_BLOCK_INSTR
#define COMMAND_WRITE_BLOCK_INSTR 2
Definition at line 9 of file m_fpga_io.h.
Referenced by m_fpga_batch_append_block_instr(), m_fpga_batch_print(), and m_fpga_command_to_string().
COMMAND_WRITE_BLOCK_REG_0
#define COMMAND_WRITE_BLOCK_REG_0 3
Definition at line 10 of file m_fpga_io.h.
Referenced by m_fpga_batch_append_block_regs(), m_fpga_batch_print(), and m_fpga_command_to_string().
COMMAND_WRITE_BLOCK_REG_1
#define COMMAND_WRITE_BLOCK_REG_1 4
Definition at line 11 of file m_fpga_io.h.
Referenced by m_fpga_batch_append_block_regs(), m_fpga_batch_print(), and m_fpga_command_to_string().
COMMAND_WRITE_FILTER_COEF
#define COMMAND_WRITE_FILTER_COEF 17
Definition at line 20 of file m_fpga_io.h.
Referenced by m_fpga_batch_print().
M_FPGA_BLOCK_ADDR_BYTES
#define M_FPGA_BLOCK_ADDR_BYTES 1
Definition at line 34 of file m_fpga_io.h.
Referenced by m_fpga_batch_print().
M_FPGA_DATA_BYTES
#define M_FPGA_DATA_BYTES (M_FPGA_DATA_WIDTH / 8)
Definition at line 39 of file m_fpga_io.h.
Referenced by m_fpga_batch_print().
M_FPGA_DATA_WIDTH
#define M_FPGA_DATA_WIDTH 16
Definition at line 38 of file m_fpga_io.h.
Referenced by float_to_q_nminus1(), and m_compute_register_formats().
M_FPGA_N_BLOCKS
#define M_FPGA_N_BLOCKS 256
Definition at line 28 of file m_fpga_io.h.
Referenced by m_fpga_batch_append_block_number(), and m_new_fpga_transfer_batch().
M_FPGA_SAMPLE_RATE
#define M_FPGA_SAMPLE_RATE 44100
Definition at line 4 of file m_fpga_io.h.
Referenced by m_fpga_batch_append_resource().
SPI_RESPONSE_INITIALISING
#define SPI_RESPONSE_INITIALISING 1
Definition at line 23 of file m_fpga_io.h.
SPI_RESPONSE_OK
#define SPI_RESPONSE_OK 0
Definition at line 22 of file m_fpga_io.h.
Referenced by m_fpga_comms_task().
SPI_RESPONSE_PROGRAMMING
#define SPI_RESPONSE_PROGRAMMING 2
Definition at line 24 of file m_fpga_io.h.
SPI_RESPONSE_REJECTED
#define SPI_RESPONSE_REJECTED 3
Definition at line 25 of file m_fpga_io.h.
SPI_RESPONSE_TIMEOUT
#define SPI_RESPONSE_TIMEOUT 4
Definition at line 26 of file m_fpga_io.h.
Typedef Documentation
m_fpga_block_addr_t
typedef uint8_t m_fpga_block_addr_t
Definition at line 35 of file m_fpga_io.h.
m_fpga_sample_t
typedef int16_t m_fpga_sample_t
Definition at line 42 of file m_fpga_io.h.
Function Documentation
float_to_q15()
int16_t float_to_q15 (float x)
Definition at line 36 of file m_fpga_io.c.
float_to_q_nminus1()
m_fpga_sample_t float_to_q_nminus1 (float x, int shift)
Definition at line 20 of file m_fpga_io.c.
Referenced by m_fpga_batch_append_block_register_updates(), m_fpga_batch_append_block_regs(), m_fpga_set_input_gain(), and m_fpga_set_output_gain().
m_fpga_batch_append()
int m_fpga_batch_append (m_fpga_transfer_batch * seq, uint8_t x)
Definition at line 150 of file m_fpga_io.c.
Referenced by m_fpga_batch_append_16(), m_fpga_batch_append_24(), m_fpga_batch_append_32(), m_fpga_batch_append_block_instr(), m_fpga_batch_append_block_number(), m_fpga_batch_append_block_register_updates(), m_fpga_batch_append_block_regs(), m_fpga_batch_append_resource(), and m_pipeline_create_fpga_transfer_batch().
m_fpga_batch_append_16()
int m_fpga_batch_append_16 (m_fpga_transfer_batch * seq, uint16_t x)
Definition at line 172 of file m_fpga_io.c.
Referenced by m_fpga_batch_append_block_number(), m_fpga_batch_append_block_register_updates(), and m_fpga_batch_append_block_regs().
m_fpga_batch_append_24()
int m_fpga_batch_append_24 (m_fpga_transfer_batch * seq, uint32_t x)
Definition at line 188 of file m_fpga_io.c.
Referenced by m_fpga_batch_append_resource().
m_fpga_batch_append_32()
int m_fpga_batch_append_32 (m_fpga_transfer_batch * seq, uint32_t x)
Definition at line 205 of file m_fpga_io.c.
Referenced by m_fpga_batch_append_block_instr().
m_fpga_command_to_string()
char * m_fpga_command_to_string (int command)
Definition at line 295 of file m_fpga_io.c.
Referenced by m_fpga_comms_task().
m_fpga_commit_reg_updates()
void m_fpga_commit_reg_updates ()
Definition at line 290 of file m_fpga_io.c.
m_fpga_read_byte()
uint8_t m_fpga_read_byte ()
Definition at line 125 of file m_fpga_io.c.
Referenced by m_fpga_comms_task().
m_fpga_send_byte()
int m_fpga_send_byte (uint8_t byte)
Definition at line 120 of file m_fpga_io.c.
Referenced by m_fpga_commit_reg_updates(), m_fpga_comms_task(), m_fpga_set_input_gain(), and m_fpga_set_output_gain().
m_fpga_set_input_gain()
void m_fpga_set_input_gain (float gain_db)
Definition at line 269 of file m_fpga_io.c.
Referenced by m_fpga_comms_task().
m_fpga_set_output_gain()
void m_fpga_set_output_gain (float gain_db)
Definition at line 279 of file m_fpga_io.c.
Referenced by m_fpga_comms_task().
m_fpga_spi_init()
int m_fpga_spi_init ()
Definition at line 44 of file m_fpga_io.c.
Referenced by m_fpga_comms_task().
m_fpga_transfer_batch_send()
int m_fpga_transfer_batch_send (m_fpga_transfer_batch batch)
Definition at line 264 of file m_fpga_io.c.
Referenced by m_fpga_comms_task().
m_free_fpga_transfer_batch()
void m_free_fpga_transfer_batch (m_fpga_transfer_batch batch)
Definition at line 145 of file m_fpga_io.c.
Referenced by m_fpga_comms_task(), and m_pipeline_create_fpga_transfer_batch().
m_new_fpga_transfer_batch()
m_fpga_transfer_batch m_new_fpga_transfer_batch ()
Definition at line 133 of file m_fpga_io.c.
Referenced by m_effect_update_fpga_registers(), and m_pipeline_create_fpga_transfer_batch().
m_send_byte_to_fpga()
int m_send_byte_to_fpga (uint8_t byte)
m_send_bytes_to_fpga()
int m_send_bytes_to_fpga (uint8_t * buf, int n)