M: m_fpga_encoding.c File Reference
m_fpga_encoding.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 1
Functions
int m_fpga_block_opcode_format (int opcode)
int m_block_instr_format (m_block *block)
uint32_t m_encode_dsp_block_instr_type_a (m_block *block)
uint32_t m_encode_dsp_block_instr_type_b (m_block *block, int res_handle)
uint32_t m_block_instr_encode_resource_aware (m_block *block, const m_eff_resource_report *res)
int m_fpga_batch_append_block_number (m_fpga_transfer_batch *batch, int block)
int m_fpga_batch_append_block_instr (m_fpga_transfer_batch *batch, m_block *block, const m_eff_resource_report *res, int pos)
int m_fpga_batch_append_block_regs (m_fpga_transfer_batch *batch, m_block *block, m_expr_scope *scope, int pos)
int m_fpga_batch_append_block_register_updates (m_fpga_transfer_batch *batch, m_block *block, m_expr_scope *scope, int pos)
int m_fpga_transfer_batch_append_effect_register_updates (m_fpga_transfer_batch *batch, m_effect_desc *eff, m_expr_scope *scope, int pos)
int m_fpga_batch_append_block (m_fpga_transfer_batch *batch, m_block *block, const m_eff_resource_report *res, m_expr_scope *scope, int pos)
int m_fpga_batch_append_blocks (m_fpga_transfer_batch *batch, m_block_pll *blocks, const m_eff_resource_report *res, m_expr_scope *scope, int pos)
int m_fpga_batch_append_resource (m_fpga_transfer_batch *batch, m_dsp_resource *res, const m_eff_resource_report *rpt, m_expr_scope *scope)
int m_fpga_batch_append_resources (m_fpga_transfer_batch *batch, m_dsp_resource_pll *list, const m_eff_resource_report *rpt, m_expr_scope *scope)
int m_fpga_batch_append_eff_desc (m_fpga_transfer_batch *batch, m_effect_desc *eff, const m_eff_resource_report *res, m_expr_scope *scope, int pos)
int m_fpga_batch_append_effect (m_fpga_transfer_batch *batch, m_effect *effect, m_eff_resource_report *res, int *pos)
int m_fpga_batch_append_effects (m_fpga_transfer_batch *batch, m_effect_pll *list, m_eff_resource_report *res, int *pos)
char * m_block_opcode_to_string (uint32_t opcode)
char * m_block_opcode_to_name (uint32_t opcode)
void print_instruction_format_a (uint32_t instr)
void print_instruction_format_b (uint32_t instr)
void print_instruction (uint32_t instr)
int m_fpga_batch_print (m_fpga_transfer_batch seq)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 1
Definition at line 10 of file m_fpga_encoding.c.
Function Documentation
m_block_instr_encode_resource_aware()
uint32_t m_block_instr_encode_resource_aware (m_block * block, const m_eff_resource_report * res)
Definition at line 60 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_block_instr().
m_block_instr_format()
int m_block_instr_format (m_block * block)
Definition at line 32 of file m_fpga_encoding.c.
Referenced by m_block_instr_encode_resource_aware().
m_block_opcode_to_name()
char * m_block_opcode_to_name (uint32_t opcode)
Definition at line 374 of file m_fpga_encoding.c.
Referenced by print_instruction_format_a(), and print_instruction_format_b().
m_block_opcode_to_string()
char * m_block_opcode_to_string (uint32_t opcode)
Definition at line 345 of file m_fpga_encoding.c.
m_encode_dsp_block_instr_type_a()
uint32_t m_encode_dsp_block_instr_type_a (m_block * block)
Definition at line 39 of file m_fpga_encoding.c.
Referenced by m_block_instr_encode_resource_aware().
m_encode_dsp_block_instr_type_b()
uint32_t m_encode_dsp_block_instr_type_b (m_block * block, int res_handle)
Definition at line 51 of file m_fpga_encoding.c.
Referenced by m_block_instr_encode_resource_aware().
m_fpga_batch_append_block()
int m_fpga_batch_append_block (m_fpga_transfer_batch * batch, m_block * block, const m_eff_resource_report * res, m_expr_scope * scope, int pos)
Definition at line 211 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_blocks().
m_fpga_batch_append_block_instr()
int m_fpga_batch_append_block_instr (m_fpga_transfer_batch * batch, m_block * block, const m_eff_resource_report * res, int pos)
Definition at line 107 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_block().
m_fpga_batch_append_block_number()
int m_fpga_batch_append_block_number (m_fpga_transfer_batch * batch, int block)
Definition at line 96 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_block_instr(), m_fpga_batch_append_block_register_updates(), and m_fpga_batch_append_block_regs().
m_fpga_batch_append_block_register_updates()
int m_fpga_batch_append_block_register_updates (m_fpga_transfer_batch * batch, m_block * block, m_expr_scope * scope, int pos)
Definition at line 153 of file m_fpga_encoding.c.
Referenced by m_fpga_transfer_batch_append_effect_register_updates().
m_fpga_batch_append_block_regs()
int m_fpga_batch_append_block_regs (m_fpga_transfer_batch * batch, m_block * block, m_expr_scope * scope, int pos)
Definition at line 121 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_block().
m_fpga_batch_append_blocks()
int m_fpga_batch_append_blocks (m_fpga_transfer_batch * batch, m_block_pll * blocks, const m_eff_resource_report * res, m_expr_scope * scope, int pos)
Definition at line 222 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_eff_desc().
m_fpga_batch_append_eff_desc()
int m_fpga_batch_append_eff_desc (m_fpga_transfer_batch * batch, m_effect_desc * eff, const m_eff_resource_report * res, m_expr_scope * scope, int pos)
Definition at line 293 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_effect().
m_fpga_batch_append_effect()
int m_fpga_batch_append_effect (m_fpga_transfer_batch * batch, m_effect * effect, m_eff_resource_report * res, int * pos)
Definition at line 304 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_effects().
m_fpga_batch_append_effects()
int m_fpga_batch_append_effects (m_fpga_transfer_batch * batch, m_effect_pll * list, m_eff_resource_report * res, int * pos)
Definition at line 327 of file m_fpga_encoding.c.
Referenced by m_pipeline_create_fpga_transfer_batch().
m_fpga_batch_append_resource()
int m_fpga_batch_append_resource (m_fpga_transfer_batch * batch, m_dsp_resource * res, const m_eff_resource_report * rpt, m_expr_scope * scope)
Definition at line 244 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_resources().
m_fpga_batch_append_resources()
int m_fpga_batch_append_resources (m_fpga_transfer_batch * batch, m_dsp_resource_pll * list, const m_eff_resource_report * rpt, m_expr_scope * scope)
Definition at line 277 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_append_eff_desc().
m_fpga_batch_print()
int m_fpga_batch_print (m_fpga_transfer_batch seq)
Definition at line 463 of file m_fpga_encoding.c.
Referenced by m_fpga_comms_task().
m_fpga_block_opcode_format()
int m_fpga_block_opcode_format (int opcode)
Definition at line 21 of file m_fpga_encoding.c.
Referenced by m_block_instr_format(), and m_fpga_batch_print().
m_fpga_transfer_batch_append_effect_register_updates()
int m_fpga_transfer_batch_append_effect_register_updates (m_fpga_transfer_batch * batch, m_effect_desc * eff, m_expr_scope * scope, int pos)
Definition at line 192 of file m_fpga_encoding.c.
Referenced by m_effect_update_fpga_registers().
print_instruction()
void print_instruction (uint32_t instr)
Definition at line 453 of file m_fpga_encoding.c.
Referenced by m_fpga_batch_print().
print_instruction_format_a()
void print_instruction_format_a (uint32_t instr)
Definition at line 401 of file m_fpga_encoding.c.
Referenced by print_instruction().
print_instruction_format_b()
void print_instruction_format_b (uint32_t instr)
Definition at line 427 of file m_fpga_encoding.c.
Referenced by print_instruction().