M: m_fpga_io.c File Reference
m_fpga_io.c File Reference
#include "m_int.h"
#include <driver/spi_master.h>
Macros
#define PRINTLINES_ALLOWED 0
#define PIN_NUM_MISO 14
#define PIN_NUM_MOSI 6
#define PIN_NUM_CLK 5
#define PIN_NUM_CS 4
Functions
int16_t float_to_q_nminus1 (float x, int shift)
int16_t float_to_q15 (float x)
int m_fpga_spi_init ()
int m_fpga_txrx (uint8_t *tx, uint8_t *rx, size_t len)
int m_fpga_send_byte (uint8_t byte)
uint8_t m_fpga_read_byte ()
m_fpga_transfer_batch m_new_fpga_transfer_batch ()
void m_free_fpga_transfer_batch (m_fpga_transfer_batch batch)
int m_fpga_batch_append (m_fpga_transfer_batch *seq, uint8_t x)
int m_fpga_batch_append_16 (m_fpga_transfer_batch *seq, uint16_t x)
int m_fpga_batch_append_24 (m_fpga_transfer_batch *seq, uint32_t x)
int m_fpga_batch_append_32 (m_fpga_transfer_batch *seq, uint32_t x)
int m_fpga_batch_concat (m_fpga_transfer_batch *seq, m_fpga_transfer_batch *seq2)
int m_fpga_transfer_batch_send (m_fpga_transfer_batch batch)
void m_fpga_set_input_gain (float gain_db)
void m_fpga_set_output_gain (float gain_db)
void m_fpga_commit_reg_updates ()
char * m_fpga_command_to_string (int command)
Variables
spi_device_handle_t spi_handle
Macro Definition Documentation
PIN_NUM_CLK
#define PIN_NUM_CLK 5
Definition at line 14 of file m_fpga_io.c.
Referenced by m_fpga_spi_init().
PIN_NUM_CS
#define PIN_NUM_CS 4
Definition at line 15 of file m_fpga_io.c.
Referenced by m_fpga_spi_init().
PIN_NUM_MISO
#define PIN_NUM_MISO 14
Definition at line 12 of file m_fpga_io.c.
Referenced by m_fpga_spi_init().
PIN_NUM_MOSI
#define PIN_NUM_MOSI 6
Definition at line 13 of file m_fpga_io.c.
Referenced by m_fpga_spi_init().
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file m_fpga_io.c.
Function Documentation
float_to_q15()
int16_t float_to_q15 (float x)
Definition at line 36 of file m_fpga_io.c.
float_to_q_nminus1()
int16_t float_to_q_nminus1 (float x, int shift)
Definition at line 20 of file m_fpga_io.c.
Referenced by m_fpga_batch_append_block_register_updates(), m_fpga_batch_append_block_regs(), m_fpga_set_input_gain(), and m_fpga_set_output_gain().
m_fpga_batch_append()
int m_fpga_batch_append (m_fpga_transfer_batch * seq, uint8_t x)
Definition at line 150 of file m_fpga_io.c.
Referenced by m_fpga_batch_append_16(), m_fpga_batch_append_24(), m_fpga_batch_append_32(), m_fpga_batch_append_block_instr(), m_fpga_batch_append_block_number(), m_fpga_batch_append_block_register_updates(), m_fpga_batch_append_block_regs(), m_fpga_batch_append_resource(), and m_pipeline_create_fpga_transfer_batch().
m_fpga_batch_append_16()
int m_fpga_batch_append_16 (m_fpga_transfer_batch * seq, uint16_t x)
Definition at line 172 of file m_fpga_io.c.
Referenced by m_fpga_batch_append_block_number(), m_fpga_batch_append_block_register_updates(), and m_fpga_batch_append_block_regs().
m_fpga_batch_append_24()
int m_fpga_batch_append_24 (m_fpga_transfer_batch * seq, uint32_t x)
Definition at line 188 of file m_fpga_io.c.
Referenced by m_fpga_batch_append_resource().
m_fpga_batch_append_32()
int m_fpga_batch_append_32 (m_fpga_transfer_batch * seq, uint32_t x)
Definition at line 205 of file m_fpga_io.c.
Referenced by m_fpga_batch_append_block_instr().
m_fpga_batch_concat()
int m_fpga_batch_concat (m_fpga_transfer_batch * seq, m_fpga_transfer_batch * seq2)
Definition at line 224 of file m_fpga_io.c.
m_fpga_command_to_string()
char * m_fpga_command_to_string (int command)
Definition at line 295 of file m_fpga_io.c.
Referenced by m_fpga_comms_task().
m_fpga_commit_reg_updates()
void m_fpga_commit_reg_updates ()
Definition at line 290 of file m_fpga_io.c.
m_fpga_read_byte()
uint8_t m_fpga_read_byte ()
Definition at line 125 of file m_fpga_io.c.
Referenced by m_fpga_comms_task().
m_fpga_send_byte()
int m_fpga_send_byte (uint8_t byte)
Definition at line 120 of file m_fpga_io.c.
Referenced by m_fpga_commit_reg_updates(), m_fpga_comms_task(), m_fpga_set_input_gain(), and m_fpga_set_output_gain().
m_fpga_set_input_gain()
void m_fpga_set_input_gain (float gain_db)
Definition at line 269 of file m_fpga_io.c.
Referenced by m_fpga_comms_task().
m_fpga_set_output_gain()
void m_fpga_set_output_gain (float gain_db)
Definition at line 279 of file m_fpga_io.c.
Referenced by m_fpga_comms_task().
m_fpga_spi_init()
int m_fpga_spi_init ()
Definition at line 44 of file m_fpga_io.c.
Referenced by m_fpga_comms_task().
m_fpga_transfer_batch_send()
int m_fpga_transfer_batch_send (m_fpga_transfer_batch batch)
Definition at line 264 of file m_fpga_io.c.
Referenced by m_fpga_comms_task().
m_fpga_txrx()
int m_fpga_txrx (uint8_t * tx, uint8_t * rx, size_t len)
Definition at line 77 of file m_fpga_io.c.
Referenced by m_fpga_read_byte(), m_fpga_send_byte(), and m_fpga_transfer_batch_send().
m_free_fpga_transfer_batch()
void m_free_fpga_transfer_batch (m_fpga_transfer_batch batch)
Definition at line 145 of file m_fpga_io.c.
Referenced by m_fpga_comms_task(), and m_pipeline_create_fpga_transfer_batch().
m_new_fpga_transfer_batch()
m_fpga_transfer_batch m_new_fpga_transfer_batch ()
Definition at line 133 of file m_fpga_io.c.
Referenced by m_effect_update_fpga_registers(), and m_pipeline_create_fpga_transfer_batch().
Variable Documentation
spi_handle
spi_device_handle_t spi_handle
Definition at line 17 of file m_fpga_io.c.
Referenced by m_fpga_spi_init(), and m_fpga_txrx().