M: m_fpga_comms.h File Reference
m_fpga_comms.h File Reference
Macros
#define PRINT_TRANSFER_BATCHES
Functions
void m_fpga_comms_task (void *param)
int m_fpga_queue_transfer_batch (m_fpga_transfer_batch batch)
int m_fpga_queue_program_batch (m_fpga_transfer_batch batch)
int m_fpga_queue_input_gain_set (float gain_db)
int m_fpga_queue_output_gain_set (float gain_db)
int m_fpga_queue_register_commit ()
Macro Definition Documentation
PRINT_TRANSFER_BATCHES
#define PRINT_TRANSFER_BATCHES
Definition at line 4 of file m_fpga_comms.h.
Function Documentation
m_fpga_comms_task()
void m_fpga_comms_task (void * param)
Definition at line 32 of file m_fpga_comms.c.
Referenced by app_main(), and main_task().
m_fpga_queue_input_gain_set()
int m_fpga_queue_input_gain_set (float gain_db)
Definition at line 152 of file m_fpga_comms.c.
m_fpga_queue_output_gain_set()
int m_fpga_queue_output_gain_set (float gain_db)
Definition at line 162 of file m_fpga_comms.c.
m_fpga_queue_program_batch()
int m_fpga_queue_program_batch (m_fpga_transfer_batch batch)
Definition at line 139 of file m_fpga_comms.c.
Referenced by m_profile_program_fpga().
m_fpga_queue_register_commit()
int m_fpga_queue_register_commit ()
Definition at line 172 of file m_fpga_comms.c.
m_fpga_queue_transfer_batch()
int m_fpga_queue_transfer_batch (m_fpga_transfer_batch batch)
Definition at line 127 of file m_fpga_comms.c.
Referenced by m_effect_update_fpga_registers().