M: m_profile_view.h File Reference
m_profile_view.h File Reference
Data Structures
struct m_profile_view_str
Functions
m_ui_page * create_profile_view_for (m_profile *profile)
int init_profile_view (m_ui_page *page)
int configure_profile_view (m_ui_page *page, void *data)
int create_profile_view_ui (m_ui_page *page)
int free_profile_view_ui (m_ui_page *page)
int free_profile_view (m_ui_page *page)
int enter_profile_view (m_ui_page *page)
int enter_profile_view_from (m_ui_page *page, m_ui_page *prev)
int refresh_profile_view (m_ui_page *page)
int profile_view_recalculate_indices (m_ui_page *page)
int profile_view_append_effect (m_ui_page *page, m_effect *effect)
int profile_view_populate_index_pos_array (m_ui_page *page)
int profile_view_index_y_position (int index)
int profile_view_refresh_play_button (m_ui_page *page)
int profile_view_refresh_save_button (m_ui_page *page)
int profile_view_change_name (m_ui_page *page, char *name)
int profile_view_set_left_button_mode (m_ui_page *page, int mode)
void profile_view_rep_update (void *representer, void *representee)
Function Documentation
configure_profile_view()
int configure_profile_view (m_ui_page * page, void * data)
Definition at line 335 of file m_profile_view.c.
Referenced by create_profile_view_for(), and init_profile_view().
create_profile_view_for()
m_ui_page * create_profile_view_for (m_profile * profile)
Definition at line 9 of file m_profile_view.c.
Referenced by create_new_profile_with_teensy(), load_saved_profiles(), and seq_view_clicked_cb().
create_profile_view_ui()
int create_profile_view_ui (m_ui_page * page)
Definition at line 416 of file m_profile_view.c.
Referenced by init_profile_view().
enter_profile_view()
int enter_profile_view (m_ui_page * page)
Definition at line 472 of file m_profile_view.c.
Referenced by init_profile_view().
enter_profile_view_from()
int enter_profile_view_from (m_ui_page * page, m_ui_page * prev)
free_profile_view()
int free_profile_view (m_ui_page * page)
Definition at line 521 of file m_profile_view.c.
Referenced by create_profile_view_for(), and init_profile_view().
free_profile_view_ui()
int free_profile_view_ui (m_ui_page * page)
init_profile_view()
int init_profile_view (m_ui_page * page)
Definition at line 116 of file m_profile_view.c.
Referenced by create_profile_view_for().
profile_view_append_effect()
int profile_view_append_effect (m_ui_page * page, m_effect * effect)
Definition at line 488 of file m_profile_view.c.
Referenced by add_effect_from_menu_eff().
profile_view_change_name()
int profile_view_change_name (m_ui_page * page, char * name)
Definition at line 552 of file m_profile_view.c.
profile_view_index_y_position()
int profile_view_index_y_position (int index)
profile_view_populate_index_pos_array()
int profile_view_populate_index_pos_array (m_ui_page * page)
profile_view_recalculate_indices()
int profile_view_recalculate_indices (m_ui_page * page)
Definition at line 510 of file m_profile_view.c.
profile_view_refresh_play_button()
int profile_view_refresh_play_button (m_ui_page * page)
Definition at line 533 of file m_profile_view.c.
profile_view_refresh_save_button()
int profile_view_refresh_save_button (m_ui_page * page)
Definition at line 544 of file m_profile_view.c.
profile_view_rep_update()
void profile_view_rep_update (void * representer, void * representee)
Definition at line 577 of file m_profile_view.c.
Referenced by init_profile_view().
profile_view_set_left_button_mode()
int profile_view_set_left_button_mode (m_ui_page * page, int mode)
Definition at line 565 of file m_profile_view.c.
refresh_profile_view()
int refresh_profile_view (m_ui_page * page)