M: m_pipeline.c File Reference
m_pipeline.c File Reference
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int init_m_pipeline (m_pipeline *pipeline)
m_effect * m_pipeline_append_effect_eff (m_pipeline *pipeline, m_effect_desc *eff)
int m_pipeline_remove_effect (m_pipeline *pipeline, uint16_t id)
int m_pipeline_move_effect (m_pipeline *pipeline, int new_pos, int old_pos)
int m_pipeline_get_n_effects (m_pipeline *pipeline)
int clone_pipeline (m_pipeline *dest, m_pipeline *src)
void gut_pipeline (m_pipeline *pipeline)
int m_pipeline_create_fpga_transfer_batch (m_pipeline *pipeline, m_fpga_transfer_batch *batch)
m_effect * m_pipeline_get_effect_by_id (m_pipeline *pipeline, int id)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file m_pipeline.c.
Function Documentation
clone_pipeline()
int clone_pipeline (m_pipeline * dest, m_pipeline * src)
Definition at line 177 of file m_pipeline.c.
Referenced by clone_profile().
gut_pipeline()
void gut_pipeline (m_pipeline * pipeline)
Definition at line 214 of file m_pipeline.c.
Referenced by gut_profile().
init_m_pipeline()
int init_m_pipeline (m_pipeline * pipeline)
Definition at line 9 of file m_pipeline.c.
Referenced by init_m_profile().
m_pipeline_append_effect_eff()
m_effect * m_pipeline_append_effect_eff (m_pipeline * pipeline, m_effect_desc * eff)
Definition at line 19 of file m_pipeline.c.
Referenced by m_profile_append_effect_eff().
m_pipeline_create_fpga_transfer_batch()
int m_pipeline_create_fpga_transfer_batch (m_pipeline * pipeline, m_fpga_transfer_batch * batch)
Definition at line 223 of file m_pipeline.c.
Referenced by m_profile_create_fpga_transfer_batch(), and m_profile_program_fpga().
m_pipeline_get_effect_by_id()
m_effect * m_pipeline_get_effect_by_id (m_pipeline * pipeline, int id)
Definition at line 271 of file m_pipeline.c.
Referenced by m_profile_get_effect_by_id().
m_pipeline_get_n_effects()
int m_pipeline_get_n_effects (m_pipeline * pipeline)
Definition at line 158 of file m_pipeline.c.
m_pipeline_move_effect()
int m_pipeline_move_effect (m_pipeline * pipeline, int new_pos, int old_pos)
Definition at line 106 of file m_pipeline.c.
Referenced by m_profile_move_effect().
m_pipeline_remove_effect()
int m_pipeline_remove_effect (m_pipeline * pipeline, uint16_t id)
Definition at line 70 of file m_pipeline.c.
Referenced by m_profile_remove_effect().