M: m_parameter.c File Reference
m_parameter.c File Reference
#include <float.h>
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
#define DEFAULT_MAX_VELOCITY 1.0
Functions
IMPLEMENT_LINKED_PTR_LIST (m_parameter)
IMPLEMENT_LINKED_PTR_LIST (m_setting)
int init_parameter_str (m_parameter *param)
int init_parameter (m_parameter *param, const char *name, float level, float min, float max)
m_parameter * new_m_parameter_wni (const char *name, const char *name_internal, float level, float min, float max)
int init_parameter_wni (m_parameter *param, const char *name, const char *name_internal, float level, float min, float max)
int init_setting_str (m_setting *setting)
int init_setting (m_setting *setting, const char *name, uint16_t level)
void gut_parameter (m_parameter *param)
void m_parameter_free (m_parameter *param)
int parameter_set_id (m_parameter *param, uint16_t pid, uint16_t tid, uint16_t ppid)
void clone_parameter (m_parameter *dest, m_parameter *src)
m_parameter * m_parameter_make_clone (m_parameter *src)
m_parameter * m_parameter_make_clone_for_effect (m_parameter *src, m_effect *effect)
int clone_setting (m_setting *dest, m_setting *src)
m_setting * m_setting_make_clone (m_setting *src)
m_setting * m_setting_make_clone_for_effect (m_setting *src, m_effect *effect)
void gut_setting (m_setting *setting)
void m_setting_free (m_setting *setting)
int m_parameters_assign_ids (m_parameter_pll *list)
int m_settings_assign_ids (m_setting_pll *list)
void m_parameter_effect_rep_update (void *representer, void *representee)
void m_setting_effect_rep_update (void *representer, void *representee)
Macro Definition Documentation
DEFAULT_MAX_VELOCITY
#define DEFAULT_MAX_VELOCITY 1.0
Definition at line 8 of file m_parameter.c.
Referenced by init_parameter(), and init_parameter_str().
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 5 of file m_parameter.c.
Function Documentation
clone_parameter()
void clone_parameter (m_parameter * dest, m_parameter * src)
Definition at line 182 of file m_parameter.c.
Referenced by clone_profile(), m_parameter_make_clone(), and m_parameter_make_clone_for_effect().
clone_setting()
int clone_setting (m_setting * dest, m_setting * src)
Definition at line 247 of file m_parameter.c.
Referenced by clone_effect(), m_setting_make_clone(), and m_setting_make_clone_for_effect().
gut_parameter()
void gut_parameter (m_parameter * param)
Definition at line 149 of file m_parameter.c.
Referenced by m_extract_parameter_from_dict(), and m_parameter_free().
gut_setting()
void gut_setting (m_setting * setting)
Definition at line 332 of file m_parameter.c.
Referenced by gut_effect(), m_extract_setting_from_dict(), and m_setting_free().
IMPLEMENT_LINKED_PTR_LIST() [1/2]
IMPLEMENT_LINKED_PTR_LIST (m_parameter)
IMPLEMENT_LINKED_PTR_LIST() [2/2]
IMPLEMENT_LINKED_PTR_LIST (m_setting)
init_parameter()
int init_parameter (m_parameter * param, const char * name, float level, float min, float max)
Definition at line 46 of file m_parameter.c.
Referenced by init_effect(), init_m_profile(), init_parameter_wni(), and m_init_context().
init_parameter_str()
int init_parameter_str (m_parameter * param)
Definition at line 15 of file m_parameter.c.
Referenced by clone_parameter(), effect_add_parameter(), and m_extract_parameter_from_dict().
init_parameter_wni()
int init_parameter_wni (m_parameter * param, const char * name, const char * name_internal, float level, float min, float max)
Definition at line 84 of file m_parameter.c.
Referenced by new_m_parameter_wni().
init_setting()
int init_setting (m_setting * setting, const char * name, uint16_t level)
Definition at line 123 of file m_parameter.c.
Referenced by init_effect().
init_setting_str()
int init_setting_str (m_setting * setting)
Definition at line 94 of file m_parameter.c.
Referenced by clone_setting(), effect_add_setting(), and m_extract_setting_from_dict().
m_parameter_effect_rep_update()
void m_parameter_effect_rep_update (void * representer, void * representee)
Definition at line 467 of file m_parameter.c.
Referenced by init_parameter(), and init_parameter_str().
m_parameter_free()
void m_parameter_free (m_parameter * param)
Definition at line 159 of file m_parameter.c.
Referenced by free_effect().
m_parameter_make_clone()
m_parameter * m_parameter_make_clone (m_parameter * src)
Definition at line 213 of file m_parameter.c.
m_parameter_make_clone_for_effect()
m_parameter * m_parameter_make_clone_for_effect (m_parameter * src, m_effect * effect)
Definition at line 228 of file m_parameter.c.
Referenced by init_effect_from_effect_desc().
m_parameters_assign_ids()
int m_parameters_assign_ids (m_parameter_pll * list)
Definition at line 357 of file m_parameter.c.
Referenced by m_parse_tokens().
m_setting_effect_rep_update()
void m_setting_effect_rep_update (void * representer, void * representee)
Definition at line 480 of file m_parameter.c.
Referenced by init_setting(), and init_setting_str().
m_setting_free()
void m_setting_free (m_setting * setting)
Definition at line 346 of file m_parameter.c.
Referenced by free_effect().
m_setting_make_clone()
m_setting * m_setting_make_clone (m_setting * src)
Definition at line 298 of file m_parameter.c.
m_setting_make_clone_for_effect()
m_setting * m_setting_make_clone_for_effect (m_setting * src, m_effect * effect)
Definition at line 313 of file m_parameter.c.
Referenced by init_effect_from_effect_desc().
m_settings_assign_ids()
int m_settings_assign_ids (m_setting_pll * list)
Definition at line 379 of file m_parameter.c.
Referenced by m_parse_tokens().
new_m_parameter_wni()
m_parameter * new_m_parameter_wni (const char * name, const char * name_internal, float level, float min, float max)
Definition at line 73 of file m_parameter.c.
parameter_set_id()
int parameter_set_id (m_parameter * param, uint16_t pid, uint16_t tid, uint16_t ppid)
Definition at line 170 of file m_parameter.c.