M: m_profile.c File Reference
m_profile.c File Reference
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (m_profile)
int init_m_profile (m_profile *profile)
int profile_set_id (m_profile *profile, uint16_t id)
int m_profile_set_active (m_profile *profile)
int m_profile_set_inactive (m_profile *profile)
int m_profile_add_representation (m_profile *profile, m_representation *rep)
int m_profile_update_representations (m_profile *profile)
int m_profile_remove_representation (m_profile *profile, m_representation *rep)
int m_profile_set_default_name_from_id (m_profile *profile)
m_effect * m_profile_append_effect_eff (m_profile *profile, m_effect_desc *eff)
int m_profile_remove_effect (m_profile *profile, uint16_t id)
int m_profile_move_effect (m_profile *profile, int new_pos, int old_pos)
int clone_profile (m_profile *dest, m_profile *src)
void gut_profile (m_profile *profile)
void free_profile (m_profile *profile)
void m_free_profile (m_profile *profile)
m_profile * create_new_profile_with_teensy ()
int m_profile_save (m_profile *profile)
int m_profile_create_fpga_transfer_batch (m_profile *profile, m_fpga_transfer_batch *batch)
int m_profile_program_fpga (m_profile *profile)
int m_profile_if_active_update_fpga (m_profile *profile)
void m_profile_file_rep_update (void *representer, void *representee)
m_effect * m_profile_get_effect_by_id (m_profile *profile, int id)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file m_profile.c.
Function Documentation
clone_profile()
int clone_profile (m_profile * dest, m_profile * src)
Definition at line 224 of file m_profile.c.
create_new_profile_with_teensy()
m_profile * create_new_profile_with_teensy ()
Definition at line 316 of file m_profile.c.
free_profile()
void free_profile (m_profile * profile)
Definition at line 271 of file m_profile.c.
Referenced by cxt_remove_profile(), load_saved_profiles(), m_context_add_profile(), m_context_add_profile_rp(), and m_free_profile().
gut_profile()
void gut_profile (m_profile * profile)
Definition at line 247 of file m_profile.c.
Referenced by free_profile().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (m_profile)
init_m_profile()
int init_m_profile (m_profile * profile)
Definition at line 13 of file m_profile.c.
Referenced by load_saved_profiles(), m_context_add_profile(), and m_context_add_profile_rp().
m_free_profile()
void m_free_profile (m_profile * profile)
Definition at line 281 of file m_profile.c.
Referenced by m_sequence_delete_profile().
m_profile_add_representation()
int m_profile_add_representation (m_profile * profile, m_representation * rep)
Definition at line 98 of file m_profile.c.
Referenced by configure_profile_view(), and seq_plus_cb().
m_profile_append_effect_eff()
m_effect * m_profile_append_effect_eff (m_profile * profile, m_effect_desc * eff)
Definition at line 174 of file m_profile.c.
Referenced by add_effect_from_menu_eff(), and read_profile_from_file().
m_profile_create_fpga_transfer_batch()
int m_profile_create_fpga_transfer_batch (m_profile * profile, m_fpga_transfer_batch * batch)
Definition at line 383 of file m_profile.c.
m_profile_file_rep_update()
void m_profile_file_rep_update (void * representer, void * representee)
Definition at line 436 of file m_profile.c.
Referenced by init_m_profile().
m_profile_get_effect_by_id()
m_effect * m_profile_get_effect_by_id (m_profile * profile, int id)
Definition at line 450 of file m_profile.c.
Referenced by m_page_id_find_page().
m_profile_if_active_update_fpga()
int m_profile_if_active_update_fpga (m_profile * profile)
Definition at line 422 of file m_profile.c.
Referenced by add_effect_from_menu_eff(), m_profile_move_effect(), m_profile_remove_effect(), profile_view_effect_delete_cb(), and sw_field_save_cb().
m_profile_move_effect()
int m_profile_move_effect (m_profile * profile, int new_pos, int old_pos)
Definition at line 205 of file m_profile.c.
Referenced by profile_view_effect_moved_cb().
m_profile_program_fpga()
int m_profile_program_fpga (m_profile * profile)
Definition at line 396 of file m_profile.c.
Referenced by m_profile_if_active_update_fpga(), and m_profile_set_active().
m_profile_remove_effect()
int m_profile_remove_effect (m_profile * profile, uint16_t id)
Definition at line 191 of file m_profile.c.
Referenced by cxt_remove_effect(), and profile_view_effect_delete_cb().
m_profile_remove_representation()
int m_profile_remove_representation (m_profile * profile, m_representation * rep)
Definition at line 132 of file m_profile.c.
m_profile_save()
int m_profile_save (m_profile * profile)
Definition at line 361 of file m_profile.c.
Referenced by cxt_save_all_profiles().
m_profile_set_active()
int m_profile_set_active (m_profile * profile)
Definition at line 72 of file m_profile.c.
Referenced by set_active_profile(), and set_active_profile_from_sequence().
m_profile_set_default_name_from_id()
int m_profile_set_default_name_from_id (m_profile * profile)
Definition at line 144 of file m_profile.c.
Referenced by configure_profile_settings_page(), and create_profile_view_ui().
m_profile_set_inactive()
int m_profile_set_inactive (m_profile * profile)
Definition at line 86 of file m_profile.c.
Referenced by set_active_profile(), and set_active_profile_from_sequence().
m_profile_update_representations()
int m_profile_update_representations (m_profile * profile)
Definition at line 119 of file m_profile.c.
Referenced by add_effect_from_menu_eff(), m_profile_save(), m_profile_set_active(), m_profile_set_inactive(), and profile_view_save_name().
profile_set_id()
int profile_set_id (m_profile * profile, uint16_t id)
Definition at line 61 of file m_profile.c.