M: m_parameter_widget.c File Reference
m_parameter_widget.c File Reference
#include "m_int.h"
#include "m_param_update.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (m_parameter_widget)
IMPLEMENT_LINKED_PTR_LIST (m_setting_widget)
int parameter_widget_update_value (m_parameter_widget *pw)
void param_widget_rep_update (void *representer, void *representee)
int nullify_parameter_widget (m_parameter_widget *pw)
void format_parameter_widget_value_label_v (m_parameter_widget *pw, float v)
void format_parameter_widget_value_label (m_parameter_widget *pw)
void parameter_widget_update_value_label_v (m_parameter_widget *pw, float v)
void parameter_widget_update_value_label (m_parameter_widget *pw)
int configure_parameter_widget (m_parameter_widget *pw, m_parameter *param, m_profile *profile, m_ui_page *parent)
void parameter_widget_refresh_cb (lv_event_t *event)
void parameter_widget_change_cb_inner (m_parameter_widget *pw)
void parameter_widget_change_cb (lv_event_t *event)
int parameter_widget_create_ui (m_parameter_widget *pw, lv_obj_t *parent)
int parameter_widget_create_ui_no_callback (m_parameter_widget *pw, lv_obj_t *parent)
void free_parameter_widget (m_parameter_widget *pw)
int setting_widget_update_value (m_setting_widget *sw)
void setting_widget_rep_update (void *representer, void *representee)
int nullify_setting_widget (m_setting_widget *sw)
int configure_setting_widget (m_setting_widget *sw, m_setting *setting, m_profile *profile, m_ui_page *parent)
void setting_widget_refresh_cb (lv_event_t *event)
int setting_widget_calc_value (m_setting_widget *sw, int16_t *target)
void sw_field_reject (m_setting_widget *sw)
void sw_field_save_cb (lv_event_t *e)
void sw_field_cancel_cb (lv_event_t *e)
void edit_sw_field_cb (lv_event_t *e)
void setting_widget_change_cb_inner (m_setting_widget *sw)
void setting_widget_change_cb (lv_event_t *event)
int setting_widget_create_ui (m_setting_widget *sw, lv_obj_t *parent)
int setting_widget_create_ui_no_callback (m_setting_widget *sw, lv_obj_t *parent)
void free_setting_widget (m_setting_widget *sw)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file m_parameter_widget.c.
Function Documentation
configure_parameter_widget()
int configure_parameter_widget (m_parameter_widget * pw, m_parameter * param, m_profile * profile, m_ui_page * parent)
Definition at line 167 of file m_parameter_widget.c.
Referenced by configure_effect_settings_page(), configure_effect_view(), configure_main_menu(), and create_parameter_widget_menu_item().
configure_setting_widget()
int configure_setting_widget (m_setting_widget * sw, m_setting * setting, m_profile * profile, m_ui_page * parent)
Definition at line 508 of file m_parameter_widget.c.
Referenced by configure_effect_settings_page(), and configure_effect_view().
edit_sw_field_cb()
void edit_sw_field_cb (lv_event_t * e)
Definition at line 702 of file m_parameter_widget.c.
Referenced by setting_widget_create_ui().
format_parameter_widget_value_label()
void format_parameter_widget_value_label (m_parameter_widget * pw)
Definition at line 64 of file m_parameter_widget.c.
Referenced by parameter_widget_update_value_label().
format_parameter_widget_value_label_v()
void format_parameter_widget_value_label_v (m_parameter_widget * pw, float v)
Definition at line 51 of file m_parameter_widget.c.
Referenced by parameter_widget_update_value_label_v().
free_parameter_widget()
void free_parameter_widget (m_parameter_widget * pw)
Definition at line 410 of file m_parameter_widget.c.
Referenced by free_effect_view().
free_setting_widget()
void free_setting_widget (m_setting_widget * sw)
Definition at line 889 of file m_parameter_widget.c.
IMPLEMENT_LINKED_PTR_LIST() [1/2]
IMPLEMENT_LINKED_PTR_LIST (m_parameter_widget)
IMPLEMENT_LINKED_PTR_LIST() [2/2]
IMPLEMENT_LINKED_PTR_LIST (m_setting_widget)
nullify_parameter_widget()
int nullify_parameter_widget (m_parameter_widget * pw)
Definition at line 29 of file m_parameter_widget.c.
Referenced by configure_effect_view(), configure_main_menu(), create_parameter_widget_menu_item(), and init_effect_settings_page().
nullify_setting_widget()
int nullify_setting_widget (m_setting_widget * sw)
Definition at line 433 of file m_parameter_widget.c.
Referenced by configure_effect_view(), and init_effect_settings_page().
param_widget_rep_update()
void param_widget_rep_update (void * representer, void * representee)
Definition at line 15 of file m_parameter_widget.c.
Referenced by nullify_parameter_widget().
parameter_widget_change_cb()
void parameter_widget_change_cb (lv_event_t * event)
Definition at line 270 of file m_parameter_widget.c.
Referenced by parameter_widget_create_ui().
parameter_widget_change_cb_inner()
void parameter_widget_change_cb_inner (m_parameter_widget * pw)
Definition at line 201 of file m_parameter_widget.c.
Referenced by parameter_widget_change_cb(), and parameter_widget_change_cb_settings_wrapper().
parameter_widget_create_ui()
int parameter_widget_create_ui (m_parameter_widget * pw, lv_obj_t * parent)
Definition at line 283 of file m_parameter_widget.c.
Referenced by create_effect_settings_page_ui(), create_effect_view_ui(), create_main_menu_ui(), and create_profile_settings_page_ui().
parameter_widget_create_ui_no_callback()
int parameter_widget_create_ui_no_callback (m_parameter_widget * pw, lv_obj_t * parent)
Definition at line 297 of file m_parameter_widget.c.
Referenced by create_menu_item_ui(), and parameter_widget_create_ui().
parameter_widget_refresh_cb()
void parameter_widget_refresh_cb (lv_event_t * event)
Definition at line 187 of file m_parameter_widget.c.
parameter_widget_update_value()
int parameter_widget_update_value (m_parameter_widget * pw)
Definition at line 77 of file m_parameter_widget.c.
Referenced by param_widget_rep_update(), parameter_widget_create_ui_no_callback(), and parameter_widget_refresh_cb().
parameter_widget_update_value_label()
void parameter_widget_update_value_label (m_parameter_widget * pw)
Definition at line 152 of file m_parameter_widget.c.
Referenced by param_widget_rep_update(), parameter_widget_create_ui_no_callback(), and parameter_widget_refresh_cb().
parameter_widget_update_value_label_v()
void parameter_widget_update_value_label_v (m_parameter_widget * pw, float v)
Definition at line 137 of file m_parameter_widget.c.
Referenced by parameter_widget_change_cb_inner().
setting_widget_calc_value()
int setting_widget_calc_value (m_setting_widget * sw, int16_t * target)
Definition at line 534 of file m_parameter_widget.c.
Referenced by setting_widget_change_cb_inner().
setting_widget_change_cb()
void setting_widget_change_cb (lv_event_t * event)
Definition at line 759 of file m_parameter_widget.c.
Referenced by setting_widget_create_ui().
setting_widget_change_cb_inner()
void setting_widget_change_cb_inner (m_setting_widget * sw)
Definition at line 721 of file m_parameter_widget.c.
Referenced by setting_widget_change_cb().
setting_widget_create_ui()
int setting_widget_create_ui (m_setting_widget * sw, lv_obj_t * parent)
Definition at line 772 of file m_parameter_widget.c.
Referenced by create_effect_view_ui().
setting_widget_create_ui_no_callback()
int setting_widget_create_ui_no_callback (m_setting_widget * sw, lv_obj_t * parent)
Definition at line 805 of file m_parameter_widget.c.
Referenced by create_effect_settings_page_ui(), and setting_widget_create_ui().
setting_widget_refresh_cb()
void setting_widget_refresh_cb (lv_event_t * event)
Definition at line 526 of file m_parameter_widget.c.
setting_widget_rep_update()
void setting_widget_rep_update (void * representer, void * representee)
Definition at line 422 of file m_parameter_widget.c.
Referenced by nullify_setting_widget().
setting_widget_update_value()
int setting_widget_update_value (m_setting_widget * sw)
Definition at line 454 of file m_parameter_widget.c.
Referenced by setting_widget_create_ui_no_callback(), and setting_widget_rep_update().
sw_field_cancel_cb()
void sw_field_cancel_cb (lv_event_t * e)
Definition at line 679 of file m_parameter_widget.c.
Referenced by edit_sw_field_cb().
sw_field_reject()
void sw_field_reject (m_setting_widget * sw)
Definition at line 577 of file m_parameter_widget.c.
Referenced by sw_field_save_cb().
sw_field_save_cb()
void sw_field_save_cb (lv_event_t * e)
Definition at line 583 of file m_parameter_widget.c.
Referenced by edit_sw_field_cb().