M: m_resource.c File Reference
m_resource.c File Reference
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (m_dsp_resource)
int m_init_dsp_resource (m_dsp_resource *res)
int string_to_resource_type (const char *type_str)
int m_resources_assign_handles (m_dsp_resource_pll *list)
m_eff_resource_report empty_m_eff_resource_report ()
Variables
m_dsp_resource sin_lut
m_dsp_resource tanh_lut
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 9 of file m_resource.c.
Function Documentation
empty_m_eff_resource_report()
m_eff_resource_report empty_m_eff_resource_report ()
Definition at line 97 of file m_resource.c.
Referenced by m_pipeline_create_fpga_transfer_batch().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (m_dsp_resource)
m_init_dsp_resource()
int m_init_dsp_resource (m_dsp_resource * res)
Definition at line 34 of file m_resource.c.
Referenced by m_extract_resource_from_dict().
m_resources_assign_handles()
int m_resources_assign_handles (m_dsp_resource_pll * list)
Definition at line 64 of file m_resource.c.
Referenced by m_parse_tokens().
string_to_resource_type()
int string_to_resource_type (const char * type_str)
Definition at line 50 of file m_resource.c.
Referenced by m_extract_resource_from_dict().
Variable Documentation
sin_lut
m_dsp_resource sin_lut
Initial value:
= {
    .type   = M_DSP_RESOURCE_LUT,
    .name   = NULL,
    .handle = 0,
    .size   = NULL,
    .delay  = NULL,
    .data   = NULL
}
Definition at line 16 of file m_resource.c.
Referenced by m_process_asm_line().
tanh_lut
m_dsp_resource tanh_lut
Initial value:
= {
    .type   = M_DSP_RESOURCE_LUT,
    .name   = NULL,
    .handle = 1,
    .size   = NULL,
    .delay  = NULL,
    .data   = NULL
}
Definition at line 25 of file m_resource.c.
Referenced by m_process_asm_line().