M: m_representation.h File Reference
m_representation.h File Reference
Data Structures
struct m_representation
Functions
DECLARE_LINKED_PTR_LIST (m_representation)
void m_representation_pll_update_all (m_representation_pll *reps)
int queue_representation_list_update (m_representation_pll *reps)
m_representation_pll * m_representation_pll_remove (m_representation_pll *reps, m_representation *rep)
Function Documentation
DECLARE_LINKED_PTR_LIST()
DECLARE_LINKED_PTR_LIST (m_representation)
m_representation_pll_remove()
m_representation_pll * m_representation_pll_remove (m_representation_pll * reps, m_representation * rep)
Definition at line 74 of file m_representation.c.
Referenced by m_profile_remove_representation().
m_representation_pll_update_all()
void m_representation_pll_update_all (m_representation_pll * reps)
Definition at line 16 of file m_representation.c.
queue_representation_list_update()
int queue_representation_list_update (m_representation_pll * reps)
Definition at line 57 of file m_representation.c.
Referenced by m_cxt_queue_save_state(), m_effect_update_reps(), m_profile_update_representations(), and m_sequence_update_representations().