M: m_state.h File Reference
m_state.h File Reference
Data Structures
struct m_state
Functions
int m_cxt_clone_state (m_context *cxt, m_state *state)
int m_cxt_restore_state (m_context *cxt, m_state *state)
int m_cxt_enter_previous_current_page (m_context *cxt, m_state *state)
int m_init_state (m_state *state)
Function Documentation
m_cxt_clone_state()
int m_cxt_clone_state (m_context * cxt, m_state * state)
Definition at line 13 of file m_state.c.
Referenced by m_state_representation_update().
m_cxt_enter_previous_current_page()
int m_cxt_enter_previous_current_page (m_context * cxt, m_state * state)
Definition at line 120 of file m_state.c.
Referenced by app_main().
m_cxt_restore_state()
int m_cxt_restore_state (m_context * cxt, m_state * state)
Definition at line 94 of file m_state.c.
Referenced by app_main(), and main_task().
m_init_state()
int m_init_state (m_state * state)