M: m_state.c File Reference
m_state.c File Reference
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
int m_cxt_clone_state (m_context *cxt, m_state *state)
void m_state_representation_update (void *representer, void *representee)
int m_cxt_restore_state (m_context *cxt, m_state *state)
int m_cxt_enter_previous_current_page (m_context *cxt, m_state *state)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file m_state.c.
Function Documentation
m_cxt_clone_state()
int m_cxt_clone_state (m_context * cxt, m_state * state)
Definition at line 13 of file m_state.c.
Referenced by m_state_representation_update().
m_cxt_enter_previous_current_page()
int m_cxt_enter_previous_current_page (m_context * cxt, m_state * state)
Definition at line 120 of file m_state.c.
Referenced by app_main().
m_cxt_restore_state()
int m_cxt_restore_state (m_context * cxt, m_state * state)
Definition at line 94 of file m_state.c.
Referenced by app_main(), and main_task().
m_state_representation_update()
void m_state_representation_update (void * representer, void * representee)
Definition at line 65 of file m_state.c.
Referenced by m_init_context().