M: m_sequence.c File Reference
m_sequence.c File Reference
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (m_sequence)
int init_m_sequence (m_sequence *sequence)
int sequence_append_profile (m_sequence *sequence, m_profile *profile)
seq_profile_ll * sequence_append_profile_rp (m_sequence *sequence, m_profile *profile)
int m_sequence_move_profile (m_sequence *sequence, int pos, int new_pos)
int m_sequence_remove_profile (m_sequence *sequence, m_profile *profile)
int m_sequence_delete_profile (m_sequence *sequence, m_profile *profile)
void free_sequence (m_sequence *sequence)
int m_sequence_add_menu_listing (m_sequence *sequence, m_menu_item *listing)
int m_sequence_begin (m_sequence *sequence)
int m_sequence_begin_at (m_sequence *sequence, m_profile *profile)
int m_sequence_regress (m_sequence *sequence)
int m_sequence_advance (m_sequence *sequence)
int m_sequence_stop (m_sequence *sequence)
int m_sequence_stop_from_profile (m_sequence *sequence)
int m_sequence_activate_at (m_sequence *sequence, m_profile *profile)
int m_sequence_add_representation (m_sequence *sequence, m_representation *rep)
int m_sequence_update_representations (m_sequence *sequence)
void m_sequence_file_rep_update (void *representer, void *representee)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file m_sequence.c.
Function Documentation
free_sequence()
void free_sequence (m_sequence * sequence)
Definition at line 246 of file m_sequence.c.
Referenced by cxt_remove_sequence(), load_saved_sequences(), and m_context_add_sequence_rp().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (m_sequence)
init_m_sequence()
int init_m_sequence (m_sequence * sequence)
Definition at line 11 of file m_sequence.c.
Referenced by load_saved_sequences(), m_context_add_sequence_rp(), and m_context_init_main_sequence().
m_sequence_activate_at()
int m_sequence_activate_at (m_sequence * sequence, m_profile * profile)
Definition at line 435 of file m_sequence.c.
Referenced by set_active_profile().
m_sequence_add_menu_listing()
int m_sequence_add_menu_listing (m_sequence * sequence, m_menu_item * listing)
Definition at line 251 of file m_sequence.c.
Referenced by create_sequence_listing_menu_item().
m_sequence_add_representation()
int m_sequence_add_representation (m_sequence * sequence, m_representation * rep)
Definition at line 461 of file m_sequence.c.
Referenced by configure_sequence_view().
m_sequence_advance()
int m_sequence_advance (m_sequence * sequence)
Definition at line 363 of file m_sequence.c.
Referenced by cxt_handle_hw_switch().
m_sequence_begin()
int m_sequence_begin (m_sequence * sequence)
Definition at line 270 of file m_sequence.c.
Referenced by seq_play_cb().
m_sequence_begin_at()
int m_sequence_begin_at (m_sequence * sequence, m_profile * profile)
Definition at line 293 of file m_sequence.c.
Referenced by profile_view_play_button_cb().
m_sequence_delete_profile()
int m_sequence_delete_profile (m_sequence * sequence, m_profile * profile)
Definition at line 231 of file m_sequence.c.
Referenced by seq_view_delete_cb().
m_sequence_file_rep_update()
void m_sequence_file_rep_update (void * representer, void * representee)
Definition at line 518 of file m_sequence.c.
Referenced by init_m_sequence().
m_sequence_move_profile()
int m_sequence_move_profile (m_sequence * sequence, int pos, int new_pos)
Definition at line 138 of file m_sequence.c.
Referenced by seq_view_moved_cb().
m_sequence_regress()
int m_sequence_regress (m_sequence * sequence)
Definition at line 331 of file m_sequence.c.
Referenced by cxt_handle_hw_switch().
m_sequence_remove_profile()
int m_sequence_remove_profile (m_sequence * sequence, m_profile * profile)
Definition at line 197 of file m_sequence.c.
Referenced by m_sequence_delete_profile().
m_sequence_stop()
int m_sequence_stop (m_sequence * sequence)
Definition at line 402 of file m_sequence.c.
m_sequence_stop_from_profile()
int m_sequence_stop_from_profile (m_sequence * sequence)
Definition at line 420 of file m_sequence.c.
m_sequence_update_representations()
int m_sequence_update_representations (m_sequence * sequence)
Definition at line 480 of file m_sequence.c.
Referenced by m_sequence_activate_at(), m_sequence_begin(), m_sequence_begin_at(), m_sequence_move_profile(), m_sequence_remove_profile(), m_sequence_stop(), m_sequence_stop_from_profile(), sequence_append_profile_rp(), and sequence_view_set_name().
sequence_append_profile()
int sequence_append_profile (m_sequence * sequence, m_profile * profile)
Definition at line 45 of file m_sequence.c.
Referenced by read_sequence_from_file().
sequence_append_profile_rp()
seq_profile_ll * sequence_append_profile_rp (m_sequence * sequence, m_profile * profile)
Definition at line 83 of file m_sequence.c.
Referenced by seq_plus_cb().