M: m_transformer_init.h File Reference
m_transformer_init.h File Reference
Functions
int init_transformer_of_type (m_transformer *trans, uint16_t type)
Function Documentation
init_transformer_of_type()
int init_transformer_of_type (m_transformer * trans, uint16_t type)
Definition at line 1209 of file m_transformer_init.c.
{
    if (!trans)
        return ERR_NULL_PTR;
    int ret_val = init_transformer(trans);
    if (ret_val != NO_ERROR)
        return ret_val;
    switch (type)
    {
        case TRANSFORMER_3_BAND_EQ:          return init_3_band_eq(trans);
        case TRANSFORMER_AMPLIFIER:          return init_amplifier(trans);
        case TRANSFORMER_BAND_PASS_FILTER:   return init_band_pass_filter(trans);
        case TRANSFORMER_COMPRESSOR:         return init_compressor(trans);
        case TRANSFORMER_DELAY:              return init_delay(trans);
        case TRANSFORMER_DIRTY_OCTAVE:       return init_dirty_octave(trans);
        case TRANSFORMER_DISTORTION:         return init_distortion(trans);
        case TRANSFORMER_ENVELOPE:           return init_envelope(trans);
        case TRANSFORMER_FLANGER:            return init_flanger(trans);
        case TRANSFORMER_HIGH_PASS_FILTER:   return init_high_pass_filter(trans);
        case TRANSFORMER_LOW_END_COMPRESSOR: return init_low_end_compressor(trans);
        case TRANSFORMER_LOW_PASS_FILTER:    return init_low_pass_filter(trans);
        case TRANSFORMER_NOISE_SUPPRESSOR:   return init_noise_suppressor(trans);
        case TRANSFORMER_PERCUSSIFIER:       return init_percussifier(trans);
        case TRANSFORMER_WARBLER:            return init_warbler(trans);
        default: return ERR_BAD_ARGS;
    }
    return NO_ERROR;
}
References ERR_BAD_ARGS, ERR_NULL_PTR, init_3_band_eq(), init_amplifier(), init_band_pass_filter(), init_compressor(), init_delay(), init_dirty_octave(), init_distortion(), init_envelope(), init_flanger(), init_high_pass_filter(), init_low_end_compressor(), init_low_pass_filter(), init_noise_suppressor(), init_percussifier(), init_transformer(), init_warbler(), NO_ERROR, TRANSFORMER_3_BAND_EQ, TRANSFORMER_AMPLIFIER, TRANSFORMER_BAND_PASS_FILTER, TRANSFORMER_COMPRESSOR, TRANSFORMER_DELAY, TRANSFORMER_DIRTY_OCTAVE, TRANSFORMER_DISTORTION, TRANSFORMER_ENVELOPE, TRANSFORMER_FLANGER, TRANSFORMER_HIGH_PASS_FILTER, TRANSFORMER_LOW_END_COMPRESSOR, TRANSFORMER_LOW_PASS_FILTER, TRANSFORMER_NOISE_SUPPRESSOR, TRANSFORMER_PERCUSSIFIER, and TRANSFORMER_WARBLER.