M: m_transformer_select.c File Reference
m_transformer_select.c File Reference
#include "m_int.h"
Macros
#define PRINTLINES_ALLOWED 0
Functions
IMPLEMENT_LINKED_PTR_LIST (m_transformer_selector_button)
void enter_transformer_selector_cb (lv_event_t *e)
int init_transformer_selector_eff (m_ui_page *page)
int configure_transformer_selector (m_ui_page *page, void *data)
int refresh_transformer_selector (m_ui_page *page)
void add_transformer_from_menu_eff (lv_event_t *e)
int init_transformer_selector_button_from_effect (m_transformer_selector_button *button, m_effect_desc *eff)
int create_transformer_selector_button_ui_eff (m_transformer_selector_button *button, lv_obj_t *parent)
int create_transformer_selector_ui_eff (m_ui_page *page)
int enter_transformer_selector (m_ui_page *page)
Macro Definition Documentation
PRINTLINES_ALLOWED
#define PRINTLINES_ALLOWED 0
Definition at line 4 of file m_transformer_select.c.
Function Documentation
add_transformer_from_menu_eff()
void add_transformer_from_menu_eff (lv_event_t * e)
Definition at line 85 of file m_transformer_select.c.
{
    m_transformer_selector_button *button = lv_event_get_user_data(e);
    // Should never happen
    if (!button)
    {
        M_PRINTF("User tried to add transformer from menu, but the pointer to the page struct is NULL!\n");
        return;
    }
    m_ui_page *pv = NULL;
    m_transformer *trans = NULL;
    m_profile *profile = global_cxt.working_profile;
    m_effect_desc *eff = button->eff;
    M_PRINTF("User wishes to add a \"%s\"\n", button->name);
    if (!profile->view_page)
    {
        M_PRINTF("Profile does not have a view page!\n");
    }
    else
    {
        enter_ui_page_backwards(profile->view_page);
        pv = profile->view_page;
    }
    trans = m_profile_append_transformer_eff(profile, eff);
    if (pv) profile_view_append_transformer(pv, trans);
    profile->unsaved_changes = 1;
    m_profile_update_representations(profile);
    #ifdef USE_FPGA
    m_profile_if_active_update_fpga(profile);
    #endif
    m_transformer_init_view_page(trans, profile->view_page);
    create_transformer_view_ui(trans->view_page);
}
References create_transformer_view_ui(), m_transformer_selector_button::eff, enter_ui_page_backwards(), global_cxt, M_PRINTF, m_profile_append_transformer_eff(), m_profile_if_active_update_fpga(), m_profile_update_representations(), m_transformer_init_view_page(), m_transformer_selector_button::name, profile_view_append_transformer(), and m_profile::unsaved_changes.
Referenced by create_transformer_selector_button_ui_eff().
configure_transformer_selector()
int configure_transformer_selector (m_ui_page * page, void * data)
Definition at line 62 of file m_transformer_select.c.
{
    //m_printf("configure_transformer_selector...\n");
    if (!page || !data)
        return ERR_NULL_PTR;
    if (page->configured)
        return NO_ERROR;
    m_transformer_selector_str *ts = page->data_struct;
    if (!ts)
        return ERR_BAD_ARGS;
    M_PRINTF("success\n");
    return NO_ERROR;
}
References m_ui_page::configured, m_ui_page::data_struct, ERR_BAD_ARGS, ERR_NULL_PTR, M_PRINTF, and NO_ERROR.
create_transformer_selector_button_ui_eff()
int create_transformer_selector_button_ui_eff (m_transformer_selector_button * button, lv_obj_t * parent)
Definition at line 148 of file m_transformer_select.c.
{
    if (!button)
        return ERR_NULL_PTR;
    create_standard_button_click_short(&button->button, &button->label, parent, button->name, add_transformer_from_menu_eff, button);
    return NO_ERROR;
}
References add_transformer_from_menu_eff(), m_transformer_selector_button::button, create_standard_button_click_short(), ERR_NULL_PTR, m_transformer_selector_button::label, m_transformer_selector_button::name, and NO_ERROR.
Referenced by create_transformer_selector_ui_eff().
create_transformer_selector_ui_eff()
int create_transformer_selector_ui_eff (m_ui_page * page)
Definition at line 158 of file m_transformer_select.c.
{
    if (!page)
        return ERR_NULL_PTR;
    if (page->ui_created)
        return NO_ERROR;
    m_transformer_selector_str *ts = (m_transformer_selector_str*)page->data_struct;
    if (!ts)
        return ERR_BAD_ARGS;
    page->screen = lv_obj_create(NULL);
    create_panel_with_back_button(page);
    set_panel_text(page, "Add Effect");
    create_standard_button_list_tall(&ts->button_list, page->screen);
    m_transformer_selector_button_pll *current = ts->buttons;
    while (current)
    {
        create_transformer_selector_button_ui_eff(current->data, ts->button_list);
        current = current->next;
    }
    page->ui_created = 1;
    return NO_ERROR;
}
References m_transformer_selector_str::button_list, m_transformer_selector_str::buttons, create_panel_with_back_button(), create_standard_button_list_tall(), create_transformer_selector_button_ui_eff(), m_ui_page::data_struct, ERR_BAD_ARGS, ERR_NULL_PTR, NO_ERROR, m_ui_page::screen, set_panel_text(), and m_ui_page::ui_created.
Referenced by init_transformer_selector_eff().
enter_transformer_selector()
int enter_transformer_selector (m_ui_page * page)
Definition at line 190 of file m_transformer_select.c.
{
    if (!page)
        return ERR_NULL_PTR;
    return NO_ERROR;
}
References ERR_NULL_PTR, and NO_ERROR.
Referenced by init_transformer_selector_eff().
enter_transformer_selector_cb()
void enter_transformer_selector_cb (lv_event_t * e)
Definition at line 11 of file m_transformer_select.c.
{
    enter_ui_page_forwards(&global_cxt.pages.transformer_selector);
}
References enter_ui_page_forwards(), and global_cxt.
Referenced by configure_profile_view().
IMPLEMENT_LINKED_PTR_LIST()
IMPLEMENT_LINKED_PTR_LIST (m_transformer_selector_button)
init_transformer_selector_button_from_effect()
int init_transformer_selector_button_from_effect (m_transformer_selector_button * button, m_effect_desc * eff)
Definition at line 131 of file m_transformer_select.c.
{
    //m_printf("Init transformer selector button. Button = %p, index = %d, profile = %p\n", button, index, profile);
    if (!button || !eff)
        return ERR_NULL_PTR;
    button->type = 0;
    button->name = eff->name;
    button->button = NULL;
    button->label  = NULL;
    button->eff = eff;
    return NO_ERROR;
}
References m_transformer_selector_button::button, m_transformer_selector_button::eff, ERR_NULL_PTR, m_transformer_selector_button::label, m_effect_desc::name, m_transformer_selector_button::name, NO_ERROR, and m_transformer_selector_button::type.
Referenced by init_transformer_selector_eff().
init_transformer_selector_eff()
int init_transformer_selector_eff (m_ui_page * page)
Definition at line 16 of file m_transformer_select.c.
{
    M_PRINTF("init_transformer_selector_eff\n");
    if (!page)
        return ERR_NULL_PTR;
    init_ui_page(page);
    page->create_ui  = create_transformer_selector_ui_eff;
    page->enter_page = enter_transformer_selector;
    m_transformer_selector_str *str = m_alloc(sizeof(m_transformer_selector_str));
    page->data_struct = str;
    if (!str) return ERR_ALLOC_FAIL;
    str->buttons      = NULL;
    str->button_list = NULL;
    str->page_offset = 0;
    m_effect_desc_pll *current = global_cxt.effects;
    int i = 0;
    m_transformer_selector_button *button;
    while (current)
    {
        button = m_alloc(sizeof(m_transformer_selector_button));
        if (!button)
            return ERR_ALLOC_FAIL;
        init_transformer_selector_button_from_effect(button, current->data);
        str->buttons = m_transformer_selector_button_pll_append(str->buttons, button);
        current = current->next;
        i++;
    }
    M_PRINTF("Created %d buttons\n", i);
    page->configured = 1;
    return NO_ERROR;
}
References m_transformer_selector_str::button_list, m_transformer_selector_str::buttons, m_ui_page::configured, create_transformer_selector_ui_eff(), m_ui_page::create_ui, m_ui_page::data_struct, m_ui_page::enter_page, enter_transformer_selector(), ERR_ALLOC_FAIL, ERR_NULL_PTR, global_cxt, init_transformer_selector_button_from_effect(), init_ui_page(), m_alloc, M_PRINTF, NO_ERROR, and m_transformer_selector_str::page_offset.
Referenced by app_main(), and main_task().
refresh_transformer_selector()
int refresh_transformer_selector (m_ui_page * page)
Definition at line 80 of file m_transformer_select.c.
{
    return ERR_UNIMPLEMENTED;
}
References ERR_UNIMPLEMENTED.