M: m_transformer_settings.h File Reference
m_transformer_settings.h File Reference
Data Structures
struct trans_settings_page_str
Functions
int init_transformer_settings_page (m_ui_page *page)
int configure_transformer_settings_page (m_ui_page *page, void *data)
int create_transformer_settings_page_ui (m_ui_page *page)
int refresh_transformer_settings_page (m_ui_page *page)
int free_transformer_settings_page_ui (m_ui_page *page)
int transformer_settings_page_free_all (m_ui_page *page)
Function Documentation
configure_transformer_settings_page()
int configure_transformer_settings_page (m_ui_page * page, void * data)
Definition at line 48 of file m_transformer_settings.c.
{
    if (!page)
        return ERR_NULL_PTR;
    ui_page_add_back_button(page);
    m_transformer *trans = (m_transformer*)data;
    if (!data)
        return ERR_NULL_PTR;
    char title_buf[128];
    snprintf(title_buf, 128, "%s Settings", m_transformer_name(trans));
    char *title =  m_strndup(title_buf, 128);
    page->panel->text = title;
    trans_settings_page_str *str = (trans_settings_page_str*)page->data_struct;
    if (!str)
    {
        return ERR_BAD_ARGS;
    }
    str->trans = trans;
    configure_parameter_widget(&str->band_lp_cutoff, &trans->band_lp_cutoff, trans->profile, page);
    configure_parameter_widget(&str->band_hp_cutoff, &trans->band_hp_cutoff, trans->profile, page);
    configure_setting_widget(&str->band_mode, &trans->band_mode, trans->profile, page);
    page->configured = 1;
    return NO_ERROR;
}
References m_transformer::band_hp_cutoff, trans_settings_page_str::band_hp_cutoff, m_transformer::band_lp_cutoff, trans_settings_page_str::band_lp_cutoff, m_transformer::band_mode, trans_settings_page_str::band_mode, configure_parameter_widget(), configure_setting_widget(), m_ui_page::configured, m_ui_page::data_struct, ERR_BAD_ARGS, ERR_NULL_PTR, m_strndup, m_transformer_name(), NO_ERROR, m_ui_page::panel, m_transformer::profile, m_ui_page_panel::text, trans_settings_page_str::trans, and ui_page_add_back_button().
Referenced by configure_transformer_view(), and init_transformer_settings_page().
create_transformer_settings_page_ui()
int create_transformer_settings_page_ui (m_ui_page * page)
Definition at line 137 of file m_transformer_settings.c.
{
    M_PRINTF("create_transformer_settings_page_ui\n");
    if (!page)
        return ERR_NULL_PTR;
    ui_page_create_base_ui(page);
    lv_obj_set_layout(page->container, LV_LAYOUT_FLEX);
    lv_obj_set_flex_flow(page->container, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(page->container, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START);
    trans_settings_page_str *str = (trans_settings_page_str*)page->data_struct;
    if (!str)
        return ERR_BAD_ARGS;
    M_PRINTF("page->container = %p\n", page->container);
    //parameter_widget_create_ui(&str->cutoff_freq, page->container);
    setting_widget_create_ui_no_callback(&str->band_mode, page->container);
    lv_obj_add_event_cb(str->band_mode.obj, band_control_value_changed_cb, LV_EVENT_VALUE_CHANGED, page);
    str->band_control_cont = lv_obj_create(page->container);
    lv_obj_remove_style_all(str->band_control_cont);
    lv_obj_set_layout(str->band_control_cont, LV_LAYOUT_FLEX);
    lv_obj_set_flex_flow(str->band_control_cont, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(str->band_control_cont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_SPACE_EVENLY);
    //lv_obj_set_flex_grow(str->band_control_cont, 1);
    parameter_widget_create_ui(&str->band_hp_cutoff, global_cxt.pages.backstage);
    parameter_widget_create_ui(&str->band_lp_cutoff, global_cxt.pages.backstage);
    refresh_transformer_settings_page(page);
    page->ui_created = 1;
    M_PRINTF("create_transformer_settings_page_ui done\n");
    return NO_ERROR;
}
References trans_settings_page_str::band_control_cont, band_control_value_changed_cb(), trans_settings_page_str::band_hp_cutoff, trans_settings_page_str::band_lp_cutoff, trans_settings_page_str::band_mode, m_ui_page::container, m_ui_page::data_struct, ERR_BAD_ARGS, ERR_NULL_PTR, global_cxt, M_PRINTF, NO_ERROR, m_setting_widget::obj, parameter_widget_create_ui(), refresh_transformer_settings_page(), setting_widget_create_ui_no_callback(), m_ui_page::ui_created, and ui_page_create_base_ui().
Referenced by create_transformer_view_ui(), and init_transformer_settings_page().
free_transformer_settings_page_ui()
int free_transformer_settings_page_ui (m_ui_page * page)
Definition at line 265 of file m_transformer_settings.c.
{
    return ERR_UNIMPLEMENTED;
    if (!page)
        return ERR_NULL_PTR;
    return NO_ERROR;
}
References ERR_NULL_PTR, ERR_UNIMPLEMENTED, and NO_ERROR.
init_transformer_settings_page()
int init_transformer_settings_page (m_ui_page * page)
Definition at line 9 of file m_transformer_settings.c.
{
    if (!page)
        return ERR_NULL_PTR;
    init_ui_page(page);
    page->type = M_UI_PAGE_TRANS_SET;
    page->configure = configure_transformer_settings_page;
    page->create_ui = create_transformer_settings_page_ui;
    page->panel = new_panel();
    if (!page->panel)
    {
        return ERR_NULL_PTR;
    }
    M_PRINTF("Created a panel; %p\n", page->panel);
    page->data_struct = m_alloc(sizeof(trans_settings_page_str));
    if (!page->data_struct)
        return ERR_ALLOC_FAIL;
    trans_settings_page_str *str = (trans_settings_page_str*)page->data_struct;
    str->text = NULL;
    nullify_parameter_widget(&str->band_lp_cutoff);
    nullify_parameter_widget(&str->band_hp_cutoff);
    nullify_setting_widget(&str->band_mode);
    str->band_control_cont = NULL;
    return NO_ERROR;
}
References trans_settings_page_str::band_control_cont, trans_settings_page_str::band_hp_cutoff, trans_settings_page_str::band_lp_cutoff, trans_settings_page_str::band_mode, m_ui_page::configure, configure_transformer_settings_page(), create_transformer_settings_page_ui(), m_ui_page::create_ui, m_ui_page::data_struct, ERR_ALLOC_FAIL, ERR_NULL_PTR, init_ui_page(), m_alloc, M_PRINTF, M_UI_PAGE_TRANS_SET, new_panel(), NO_ERROR, nullify_parameter_widget(), nullify_setting_widget(), m_ui_page::panel, trans_settings_page_str::text, and m_ui_page::type.
Referenced by init_transformer_view().
refresh_transformer_settings_page()
int refresh_transformer_settings_page (m_ui_page * page)
Definition at line 182 of file m_transformer_settings.c.
{
    if (!page)
        return ERR_NULL_PTR;
    trans_settings_page_str *str = (trans_settings_page_str*)page->data_struct;
    if (!str)
        return ERR_NULL_PTR;
    if (str->band_mode.setting && str->band_control_cont)
    {
        switch (str->band_mode.setting->value)
        {
            case TRANSFORMER_MODE_FULL_SPECTRUM:
                if (str->band_lp_cutoff.container)
                {
                    lv_obj_set_parent(str->band_lp_cutoff.container, global_cxt.pages.backstage);
                }
                if (str->band_hp_cutoff.container)
                {
                    lv_obj_set_parent(str->band_hp_cutoff.container, global_cxt.pages.backstage);
                }
                break;
            case TRANSFORMER_MODE_UPPER_SPECTRUM:
                if (str->band_lp_cutoff.container)
                {
                    lv_obj_set_parent(str->band_lp_cutoff.container, global_cxt.pages.backstage);
                }
                if (str->band_hp_cutoff.container)
                {
                    lv_obj_set_parent(str->band_hp_cutoff.container, str->band_control_cont);
                }
                break;
            case TRANSFORMER_MODE_LOWER_SPECTRUM:
                if (str->band_lp_cutoff.container)
                {
                    lv_obj_set_parent(str->band_lp_cutoff.container, str->band_control_cont);
                }
                if (str->band_hp_cutoff.container)
                {
                    lv_obj_set_parent(str->band_hp_cutoff.container, global_cxt.pages.backstage);
                }
                break;
            case TRANSFORMER_MODE_BAND:
                if (str->band_hp_cutoff.container)
                {
                    lv_obj_set_parent(str->band_hp_cutoff.container, str->band_control_cont);
                }
                if (str->band_lp_cutoff.container)
                {
                    lv_obj_set_parent(str->band_lp_cutoff.container, str->band_control_cont);
                }
                break;
            default:
                return ERR_BAD_ARGS;
        }
        lv_obj_set_size(str->band_control_cont, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
        lv_obj_update_layout(str->band_control_cont);
    }
    lv_obj_update_layout(page->container);
    lv_obj_update_layout(page->screen);
    return NO_ERROR;
}
References trans_settings_page_str::band_control_cont, trans_settings_page_str::band_hp_cutoff, trans_settings_page_str::band_lp_cutoff, trans_settings_page_str::band_mode, m_parameter_widget::container, m_ui_page::container, m_ui_page::data_struct, ERR_BAD_ARGS, ERR_NULL_PTR, global_cxt, NO_ERROR, m_ui_page::screen, m_setting_widget::setting, TRANSFORMER_MODE_BAND, TRANSFORMER_MODE_FULL_SPECTRUM, TRANSFORMER_MODE_LOWER_SPECTRUM, TRANSFORMER_MODE_UPPER_SPECTRUM, and m_setting::value.
Referenced by band_control_value_changed_cb(), and create_transformer_settings_page_ui().
transformer_settings_page_free_all()
int transformer_settings_page_free_all (m_ui_page * page)
Definition at line 276 of file m_transformer_settings.c.
{
    return ERR_UNIMPLEMENTED;
    if (!page)
        return ERR_NULL_PTR;
    return NO_ERROR;
}
References ERR_NULL_PTR, ERR_UNIMPLEMENTED, and NO_ERROR.